In [1]:
import os
import sys
from pathlib import Path
import pandas as pd
import json

In [ ]:
repo_id = "Exploration-Lab/CISLR"
HF_TOKEN = os.getenv("HF_TOKEN")
if HF_TOKEN is None:
    raise ValueError("HF_TOKEN is not set")
SEED = 1990
ROOT = Path.cwd().resolve().parents[2]
sys.path.insert(0, str(ROOT))

print("Project root:", ROOT)

Project root: /Users/lokeshkumar/eMasters/EE964_Projects

In [ ]:
from src.scripts.download_from_hugging_face import download_file_from_hf

# Download the model file from Hugging Face
local_dir = ROOT / 'dataset/task3_cislr/features'
file_name = "I3D_features.pkl"
download_file_from_hf(repo_id, file_name, local_dir, repo_type="dataset", revision="main")

Total files in repo: 7
Downloaded: I3D_features.pkl
Saved to: /Users/lokeshkumar/eMasters/EE964_Projects/dataset/cislr/features/I3D_features.pkl

In [22]:
import pandas as pd
import numpy as np

pkl_file_path = ROOT / "dataset/task3_cislr/features/I3D_features.pkl"

features_df = pd.read_pickle(pkl_file_path)

print("Type:", type(features_df))
print("Shape:", getattr(features_df, "shape", None))

print("\nColumns:")
print(features_df.columns)

print("\nHead:")
print(features_df.head())
sample = features_df.iloc[0]

print("\nRow type:", type(sample))
print(sample)

feat = features_df.iloc[0]["I3D_features"]

print(type(feat))
print(np.array(feat).shape)


lengths = features_df["I3D_features"].apply(lambda x: len(x))

print("Min length:", lengths.min())
print("Max length:", lengths.max())
print("Mean length:", lengths.mean())
features_df = features_df.rename(columns={"id": "uid"})

Type: <class 'pandas.core.frame.DataFrame'>
Shape: (7050, 2)

Columns:
Index(['id', 'I3D_features'], dtype='object')

Head:
              id                                       I3D_features
0    ZcVzjZeVwj0  [[[[[0.03112409]], [[0.00099271]], [[0.000154]...
1    ZIKWlQUff9c  [[[[[0.22031154]], [[0.22767238]], [[0.1475680...
2  FnTehW6ik-Y_2  [[[[[0.20237736]], [[0.38866925]], [[0.4987630...
3    0lrX7s_3ScY  [[[[[0.04070692]], [[0.00172393]], [[0.0040934...
4    bgwSjzhyPs8  [[[[[0.]], [[0.]], [[0.]], [[0.]], [[0.0005370...

Row type: <class 'pandas.core.series.Series'>
id                                                    ZcVzjZeVwj0
I3D_features    [[[[[0.03112409]], [[0.00099271]], [[0.000154]...
Name: 0, dtype: object
<class 'numpy.ndarray'>
(1, 1024, 11, 1, 1)
Min length: 1
Max length: 1
Mean length: 1.0

In [16]:
import numpy as np

def to_td(x):
    x = np.asarray(x)
    x = np.squeeze(x)   # (1024, T)
    if x.ndim != 2:
        raise ValueError(f"Unexpected shape after squeeze: {x.shape}")
    x = x.T             # (T, 1024)
    return x

sample = to_td(features_df.iloc[0]["I3D_features"])
print("Sample final shape:", sample.shape)

lengths = features_df["I3D_features"].apply(lambda x: to_td(x).shape[0])
dims = features_df["I3D_features"].apply(lambda x: to_td(x).shape[1])

print("Min T:", lengths.min())
print("Max T:", lengths.max())
print("Mean T:", lengths.mean())
print("Unique feature dims:", dims.unique())

Sample final shape: (11, 1024)
Min T: 3
Max T: 51
Mean T: 14.406666666666666
Unique feature dims: [1024]

In [17]:
dataset_path = '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/dataset.csv'
df_dataset = pd.read_csv(dataset_path)
print("----- Dataset CSV -----")
print(df_dataset.head())
print(type(df_dataset), getattr(df_dataset, "shape", None))
print(df_dataset.columns)

prototype_path = '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/prototype.csv'
df_prototype = pd.read_csv(prototype_path)
print("----- Prototype CSV -----")
print(df_prototype.head())
print(type(df_prototype), getattr(df_prototype, "shape", None))
print(df_prototype.columns)

test_path = '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/test.csv'
df_test = pd.read_csv(test_path)
print("----- Test CSV -----")
print(df_test.head())
print(type(df_test), getattr(df_test, "shape", None))
print(df_test.columns)

----- Dataset CSV -----
             uid             gloss  duration         category
0  --7-rCNOiK0_1            branch       6.0  flora and fauna
1    -02y2VaVBmw  divorce petition      11.0            legal
2    -03Dju3yPHE   air conditioner       5.0          machine
3    -0Oo1kPonYQ            stapoo       6.0            sport
4  -0XujLX2_9I_2       application       6.0           action
<class 'pandas.core.frame.DataFrame'> (7050, 4)
Index(['uid', 'gloss', 'duration', 'category'], dtype='object')
----- Prototype CSV -----
             uid             gloss  duration         category
0  --7-rCNOiK0_1            branch       6.0  flora and fauna
1    -02y2VaVBmw  divorce petition      11.0            legal
2    -03Dju3yPHE   air conditioner       5.0          machine
3    -0Oo1kPonYQ            stapoo       6.0            sport
4  -0XujLX2_9I_2       application       6.0           action
<class 'pandas.core.frame.DataFrame'> (4765, 4)
Index(['uid', 'gloss', 'duration', 'category'], dtype='object')
----- Test CSV -----
             uid       gloss  duration         category
0  -NIz596Y27Q_1   severally       7.0         quantity
1  06tYXs9inPk_1      branch       6.0  flora and fauna
2  08E4Dr0zyKk_2  difference       7.0       comparator
3  0i1qCUd3BdM_1    increase       8.0       comparator
4    0p_iET-2TRw      pencil       4.0     utility item
<class 'pandas.core.frame.DataFrame'> (2285, 4)
Index(['uid', 'gloss', 'duration', 'category'], dtype='object')

In [23]:
test_uids = set(df_test["uid"])
dataset_uids = set(df_dataset["uid"])
prototype_uids = set(df_prototype["uid"])
print("UIDs in test but not in dataset:", test_uids - dataset_uids)
print("number of UIDs in test but not in prototype:", len(test_uids - prototype_uids))
I3d_uids = set(features_df["uid"])
print("UIDs in test but not in I3D features:", test_uids - I3d_uids)
print("UIDs in prototype but not in I3D features:", prototype_uids - I3d_uids)

UIDs in test but not in dataset: set()
number of UIDs in test but not in prototype: 2285
UIDs in test but not in I3D features: set()
UIDs in prototype but not in I3D features: set()

In [24]:
print(df_prototype.shape)
print(features_df.shape)
print(df_test.shape)

(4765, 4)
(7050, 2)
(2285, 4)

In [31]:
split = 0.8

train_df = df_prototype.sample(frac=split, random_state=SEED)
val_df = df_prototype.drop(train_df.index)

train_df = train_df.reset_index(drop=True)
val_df = val_df.reset_index(drop=True)

print("Train shape:", train_df.shape)
print("Val shape:", val_df.shape)
print("Test shape:", df_test.shape)

Train shape: (3812, 4)
Val shape: (953, 4)
Test shape: (2285, 4)

In [34]:
train_df.to_csv(f"{ROOT}/dataset/task3_cislr/splits/train.csv", index=False)
val_df.to_csv(f"{ROOT}/dataset/task3_cislr/splits/val.csv", index=False)

In [4]:
from src.tasks.task3_cislr.data.dataset import Task3CISLRDataset, task3_collate_fn, reshape_i3d_feature

In [10]:
from torch.utils.data import DataLoader

train_ds = Task3CISLRDataset(
    split_csv= ROOT / "dataset/task3_cislr/splits/train.csv",
    features_pkl= ROOT / "dataset/task3_cislr/features/I3D_features.pkl",
)

print("Dataset size:", len(train_ds))
sample = train_ds[0]
print(sample["uid"], sample["gloss"], sample["features"].shape, sample["feat_len"])

loader = DataLoader(train_ds, batch_size=4, shuffle=True, collate_fn=task3_collate_fn)
batch = next(iter(loader))
print(batch["features"].shape)
print(batch["feat_len"])
print(batch["uid"][:2])

Dataset size: 3812
K1N6oh0nYvo_1 faith torch.Size([11, 1024]) 11
torch.Size([4, 25, 1024])
tensor([25,  8, 21, 13])
['fx9psR2uzxs', 'EQ1yzB0YoPY']

In [9]:
print(sample.keys())

dict_keys(['uid', 'gloss', 'features', 'feat_len'])

In [13]:
from src.tasks.task3_cislr.evaluation.baseline_i3d_nn import run_baseline

results = run_baseline(
    train_csv=ROOT / "dataset/task3_cislr/splits/train.csv",
    query_csv=ROOT / "dataset/task3_cislr/splits/val.csv",
    feature_pkl=ROOT / "dataset/task3_cislr/features/I3D_features.pkl",
)

print(results)

{'train_csv': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/train.csv', 'query_csv': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/val.csv', 'feature_pkl': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/features/I3D_features.pkl', 'num_bank_samples': 3812, 'num_query_samples': 953, 'embedding_dim': 1024, 'metrics': {'top1': 0.0, 'top5': 0.0, 'top10': 0.0}}

In [14]:
from src.tasks.task3_cislr.evaluation.baseline_i3d_nn import run_baseline

results = run_baseline(
    train_csv=ROOT / "dataset/task3_cislr/splits/train.csv",
    query_csv=ROOT / "dataset/task3_cislr/splits/val.csv",
    feature_pkl=ROOT / "dataset/task3_cislr/features/I3D_features.pkl",
)

print(results)

{'train_csv': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/train.csv', 'query_csv': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/val.csv', 'feature_pkl': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/features/I3D_features.pkl', 'num_bank_samples': 3812, 'num_query_samples': 953, 'embedding_dim': 1024, 'metrics': {'top1': 0.0, 'top5': 0.0, 'top10': 0.0}}

In [15]:
results = run_baseline(
    train_csv=ROOT / "dataset/task3_cislr/splits/prototype.csv",
    query_csv=ROOT / "dataset/task3_cislr/splits/test.csv",
    feature_pkl=ROOT / "dataset/task3_cislr/features/I3D_features.pkl",
)

print(results)

{'train_csv': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/prototype.csv', 'query_csv': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/test.csv', 'feature_pkl': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/features/I3D_features.pkl', 'num_bank_samples': 4765, 'num_query_samples': 2285, 'embedding_dim': 1024, 'metrics': {'top1': 16.805251641137854, 'top5': 20.043763676148796, 'top10': 22.582056892778994}}

In [7]:
from src.tasks.task3_cislr.evaluation.baseline_i3d_pooling_variants import run_multi_variant_baseline
pooling_variants = ("mean", "max", "meanmax", "meanstd")
for variant in pooling_variants:
    results = run_multi_variant_baseline(
        train_csv=ROOT / "dataset/task3_cislr/splits/prototype.csv",
        query_csv=ROOT / "dataset/task3_cislr/splits/test.csv",
        feature_pkl=ROOT / "dataset/task3_cislr/features/I3D_features.pkl",
        save_path=ROOT / f"results/task3_cislr/baseline_pooling_variants_{variant}.json",
        pooling_variants=variant
    )
    print(results)

Running baseline with mean pooling...
Results saved to: /Users/lokeshkumar/eMasters/EE964_Projects/results/task3_cislr/baseline_pooling_variants_mean.json
{'train_csv': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/prototype.csv', 'query_csv': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/test.csv', 'feature_pkl': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/features/I3D_features.pkl', 'device': 'mps', 'results': {'mean': {'num_bank_samples': 4765, 'num_query_samples': 2285, 'embedding_dim': 1024, 'metrics': {'top1': 16.805251641137854, 'top5': 20.043763676148796, 'top10': 22.582056892778994}}}}
Running baseline with max pooling...
Results saved to: /Users/lokeshkumar/eMasters/EE964_Projects/results/task3_cislr/baseline_pooling_variants_max.json
{'train_csv': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/prototype.csv', 'query_csv': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/test.csv', 'feature_pkl': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/features/I3D_features.pkl', 'device': 'mps', 'results': {'max': {'num_bank_samples': 4765, 'num_query_samples': 2285, 'embedding_dim': 1024, 'metrics': {'top1': 17.330415754923415, 'top5': 20.700218818380744, 'top10': 22.800875273522976}}}}
Running baseline with meanmax pooling...
Results saved to: /Users/lokeshkumar/eMasters/EE964_Projects/results/task3_cislr/baseline_pooling_variants_meanmax.json
{'train_csv': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/prototype.csv', 'query_csv': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/test.csv', 'feature_pkl': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/features/I3D_features.pkl', 'device': 'mps', 'results': {'meanmax': {'num_bank_samples': 4765, 'num_query_samples': 2285, 'embedding_dim': 2048, 'metrics': {'top1': 17.199124726477024, 'top5': 20.700218818380744, 'top10': 22.888402625820568}}}}
Running baseline with meanstd pooling...
Results saved to: /Users/lokeshkumar/eMasters/EE964_Projects/results/task3_cislr/baseline_pooling_variants_meanstd.json
{'train_csv': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/prototype.csv', 'query_csv': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/test.csv', 'feature_pkl': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/features/I3D_features.pkl', 'device': 'mps', 'results': {'meanstd': {'num_bank_samples': 4765, 'num_query_samples': 2285, 'embedding_dim': 2048, 'metrics': {'top1': 17.155361050328228, 'top5': 20.831509846827135, 'top10': 22.932166301969364}}}}

In [12]:
from src.tasks.task3_cislr.models.bigru_encoder import BiGRUEncoder
from torch.utils.data import DataLoader
from src.tasks.task3_cislr.data.dataset import Task3CISLRDataset, task3_collate_fn

model = BiGRUEncoder(
    input_dim=1024,
    hidden_dim=128,
    out_dim=128,
    pooling="max",
    num_layers=1,
    dropout=0.1,
)



ds = Task3CISLRDataset(
    split_csv=ROOT / "dataset/task3_cislr/splits/prototype.csv",
    features_pkl=ROOT / "dataset/task3_cislr/features/I3D_features.pkl",
)

loader = DataLoader(ds, batch_size=4, shuffle=False, collate_fn=task3_collate_fn)
batch = next(iter(loader))


emb = model(batch["features"], batch["feat_len"])
print("Input shape:", batch["features"].shape)
print("Length shape:", batch["feat_len"].shape)
print("Embedding shape:", emb.shape)

Input shape: torch.Size([4, 31, 1024])
Length shape: torch.Size([4])
Embedding shape: torch.Size([4, 128])

In [18]:
vc = df_dataset["gloss"].value_counts()

print(vc.describe())
print("Glosses with >1 sample:", (vc > 1).sum())
print("Glosses with >2 samples:", (vc > 2).sum())
print("Glosses with >3 samples:", (vc > 3).sum())
print("Max samples for a gloss:", vc.max())

count    4764.000000
mean        1.479639
std         0.967998
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max        13.000000
Name: count, dtype: float64
Glosses with >1 sample: 1363
Glosses with >2 samples: 543
Glosses with >3 samples: 215
Max samples for a gloss: 13

In [4]:
import pandas as pd
from pathlib import Path

SEED = 1990

split_dir = ROOT / "dataset/task3_cislr/splits"
df_dataset = pd.read_csv(split_dir / "dataset.csv")

# 1) keep only glosses with at least 2 samples
gloss_counts = df_dataset["gloss"].value_counts()
repeated_glosses = gloss_counts[gloss_counts >= 2].index

df_repeated = df_dataset[df_dataset["gloss"].isin(repeated_glosses)].copy()

print("Original dataset shape:", df_dataset.shape)
print("Repeated-gloss subset shape:", df_repeated.shape)
print("Unique repeated glosses:", df_repeated["gloss"].nunique())
print(df_repeated["gloss"].value_counts().describe())

Original dataset shape: (7050, 4)
Repeated-gloss subset shape: (3648, 4)
Unique repeated glosses: 1363
count    1363.000000
mean        2.676449
std         1.126478
min         2.000000
25%         2.000000
50%         2.000000
75%         3.000000
max        13.000000
Name: count, dtype: float64

In [5]:
train_parts = []
val_parts = []

for gloss, group in df_repeated.groupby("gloss"):
    group = group.sample(frac=1.0, random_state=SEED).reset_index(drop=True)
    n = len(group)

    if n == 2:
        # one sample in train, one in val
        train_parts.append(group.iloc[:1])
        val_parts.append(group.iloc[1:])
    else:
        # keep at least one in val, rest in train
        val_count = max(1, round(0.2 * n))
        train_count = n - val_count

        # safety: ensure train has at least 1 sample too
        if train_count < 1:
            train_count = n - 1
            val_count = 1

        train_parts.append(group.iloc[:train_count])
        val_parts.append(group.iloc[train_count:])

train_repeated_df = pd.concat(train_parts, ignore_index=True)
val_repeated_df = pd.concat(val_parts, ignore_index=True)

print("Train repeated shape:", train_repeated_df.shape)
print("Val repeated shape:", val_repeated_df.shape)

print("Train repeated unique glosses:", train_repeated_df["gloss"].nunique())
print("Val repeated unique glosses:", val_repeated_df["gloss"].nunique())

Train repeated shape: (2275, 4)
Val repeated shape: (1373, 4)
Train repeated unique glosses: 1363
Val repeated unique glosses: 1363

In [6]:
train_glosses = set(train_repeated_df["gloss"])
val_glosses = set(val_repeated_df["gloss"])

print("Glosses in val but not in train:", len(val_glosses - train_glosses))
print("Glosses in train but not in val:", len(train_glosses - val_glosses))
print("Shared glosses:", len(train_glosses & val_glosses))

Glosses in val but not in train: 0
Glosses in train but not in val: 0
Shared glosses: 1363

In [7]:
train_uids = set(train_repeated_df["uid"])
val_uids = set(val_repeated_df["uid"])

print("UID overlap between train and val:", len(train_uids & val_uids))

UID overlap between train and val: 0

In [8]:
train_repeated_path = split_dir / "train_repeated.csv"
val_repeated_path = split_dir / "val_repeated.csv"

train_repeated_df.to_csv(train_repeated_path, index=False)
val_repeated_df.to_csv(val_repeated_path, index=False)

print("Saved:", train_repeated_path)
print("Saved:", val_repeated_path)

Saved: /Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/train_repeated.csv
Saved: /Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/val_repeated.csv

In [9]:
print("\nTrain gloss frequency summary:")
print(train_repeated_df["gloss"].value_counts().describe())

print("\nVal gloss frequency summary:")
print(val_repeated_df["gloss"].value_counts().describe())

Train gloss frequency summary:
count    1363.000000
mean        1.669112
std         1.083778
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max        10.000000
Name: count, dtype: float64

Val gloss frequency summary:
count    1363.000000
mean        1.007337
std         0.093577
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         3.000000
Name: count, dtype: float64

In [10]:
vc = train_repeated_df["gloss"].value_counts()
print("Train glosses with >=2 samples:", (vc >= 2).sum())
print("Train glosses with >=3 samples:", (vc >= 3).sum())

Train glosses with >=2 samples: 543
Train glosses with >=3 samples: 215

In [11]:
from src.tasks.task3_cislr.data.dataset import Task3CISLRDataset, task3_collate_fn, reshape_i3d_feature
from src.tasks.task3_cislr.data.samplers import GroupedBatchSampler, build_grouped_batch_sampler

In [12]:
from torch.utils.data import DataLoader
from src.tasks.task3_cislr.data.dataset import Task3CISLRDataset, task3_collate_fn
from src.tasks.task3_cislr.data.samplers import build_grouped_batch_sampler

train_repeated_csv = ROOT / "dataset/task3_cislr/splits/train_repeated.csv"
feature_pkl = ROOT / "dataset/task3_cislr/features/I3D_features.pkl"

train_ds = Task3CISLRDataset(
    split_csv=train_repeated_csv,
    features_pkl=feature_pkl,
)

sampler = build_grouped_batch_sampler(
    split_csv=train_repeated_csv,
    n_glosses_per_batch=8,
    n_samples_per_gloss=2,
    seed=1990,
)

train_loader = DataLoader(
    train_ds,
    batch_sampler=sampler,
    collate_fn=task3_collate_fn,
)

batch = next(iter(train_loader))
print("Batch feature shape:", batch["features"].shape)
print("Batch size:", len(batch["gloss"]))
print("Glosses:", batch["gloss"])

Batch feature shape: torch.Size([16, 43, 1024])
Batch size: 16
Glosses: ['bury', 'bury', 'maha shivaratri', 'maha shivaratri', 'skin', 'skin', 'air', 'air', 'distribute', 'distribute', 'pause', 'pause', 'angle', 'angle', 'division', 'division']

In [13]:
from collections import Counter

gloss_counts = Counter(batch["gloss"])
print(gloss_counts)

Counter({'bury': 2, 'maha shivaratri': 2, 'skin': 2, 'air': 2, 'distribute': 2, 'pause': 2, 'angle': 2, 'division': 2})

In [ ]:
from src.tasks.task3_cislr.training.train_retreival import run_training

results = run_training(
    train_csv=ROOT / "dataset/task3_cislr/splits/train_repeated.csv",
    val_csv=ROOT / "dataset/task3_cislr/splits/val_repeated.csv",
    prototype_csv=ROOT / "dataset/task3_cislr/splits/prototype.csv",
    test_csv=ROOT / "dataset/task3_cislr/splits/test.csv",
    feature_pkl=ROOT / "dataset/task3_cislr/features/I3D_features.pkl",
    out_dir=ROOT / "results/task3_cislr/bigru_contrastive_sanity_h128_o128_max",
    batch_size=64,
    num_workers=0,
    hidden_dim=128,
    out_dim=128,
    pooling="max",
    num_layers=1,
    dropout=0.1,
    lr=1e-3,
    weight_decay=1e-4,
    temperature=0.07,
    epochs=5,
)

results

Epoch 01 | loss=1.9997 | val_top1=93.74 | val_top5=93.95 | val_top10=94.03
Epoch 02 | loss=1.3181 | val_top1=93.81 | val_top5=93.95 | val_top10=94.10
Epoch 03 | loss=0.8943 | val_top1=93.95 | val_top5=94.10 | val_top10=94.32
Epoch 04 | loss=0.5006 | val_top1=93.95 | val_top5=94.10 | val_top10=94.25
Epoch 05 | loss=0.3954 | val_top1=93.88 | val_top5=94.10 | val_top10=94.25

Best validation top1: 93.95484340859431
Test metrics: {'top1': 14.835886214442013, 'top5': 19.212253829321664, 'top10': 21.88183807439825}

{'train_csv': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/train_repeated.csv',
 'val_csv': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/val_repeated.csv',
 'prototype_csv': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/prototype.csv',
 'test_csv': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/splits/test.csv',
 'feature_pkl': '/Users/lokeshkumar/eMasters/EE964_Projects/dataset/task3_cislr/features/I3D_features.pkl',
 'device': 'mps',
 'config': {'batch_size': 64,
  'hidden_dim': 128,
  'out_dim': 128,
  'pooling': 'max',
  'num_layers': 1,
  'dropout': 0.1,
  'lr': 0.001,
  'weight_decay': 0.0001,
  'temperature': 0.07,
  'epochs': 5},
 'best_val_top1': 93.95484340859431,
 'test_metrics': {'top1': 14.835886214442013,
  'top5': 19.212253829321664,
  'top10': 21.88183807439825},
 'history': [{'epoch': 1,
   'train_loss': 1.9997030562824674,
   'val_top1': 93.73634377276038,
   'val_top5': 93.95484340859431,
   'val_top10': 94.02767662053897},
  {'epoch': 2,
   'train_loss': 1.3181300090418921,
   'val_top1': 93.80917698470502,
   'val_top5': 93.95484340859431,
   'val_top10': 94.10050983248361},
  {'epoch': 3,
   'train_loss': 0.8942913169662158,
   'val_top1': 93.95484340859431,
   'val_top5': 94.10050983248361,
   'val_top10': 94.31900946831755},
  {'epoch': 4,
   'train_loss': 0.5005515929725435,
   'val_top1': 93.95484340859431,
   'val_top5': 94.10050983248361,
   'val_top10': 94.2461762563729},
  {'epoch': 5,
   'train_loss': 0.3954346709781223,
   'val_top1': 93.88201019664967,
   'val_top5': 94.10050983248361,
   'val_top10': 94.2461762563729}]}

In [5]:
from torch.utils.data import DataLoader 
from src.tasks.task3_cislr.data.dataset import Task3CISLRDataset, task3_collate_fn 
from src.tasks.task3_cislr.models.maxpool_projection import MaxPoolProjectionV1
ds = Task3CISLRDataset( split_csv=ROOT / "dataset/task3_cislr/splits/prototype.csv", features_pkl=ROOT / "dataset/task3_cislr/features/I3D_features.pkl", )
loader = DataLoader(ds, batch_size=4, shuffle=False, collate_fn=task3_collate_fn) 
batch = next(iter(loader)) 
model = MaxPoolProjectionV1( input_dim=1024, out_dim=128, dropout=0.1, ) 
emb = model(batch["features"], batch["feat_len"]) 
print("Input shape:", batch["features"].shape) 
print("Length shape:", batch["feat_len"].shape) 
print("Embedding shape:", emb.shape) 
print("Norms:", emb.norm(dim=1))

Input shape: torch.Size([4, 31, 1024])
Length shape: torch.Size([4])
Embedding shape: torch.Size([4, 128])
Norms: tensor([1.0000, 1.0000, 1.0000, 1.0000], grad_fn=<LinalgVectorNormBackward0>)

In [ ]:
from src.tasks.task3_cislr.models.maxpool_projection import MaxPoolProjectionV1
from src.scripts.get_device import get_device
device = get_device()
print("Using device:", device)
model = MaxPoolProjectionV1(
    input_dim=1024,
    out_dim=128,
    dropout=0.1,
).to(device)

Using device: mps

In [ ]:
from src.tasks.task3_cislr.training.train_retreival import run_training

results = run_training(
    train_csv=ROOT / "dataset/task3_cislr/splits/train_repeated.csv",
    val_csv=ROOT / "dataset/task3_cislr/splits/val_repeated.csv",
    prototype_csv=ROOT / "dataset/task3_cislr/splits/prototype.csv",
    test_csv=ROOT / "dataset/task3_cislr/splits/test.csv",
    feature_pkl=ROOT / "dataset/task3_cislr/features/I3D_features.pkl",
    out_dir=ROOT / "results/task3_cislr/bigru_contrastive_sanity_h128_o128_max",
    batch_size=64,
    num_workers=0,
    hidden_dim=128,
    out_dim=128,
    pooling="max",
    num_layers=1,
    dropout=0.1,
    lr=1e-3,
    weight_decay=1e-4,
    temperature=0.07,
    epochs=5,
    model=model,
)

Epoch 01 | loss=1.9077 | val_top1=26.73 | val_top5=32.92 | val_top10=36.34
Epoch 02 | loss=1.0155 | val_top1=26.80 | val_top5=32.19 | val_top10=36.20
Epoch 03 | loss=0.5579 | val_top1=27.09 | val_top5=32.77 | val_top10=36.13
Epoch 04 | loss=0.3370 | val_top1=27.31 | val_top5=33.21 | val_top10=36.85
Epoch 05 | loss=0.1811 | val_top1=27.53 | val_top5=33.21 | val_top10=37.29

Best validation top1: 27.530954115076476
Test metrics: {'top1': 16.49890590809628, 'top5': 22.27571115973742, 'top10': 25.689277899343544}

In [3]:
from torch.utils.data import DataLoader
from src.tasks.task3_cislr.data.dataset import Task3CISLRDataset, task3_collate_fn
from src.tasks.task3_cislr.models.maxpool_projection import MaxPoolProjectionV2

ds = Task3CISLRDataset(
    split_csv=ROOT / "dataset/task3_cislr/splits/prototype.csv",
    features_pkl=ROOT / "dataset/task3_cislr/features/I3D_features.pkl",
)

loader = DataLoader(ds, batch_size=4, shuffle=False, collate_fn=task3_collate_fn)
batch = next(iter(loader))

model = MaxPoolProjectionV2(
    input_dim=1024,
    hidden_dim=256,
    out_dim=128,
    dropout=0.1,
)

emb = model(batch["features"], batch["feat_len"])
print("Input shape:", batch["features"].shape)
print("Length shape:", batch["feat_len"].shape)
print("Embedding shape:", emb.shape)
print("Norms:", emb.norm(dim=1))
print(model)

Input shape: torch.Size([4, 31, 1024])
Length shape: torch.Size([4])
Embedding shape: torch.Size([4, 128])
Norms: tensor([1.0000, 1.0000, 1.0000, 1.0000], grad_fn=<LinalgVectorNormBackward0>)
MaxPoolProjectionV2(
  (fc1): Linear(in_features=1024, out_features=256, bias=True)
  (act): ReLU()
  (dropout): Dropout(p=0.1, inplace=False)
  (fc2): Linear(in_features=256, out_features=128, bias=True)
)

In [ ]:
from src.tasks.task3_cislr.training.train_retreival import run_training
from src.tasks.task3_cislr.models.maxpool_projection import MaxPoolProjectionV2

model = MaxPoolProjectionV2(
    input_dim=1024,
    hidden_dim=256,
    out_dim=128,
    dropout=0.1,
)

results = run_training(
    train_csv=ROOT / "dataset/task3_cislr/splits/train_repeated.csv",
    val_csv=ROOT / "dataset/task3_cislr/splits/val_repeated.csv",
    prototype_csv=ROOT / "dataset/task3_cislr/splits/prototype.csv",
    test_csv=ROOT / "dataset/task3_cislr/splits/test.csv",
    feature_pkl=ROOT / "dataset/task3_cislr/features/I3D_features.pkl",
    out_dir=ROOT / "results/task3_cislr/maxpool_projection_v2_h256_o128",
    batch_size=64,
    num_workers=0,
    hidden_dim=128,   # ignored by V2 model object
    out_dim=128,
    pooling="max",
    num_layers=1,     # ignored by V2 model object
    dropout=0.1,
    lr=1e-3,
    weight_decay=1e-4,
    temperature=0.07,
    epochs=5,
    model=model,
)

results["test_metrics"]

Epoch 01 | loss=2.2401 | val_top1=24.84 | val_top5=29.13 | val_top10=32.56
Epoch 02 | loss=1.6809 | val_top1=23.67 | val_top5=28.62 | val_top10=31.83
Epoch 03 | loss=1.4217 | val_top1=23.60 | val_top5=28.55 | val_top10=31.03
Epoch 04 | loss=1.1060 | val_top1=23.23 | val_top5=27.90 | val_top10=30.95
Epoch 05 | loss=1.0175 | val_top1=23.23 | val_top5=27.53 | val_top10=31.10

Best validation top1: 24.836125273124544
Test metrics: {'top1': 14.223194748358862, 'top5': 17.37417943107221, 'top10': 19.51859956236324}

{'top1': 14.223194748358862,
 'top5': 17.37417943107221,
 'top10': 19.51859956236324}

In [3]:
from src.utils.expand_grid import expand_grid

MaxPoolProjectionV2_grid = {
    "output_dim": [64, 128, 256],
    "input_dim": [1024],
    "dropout": [0.0, 0.1, 0.2],
    "lr": [1e-3, 5e-4, 2e-4],
    "weight_decay": [1e-4, 1e-5],
    "batch_size": [32],
    "temperature": [0.07, 0.1],
}

configs = expand_grid(MaxPoolProjectionV2_grid)
print(f"Total configs: {len(configs)}")
print("Sample config:", configs[0])

Total configs: 108
Sample config: {'output_dim': 64, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}

In [3]:
import pandas as pd

from src.utils.expand_grid import expand_grid
from src.tasks.task3_cislr.training.train_retreival import run_training
from src.tasks.task3_cislr.models.maxpool_projection import MaxPoolProjectionV2

MaxPoolProjectionV2_grid = {
    "output_dim": [64, 128, 256],
    "input_dim": [1024],
    "dropout": [0.0, 0.1],
    "lr": [1e-3, 5e-4],
    "weight_decay": [1e-4],
    "batch_size": [32],
    "temperature": [0.07, 0.1],
}
NUM_EPOCHS = 5
configs = expand_grid(MaxPoolProjectionV2_grid)
print(f"Total configs: {len(configs)}")
print("Sample config:", configs[0])

all_results = []

for i, cfg in enumerate(configs, start=1):
    print("\n" + "=" * 80)
    print(f"[{i}/{len(configs)}] Running MaxPoolProjectionV2 with config:")
    print(cfg)

    exp_name = (
        f"dim{cfg['output_dim']}_"
        f"drop{str(cfg['dropout']).replace('.', 'p')}_"
        f"lr{cfg['lr']}_"
        f"wd{cfg['weight_decay']}_"
        f"temp{str(cfg['temperature']).replace('.', 'p')}"
    )

    try:
        model = MaxPoolProjectionV2(
            input_dim=cfg["input_dim"],
            hidden_dim=cfg["output_dim"] * 2,
            out_dim=cfg["output_dim"],
            dropout=cfg["dropout"],
        )

        results = run_training(
            train_csv=ROOT / "dataset/task3_cislr/splits/train_repeated.csv",
            val_csv=ROOT / "dataset/task3_cislr/splits/val_repeated.csv",
            prototype_csv=ROOT / "dataset/task3_cislr/splits/prototype.csv",
            test_csv=ROOT / "dataset/task3_cislr/splits/test.csv",
            feature_pkl=ROOT / "dataset/task3_cislr/features/I3D_features.pkl",
            out_dir=ROOT / "results/task3_cislr/maxpool_projection_v2_gridsearch" / exp_name,
            batch_size=cfg["batch_size"],
            num_workers=0,
            pooling="max",
            num_layers=1,
            dropout=cfg["dropout"],
            lr=cfg["lr"],
            weight_decay=cfg["weight_decay"],
            temperature=cfg["temperature"],
            epochs=NUM_EPOCHS,
            model=model,
        )
        
        row = {
            "exp_name": exp_name,
            **cfg,
            "best_val_top1": results["best_val_top1"],
            "val_top1": results["best_val_metrics"]["top1"],
            "val_top5": results["best_val_metrics"]["top5"],
            "val_top10": results["best_val_metrics"]["top10"],
            "test_top1": results["test_metrics"]["top1"],
            "test_top5": results["test_metrics"]["top5"],
            "test_top10": results["test_metrics"]["top10"],
        }
        all_results.append(row)

    except Exception as e:
        print(f"Failed config: {cfg}")
        print("Error:", e)
        all_results.append({
            "exp_name": exp_name,
            **cfg,
            "error": str(e),
        })

df = pd.DataFrame(all_results)
df.to_csv(ROOT / "results/task3_cislr/maxpool_projection_v2_gridsearch_results.csv", index=False)
display(df.sort_values("val_top1", ascending=False))

Total configs: 24
Sample config: {'output_dim': 64, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}

================================================================================
[1/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 64, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=2.1830 | val_top1=24.33 | val_top5=29.13 | val_top10=32.41
Epoch 02 | loss=1.4008 | val_top1=24.33 | val_top5=28.19 | val_top10=30.52
Epoch 03 | loss=0.8427 | val_top1=23.38 | val_top5=27.31 | val_top10=29.79
Epoch 04 | loss=0.4689 | val_top1=23.96 | val_top5=27.75 | val_top10=30.59
Epoch 05 | loss=0.2580 | val_top1=23.38 | val_top5=27.39 | val_top10=30.66

Best validation top1: 24.326292789512017
Test metrics: {'top1': 14.61706783369803, 'top5': 17.067833698030636, 'top10': 19.168490153172865}

================================================================================
[2/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 64, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=2.0603 | val_top1=23.23 | val_top5=28.70 | val_top10=31.97
Epoch 02 | loss=1.2348 | val_top1=23.89 | val_top5=28.77 | val_top10=31.97
Epoch 03 | loss=0.7545 | val_top1=23.45 | val_top5=28.19 | val_top10=30.74
Epoch 04 | loss=0.4448 | val_top1=24.11 | val_top5=28.04 | val_top10=30.30
Epoch 05 | loss=0.1899 | val_top1=23.60 | val_top5=28.11 | val_top10=31.68

Best validation top1: 24.107793153678077
Test metrics: {'top1': 14.485776805251641, 'top5': 18.161925601750546, 'top10': 20.26258205689278}

================================================================================
[3/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 64, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=2.0097 | val_top1=25.05 | val_top5=29.86 | val_top10=33.21
Epoch 02 | loss=1.1698 | val_top1=24.98 | val_top5=30.15 | val_top10=33.21
Epoch 03 | loss=0.5950 | val_top1=25.42 | val_top5=29.35 | val_top10=31.90
Epoch 04 | loss=0.2763 | val_top1=25.20 | val_top5=29.21 | val_top10=31.76
Epoch 05 | loss=0.1256 | val_top1=25.05 | val_top5=29.64 | val_top10=32.70

Best validation top1: 25.41879096868172
Test metrics: {'top1': 15.22975929978118, 'top5': 18.46827133479212, 'top10': 20.87527352297593}

================================================================================
[4/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 64, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=2.0513 | val_top1=24.18 | val_top5=29.42 | val_top10=31.68
Epoch 02 | loss=1.1784 | val_top1=24.62 | val_top5=29.64 | val_top10=32.19
Epoch 03 | loss=0.6367 | val_top1=24.25 | val_top5=28.55 | val_top10=31.83
Epoch 04 | loss=0.3586 | val_top1=23.67 | val_top5=27.82 | val_top10=30.37
Epoch 05 | loss=0.1730 | val_top1=24.47 | val_top5=28.91 | val_top10=30.52

Best validation top1: 24.617625637290605
Test metrics: {'top1': 14.310722100656456, 'top5': 18.293216630196937, 'top10': 20.175054704595187}

================================================================================
[5/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 64, 'input_dim': 1024, 'dropout': 0.1, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=2.3868 | val_top1=23.45 | val_top5=28.62 | val_top10=30.66
Epoch 02 | loss=1.8579 | val_top1=23.38 | val_top5=27.39 | val_top10=29.28
Epoch 03 | loss=1.5646 | val_top1=23.09 | val_top5=27.60 | val_top10=29.93
Epoch 04 | loss=1.2787 | val_top1=23.02 | val_top5=27.82 | val_top10=30.30
Epoch 05 | loss=1.1815 | val_top1=22.07 | val_top5=26.66 | val_top10=29.06

Best validation top1: 23.452294246176255
Test metrics: {'top1': 13.698030634573303, 'top5': 16.280087527352297, 'top10': 17.98687089715536}

================================================================================
[6/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 64, 'input_dim': 1024, 'dropout': 0.1, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=2.3399 | val_top1=23.31 | val_top5=27.39 | val_top10=29.28
Epoch 02 | loss=1.8787 | val_top1=22.36 | val_top5=27.31 | val_top10=29.72
Epoch 03 | loss=1.4803 | val_top1=23.45 | val_top5=27.46 | val_top10=29.72
Epoch 04 | loss=1.2934 | val_top1=21.85 | val_top5=26.37 | val_top10=28.77
Epoch 05 | loss=1.1095 | val_top1=21.12 | val_top5=26.37 | val_top10=29.13

Best validation top1: 23.452294246176255
Test metrics: {'top1': 13.610503282275712, 'top5': 16.76148796498906, 'top10': 18.643326039387308}

================================================================================
[7/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 64, 'input_dim': 1024, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=2.3329 | val_top1=24.33 | val_top5=28.84 | val_top10=31.83
Epoch 02 | loss=1.7564 | val_top1=24.40 | val_top5=28.48 | val_top10=31.32
Epoch 03 | loss=1.4372 | val_top1=23.60 | val_top5=27.75 | val_top10=31.25
Epoch 04 | loss=1.1259 | val_top1=23.60 | val_top5=28.99 | val_top10=31.25
Epoch 05 | loss=1.0765 | val_top1=22.87 | val_top5=27.68 | val_top10=31.03

Best validation top1: 24.399126001456665
Test metrics: {'top1': 14.00437636761488, 'top5': 17.286652078774615, 'top10': 19.51859956236324}

================================================================================
[8/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 64, 'input_dim': 1024, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=2.2545 | val_top1=24.25 | val_top5=29.13 | val_top10=32.77
Epoch 02 | loss=1.6506 | val_top1=24.11 | val_top5=28.26 | val_top10=31.90
Epoch 03 | loss=1.3492 | val_top1=23.67 | val_top5=28.48 | val_top10=32.34
Epoch 04 | loss=1.1476 | val_top1=24.76 | val_top5=28.91 | val_top10=31.10
Epoch 05 | loss=0.8886 | val_top1=23.53 | val_top5=28.62 | val_top10=30.66

Best validation top1: 24.763292061179897
Test metrics: {'top1': 14.179431072210066, 'top5': 17.330415754923415, 'top10': 19.64989059080963}

================================================================================
[9/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 128, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=2.0674 | val_top1=24.69 | val_top5=29.93 | val_top10=32.99
Epoch 02 | loss=1.3063 | val_top1=24.62 | val_top5=29.57 | val_top10=32.70
Epoch 03 | loss=0.7409 | val_top1=24.91 | val_top5=29.79 | val_top10=32.70
Epoch 04 | loss=0.4619 | val_top1=24.25 | val_top5=28.99 | val_top10=31.61
Epoch 05 | loss=0.2442 | val_top1=23.96 | val_top5=28.55 | val_top10=30.81

Best validation top1: 24.908958485069192
Test metrics: {'top1': 14.61706783369803, 'top5': 18.687089715536104, 'top10': 20.962800875273523}

================================================================================
[10/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 128, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=2.0296 | val_top1=24.18 | val_top5=30.01 | val_top10=33.28
Epoch 02 | loss=1.2549 | val_top1=24.54 | val_top5=29.42 | val_top10=31.83
Epoch 03 | loss=0.7133 | val_top1=24.40 | val_top5=29.21 | val_top10=31.97
Epoch 04 | loss=0.3993 | val_top1=23.89 | val_top5=28.77 | val_top10=30.95
Epoch 05 | loss=0.1990 | val_top1=24.62 | val_top5=28.99 | val_top10=31.10

Best validation top1: 24.617625637290605
Test metrics: {'top1': 15.185995623632385, 'top5': 18.949671772428886, 'top10': 21.2253829321663}

================================================================================
[11/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 128, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=1.9285 | val_top1=25.56 | val_top5=31.39 | val_top10=34.30
Epoch 02 | loss=1.0575 | val_top1=25.35 | val_top5=30.59 | val_top10=33.43
Epoch 03 | loss=0.4956 | val_top1=25.42 | val_top5=30.44 | val_top10=33.43
Epoch 04 | loss=0.2107 | val_top1=25.20 | val_top5=30.23 | val_top10=33.28
Epoch 05 | loss=0.0734 | val_top1=25.13 | val_top5=30.08 | val_top10=32.41

Best validation top1: 25.56445739257101
Test metrics: {'top1': 15.492341356673961, 'top5': 18.86214442013129, 'top10': 20.74398249452954}

================================================================================
[12/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 128, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=1.9596 | val_top1=25.71 | val_top5=30.37 | val_top10=33.87
Epoch 02 | loss=1.0189 | val_top1=25.86 | val_top5=30.44 | val_top10=33.28
Epoch 03 | loss=0.4968 | val_top1=25.42 | val_top5=30.23 | val_top10=32.63
Epoch 04 | loss=0.2567 | val_top1=24.62 | val_top5=30.15 | val_top10=32.77
Epoch 05 | loss=0.1090 | val_top1=25.13 | val_top5=30.37 | val_top10=33.14

Best validation top1: 25.8557902403496
Test metrics: {'top1': 15.579868708971553, 'top5': 19.212253829321664, 'top10': 21.53172866520788}

================================================================================
[13/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 128, 'input_dim': 1024, 'dropout': 0.1, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=2.2372 | val_top1=24.47 | val_top5=28.70 | val_top10=31.54
Epoch 02 | loss=1.6946 | val_top1=23.45 | val_top5=29.35 | val_top10=31.83
Epoch 03 | loss=1.3632 | val_top1=23.82 | val_top5=28.04 | val_top10=30.95
Epoch 04 | loss=1.1643 | val_top1=23.02 | val_top5=27.60 | val_top10=30.37
Epoch 05 | loss=1.0270 | val_top1=22.58 | val_top5=27.60 | val_top10=30.08

Best validation top1: 24.471959213401313
Test metrics: {'top1': 14.354485776805252, 'top5': 17.592997811816193, 'top10': 18.905908096280086}

================================================================================
[14/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 128, 'input_dim': 1024, 'dropout': 0.1, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=2.2515 | val_top1=24.47 | val_top5=29.28 | val_top10=32.12
Epoch 02 | loss=1.7463 | val_top1=24.33 | val_top5=28.55 | val_top10=31.97
Epoch 03 | loss=1.3656 | val_top1=23.67 | val_top5=27.82 | val_top10=30.23
Epoch 04 | loss=1.1143 | val_top1=23.31 | val_top5=27.09 | val_top10=30.01
Epoch 05 | loss=1.0011 | val_top1=23.02 | val_top5=27.53 | val_top10=31.03

Best validation top1: 24.471959213401313
Test metrics: {'top1': 14.660831509846828, 'top5': 17.067833698030636, 'top10': 18.949671772428886}

================================================================================
[15/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 128, 'input_dim': 1024, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=2.1399 | val_top1=25.56 | val_top5=30.81 | val_top10=33.94
Epoch 02 | loss=1.4953 | val_top1=24.76 | val_top5=30.30 | val_top10=33.43
Epoch 03 | loss=1.0726 | val_top1=25.27 | val_top5=30.15 | val_top10=32.63
Epoch 04 | loss=0.8967 | val_top1=24.25 | val_top5=29.13 | val_top10=31.76
Epoch 05 | loss=0.7233 | val_top1=24.33 | val_top5=29.42 | val_top10=32.27

Best validation top1: 25.56445739257101
Test metrics: {'top1': 15.098468271334792, 'top5': 18.730853391684903, 'top10': 20.568927789934353}

================================================================================
[16/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 128, 'input_dim': 1024, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=2.1907 | val_top1=24.62 | val_top5=30.74 | val_top10=33.28
Epoch 02 | loss=1.6405 | val_top1=24.91 | val_top5=28.99 | val_top10=32.34
Epoch 03 | loss=1.2314 | val_top1=24.84 | val_top5=29.06 | val_top10=31.97
Epoch 04 | loss=1.0702 | val_top1=24.25 | val_top5=28.62 | val_top10=31.61
Epoch 05 | loss=0.8629 | val_top1=23.96 | val_top5=28.11 | val_top10=31.17

Best validation top1: 24.908958485069192
Test metrics: {'top1': 15.054704595185996, 'top5': 17.76805251641138, 'top10': 19.474835886214443}

================================================================================
[17/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 256, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=2.0277 | val_top1=23.89 | val_top5=28.77 | val_top10=31.97
Epoch 02 | loss=1.3581 | val_top1=24.11 | val_top5=28.70 | val_top10=31.83
Epoch 03 | loss=0.9394 | val_top1=23.45 | val_top5=28.04 | val_top10=30.88
Epoch 04 | loss=0.5497 | val_top1=24.11 | val_top5=28.55 | val_top10=31.46
Epoch 05 | loss=0.3225 | val_top1=23.31 | val_top5=28.26 | val_top10=30.44

Best validation top1: 24.107793153678077
Test metrics: {'top1': 14.398249452954047, 'top5': 18.03063457330416, 'top10': 19.64989059080963}

================================================================================
[18/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 256, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=2.1281 | val_top1=23.53 | val_top5=28.40 | val_top10=30.95
Epoch 02 | loss=1.4553 | val_top1=23.45 | val_top5=27.82 | val_top10=31.03
Epoch 03 | loss=0.9346 | val_top1=24.25 | val_top5=27.75 | val_top10=30.44
Epoch 04 | loss=0.5804 | val_top1=23.60 | val_top5=28.33 | val_top10=30.52
Epoch 05 | loss=0.3387 | val_top1=23.45 | val_top5=28.33 | val_top10=30.59

Best validation top1: 24.25345957756737
Test metrics: {'top1': 14.091903719912473, 'top5': 16.76148796498906, 'top10': 18.86214442013129}

================================================================================
[19/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 256, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=1.9067 | val_top1=26.07 | val_top5=30.74 | val_top10=34.23
Epoch 02 | loss=0.9897 | val_top1=26.80 | val_top5=31.03 | val_top10=34.67
Epoch 03 | loss=0.4510 | val_top1=26.29 | val_top5=30.23 | val_top10=32.99
Epoch 04 | loss=0.2019 | val_top1=24.54 | val_top5=30.15 | val_top10=33.36
Epoch 05 | loss=0.0736 | val_top1=25.35 | val_top5=30.37 | val_top10=33.07

Best validation top1: 26.80262199563001
Test metrics: {'top1': 16.192560175054705, 'top5': 19.91247264770241, 'top10': 22.144420131291028}

================================================================================
[20/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 256, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=1.8770 | val_top1=25.93 | val_top5=30.52 | val_top10=33.58
Epoch 02 | loss=0.9608 | val_top1=25.78 | val_top5=30.74 | val_top10=33.36
Epoch 03 | loss=0.4528 | val_top1=25.49 | val_top5=30.44 | val_top10=33.43
Epoch 04 | loss=0.1923 | val_top1=25.20 | val_top5=29.93 | val_top10=33.72
Epoch 05 | loss=0.0878 | val_top1=25.49 | val_top5=29.64 | val_top10=33.07

Best validation top1: 25.928623452294246
Test metrics: {'top1': 15.404814004376368, 'top5': 18.905908096280086, 'top10': 21.444201312910284}

================================================================================
[21/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 256, 'input_dim': 1024, 'dropout': 0.1, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=2.1803 | val_top1=24.40 | val_top5=28.84 | val_top10=32.85
Epoch 02 | loss=1.6301 | val_top1=23.53 | val_top5=29.13 | val_top10=31.90
Epoch 03 | loss=1.2027 | val_top1=23.96 | val_top5=29.79 | val_top10=33.36
Epoch 04 | loss=0.9871 | val_top1=24.25 | val_top5=29.06 | val_top10=31.97
Epoch 05 | loss=0.7224 | val_top1=23.38 | val_top5=27.60 | val_top10=30.01

Best validation top1: 24.399126001456665
Test metrics: {'top1': 14.091903719912473, 'top5': 17.37417943107221, 'top10': 19.25601750547046}

================================================================================
[22/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 256, 'input_dim': 1024, 'dropout': 0.1, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=2.1611 | val_top1=24.11 | val_top5=29.21 | val_top10=33.21
Epoch 02 | loss=1.6190 | val_top1=23.89 | val_top5=29.50 | val_top10=31.83
Epoch 03 | loss=1.2647 | val_top1=23.89 | val_top5=28.91 | val_top10=31.10
Epoch 04 | loss=0.9515 | val_top1=23.53 | val_top5=28.48 | val_top10=31.61
Epoch 05 | loss=0.7164 | val_top1=23.53 | val_top5=28.91 | val_top10=31.17

Best validation top1: 24.107793153678077
Test metrics: {'top1': 14.704595185995624, 'top5': 17.592997811816193, 'top10': 19.60612691466083}

================================================================================
[23/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 256, 'input_dim': 1024, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=2.0266 | val_top1=25.56 | val_top5=31.97 | val_top10=35.91
Epoch 02 | loss=1.4053 | val_top1=25.86 | val_top5=31.61 | val_top10=34.09
Epoch 03 | loss=0.9527 | val_top1=25.86 | val_top5=31.03 | val_top10=34.30
Epoch 04 | loss=0.7248 | val_top1=25.42 | val_top5=30.23 | val_top10=32.63
Epoch 05 | loss=0.5411 | val_top1=25.78 | val_top5=30.74 | val_top10=33.65

Best validation top1: 25.8557902403496
Test metrics: {'top1': 15.75492341356674, 'top5': 19.212253829321664, 'top10': 21.663019693654267}

================================================================================
[24/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 256, 'input_dim': 1024, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=2.0713 | val_top1=25.20 | val_top5=31.32 | val_top10=34.96
Epoch 02 | loss=1.3812 | val_top1=25.71 | val_top5=31.46 | val_top10=34.81
Epoch 03 | loss=0.9154 | val_top1=26.07 | val_top5=30.81 | val_top10=33.65
Epoch 04 | loss=0.6306 | val_top1=24.54 | val_top5=29.35 | val_top10=32.12
Epoch 05 | loss=0.4690 | val_top1=23.89 | val_top5=29.35 | val_top10=32.12

Best validation top1: 26.07428987618354
Test metrics: {'top1': 14.923413566739606, 'top5': 19.34354485776805, 'top10': 21.61925601750547}

,exp_name,output_dim,input_dim,dropout,lr,weight_decay,batch_size,temperature,best_val_top1,val_top1,val_top5,val_top10,test_top1,test_top5,test_top10
18,dim256_drop0p0_lr0.0005_wd0.0001_temp0p07,256,1024,0.0,0.0005,0.0001,32,0.07,26.802622,26.802622,31.026948,34.668609,16.192560,19.912473,22.144420
23,dim256_drop0p1_lr0.0005_wd0.0001_temp0p1,256,1024,0.1,0.0005,0.0001,32,0.10,26.074290,26.074290,30.808449,33.648944,14.923414,19.343545,21.619256
19,dim256_drop0p0_lr0.0005_wd0.0001_temp0p1,256,1024,0.0,0.0005,0.0001,32,0.10,25.928623,25.928623,30.517116,33.576111,15.404814,18.905908,21.444201
22,dim256_drop0p1_lr0.0005_wd0.0001_temp0p07,256,1024,0.1,0.0005,0.0001,32,0.07,25.855790,25.855790,31.609614,34.085943,15.754923,19.212254,21.663020
11,dim128_drop0p0_lr0.0005_wd0.0001_temp0p1,128,1024,0.0,0.0005,0.0001,32,0.10,25.855790,25.855790,30.444283,33.284778,15.579869,19.212254,21.531729
14,dim128_drop0p1_lr0.0005_wd0.0001_temp0p07,128,1024,0.1,0.0005,0.0001,32,0.07,25.564457,25.564457,30.808449,33.940277,15.098468,18.730853,20.568928
10,dim128_drop0p0_lr0.0005_wd0.0001_temp0p07,128,1024,0.0,0.0005,0.0001,32,0.07,25.564457,25.564457,31.391114,34.304443,15.492341,18.862144,20.743982
2,dim64_drop0p0_lr0.0005_wd0.0001_temp0p07,64,1024,0.0,0.0005,0.0001,32,0.07,25.418791,25.418791,29.351784,31.900947,15.229759,18.468271,20.875274
8,dim128_drop0p0_lr0.001_wd0.0001_temp0p07,128,1024,0.0,0.0010,0.0001,32,0.07,24.908958,24.908958,29.788784,32.702112,14.617068,18.687090,20.962801
15,dim128_drop0p1_lr0.0005_wd0.0001_temp0p1,128,1024,0.1,0.0005,0.0001,32,0.10,24.908958,24.908958,28.987618,32.337946,15.054705,17.768053,19.474836
7,dim64_drop0p1_lr0.0005_wd0.0001_temp0p1,64,1024,0.1,0.0005,0.0001,32,0.10,24.763292,24.763292,28.914785,31.099782,14.179431,17.330416,19.649891
3,dim64_drop0p0_lr0.0005_wd0.0001_temp0p1,64,1024,0.0,0.0005,0.0001,32,0.10,24.617626,24.617626,29.643117,32.192280,14.310722,18.293217,20.175055
9,dim128_drop0p0_lr0.001_wd0.0001_temp0p1,128,1024,0.0,0.0010,0.0001,32,0.10,24.617626,24.617626,28.987618,31.099782,15.185996,18.949672,21.225383
12,dim128_drop0p1_lr0.001_wd0.0001_temp0p07,128,1024,0.1,0.0010,0.0001,32,0.07,24.471959,24.471959,28.696286,31.536781,14.354486,17.592998,18.905908
13,dim128_drop0p1_lr0.001_wd0.0001_temp0p1,128,1024,0.1,0.0010,0.0001,32,0.10,24.471959,24.471959,29.278951,32.119446,14.660832,17.067834,18.949672
6,dim64_drop0p1_lr0.0005_wd0.0001_temp0p07,64,1024,0.1,0.0005,0.0001,32,0.07,24.399126,24.399126,28.477786,31.318281,14.004376,17.286652,19.518600
20,dim256_drop0p1_lr0.001_wd0.0001_temp0p07,256,1024,0.1,0.0010,0.0001,32,0.07,24.399126,24.399126,28.841952,32.847779,14.091904,17.374179,19.256018
0,dim64_drop0p0_lr0.001_wd0.0001_temp0p07,64,1024,0.0,0.0010,0.0001,32,0.07,24.326293,24.326293,29.133285,32.410779,14.617068,17.067834,19.168490
17,dim256_drop0p0_lr0.001_wd0.0001_temp0p1,256,1024,0.0,0.0010,0.0001,32,0.10,24.253460,24.253460,27.749454,30.444283,14.091904,16.761488,18.862144
1,dim64_drop0p0_lr0.001_wd0.0001_temp0p1,64,1024,0.0,0.0010,0.0001,32,0.10,24.107793,24.107793,28.040787,30.298616,14.485777,18.161926,20.262582
16,dim256_drop0p0_lr0.001_wd0.0001_temp0p07,256,1024,0.0,0.0010,0.0001,32,0.07,24.107793,24.107793,28.696286,31.828114,14.398249,18.030635,19.649891
21,dim256_drop0p1_lr0.001_wd0.0001_temp0p1,256,1024,0.1,0.0010,0.0001,32,0.10,24.107793,24.107793,29.206118,33.211945,14.704595,17.592998,19.606127
5,dim64_drop0p1_lr0.001_wd0.0001_temp0p1,64,1024,0.1,0.0010,0.0001,32,0.10,23.452294,23.452294,27.458121,29.715950,13.610503,16.761488,18.643326
4,dim64_drop0p1_lr0.001_wd0.0001_temp0p07,64,1024,0.1,0.0010,0.0001,32,0.07,23.452294,23.452294,28.623452,30.662782,13.698031,16.280088,17.986871

In [4]:
import pandas as pd

from src.utils.expand_grid import expand_grid
from src.tasks.task3_cislr.training.train_retreival import run_training
from src.tasks.task3_cislr.models.maxpool_projection import MaxPoolProjectionV1

In [ ]:
MaxPoolProjectionV1_grid = {
    "input_dim": [1024],
    "output_dim": [128, 256],
    "dropout": [0.0, 0.1],
    "lr": [5e-4, 2e-4],
    "weight_decay": [1e-4, 1e-5],
    "batch_size": [32],
    "temperature": [0.07, 0.1],
}


NUM_EPOCHS = 5
configs = expand_grid(MaxPoolProjectionV1_grid)
print(f"Total configs: {len(configs)}")
print("Sample config:", configs[0])

all_results = []

for i, cfg in enumerate(configs, start=1):
    print("\n" + "=" * 80)
    print(f"[{i}/{len(configs)}] Running MaxPoolProjectionV1 with config:")
    print(cfg)

    exp_name = (
        f"dim{cfg['output_dim']}_"
        f"drop{str(cfg['dropout']).replace('.', 'p')}_"
        f"lr{cfg['lr']}_"
        f"wd{cfg['weight_decay']}_"
        f"temp{str(cfg['temperature']).replace('.', 'p')}"
    )

    try:
        model = MaxPoolProjectionV1(
            input_dim=cfg["input_dim"],
            out_dim=cfg["output_dim"],
            dropout=cfg["dropout"],
        )

        results = run_training(
            train_csv=ROOT / "dataset/task3_cislr/splits/train_repeated.csv",
            val_csv=ROOT / "dataset/task3_cislr/splits/val_repeated.csv",
            prototype_csv=ROOT / "dataset/task3_cislr/splits/prototype.csv",
            test_csv=ROOT / "dataset/task3_cislr/splits/test.csv",
            feature_pkl=ROOT / "dataset/task3_cislr/features/I3D_features.pkl",
            out_dir=ROOT / "results/task3_cislr/maxpool_projection_v1_gridsearch" / exp_name,
            batch_size=cfg["batch_size"],
            num_workers=0,
            pooling="max",
            lr=cfg["lr"],
            weight_decay=cfg["weight_decay"],
            temperature=cfg["temperature"],
            epochs=NUM_EPOCHS,
            model=model,
        )
        
        row = {
            "exp_name": exp_name,
            **cfg,
            "best_val_top1": results["best_val_top1"],
            "val_top1": results["best_val_metrics"]["top1"],
            "val_top5": results["best_val_metrics"]["top5"],
            "val_top10": results["best_val_metrics"]["top10"],
            "test_top1": results["test_metrics"]["top1"],
            "test_top5": results["test_metrics"]["top5"],
            "test_top10": results["test_metrics"]["top10"],
        }
        all_results.append(row)

    except Exception as e:
        print(f"Failed config: {cfg}")
        print("Error:", e)
        all_results.append({
            "exp_name": exp_name,
            **cfg,
            "error": str(e),
        })

df = pd.DataFrame(all_results)
df.to_csv(ROOT / "results/task3_cislr/maxpool_projection_v1_gridsearch_results.csv", index=False)
display(df.sort_values("val_top1", ascending=False))

Total configs: 32
Sample config: {'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}

================================================================================
[1/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=1.7824 | val_top1=27.39 | val_top5=33.50 | val_top10=37.00
Epoch 02 | loss=0.6985 | val_top1=27.68 | val_top5=33.43 | val_top10=36.49
Epoch 03 | loss=0.2078 | val_top1=27.24 | val_top5=33.87 | val_top10=37.22
Epoch 04 | loss=0.0385 | val_top1=27.75 | val_top5=34.16 | val_top10=37.36
Epoch 05 | loss=0.0149 | val_top1=27.46 | val_top5=33.72 | val_top10=37.65

Best validation top1: 27.749453750910416
Test metrics: {'top1': 17.505470459518598, 'top5': 23.063457330415755, 'top10': 26.170678336980306}

================================================================================
[2/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=1.7691 | val_top1=27.02 | val_top5=33.28 | val_top10=36.93
Epoch 02 | loss=0.7523 | val_top1=27.17 | val_top5=32.85 | val_top10=36.34
Epoch 03 | loss=0.3185 | val_top1=26.95 | val_top5=32.92 | val_top10=36.27
Epoch 04 | loss=0.1297 | val_top1=27.09 | val_top5=33.14 | val_top10=36.20
Epoch 05 | loss=0.0682 | val_top1=27.46 | val_top5=32.99 | val_top10=36.27

Best validation top1: 27.458120903131828
Test metrics: {'top1': 18.555798687089716, 'top5': 24.50765864332604, 'top10': 27.26477024070022}

================================================================================
[3/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=1.7698 | val_top1=27.17 | val_top5=33.72 | val_top10=37.51
Epoch 02 | loss=0.6961 | val_top1=27.31 | val_top5=34.38 | val_top10=37.65
Epoch 03 | loss=0.1990 | val_top1=27.68 | val_top5=34.52 | val_top10=37.29
Epoch 04 | loss=0.0434 | val_top1=27.97 | val_top5=34.52 | val_top10=37.29
Epoch 05 | loss=0.0158 | val_top1=28.19 | val_top5=34.60 | val_top10=37.36

Best validation top1: 28.186453022578295
Test metrics: {'top1': 18.205689277899342, 'top5': 23.457330415754925, 'top10': 27.483588621444202}

================================================================================
[4/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=1.7829 | val_top1=27.68 | val_top5=33.28 | val_top10=37.44
Epoch 02 | loss=0.7443 | val_top1=28.55 | val_top5=33.94 | val_top10=36.64
Epoch 03 | loss=0.3090 | val_top1=29.13 | val_top5=34.01 | val_top10=36.71
Epoch 04 | loss=0.1208 | val_top1=28.84 | val_top5=34.01 | val_top10=36.64
Epoch 05 | loss=0.0643 | val_top1=29.28 | val_top5=34.01 | val_top10=36.85

Best validation top1: 29.278951201747997
Test metrics: {'top1': 18.730853391684903, 'top5': 24.72647702407002, 'top10': 27.921225382932167}

================================================================================
[5/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=1.8153 | val_top1=28.33 | val_top5=34.01 | val_top10=37.36
Epoch 02 | loss=0.8707 | val_top1=28.48 | val_top5=34.01 | val_top10=37.87
Epoch 03 | loss=0.3458 | val_top1=28.26 | val_top5=34.52 | val_top10=37.80
Epoch 04 | loss=0.1301 | val_top1=27.82 | val_top5=34.67 | val_top10=38.02
Epoch 05 | loss=0.0599 | val_top1=28.33 | val_top5=35.11 | val_top10=37.87

Best validation top1: 28.477785870356882
Test metrics: {'top1': 16.76148796498906, 'top5': 21.444201312910284, 'top10': 24.463894967177243}

================================================================================
[6/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=1.7570 | val_top1=28.11 | val_top5=33.94 | val_top10=38.16
Epoch 02 | loss=0.8866 | val_top1=28.11 | val_top5=34.38 | val_top10=37.58
Epoch 03 | loss=0.4805 | val_top1=27.53 | val_top5=34.38 | val_top10=37.87
Epoch 04 | loss=0.2801 | val_top1=27.68 | val_top5=34.45 | val_top10=38.16
Epoch 05 | loss=0.1777 | val_top1=27.68 | val_top5=34.16 | val_top10=37.87

Best validation top1: 28.113619810633647
Test metrics: {'top1': 16.98030634573304, 'top5': 21.00656455142232, 'top10': 23.676148796498907}

================================================================================
[7/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=1.8140 | val_top1=27.90 | val_top5=33.65 | val_top10=37.44
Epoch 02 | loss=0.8943 | val_top1=27.90 | val_top5=33.87 | val_top10=37.14
Epoch 03 | loss=0.3615 | val_top1=27.68 | val_top5=33.79 | val_top10=37.58
Epoch 04 | loss=0.1286 | val_top1=27.60 | val_top5=34.09 | val_top10=37.73
Epoch 05 | loss=0.0580 | val_top1=27.53 | val_top5=34.16 | val_top10=37.65

Best validation top1: 27.895120174799708
Test metrics: {'top1': 16.455142231947484, 'top5': 21.13785557986871, 'top10': 23.36980306345733}

================================================================================
[8/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=1.7668 | val_top1=28.55 | val_top5=34.16 | val_top10=37.00
Epoch 02 | loss=0.8818 | val_top1=28.33 | val_top5=34.45 | val_top10=37.14
Epoch 03 | loss=0.4710 | val_top1=28.04 | val_top5=34.52 | val_top10=37.58
Epoch 04 | loss=0.2681 | val_top1=28.04 | val_top5=34.45 | val_top10=37.36
Epoch 05 | loss=0.1666 | val_top1=28.26 | val_top5=34.23 | val_top10=37.58

Best validation top1: 28.55061908230153
Test metrics: {'top1': 17.024070021881837, 'top5': 20.74398249452954, 'top10': 23.50109409190372}

================================================================================
[9/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=1.8867 | val_top1=27.75 | val_top5=33.58 | val_top10=37.29
Epoch 02 | loss=1.0194 | val_top1=27.39 | val_top5=33.14 | val_top10=36.71
Epoch 03 | loss=0.5485 | val_top1=27.17 | val_top5=33.72 | val_top10=37.07
Epoch 04 | loss=0.3573 | val_top1=26.88 | val_top5=33.28 | val_top10=36.85
Epoch 05 | loss=0.2297 | val_top1=27.31 | val_top5=34.09 | val_top10=37.22

Best validation top1: 27.749453750910416
Test metrics: {'top1': 16.673960612691467, 'top5': 20.568927789934353, 'top10': 22.800875273522976}

================================================================================
[10/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=1.8457 | val_top1=27.02 | val_top5=33.65 | val_top10=37.51
Epoch 02 | loss=1.0320 | val_top1=27.68 | val_top5=33.65 | val_top10=36.64
Epoch 03 | loss=0.6620 | val_top1=27.60 | val_top5=33.07 | val_top10=36.93
Epoch 04 | loss=0.4726 | val_top1=27.31 | val_top5=33.50 | val_top10=36.56
Epoch 05 | loss=0.3455 | val_top1=27.39 | val_top5=33.36 | val_top10=36.34

Best validation top1: 27.676620538965768
Test metrics: {'top1': 16.849015317286653, 'top5': 21.794310722100658, 'top10': 24.50765864332604}

================================================================================
[11/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=1.8836 | val_top1=27.90 | val_top5=33.79 | val_top10=37.00
Epoch 02 | loss=0.9841 | val_top1=27.24 | val_top5=34.38 | val_top10=37.73
Epoch 03 | loss=0.5008 | val_top1=27.82 | val_top5=33.50 | val_top10=37.22
Epoch 04 | loss=0.3415 | val_top1=27.24 | val_top5=33.58 | val_top10=37.14
Epoch 05 | loss=0.2207 | val_top1=27.31 | val_top5=33.36 | val_top10=37.36

Best validation top1: 27.895120174799708
Test metrics: {'top1': 16.542669584245075, 'top5': 20.700218818380744, 'top10': 23.063457330415755}

================================================================================
[12/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=1.8645 | val_top1=27.60 | val_top5=33.72 | val_top10=37.95
Epoch 02 | loss=1.0216 | val_top1=28.26 | val_top5=34.52 | val_top10=37.44
Epoch 03 | loss=0.6593 | val_top1=27.60 | val_top5=34.01 | val_top10=37.65
Epoch 04 | loss=0.4571 | val_top1=27.31 | val_top5=34.52 | val_top10=37.29
Epoch 05 | loss=0.3364 | val_top1=27.97 | val_top5=34.01 | val_top10=37.14

Best validation top1: 28.259286234522943
Test metrics: {'top1': 17.024070021881837, 'top5': 21.400437636761488, 'top10': 24.595185995623634}

================================================================================
[13/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=1.9650 | val_top1=27.60 | val_top5=33.94 | val_top10=37.51
Epoch 02 | loss=1.2118 | val_top1=28.40 | val_top5=33.72 | val_top10=37.58
Epoch 03 | loss=0.8073 | val_top1=28.04 | val_top5=34.60 | val_top10=37.87
Epoch 04 | loss=0.6032 | val_top1=27.82 | val_top5=34.38 | val_top10=37.44
Epoch 05 | loss=0.4138 | val_top1=27.68 | val_top5=34.30 | val_top10=37.73

Best validation top1: 28.404952658412235
Test metrics: {'top1': 16.717724288840262, 'top5': 21.53172866520788, 'top10': 23.938730853391686}

================================================================================
[14/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=1.9061 | val_top1=28.04 | val_top5=34.23 | val_top10=37.58
Epoch 02 | loss=1.2228 | val_top1=27.97 | val_top5=33.94 | val_top10=37.87
Epoch 03 | loss=0.9016 | val_top1=27.90 | val_top5=33.72 | val_top10=37.87
Epoch 04 | loss=0.7093 | val_top1=27.75 | val_top5=34.16 | val_top10=37.65
Epoch 05 | loss=0.5803 | val_top1=27.75 | val_top5=34.23 | val_top10=37.44

Best validation top1: 28.040786598689003
Test metrics: {'top1': 16.805251641137854, 'top5': 20.568927789934353, 'top10': 23.457330415754925}

================================================================================
[15/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=1.9626 | val_top1=27.75 | val_top5=33.43 | val_top10=37.80
Epoch 02 | loss=1.2693 | val_top1=27.75 | val_top5=34.23 | val_top10=38.60
Epoch 03 | loss=0.8149 | val_top1=27.60 | val_top5=34.67 | val_top10=38.60
Epoch 04 | loss=0.5822 | val_top1=27.68 | val_top5=34.45 | val_top10=38.53
Epoch 05 | loss=0.4446 | val_top1=27.75 | val_top5=35.18 | val_top10=38.16

Best validation top1: 27.749453750910416
Test metrics: {'top1': 16.63019693654267, 'top5': 21.094091903719914, 'top10': 23.41356673960613}

================================================================================
[16/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=1.8901 | val_top1=28.33 | val_top5=34.16 | val_top10=38.09
Epoch 02 | loss=1.2488 | val_top1=28.11 | val_top5=34.74 | val_top10=38.31
Epoch 03 | loss=0.9402 | val_top1=28.26 | val_top5=34.81 | val_top10=38.53
Epoch 04 | loss=0.7389 | val_top1=28.55 | val_top5=34.67 | val_top10=38.31
Epoch 05 | loss=0.6024 | val_top1=28.62 | val_top5=34.67 | val_top10=37.36

Best validation top1: 28.623452294246178
Test metrics: {'top1': 16.849015317286653, 'top5': 21.925601750547045, 'top10': 25.164113785557987}

================================================================================
[17/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=1.7253 | val_top1=27.68 | val_top5=34.09 | val_top10=37.87
Epoch 02 | loss=0.6373 | val_top1=27.39 | val_top5=34.81 | val_top10=38.02
Epoch 03 | loss=0.1510 | val_top1=27.31 | val_top5=34.52 | val_top10=38.16
Epoch 04 | loss=0.0312 | val_top1=27.39 | val_top5=34.45 | val_top10=38.53
Epoch 05 | loss=0.0139 | val_top1=27.46 | val_top5=34.30 | val_top10=38.46

Best validation top1: 27.676620538965768
Test metrics: {'top1': 16.542669584245075, 'top5': 21.2253829321663, 'top10': 23.807439824945295}

================================================================================
[18/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=1.6991 | val_top1=27.90 | val_top5=34.45 | val_top10=37.95
Epoch 02 | loss=0.6782 | val_top1=27.97 | val_top5=34.52 | val_top10=37.65
Epoch 03 | loss=0.2711 | val_top1=27.97 | val_top5=34.23 | val_top10=37.36
Epoch 04 | loss=0.1100 | val_top1=28.19 | val_top5=34.23 | val_top10=37.44
Epoch 05 | loss=0.0620 | val_top1=28.48 | val_top5=33.94 | val_top10=37.22

Best validation top1: 28.477785870356882
Test metrics: {'top1': 18.905908096280086, 'top5': 25.426695842450766, 'top10': 28.577680525164112}

================================================================================
[19/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=1.7285 | val_top1=27.68 | val_top5=34.01 | val_top10=37.58
Epoch 02 | loss=0.6420 | val_top1=27.68 | val_top5=34.23 | val_top10=37.51
Epoch 03 | loss=0.1688 | val_top1=27.90 | val_top5=34.45 | val_top10=38.09
Epoch 04 | loss=0.0315 | val_top1=27.53 | val_top5=34.67 | val_top10=37.80
Epoch 05 | loss=0.0138 | val_top1=27.90 | val_top5=34.52 | val_top10=37.73

Best validation top1: 27.895120174799708
Test metrics: {'top1': 17.98687089715536, 'top5': 23.23851203501094, 'top10': 26.87089715536105}

================================================================================
[20/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=1.7151 | val_top1=27.97 | val_top5=33.65 | val_top10=37.29
Epoch 02 | loss=0.6917 | val_top1=28.40 | val_top5=33.79 | val_top10=37.00
Epoch 03 | loss=0.2779 | val_top1=27.75 | val_top5=33.58 | val_top10=37.80
Epoch 04 | loss=0.1121 | val_top1=28.04 | val_top5=33.94 | val_top10=37.07
Epoch 05 | loss=0.0615 | val_top1=27.90 | val_top5=33.43 | val_top10=37.00

Best validation top1: 28.404952658412235
Test metrics: {'top1': 17.417943107221006, 'top5': 22.36323851203501, 'top10': 25.12035010940919}

================================================================================
[21/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=1.7578 | val_top1=28.26 | val_top5=34.74 | val_top10=38.24
Epoch 02 | loss=0.8095 | val_top1=27.97 | val_top5=34.96 | val_top10=38.46
Epoch 03 | loss=0.2984 | val_top1=27.75 | val_top5=35.40 | val_top10=38.60
Epoch 04 | loss=0.1011 | val_top1=27.97 | val_top5=35.25 | val_top10=39.04
Epoch 05 | loss=0.0504 | val_top1=27.97 | val_top5=35.32 | val_top10=38.46

Best validation top1: 28.259286234522943
Test metrics: {'top1': 17.330415754923415, 'top5': 21.575492341356675, 'top10': 23.544857768052516}

================================================================================
[22/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=1.7568 | val_top1=29.35 | val_top5=34.96 | val_top10=37.87
Epoch 02 | loss=0.8682 | val_top1=28.91 | val_top5=35.62 | val_top10=38.46
Epoch 03 | loss=0.4548 | val_top1=28.99 | val_top5=35.62 | val_top10=38.75
Epoch 04 | loss=0.2563 | val_top1=28.77 | val_top5=35.47 | val_top10=38.38
Epoch 05 | loss=0.1607 | val_top1=28.70 | val_top5=35.47 | val_top10=38.24

Best validation top1: 29.351784413692645
Test metrics: {'top1': 17.286652078774615, 'top5': 21.88183807439825, 'top10': 24.026258205689278}

================================================================================
[23/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=1.7439 | val_top1=28.55 | val_top5=35.25 | val_top10=38.46
Epoch 02 | loss=0.7751 | val_top1=28.19 | val_top5=35.18 | val_top10=38.97
Epoch 03 | loss=0.2730 | val_top1=27.97 | val_top5=35.32 | val_top10=38.75
Epoch 04 | loss=0.0949 | val_top1=28.11 | val_top5=35.62 | val_top10=38.82
Epoch 05 | loss=0.0492 | val_top1=28.33 | val_top5=35.62 | val_top10=38.75

Best validation top1: 28.55061908230153
Test metrics: {'top1': 17.592997811816193, 'top5': 22.056892778993436, 'top10': 24.15754923413567}

================================================================================
[24/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=1.7367 | val_top1=28.62 | val_top5=34.81 | val_top10=38.38
Epoch 02 | loss=0.8617 | val_top1=28.40 | val_top5=35.69 | val_top10=39.11
Epoch 03 | loss=0.4630 | val_top1=28.48 | val_top5=35.62 | val_top10=39.26
Epoch 04 | loss=0.2658 | val_top1=28.48 | val_top5=35.62 | val_top10=39.04
Epoch 05 | loss=0.1660 | val_top1=28.62 | val_top5=35.69 | val_top10=39.04

Best validation top1: 28.623452294246178
Test metrics: {'top1': 17.592997811816193, 'top5': 22.188183807439824, 'top10': 24.332603938730852}

================================================================================
[25/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=1.8017 | val_top1=28.11 | val_top5=34.01 | val_top10=38.31
Epoch 02 | loss=0.9292 | val_top1=27.90 | val_top5=34.45 | val_top10=38.75
Epoch 03 | loss=0.5098 | val_top1=27.97 | val_top5=35.11 | val_top10=38.67
Epoch 04 | loss=0.2974 | val_top1=27.97 | val_top5=34.38 | val_top10=38.02
Epoch 05 | loss=0.1911 | val_top1=28.04 | val_top5=34.30 | val_top10=37.51

Best validation top1: 28.113619810633647
Test metrics: {'top1': 16.805251641137854, 'top5': 21.312910284463896, 'top10': 23.588621444201312}

================================================================================
[26/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=1.7897 | val_top1=28.19 | val_top5=34.67 | val_top10=37.73

,exp_name,input_dim,output_dim,dropout,lr,weight_decay,batch_size,temperature,best_val_top1,val_top1,val_top5,val_top10,test_top1,test_top5,test_top10
21,dim256_drop0p0_lr0.0002_wd0.0001_temp0p1,1024,256,0.0,0.0002,0.00010,32,0.10,29.351784,29.351784,34.959942,37.873270,17.286652,21.881838,24.026258
3,dim128_drop0p0_lr0.0005_wd1e-05_temp0p1,1024,128,0.0,0.0005,0.00001,32,0.10,29.278951,29.278951,34.013110,36.853605,18.730853,24.726477,27.921225
29,dim256_drop0p1_lr0.0002_wd0.0001_temp0p1,1024,256,0.1,0.0002,0.00010,32,0.10,28.987618,28.987618,34.959942,38.601602,17.417943,22.494530,25.382932
28,dim256_drop0p1_lr0.0002_wd0.0001_temp0p07,1024,256,0.1,0.0002,0.00010,32,0.07,28.841952,28.841952,35.324108,39.184268,17.592998,21.269147,23.501094
31,dim256_drop0p1_lr0.0002_wd1e-05_temp0p1,1024,256,0.1,0.0002,0.00001,32,0.10,28.769119,28.769119,34.668609,38.674436,17.549234,21.312910,23.632385
30,dim256_drop0p1_lr0.0002_wd1e-05_temp0p07,1024,256,0.1,0.0002,0.00001,32,0.07,28.696286,28.696286,34.959942,39.329934,17.111597,21.619256,23.938731
23,dim256_drop0p0_lr0.0002_wd1e-05_temp0p1,1024,256,0.0,0.0002,0.00001,32,0.10,28.623452,28.623452,34.814275,38.383103,17.592998,22.188184,24.332604
15,dim128_drop0p1_lr0.0002_wd1e-05_temp0p1,1024,128,0.1,0.0002,0.00001,32,0.10,28.623452,28.623452,34.668609,37.363438,16.849015,21.925602,25.164114
22,dim256_drop0p0_lr0.0002_wd1e-05_temp0p07,1024,256,0.0,0.0002,0.00001,32,0.07,28.550619,28.550619,35.251275,38.455936,17.592998,22.056893,24.157549
7,dim128_drop0p0_lr0.0002_wd1e-05_temp0p1,1024,128,0.0,0.0002,0.00001,32,0.10,28.550619,28.550619,34.158776,36.999272,17.024070,20.743982,23.501094
4,dim128_drop0p0_lr0.0002_wd0.0001_temp0p07,1024,128,0.0,0.0002,0.00010,32,0.07,28.477786,28.477786,34.013110,37.873270,16.761488,21.444201,24.463895
17,dim256_drop0p0_lr0.0005_wd0.0001_temp0p1,1024,256,0.0,0.0005,0.00010,32,0.10,28.477786,28.477786,33.940277,37.217771,18.905908,25.426696,28.577681
19,dim256_drop0p0_lr0.0005_wd1e-05_temp0p1,1024,256,0.0,0.0005,0.00001,32,0.10,28.404953,28.404953,33.794610,36.999272,17.417943,22.363239,25.120350
25,dim256_drop0p1_lr0.0005_wd0.0001_temp0p1,1024,256,0.1,0.0005,0.00010,32,0.10,28.404953,28.404953,33.940277,37.581937,17.461707,21.969365,24.420131
12,dim128_drop0p1_lr0.0002_wd0.0001_temp0p07,1024,128,0.1,0.0002,0.00010,32,0.07,28.404953,28.404953,33.721777,37.581937,16.717724,21.531729,23.938731
11,dim128_drop0p1_lr0.0005_wd1e-05_temp0p1,1024,128,0.1,0.0005,0.00001,32,0.10,28.259286,28.259286,34.522942,37.436271,17.024070,21.400438,24.595186
20,dim256_drop0p0_lr0.0002_wd0.0001_temp0p07,1024,256,0.0,0.0002,0.00010,32,0.07,28.259286,28.259286,34.741442,38.237436,17.330416,21.575492,23.544858
2,dim128_drop0p0_lr0.0005_wd1e-05_temp0p07,1024,128,0.0,0.0005,0.00001,32,0.07,28.186453,28.186453,34.595776,37.363438,18.205689,23.457330,27.483589
27,dim256_drop0p1_lr0.0005_wd1e-05_temp0p1,1024,256,0.1,0.0005,0.00001,32,0.10,28.113620,28.113620,33.940277,37.144938,17.024070,22.100656,24.288840
5,dim128_drop0p0_lr0.0002_wd0.0001_temp0p1,1024,128,0.0,0.0002,0.00010,32,0.10,28.113620,28.113620,33.940277,38.164603,16.980306,21.006565,23.676149
24,dim256_drop0p1_lr0.0005_wd0.0001_temp0p07,1024,256,0.1,0.0005,0.00010,32,0.07,28.113620,28.113620,34.013110,38.310269,16.805252,21.312910,23.588621
13,dim128_drop0p1_lr0.0002_wd0.0001_temp0p1,1024,128,0.1,0.0002,0.00010,32,0.10,28.040787,28.040787,34.231610,37.581937,16.805252,20.568928,23.457330
26,dim256_drop0p1_lr0.0005_wd1e-05_temp0p07,1024,256,0.1,0.0005,0.00001,32,0.07,27.967953,27.967953,34.085943,36.999272,17.549234,23.150985,26.345733
18,dim256_drop0p0_lr0.0005_wd1e-05_temp0p07,1024,256,0.0,0.0005,0.00001,32,0.07,27.895120,27.895120,34.450109,38.091770,17.986871,23.238512,26.870897
10,dim128_drop0p1_lr0.0005_wd1e-05_temp0p07,1024,128,0.1,0.0005,0.00001,32,0.07,27.895120,27.895120,33.794610,36.999272,16.542670,20.700219,23.063457
6,dim128_drop0p0_lr0.0002_wd1e-05_temp0p07,1024,128,0.0,0.0002,0.00001,32,0.07,27.895120,27.895120,33.648944,37.436271,16.455142,21.137856,23.369803
0,dim128_drop0p0_lr0.0005_wd0.0001_temp0p07,1024,128,0.0,0.0005,0.00010,32,0.07,27.749454,27.749454,34.158776,37.363438,17.505470,23.063457,26.170678
14,dim128_drop0p1_lr0.0002_wd1e-05_temp0p07,1024,128,0.1,0.0002,0.00001,32,0.07,27.749454,27.749454,33.430444,37.800437,16.630197,21.094092,23.413567
8,dim128_drop0p1_lr0.0005_wd0.0001_temp0p07,1024,128,0.1,0.0005,0.00010,32,0.07,27.749454,27.749454,33.576111,37.290605,16.673961,20.568928,22.800875
9,dim128_drop0p1_lr0.0005_wd0.0001_temp0p1,1024,128,0.1,0.0005,0.00010,32,0.10,27.676621,27.676621,33.648944,36.635106,16.849015,21.794311,24.507659
16,dim256_drop0p0_lr0.0005_wd0.0001_temp0p07,1024,256,0.0,0.0005,0.00010,32,0.07,27.676621,27.676621,34.085943,37.873270,16.542670,21.225383,23.807440
1,dim128_drop0p0_lr0.0005_wd0.0001_temp0p1,1024,128,0.0,0.0005,0.00010,32,0.10,27.458121,27.458121,32.993445,36.270940,18.555799,24.507659,27.264770

In [6]:
import pandas as pd

train_df = pd.read_csv(ROOT / "dataset/task3_cislr/splits/train_repeated.csv")
val_df = pd.read_csv(ROOT / "dataset/task3_cislr/splits/val_repeated.csv")
test_df = pd.read_csv(ROOT / "dataset/task3_cislr/splits/test.csv")
proto_df = pd.read_csv(ROOT / "dataset/task3_cislr/splits/prototype.csv")

train_glosses = set(train_df["gloss"].unique())
val_glosses = set(val_df["gloss"].unique())
test_glosses = set(test_df["gloss"].unique())
proto_glosses = set(proto_df["gloss"].unique())

missing_val_in_proto = sorted(val_glosses - proto_glosses)
missing_test_in_proto = sorted(test_glosses - proto_glosses)

print("Unique gloss counts")
print("train:", len(train_glosses))
print("val:", len(val_glosses))
print("test:", len(test_glosses))
print("prototype:", len(proto_glosses))

print("\nMissing val glosses in prototype:", len(missing_val_in_proto))
print(missing_val_in_proto[:20])

print("\nMissing test glosses in prototype:", len(missing_test_in_proto))
print(missing_test_in_proto[:20])

Unique gloss counts
train: 1363
val: 1363
test: 1363
prototype: 4765

Missing val glosses in prototype: 0
[]

Missing test glosses in prototype: 0
[]

In [ ]:
import pandas as pd

from src.utils.expand_grid import expand_grid
from src.tasks.task3_cislr.training.train_retreival import run_training
from src.tasks.task3_cislr.models.maxpool_projection import MaxPoolProjectionV2

MaxPoolProjectionV2_grid = {
    "output_dim": [64, 128, 256],
    "input_dim": [1024],
    "dropout": [0.0, 0.1],
    "lr": [1e-3, 5e-4],
    "weight_decay": [1e-4],
    "batch_size": [32],
    "temperature": [0.07, 0.1],
}
NUM_EPOCHS = 20
configs = expand_grid(MaxPoolProjectionV2_grid)
print(f"Total configs: {len(configs)}")
print("Sample config:", configs[0])

all_results = []

for i, cfg in enumerate(configs, start=1):
    print("\n" + "=" * 80)
    print(f"[{i}/{len(configs)}] Running MaxPoolProjectionV2 with config:")
    print(cfg)

    exp_name = (
        f"mpv2_dim{cfg['output_dim']}_"
        f"drop{str(cfg['dropout']).replace('.', 'p')}_"
        f"lr{cfg['lr']}_"
        f"wd{cfg['weight_decay']}_"
        f"temp{str(cfg['temperature']).replace('.', 'p')}"
    )

    try:
        model = MaxPoolProjectionV2(
            input_dim=cfg["input_dim"],
            hidden_dim=cfg["output_dim"] * 2,
            out_dim=cfg["output_dim"],
            dropout=cfg["dropout"],
        )

        results = run_training(
            train_csv=ROOT / "dataset/task3_cislr/splits/train_repeated.csv",
            val_csv=ROOT / "dataset/task3_cislr/splits/val_repeated.csv",
            prototype_csv=ROOT / "dataset/task3_cislr/splits/prototype.csv",
            test_csv=ROOT / "dataset/task3_cislr/splits/test.csv",
            feature_pkl=ROOT / "dataset/task3_cislr/features/I3D_features.pkl",
            out_dir=ROOT / "results/task3_cislr/maxpool_projection_v2_gridsearch" / exp_name,
            batch_size=cfg["batch_size"],
            num_workers=0,
            pooling="max",
            lr=cfg["lr"],
            weight_decay=cfg["weight_decay"],
            temperature=cfg["temperature"],
            epochs=NUM_EPOCHS,
            model=model,
        )
        
        row = {
            "exp_name": exp_name,
            **cfg,
            "best_val_top1": results["best_val_top1"],
            "val_top1": results["best_val_metrics"]["top1"],
            "val_top5": results["best_val_metrics"]["top5"],
            "val_top10": results["best_val_metrics"]["top10"],
            "test_top1": results["test_metrics"]["top1"],
            "test_top5": results["test_metrics"]["top5"],
            "test_top10": results["test_metrics"]["top10"],
        }
        all_results.append(row)
        df = pd.DataFrame(all_results)
        df.to_csv(ROOT / "results/task3_cislr/maxpool_projection_v2_gridsearch_results.csv", index=False)


    except Exception as e:
        print(f"Failed config: {cfg}")
        print("Error:", e)
        all_results.append({
            "exp_name": exp_name,
            **cfg,
            "error": str(e),
        })

Total configs: 24
Sample config: {'output_dim': 64, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}

================================================================================
[1/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 64, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=2.0651 | val_top1=93.88 | val_top5=94.03 | val_top10=94.03
Epoch 02 | loss=1.2754 | val_top1=93.81 | val_top5=94.10 | val_top10=94.10
Epoch 03 | loss=0.7982 | val_top1=93.88 | val_top5=94.10 | val_top10=94.10
Epoch 04 | loss=0.4974 | val_top1=93.81 | val_top5=94.03 | val_top10=94.17
Epoch 05 | loss=0.2623 | val_top1=93.88 | val_top5=94.03 | val_top10=94.25
Epoch 06 | loss=0.1366 | val_top1=93.74 | val_top5=94.10 | val_top10=94.17
Early stopping triggered at epoch 6.

Best validation top1: 93.88201019664967
Test metrics: {'top1': 14.00437636761488, 'top5': 17.855579868708972, 'top10': 19.474835886214443}

================================================================================
[2/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 64, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=2.1427 | val_top1=93.88 | val_top5=93.95 | val_top10=94.03
Epoch 02 | loss=1.3892 | val_top1=93.88 | val_top5=93.95 | val_top10=93.95
Epoch 03 | loss=0.8312 | val_top1=93.81 | val_top5=94.10 | val_top10=94.10
Epoch 04 | loss=0.5088 | val_top1=93.81 | val_top5=93.88 | val_top10=94.03
Epoch 05 | loss=0.3184 | val_top1=93.88 | val_top5=93.95 | val_top10=94.03
Epoch 06 | loss=0.1744 | val_top1=93.88 | val_top5=94.03 | val_top10=94.17
Early stopping triggered at epoch 6.

Best validation top1: 93.88201019664967
Test metrics: {'top1': 13.87308533916849, 'top5': 17.505470459518598, 'top10': 19.34354485776805}

================================================================================
[3/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 64, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=1.9563 | val_top1=93.88 | val_top5=94.03 | val_top10=94.10
Epoch 02 | loss=1.0847 | val_top1=93.95 | val_top5=94.17 | val_top10=94.17
Epoch 03 | loss=0.5437 | val_top1=94.03 | val_top5=94.25 | val_top10=94.32
Epoch 04 | loss=0.2498 | val_top1=94.10 | val_top5=94.17 | val_top10=94.25
Epoch 05 | loss=0.0930 | val_top1=93.95 | val_top5=94.10 | val_top10=94.25
Epoch 06 | loss=0.0291 | val_top1=94.03 | val_top5=94.25 | val_top10=94.46
Epoch 07 | loss=0.0106 | val_top1=94.03 | val_top5=94.32 | val_top10=94.46
Epoch 08 | loss=0.0077 | val_top1=94.03 | val_top5=94.32 | val_top10=94.46
Epoch 09 | loss=0.0065 | val_top1=94.03 | val_top5=94.32 | val_top10=94.46
Early stopping triggered at epoch 9.

Best validation top1: 94.10050983248361
Test metrics: {'top1': 14.967177242888402, 'top5': 18.687089715536104, 'top10': 20.787746170678336}

================================================================================
[4/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 64, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=2.0157 | val_top1=93.88 | val_top5=94.10 | val_top10=94.17
Epoch 02 | loss=1.1577 | val_top1=93.81 | val_top5=93.95 | val_top10=94.10
Epoch 03 | loss=0.6170 | val_top1=93.88 | val_top5=94.03 | val_top10=94.17
Epoch 04 | loss=0.3066 | val_top1=93.88 | val_top5=93.88 | val_top10=93.95
Epoch 05 | loss=0.1518 | val_top1=93.88 | val_top5=94.03 | val_top10=94.03
Epoch 06 | loss=0.0833 | val_top1=93.95 | val_top5=94.03 | val_top10=94.32
Epoch 07 | loss=0.0515 | val_top1=93.88 | val_top5=94.17 | val_top10=94.32
Epoch 08 | loss=0.0378 | val_top1=93.81 | val_top5=94.17 | val_top10=94.32
Epoch 09 | loss=0.0300 | val_top1=93.81 | val_top5=94.10 | val_top10=94.32
Epoch 10 | loss=0.0250 | val_top1=93.88 | val_top5=94.10 | val_top10=94.32
Epoch 11 | loss=0.0215 | val_top1=93.88 | val_top5=94.03 | val_top10=94.32
Early stopping triggered at epoch 11.

Best validation top1: 93.95484340859431
Test metrics: {'top1': 15.098468271334792, 'top5': 19.387308533916848, 'top10': 22.27571115973742}

================================================================================
[5/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 64, 'input_dim': 1024, 'dropout': 0.1, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=2.3835 | val_top1=93.88 | val_top5=94.03 | val_top10=94.10
Epoch 02 | loss=1.8542 | val_top1=93.88 | val_top5=94.03 | val_top10=94.03
Epoch 03 | loss=1.4610 | val_top1=93.81 | val_top5=93.88 | val_top10=93.88
Epoch 04 | loss=1.3943 | val_top1=93.66 | val_top5=93.95 | val_top10=93.95
Epoch 05 | loss=1.1212 | val_top1=93.81 | val_top5=93.95 | val_top10=94.10
Epoch 06 | loss=0.9581 | val_top1=93.74 | val_top5=93.88 | val_top10=93.88
Early stopping triggered at epoch 6.

Best validation top1: 93.88201019664967
Test metrics: {'top1': 13.87308533916849, 'top5': 16.849015317286653, 'top10': 18.687089715536104}

================================================================================
[6/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 64, 'input_dim': 1024, 'dropout': 0.1, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=2.3698 | val_top1=93.81 | val_top5=93.88 | val_top10=94.03
Epoch 02 | loss=1.8655 | val_top1=93.88 | val_top5=94.03 | val_top10=94.03
Epoch 03 | loss=1.5304 | val_top1=93.74 | val_top5=93.88 | val_top10=94.03
Epoch 04 | loss=1.3305 | val_top1=93.74 | val_top5=93.81 | val_top10=93.81
Epoch 05 | loss=1.2657 | val_top1=93.81 | val_top5=93.88 | val_top10=93.88
Epoch 06 | loss=1.1664 | val_top1=93.74 | val_top5=93.88 | val_top10=93.95
Epoch 07 | loss=1.0623 | val_top1=93.74 | val_top5=93.81 | val_top10=93.95
Early stopping triggered at epoch 7.

Best validation top1: 93.88201019664967
Test metrics: {'top1': 13.435448577680525, 'top5': 16.2363238512035, 'top10': 17.72428884026258}

================================================================================
[7/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 64, 'input_dim': 1024, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=2.2343 | val_top1=93.88 | val_top5=94.17 | val_top10=94.25
Epoch 02 | loss=1.6489 | val_top1=93.88 | val_top5=94.03 | val_top10=94.03
Epoch 03 | loss=1.3538 | val_top1=93.81 | val_top5=93.95 | val_top10=93.95
Epoch 04 | loss=1.1329 | val_top1=93.88 | val_top5=94.10 | val_top10=94.10
Epoch 05 | loss=0.9029 | val_top1=93.81 | val_top5=93.95 | val_top10=94.17
Epoch 06 | loss=0.8437 | val_top1=93.81 | val_top5=93.88 | val_top10=93.88
Early stopping triggered at epoch 6.

Best validation top1: 93.88201019664967
Test metrics: {'top1': 14.529540481400439, 'top5': 17.899343544857768, 'top10': 19.86870897155361}

================================================================================
[8/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 64, 'input_dim': 1024, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=2.2015 | val_top1=93.95 | val_top5=94.10 | val_top10=94.17
Epoch 02 | loss=1.6531 | val_top1=93.88 | val_top5=94.03 | val_top10=94.03
Epoch 03 | loss=1.3741 | val_top1=93.88 | val_top5=94.10 | val_top10=94.25
Epoch 04 | loss=1.1385 | val_top1=93.81 | val_top5=94.03 | val_top10=94.17
Epoch 05 | loss=1.0284 | val_top1=93.81 | val_top5=93.88 | val_top10=94.03
Epoch 06 | loss=0.8529 | val_top1=93.88 | val_top5=94.03 | val_top10=94.32
Early stopping triggered at epoch 6.

Best validation top1: 93.95484340859431
Test metrics: {'top1': 14.485776805251641, 'top5': 17.24288840262582, 'top10': 19.562363238512035}

================================================================================
[9/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 128, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=2.0478 | val_top1=93.81 | val_top5=94.03 | val_top10=94.10
Epoch 02 | loss=1.3202 | val_top1=93.81 | val_top5=93.95 | val_top10=94.03
Epoch 03 | loss=0.8158 | val_top1=93.74 | val_top5=94.10 | val_top10=94.25
Epoch 04 | loss=0.5086 | val_top1=93.81 | val_top5=94.03 | val_top10=94.17
Epoch 05 | loss=0.2983 | val_top1=93.66 | val_top5=94.03 | val_top10=94.17
Epoch 06 | loss=0.1147 | val_top1=93.74 | val_top5=93.95 | val_top10=94.03
Early stopping triggered at epoch 6.

Best validation top1: 93.80917698470502
Test metrics: {'top1': 14.135667396061269, 'top5': 17.37417943107221, 'top10': 19.91247264770241}

================================================================================
[10/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 128, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=2.0569 | val_top1=93.81 | val_top5=94.17 | val_top10=94.17
Epoch 02 | loss=1.2812 | val_top1=93.88 | val_top5=94.03 | val_top10=94.10
Epoch 03 | loss=0.8077 | val_top1=93.81 | val_top5=94.03 | val_top10=94.32
Epoch 04 | loss=0.4790 | val_top1=93.88 | val_top5=94.03 | val_top10=94.32
Epoch 05 | loss=0.2903 | val_top1=93.88 | val_top5=94.10 | val_top10=94.17
Epoch 06 | loss=0.1698 | val_top1=93.88 | val_top5=94.10 | val_top10=94.17
Epoch 07 | loss=0.0822 | val_top1=93.81 | val_top5=94.10 | val_top10=94.25
Early stopping triggered at epoch 7.

Best validation top1: 93.88201019664967
Test metrics: {'top1': 14.135667396061269, 'top5': 17.72428884026258, 'top10': 20.043763676148796}

================================================================================
[11/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 128, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=1.9119 | val_top1=93.88 | val_top5=94.03 | val_top10=94.10
Epoch 02 | loss=1.0315 | val_top1=93.88 | val_top5=94.17 | val_top10=94.32
Epoch 03 | loss=0.4866 | val_top1=93.95 | val_top5=94.03 | val_top10=94.25
Epoch 04 | loss=0.2166 | val_top1=93.95 | val_top5=94.03 | val_top10=94.17
Epoch 05 | loss=0.0720 | val_top1=94.03 | val_top5=94.17 | val_top10=94.25
Epoch 06 | loss=0.0196 | val_top1=94.10 | val_top5=94.39 | val_top10=94.39
Epoch 07 | loss=0.0074 | val_top1=94.03 | val_top5=94.39 | val_top10=94.39
Epoch 08 | loss=0.0057 | val_top1=94.10 | val_top5=94.39 | val_top10=94.39
Epoch 09 | loss=0.0048 | val_top1=94.10 | val_top5=94.39 | val_top10=94.39
Epoch 10 | loss=0.0042 | val_top1=94.10 | val_top5=94.39 | val_top10=94.39
Epoch 11 | loss=0.0038 | val_top1=94.03 | val_top5=94.39 | val_top10=94.39
Early stopping triggered at epoch 11.

Best validation top1: 94.10050983248361
Test metrics: {'top1': 16.717724288840262, 'top5': 21.53172866520788, 'top10': 24.595185995623634}

================================================================================
[12/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 128, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=1.9850 | val_top1=93.95 | val_top5=94.03 | val_top10=94.25
Epoch 02 | loss=1.0457 | val_top1=93.95 | val_top5=93.95 | val_top10=94.17
Epoch 03 | loss=0.5265 | val_top1=93.95 | val_top5=94.10 | val_top10=94.10
Epoch 04 | loss=0.2467 | val_top1=93.95 | val_top5=94.10 | val_top10=94.39
Epoch 05 | loss=0.1083 | val_top1=93.95 | val_top5=94.03 | val_top10=94.39
Epoch 06 | loss=0.0483 | val_top1=93.95 | val_top5=94.39 | val_top10=94.46
Early stopping triggered at epoch 6.

Best validation top1: 93.95484340859431
Test metrics: {'top1': 15.317286652078774, 'top5': 19.080962800875273, 'top10': 21.269146608315097}

================================================================================
[13/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 128, 'input_dim': 1024, 'dropout': 0.1, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=2.3350 | val_top1=93.74 | val_top5=94.03 | val_top10=94.03
Epoch 02 | loss=1.7489 | val_top1=93.81 | val_top5=93.95 | val_top10=94.10
Epoch 03 | loss=1.3321 | val_top1=93.81 | val_top5=94.03 | val_top10=94.03
Epoch 04 | loss=1.1325 | val_top1=93.81 | val_top5=93.95 | val_top10=94.17
Epoch 05 | loss=0.9197 | val_top1=93.81 | val_top5=94.03 | val_top10=94.32
Epoch 06 | loss=0.7839 | val_top1=93.81 | val_top5=94.10 | val_top10=94.17
Epoch 07 | loss=0.6600 | val_top1=93.88 | val_top5=93.88 | val_top10=93.88
Epoch 08 | loss=0.5871 | val_top1=93.81 | val_top5=93.95 | val_top10=94.25
Epoch 09 | loss=0.4773 | val_top1=93.88 | val_top5=93.95 | val_top10=94.25
Epoch 10 | loss=0.3910 | val_top1=93.81 | val_top5=94.03 | val_top10=94.32
Epoch 11 | loss=0.3850 | val_top1=93.88 | val_top5=93.95 | val_top10=94.25
Epoch 12 | loss=0.2680 | val_top1=93.74 | val_top5=94.03 | val_top10=94.10
Early stopping triggered at epoch 12.

Best validation top1: 93.88201019664967
Test metrics: {'top1': 13.785557986870897, 'top5': 16.98030634573304, 'top10': 18.687089715536104}

================================================================================
[14/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 128, 'input_dim': 1024, 'dropout': 0.1, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=2.2606 | val_top1=93.95 | val_top5=93.95 | val_top10=94.03
Epoch 02 | loss=1.6722 | val_top1=93.88 | val_top5=93.95 | val_top10=94.17
Epoch 03 | loss=1.2652 | val_top1=93.88 | val_top5=93.95 | val_top10=94.03
Epoch 04 | loss=1.0455 | val_top1=93.95 | val_top5=94.03 | val_top10=94.17
Epoch 05 | loss=1.0937 | val_top1=93.81 | val_top5=94.03 | val_top10=94.10
Epoch 06 | loss=1.0433 | val_top1=93.74 | val_top5=94.03 | val_top10=94.03
Early stopping triggered at epoch 6.

Best validation top1: 93.95484340859431
Test metrics: {'top1': 14.048140043763675, 'top5': 17.37417943107221, 'top10': 18.905908096280086}

================================================================================
[15/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 128, 'input_dim': 1024, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=2.1314 | val_top1=93.88 | val_top5=93.95 | val_top10=94.03
Epoch 02 | loss=1.5710 | val_top1=93.81 | val_top5=94.03 | val_top10=94.03
Epoch 03 | loss=1.2052 | val_top1=93.74 | val_top5=94.10 | val_top10=94.10
Epoch 04 | loss=0.9300 | val_top1=93.81 | val_top5=94.17 | val_top10=94.25
Epoch 05 | loss=0.7460 | val_top1=93.95 | val_top5=94.03 | val_top10=94.10
Epoch 06 | loss=0.6102 | val_top1=93.88 | val_top5=94.03 | val_top10=94.03
Epoch 07 | loss=0.5577 | val_top1=93.95 | val_top5=94.03 | val_top10=94.03
Epoch 08 | loss=0.4503 | val_top1=93.81 | val_top5=93.88 | val_top10=93.95
Epoch 09 | loss=0.3947 | val_top1=93.88 | val_top5=94.10 | val_top10=94.39
Epoch 10 | loss=0.3072 | val_top1=93.81 | val_top5=94.10 | val_top10=94.32
Early stopping triggered at epoch 10.

Best validation top1: 93.95484340859431
Test metrics: {'top1': 14.74835886214442, 'top5': 18.161925601750546, 'top10': 20.437636761487965}

================================================================================
[16/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 128, 'input_dim': 1024, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=2.1546 | val_top1=94.03 | val_top5=94.03 | val_top10=94.17
Epoch 02 | loss=1.5365 | val_top1=93.95 | val_top5=94.03 | val_top10=94.17
Epoch 03 | loss=1.0955 | val_top1=93.95 | val_top5=94.10 | val_top10=94.17
Epoch 04 | loss=0.8683 | val_top1=93.81 | val_top5=94.17 | val_top10=94.32
Epoch 05 | loss=0.6800 | val_top1=93.88 | val_top5=94.10 | val_top10=94.10
Epoch 06 | loss=0.4898 | val_top1=93.81 | val_top5=94.03 | val_top10=94.17
Early stopping triggered at epoch 6.

Best validation top1: 94.02767662053897
Test metrics: {'top1': 15.0109409190372, 'top5': 18.555798687089716, 'top10': 20.612691466083152}

================================================================================
[17/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 256, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=2.0921 | val_top1=93.81 | val_top5=93.95 | val_top10=94.03
Epoch 02 | loss=1.3744 | val_top1=93.74 | val_top5=94.17 | val_top10=94.25
Epoch 03 | loss=0.9003 | val_top1=93.81 | val_top5=94.17 | val_top10=94.17
Epoch 04 | loss=0.5899 | val_top1=93.74 | val_top5=93.95 | val_top10=94.10
Epoch 05 | loss=0.3372 | val_top1=93.88 | val_top5=94.17 | val_top10=94.32
Epoch 06 | loss=0.1961 | val_top1=93.95 | val_top5=94.03 | val_top10=94.10
Epoch 07 | loss=0.1416 | val_top1=93.95 | val_top5=94.17 | val_top10=94.32
Epoch 08 | loss=0.0638 | val_top1=93.81 | val_top5=94.17 | val_top10=94.25
Epoch 09 | loss=0.0115 | val_top1=93.81 | val_top5=94.10 | val_top10=94.25
Epoch 10 | loss=0.0049 | val_top1=93.81 | val_top5=94.10 | val_top10=94.25
Epoch 11 | loss=0.0036 | val_top1=93.81 | val_top5=94.10 | val_top10=94.25
Early stopping triggered at epoch 11.

Best validation top1: 93.95484340859431
Test metrics: {'top1': 13.960612691466084, 'top5': 18.11816192560175, 'top10': 20.437636761487965}

================================================================================
[18/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 256, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.001, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=2.0335 | val_top1=93.88 | val_top5=94.10 | val_top10=94.10
Epoch 02 | loss=1.2765 | val_top1=93.88 | val_top5=94.03 | val_top10=94.03
Epoch 03 | loss=0.7929 | val_top1=93.88 | val_top5=94.03 | val_top10=94.10
Epoch 04 | loss=0.4877 | val_top1=93.74 | val_top5=93.95 | val_top10=94.25
Epoch 05 | loss=0.3037 | val_top1=93.74 | val_top5=94.03 | val_top10=94.25
Epoch 06 | loss=0.2128 | val_top1=93.74 | val_top5=93.88 | val_top10=93.95
Early stopping triggered at epoch 6.

Best validation top1: 93.88201019664967
Test metrics: {'top1': 14.704595185995624, 'top5': 17.855579868708972, 'top10': 20.08752735229759}

================================================================================
[19/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 256, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Epoch 01 | loss=1.8792 | val_top1=93.95 | val_top5=94.03 | val_top10=94.25
Epoch 02 | loss=0.9896 | val_top1=94.03 | val_top5=94.25 | val_top10=94.32
Epoch 03 | loss=0.4302 | val_top1=93.95 | val_top5=94.17 | val_top10=94.39
Epoch 04 | loss=0.1718 | val_top1=94.03 | val_top5=94.39 | val_top10=94.61
Epoch 05 | loss=0.0734 | val_top1=94.10 | val_top5=94.25 | val_top10=94.39
Epoch 06 | loss=0.0169 | val_top1=94.03 | val_top5=94.32 | val_top10=94.54
Epoch 07 | loss=0.0048 | val_top1=94.03 | val_top5=94.32 | val_top10=94.68
Epoch 08 | loss=0.0037 | val_top1=94.03 | val_top5=94.32 | val_top10=94.68
Epoch 09 | loss=0.0032 | val_top1=94.03 | val_top5=94.32 | val_top10=94.68
Epoch 10 | loss=0.0028 | val_top1=94.03 | val_top5=94.32 | val_top10=94.68
Early stopping triggered at epoch 10.

Best validation top1: 94.10050983248361
Test metrics: {'top1': 16.455142231947484, 'top5': 21.444201312910284, 'top10': 23.938730853391686}

================================================================================
[20/24] Running MaxPoolProjectionV2 with config:
{'output_dim': 256, 'input_dim': 1024, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Epoch 01 | loss=1.9356 | val_top1=93.88 | val_top5=93.95 | val_top10=94.10

,exp_name,output_dim,input_dim,dropout,lr,weight_decay,batch_size,temperature,best_val_top1,val_top1,val_top5,val_top10,test_top1,test_top5,test_top10
2,mpv2_dim64_drop0p0_lr0.0005_wd0.0001_temp0p07,64,1024,0.0,0.0005,0.0001,32,0.07,94.100510,94.100510,94.173343,94.246176,14.967177,18.687090,20.787746
18,mpv2_dim256_drop0p0_lr0.0005_wd0.0001_temp0p07,256,1024,0.0,0.0005,0.0001,32,0.07,94.100510,94.100510,94.246176,94.391843,16.455142,21.444201,23.938731
10,mpv2_dim128_drop0p0_lr0.0005_wd0.0001_temp0p07,128,1024,0.0,0.0005,0.0001,32,0.07,94.100510,94.100510,94.391843,94.391843,16.717724,21.531729,24.595186
23,mpv2_dim256_drop0p1_lr0.0005_wd0.0001_temp0p1,256,1024,0.1,0.0005,0.0001,32,0.10,94.027677,94.027677,94.100510,94.173343,15.317287,20.043764,22.144420
22,mpv2_dim256_drop0p1_lr0.0005_wd0.0001_temp0p07,256,1024,0.1,0.0005,0.0001,32,0.07,94.027677,94.027677,94.100510,94.319009,15.142232,19.168490,21.181619
20,mpv2_dim256_drop0p1_lr0.001_wd0.0001_temp0p07,256,1024,0.1,0.0010,0.0001,32,0.07,94.027677,94.027677,94.173343,94.173343,13.785558,18.074398,19.693654
15,mpv2_dim128_drop0p1_lr0.0005_wd0.0001_temp0p1,128,1024,0.1,0.0005,0.0001,32,0.10,94.027677,94.027677,94.027677,94.173343,15.010941,18.555799,20.612691
16,mpv2_dim256_drop0p0_lr0.001_wd0.0001_temp0p07,256,1024,0.0,0.0010,0.0001,32,0.07,93.954843,93.954843,94.027677,94.100510,13.960613,18.118162,20.437637
3,mpv2_dim64_drop0p0_lr0.0005_wd0.0001_temp0p1,64,1024,0.0,0.0005,0.0001,32,0.10,93.954843,93.954843,94.027677,94.319009,15.098468,19.387309,22.275711
21,mpv2_dim256_drop0p1_lr0.001_wd0.0001_temp0p1,256,1024,0.1,0.0010,0.0001,32,0.10,93.954843,93.954843,94.173343,94.319009,14.135667,16.761488,19.124726
7,mpv2_dim64_drop0p1_lr0.0005_wd0.0001_temp0p1,64,1024,0.1,0.0005,0.0001,32,0.10,93.954843,93.954843,94.100510,94.173343,14.485777,17.242888,19.562363
19,mpv2_dim256_drop0p0_lr0.0005_wd0.0001_temp0p1,256,1024,0.0,0.0005,0.0001,32,0.10,93.954843,93.954843,93.954843,94.100510,15.711160,19.299781,21.925602
11,mpv2_dim128_drop0p0_lr0.0005_wd0.0001_temp0p1,128,1024,0.0,0.0005,0.0001,32,0.10,93.954843,93.954843,94.027677,94.246176,15.317287,19.080963,21.269147
13,mpv2_dim128_drop0p1_lr0.001_wd0.0001_temp0p1,128,1024,0.1,0.0010,0.0001,32,0.10,93.954843,93.954843,93.954843,94.027677,14.048140,17.374179,18.905908
14,mpv2_dim128_drop0p1_lr0.0005_wd0.0001_temp0p07,128,1024,0.1,0.0005,0.0001,32,0.07,93.954843,93.954843,94.027677,94.100510,14.748359,18.161926,20.437637
17,mpv2_dim256_drop0p0_lr0.001_wd0.0001_temp0p1,256,1024,0.0,0.0010,0.0001,32,0.10,93.882010,93.882010,94.100510,94.100510,14.704595,17.855580,20.087527
0,mpv2_dim64_drop0p0_lr0.001_wd0.0001_temp0p07,64,1024,0.0,0.0010,0.0001,32,0.07,93.882010,93.882010,94.027677,94.027677,14.004376,17.855580,19.474836
1,mpv2_dim64_drop0p0_lr0.001_wd0.0001_temp0p1,64,1024,0.0,0.0010,0.0001,32,0.10,93.882010,93.882010,93.954843,94.027677,13.873085,17.505470,19.343545
9,mpv2_dim128_drop0p0_lr0.001_wd0.0001_temp0p1,128,1024,0.0,0.0010,0.0001,32,0.10,93.882010,93.882010,94.027677,94.100510,14.135667,17.724289,20.043764
6,mpv2_dim64_drop0p1_lr0.0005_wd0.0001_temp0p07,64,1024,0.1,0.0005,0.0001,32,0.07,93.882010,93.882010,94.173343,94.246176,14.529540,17.899344,19.868709
5,mpv2_dim64_drop0p1_lr0.001_wd0.0001_temp0p1,64,1024,0.1,0.0010,0.0001,32,0.10,93.882010,93.882010,94.027677,94.027677,13.435449,16.236324,17.724289
4,mpv2_dim64_drop0p1_lr0.001_wd0.0001_temp0p07,64,1024,0.1,0.0010,0.0001,32,0.07,93.882010,93.882010,94.027677,94.100510,13.873085,16.849015,18.687090
12,mpv2_dim128_drop0p1_lr0.001_wd0.0001_temp0p07,128,1024,0.1,0.0010,0.0001,32,0.07,93.882010,93.882010,93.882010,93.882010,13.785558,16.980306,18.687090
8,mpv2_dim128_drop0p0_lr0.001_wd0.0001_temp0p07,128,1024,0.0,0.0010,0.0001,32,0.07,93.809177,93.809177,94.027677,94.100510,14.135667,17.374179,19.912473

In [4]:
MaxPoolProjectionV1_grid = {
    "input_dim": [1024],
    "output_dim": [128, 256],
    "dropout": [0.0, 0.1],
    "lr": [5e-4, 2e-4],
    "weight_decay": [1e-4, 1e-5],
    "batch_size": [32],
    "temperature": [0.07, 0.1],
}


NUM_EPOCHS = 20
configs = expand_grid(MaxPoolProjectionV1_grid)
print(f"Total configs: {len(configs)}")
print("Sample config:", configs[0])

all_results = []

for i, cfg in enumerate(configs, start=1):
    print("\n" + "=" * 80)
    print(f"[{i}/{len(configs)}] Running MaxPoolProjectionV1 with config:")
    print(cfg)

    exp_name = (
        f"mpv1_dim{cfg['output_dim']}_"
        f"drop{str(cfg['dropout']).replace('.', 'p')}_"
        f"lr{cfg['lr']}_"
        f"wd{cfg['weight_decay']}_"
        f"temp{str(cfg['temperature']).replace('.', 'p')}"
    )

    try:
        model = MaxPoolProjectionV1(
            input_dim=cfg["input_dim"],
            out_dim=cfg["output_dim"],
            dropout=cfg["dropout"],
        )

        results = run_training(
            train_csv=ROOT / "dataset/task3_cislr/splits/train_repeated.csv",
            val_csv=ROOT / "dataset/task3_cislr/splits/val_repeated.csv",
            prototype_csv=ROOT / "dataset/task3_cislr/splits/prototype.csv",
            test_csv=ROOT / "dataset/task3_cislr/splits/test.csv",
            feature_pkl=ROOT / "dataset/task3_cislr/features/I3D_features.pkl",
            out_dir=ROOT / "results/task3_cislr/maxpool_projection_v1_gridsearch" / exp_name,
            batch_size=cfg["batch_size"],
            num_workers=0,
            pooling="max",
            lr=cfg["lr"],
            weight_decay=cfg["weight_decay"],
            temperature=cfg["temperature"],
            epochs=NUM_EPOCHS,
            model=model,
        )
        
        row = {
            "exp_name": exp_name,
            **cfg,
            "best_val_top1": results["best_val_top1"],
            "val_top1": results["best_val_metrics"]["top1"],
            "val_top5": results["best_val_metrics"]["top5"],
            "val_top10": results["best_val_metrics"]["top10"],
            "test_top1": results["test_metrics"]["top1"],
            "test_top5": results["test_metrics"]["top5"],
            "test_top10": results["test_metrics"]["top10"],
        }
        all_results.append(row)
        df = pd.DataFrame(all_results)
        df.to_csv(ROOT / "results/task3_cislr/maxpool_projection_v1_gridsearch_results.csv", index=False)

    except Exception as e:
        print(f"Failed config: {cfg}")
        print("Error:", e)
        all_results.append({
            "exp_name": exp_name,
            **cfg,
            "error": str(e),
        })

display(df.sort_values("val_top1", ascending=False))

Total configs: 32
Sample config: {'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}

================================================================================
[1/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Failed config: {'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[2/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Failed config: {'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[3/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.07}
Failed config: {'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.07}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[4/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.1}
Failed config: {'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.1}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[5/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Failed config: {'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[6/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Failed config: {'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[7/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.07}
Failed config: {'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.07}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[8/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.1}
Failed config: {'input_dim': 1024, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.1}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[9/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Failed config: {'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[10/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Failed config: {'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[11/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.07}
Failed config: {'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.07}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[12/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.1}
Failed config: {'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.1}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[13/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Failed config: {'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[14/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Failed config: {'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[15/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.07}
Failed config: {'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.07}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[16/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.1}
Failed config: {'input_dim': 1024, 'output_dim': 128, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.1}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[17/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Failed config: {'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[18/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Failed config: {'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[19/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.07}
Failed config: {'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.07}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[20/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.1}
Failed config: {'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.1}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[21/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Failed config: {'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[22/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Failed config: {'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[23/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.07}
Failed config: {'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.07}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[24/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.1}
Failed config: {'input_dim': 1024, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.1}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[25/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Failed config: {'input_dim': 1024, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[26/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Failed config: {'input_dim': 1024, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[27/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.07}
Failed config: {'input_dim': 1024, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.07}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[28/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.1}
Failed config: {'input_dim': 1024, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.1}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[29/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Failed config: {'input_dim': 1024, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[30/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Failed config: {'input_dim': 1024, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[31/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.07}
Failed config: {'input_dim': 1024, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.07}
Error: name 'MaxPoolProjectionV1' is not defined

================================================================================
[32/32] Running MaxPoolProjectionV1 with config:
{'input_dim': 1024, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.1}
Failed config: {'input_dim': 1024, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 1e-05, 'batch_size': 32, 'temperature': 0.1}
Error: name 'MaxPoolProjectionV1' is not defined

,exp_name,output_dim,input_dim,dropout,lr,weight_decay,batch_size,temperature,best_val_top1,val_top1,val_top5,val_top10,test_top1,test_top5,test_top10
2,mpv2_dim64_drop0p0_lr0.0005_wd0.0001_temp0p07,64,1024,0.0,0.0005,0.0001,32,0.07,94.100510,94.100510,94.173343,94.246176,14.967177,18.687090,20.787746
18,mpv2_dim256_drop0p0_lr0.0005_wd0.0001_temp0p07,256,1024,0.0,0.0005,0.0001,32,0.07,94.100510,94.100510,94.246176,94.391843,16.455142,21.444201,23.938731
10,mpv2_dim128_drop0p0_lr0.0005_wd0.0001_temp0p07,128,1024,0.0,0.0005,0.0001,32,0.07,94.100510,94.100510,94.391843,94.391843,16.717724,21.531729,24.595186
23,mpv2_dim256_drop0p1_lr0.0005_wd0.0001_temp0p1,256,1024,0.1,0.0005,0.0001,32,0.10,94.027677,94.027677,94.100510,94.173343,15.317287,20.043764,22.144420
22,mpv2_dim256_drop0p1_lr0.0005_wd0.0001_temp0p07,256,1024,0.1,0.0005,0.0001,32,0.07,94.027677,94.027677,94.100510,94.319009,15.142232,19.168490,21.181619
20,mpv2_dim256_drop0p1_lr0.001_wd0.0001_temp0p07,256,1024,0.1,0.0010,0.0001,32,0.07,94.027677,94.027677,94.173343,94.173343,13.785558,18.074398,19.693654
15,mpv2_dim128_drop0p1_lr0.0005_wd0.0001_temp0p1,128,1024,0.1,0.0005,0.0001,32,0.10,94.027677,94.027677,94.027677,94.173343,15.010941,18.555799,20.612691
16,mpv2_dim256_drop0p0_lr0.001_wd0.0001_temp0p07,256,1024,0.0,0.0010,0.0001,32,0.07,93.954843,93.954843,94.027677,94.100510,13.960613,18.118162,20.437637
3,mpv2_dim64_drop0p0_lr0.0005_wd0.0001_temp0p1,64,1024,0.0,0.0005,0.0001,32,0.10,93.954843,93.954843,94.027677,94.319009,15.098468,19.387309,22.275711
21,mpv2_dim256_drop0p1_lr0.001_wd0.0001_temp0p1,256,1024,0.1,0.0010,0.0001,32,0.10,93.954843,93.954843,94.173343,94.319009,14.135667,16.761488,19.124726
7,mpv2_dim64_drop0p1_lr0.0005_wd0.0001_temp0p1,64,1024,0.1,0.0005,0.0001,32,0.10,93.954843,93.954843,94.100510,94.173343,14.485777,17.242888,19.562363
19,mpv2_dim256_drop0p0_lr0.0005_wd0.0001_temp0p1,256,1024,0.0,0.0005,0.0001,32,0.10,93.954843,93.954843,93.954843,94.100510,15.711160,19.299781,21.925602
11,mpv2_dim128_drop0p0_lr0.0005_wd0.0001_temp0p1,128,1024,0.0,0.0005,0.0001,32,0.10,93.954843,93.954843,94.027677,94.246176,15.317287,19.080963,21.269147
13,mpv2_dim128_drop0p1_lr0.001_wd0.0001_temp0p1,128,1024,0.1,0.0010,0.0001,32,0.10,93.954843,93.954843,93.954843,94.027677,14.048140,17.374179,18.905908
14,mpv2_dim128_drop0p1_lr0.0005_wd0.0001_temp0p07,128,1024,0.1,0.0005,0.0001,32,0.07,93.954843,93.954843,94.027677,94.100510,14.748359,18.161926,20.437637
17,mpv2_dim256_drop0p0_lr0.001_wd0.0001_temp0p1,256,1024,0.0,0.0010,0.0001,32,0.10,93.882010,93.882010,94.100510,94.100510,14.704595,17.855580,20.087527
0,mpv2_dim64_drop0p0_lr0.001_wd0.0001_temp0p07,64,1024,0.0,0.0010,0.0001,32,0.07,93.882010,93.882010,94.027677,94.027677,14.004376,17.855580,19.474836
1,mpv2_dim64_drop0p0_lr0.001_wd0.0001_temp0p1,64,1024,0.0,0.0010,0.0001,32,0.10,93.882010,93.882010,93.954843,94.027677,13.873085,17.505470,19.343545
9,mpv2_dim128_drop0p0_lr0.001_wd0.0001_temp0p1,128,1024,0.0,0.0010,0.0001,32,0.10,93.882010,93.882010,94.027677,94.100510,14.135667,17.724289,20.043764
6,mpv2_dim64_drop0p1_lr0.0005_wd0.0001_temp0p07,64,1024,0.1,0.0005,0.0001,32,0.07,93.882010,93.882010,94.173343,94.246176,14.529540,17.899344,19.868709
5,mpv2_dim64_drop0p1_lr0.001_wd0.0001_temp0p1,64,1024,0.1,0.0010,0.0001,32,0.10,93.882010,93.882010,94.027677,94.027677,13.435449,16.236324,17.724289
4,mpv2_dim64_drop0p1_lr0.001_wd0.0001_temp0p07,64,1024,0.1,0.0010,0.0001,32,0.07,93.882010,93.882010,94.027677,94.100510,13.873085,16.849015,18.687090
12,mpv2_dim128_drop0p1_lr0.001_wd0.0001_temp0p07,128,1024,0.1,0.0010,0.0001,32,0.07,93.882010,93.882010,93.882010,93.882010,13.785558,16.980306,18.687090
8,mpv2_dim128_drop0p0_lr0.001_wd0.0001_temp0p07,128,1024,0.0,0.0010,0.0001,32,0.07,93.809177,93.809177,94.027677,94.100510,14.135667,17.374179,19.912473

In [6]:
df_mp_v2 = pd.read_csv(ROOT / "results/task3_cislr/maxpool_projection_v2_gridsearch_results.csv")
display(df_mp_v2.sort_values("test_top1", ascending=False))

,exp_name,output_dim,input_dim,dropout,lr,weight_decay,batch_size,temperature,best_val_top1,val_top1,val_top5,val_top10,test_top1,test_top5,test_top10
10,mpv2_dim128_drop0p0_lr0.0005_wd0.0001_temp0p07,128,1024,0.0,0.0005,0.0001,32,0.07,94.100510,94.100510,94.391843,94.391843,16.717724,21.531729,24.595186
18,mpv2_dim256_drop0p0_lr0.0005_wd0.0001_temp0p07,256,1024,0.0,0.0005,0.0001,32,0.07,94.100510,94.100510,94.246176,94.391843,16.455142,21.444201,23.938731
19,mpv2_dim256_drop0p0_lr0.0005_wd0.0001_temp0p1,256,1024,0.0,0.0005,0.0001,32,0.10,93.954843,93.954843,93.954843,94.100510,15.711160,19.299781,21.925602
11,mpv2_dim128_drop0p0_lr0.0005_wd0.0001_temp0p1,128,1024,0.0,0.0005,0.0001,32,0.10,93.954843,93.954843,94.027677,94.246176,15.317287,19.080963,21.269147
23,mpv2_dim256_drop0p1_lr0.0005_wd0.0001_temp0p1,256,1024,0.1,0.0005,0.0001,32,0.10,94.027677,94.027677,94.100510,94.173343,15.317287,20.043764,22.144420
22,mpv2_dim256_drop0p1_lr0.0005_wd0.0001_temp0p07,256,1024,0.1,0.0005,0.0001,32,0.07,94.027677,94.027677,94.100510,94.319009,15.142232,19.168490,21.181619
3,mpv2_dim64_drop0p0_lr0.0005_wd0.0001_temp0p1,64,1024,0.0,0.0005,0.0001,32,0.10,93.954843,93.954843,94.027677,94.319009,15.098468,19.387309,22.275711
15,mpv2_dim128_drop0p1_lr0.0005_wd0.0001_temp0p1,128,1024,0.1,0.0005,0.0001,32,0.10,94.027677,94.027677,94.027677,94.173343,15.010941,18.555799,20.612691
2,mpv2_dim64_drop0p0_lr0.0005_wd0.0001_temp0p07,64,1024,0.0,0.0005,0.0001,32,0.07,94.100510,94.100510,94.173343,94.246176,14.967177,18.687090,20.787746
14,mpv2_dim128_drop0p1_lr0.0005_wd0.0001_temp0p07,128,1024,0.1,0.0005,0.0001,32,0.07,93.954843,93.954843,94.027677,94.100510,14.748359,18.161926,20.437637
17,mpv2_dim256_drop0p0_lr0.001_wd0.0001_temp0p1,256,1024,0.0,0.0010,0.0001,32,0.10,93.882010,93.882010,94.100510,94.100510,14.704595,17.855580,20.087527
6,mpv2_dim64_drop0p1_lr0.0005_wd0.0001_temp0p07,64,1024,0.1,0.0005,0.0001,32,0.07,93.882010,93.882010,94.173343,94.246176,14.529540,17.899344,19.868709
7,mpv2_dim64_drop0p1_lr0.0005_wd0.0001_temp0p1,64,1024,0.1,0.0005,0.0001,32,0.10,93.954843,93.954843,94.100510,94.173343,14.485777,17.242888,19.562363
21,mpv2_dim256_drop0p1_lr0.001_wd0.0001_temp0p1,256,1024,0.1,0.0010,0.0001,32,0.10,93.954843,93.954843,94.173343,94.319009,14.135667,16.761488,19.124726
9,mpv2_dim128_drop0p0_lr0.001_wd0.0001_temp0p1,128,1024,0.0,0.0010,0.0001,32,0.10,93.882010,93.882010,94.027677,94.100510,14.135667,17.724289,20.043764
8,mpv2_dim128_drop0p0_lr0.001_wd0.0001_temp0p07,128,1024,0.0,0.0010,0.0001,32,0.07,93.809177,93.809177,94.027677,94.100510,14.135667,17.374179,19.912473
13,mpv2_dim128_drop0p1_lr0.001_wd0.0001_temp0p1,128,1024,0.1,0.0010,0.0001,32,0.10,93.954843,93.954843,93.954843,94.027677,14.048140,17.374179,18.905908
0,mpv2_dim64_drop0p0_lr0.001_wd0.0001_temp0p07,64,1024,0.0,0.0010,0.0001,32,0.07,93.882010,93.882010,94.027677,94.027677,14.004376,17.855580,19.474836
16,mpv2_dim256_drop0p0_lr0.001_wd0.0001_temp0p07,256,1024,0.0,0.0010,0.0001,32,0.07,93.954843,93.954843,94.027677,94.100510,13.960613,18.118162,20.437637
1,mpv2_dim64_drop0p0_lr0.001_wd0.0001_temp0p1,64,1024,0.0,0.0010,0.0001,32,0.10,93.882010,93.882010,93.954843,94.027677,13.873085,17.505470,19.343545
4,mpv2_dim64_drop0p1_lr0.001_wd0.0001_temp0p07,64,1024,0.1,0.0010,0.0001,32,0.07,93.882010,93.882010,94.027677,94.100510,13.873085,16.849015,18.687090
20,mpv2_dim256_drop0p1_lr0.001_wd0.0001_temp0p07,256,1024,0.1,0.0010,0.0001,32,0.07,94.027677,94.027677,94.173343,94.173343,13.785558,18.074398,19.693654
12,mpv2_dim128_drop0p1_lr0.001_wd0.0001_temp0p07,128,1024,0.1,0.0010,0.0001,32,0.07,93.882010,93.882010,93.882010,93.882010,13.785558,16.980306,18.687090
5,mpv2_dim64_drop0p1_lr0.001_wd0.0001_temp0p1,64,1024,0.1,0.0010,0.0001,32,0.10,93.882010,93.882010,94.027677,94.027677,13.435449,16.236324,17.724289

In [7]:
df_mp_v1 = pd.read_csv(ROOT / "results/task3_cislr/maxpool_projection_v1_gridsearch_results.csv")
display(df_mp_v1.sort_values("test_top1", ascending=False))

,exp_name,input_dim,output_dim,dropout,lr,weight_decay,batch_size,temperature,best_val_top1,val_top1,val_top5,val_top10,test_top1,test_top5,test_top10
17,dim256_drop0p0_lr0.0005_wd0.0001_temp0p1,1024,256,0.0,0.0005,0.00010,32,0.10,28.477786,28.477786,33.940277,37.217771,18.905908,25.426696,28.577681
3,dim128_drop0p0_lr0.0005_wd1e-05_temp0p1,1024,128,0.0,0.0005,0.00001,32,0.10,29.278951,29.278951,34.013110,36.853605,18.730853,24.726477,27.921225
1,dim128_drop0p0_lr0.0005_wd0.0001_temp0p1,1024,128,0.0,0.0005,0.00010,32,0.10,27.458121,27.458121,32.993445,36.270940,18.555799,24.507659,27.264770
2,dim128_drop0p0_lr0.0005_wd1e-05_temp0p07,1024,128,0.0,0.0005,0.00001,32,0.07,28.186453,28.186453,34.595776,37.363438,18.205689,23.457330,27.483589
18,dim256_drop0p0_lr0.0005_wd1e-05_temp0p07,1024,256,0.0,0.0005,0.00001,32,0.07,27.895120,27.895120,34.450109,38.091770,17.986871,23.238512,26.870897
28,dim256_drop0p1_lr0.0002_wd0.0001_temp0p07,1024,256,0.1,0.0002,0.00010,32,0.07,28.841952,28.841952,35.324108,39.184268,17.592998,21.269147,23.501094
23,dim256_drop0p0_lr0.0002_wd1e-05_temp0p1,1024,256,0.0,0.0002,0.00001,32,0.10,28.623452,28.623452,34.814275,38.383103,17.592998,22.188184,24.332604
22,dim256_drop0p0_lr0.0002_wd1e-05_temp0p07,1024,256,0.0,0.0002,0.00001,32,0.07,28.550619,28.550619,35.251275,38.455936,17.592998,22.056893,24.157549
31,dim256_drop0p1_lr0.0002_wd1e-05_temp0p1,1024,256,0.1,0.0002,0.00001,32,0.10,28.769119,28.769119,34.668609,38.674436,17.549234,21.312910,23.632385
26,dim256_drop0p1_lr0.0005_wd1e-05_temp0p07,1024,256,0.1,0.0005,0.00001,32,0.07,27.967953,27.967953,34.085943,36.999272,17.549234,23.150985,26.345733
0,dim128_drop0p0_lr0.0005_wd0.0001_temp0p07,1024,128,0.0,0.0005,0.00010,32,0.07,27.749454,27.749454,34.158776,37.363438,17.505470,23.063457,26.170678
25,dim256_drop0p1_lr0.0005_wd0.0001_temp0p1,1024,256,0.1,0.0005,0.00010,32,0.10,28.404953,28.404953,33.940277,37.581937,17.461707,21.969365,24.420131
19,dim256_drop0p0_lr0.0005_wd1e-05_temp0p1,1024,256,0.0,0.0005,0.00001,32,0.10,28.404953,28.404953,33.794610,36.999272,17.417943,22.363239,25.120350
29,dim256_drop0p1_lr0.0002_wd0.0001_temp0p1,1024,256,0.1,0.0002,0.00010,32,0.10,28.987618,28.987618,34.959942,38.601602,17.417943,22.494530,25.382932
20,dim256_drop0p0_lr0.0002_wd0.0001_temp0p07,1024,256,0.0,0.0002,0.00010,32,0.07,28.259286,28.259286,34.741442,38.237436,17.330416,21.575492,23.544858
21,dim256_drop0p0_lr0.0002_wd0.0001_temp0p1,1024,256,0.0,0.0002,0.00010,32,0.10,29.351784,29.351784,34.959942,37.873270,17.286652,21.881838,24.026258
30,dim256_drop0p1_lr0.0002_wd1e-05_temp0p07,1024,256,0.1,0.0002,0.00001,32,0.07,28.696286,28.696286,34.959942,39.329934,17.111597,21.619256,23.938731
27,dim256_drop0p1_lr0.0005_wd1e-05_temp0p1,1024,256,0.1,0.0005,0.00001,32,0.10,28.113620,28.113620,33.940277,37.144938,17.024070,22.100656,24.288840
7,dim128_drop0p0_lr0.0002_wd1e-05_temp0p1,1024,128,0.0,0.0002,0.00001,32,0.10,28.550619,28.550619,34.158776,36.999272,17.024070,20.743982,23.501094
11,dim128_drop0p1_lr0.0005_wd1e-05_temp0p1,1024,128,0.1,0.0005,0.00001,32,0.10,28.259286,28.259286,34.522942,37.436271,17.024070,21.400438,24.595186
5,dim128_drop0p0_lr0.0002_wd0.0001_temp0p1,1024,128,0.0,0.0002,0.00010,32,0.10,28.113620,28.113620,33.940277,38.164603,16.980306,21.006565,23.676149
9,dim128_drop0p1_lr0.0005_wd0.0001_temp0p1,1024,128,0.1,0.0005,0.00010,32,0.10,27.676621,27.676621,33.648944,36.635106,16.849015,21.794311,24.507659
15,dim128_drop0p1_lr0.0002_wd1e-05_temp0p1,1024,128,0.1,0.0002,0.00001,32,0.10,28.623452,28.623452,34.668609,37.363438,16.849015,21.925602,25.164114
24,dim256_drop0p1_lr0.0005_wd0.0001_temp0p07,1024,256,0.1,0.0005,0.00010,32,0.07,28.113620,28.113620,34.013110,38.310269,16.805252,21.312910,23.588621
13,dim128_drop0p1_lr0.0002_wd0.0001_temp0p1,1024,128,0.1,0.0002,0.00010,32,0.10,28.040787,28.040787,34.231610,37.581937,16.805252,20.568928,23.457330
4,dim128_drop0p0_lr0.0002_wd0.0001_temp0p07,1024,128,0.0,0.0002,0.00010,32,0.07,28.477786,28.477786,34.013110,37.873270,16.761488,21.444201,24.463895
12,dim128_drop0p1_lr0.0002_wd0.0001_temp0p07,1024,128,0.1,0.0002,0.00010,32,0.07,28.404953,28.404953,33.721777,37.581937,16.717724,21.531729,23.938731
8,dim128_drop0p1_lr0.0005_wd0.0001_temp0p07,1024,128,0.1,0.0005,0.00010,32,0.07,27.749454,27.749454,33.576111,37.290605,16.673961,20.568928,22.800875
14,dim128_drop0p1_lr0.0002_wd1e-05_temp0p07,1024,128,0.1,0.0002,0.00001,32,0.07,27.749454,27.749454,33.430444,37.800437,16.630197,21.094092,23.413567
10,dim128_drop0p1_lr0.0005_wd1e-05_temp0p07,1024,128,0.1,0.0005,0.00001,32,0.07,27.895120,27.895120,33.794610,36.999272,16.542670,20.700219,23.063457
16,dim256_drop0p0_lr0.0005_wd0.0001_temp0p07,1024,256,0.0,0.0005,0.00010,32,0.07,27.676621,27.676621,34.085943,37.873270,16.542670,21.225383,23.807440
6,dim128_drop0p0_lr0.0002_wd1e-05_temp0p07,1024,128,0.0,0.0002,0.00001,32,0.07,27.895120,27.895120,33.648944,37.436271,16.455142,21.137856,23.369803

In [8]:
import json

path = ROOT / "results/task3_cislr/maxpool_projection_v2_gridsearch" / \
    "mpv2_dim128_drop0p0_lr0.0005_wd0.0001_temp0p07" / \
    "results_MaxPoolProjectionV2_h256_o128_lr0.0005_temp0.07.json"

with open(path, "r") as f:
    obj = json.load(f)

print(obj["best_val_top1"])
print(obj["best_val_metrics"])
print(obj["test_metrics"])
print(obj["history"][:3])
print(obj["history"][-3:])

94.10050983248361
{'top1': 94.10050983248361, 'top5': 94.3918426802622, 'top10': 94.3918426802622}
{'top1': 16.717724288840262, 'top5': 21.53172866520788, 'top10': 24.595185995623634}
[{'epoch': 1, 'train_loss': 1.9119267834557427, 'val_top1': 93.88201019664967, 'val_top5': 94.02767662053897, 'val_top10': 94.10050983248361}, {'epoch': 2, 'train_loss': 1.0314695756468508, 'val_top1': 93.88201019664967, 'val_top5': 94.17334304442826, 'val_top10': 94.31900946831755}, {'epoch': 3, 'train_loss': 0.48663332093920975, 'val_top1': 93.95484340859431, 'val_top5': 94.02767662053897, 'val_top10': 94.2461762563729}]
[{'epoch': 9, 'train_loss': 0.004803919657650921, 'val_top1': 94.10050983248361, 'val_top5': 94.3918426802622, 'val_top10': 94.3918426802622}, {'epoch': 10, 'train_loss': 0.004208534924934308, 'val_top1': 94.10050983248361, 'val_top5': 94.3918426802622, 'val_top10': 94.3918426802622}, {'epoch': 11, 'train_loss': 0.0037619197223749427, 'val_top1': 94.02767662053897, 'val_top5': 94.3918426802622, 'val_top10': 94.3918426802622}]

In [10]:
from src.tasks.task3_cislr.training.train_retreival import make_loader, evaluate_retrieval
from src.tasks.task3_cislr.models.maxpool_projection import MaxPoolProjectionV2
import torch
from src.scripts.get_device import get_device


device = get_device()

model = MaxPoolProjectionV2(
    input_dim=1024,
    hidden_dim=256,
    out_dim=128,
    dropout=0.0,
).to(device)

ckpt_path = ROOT / "results/task3_cislr/maxpool_projection_v2_gridsearch" / \
    "mpv2_dim128_drop0p0_lr0.0005_wd0.0001_temp0p07" / \
    "MaxPoolProjectionV2_h256_o128_lr0.0005_temp0.07_best.pt"

ckpt = torch.load(ckpt_path, map_location=device)
model.load_state_dict(ckpt["model_state_dict"])

prototype_loader = make_loader(
    split_csv=ROOT / "dataset/task3_cislr/splits/prototype.csv",
    feature_pkl=ROOT / "dataset/task3_cislr/features/I3D_features.pkl",
    batch_size=32,
    shuffle=False,
    num_workers=0,
)

val_loader = make_loader(
    split_csv=ROOT / "dataset/task3_cislr/splits/val_repeated.csv",
    feature_pkl=ROOT / "dataset/task3_cislr/features/I3D_features.pkl",
    batch_size=32,
    shuffle=False,
    num_workers=0,
)

test_loader = make_loader(
    split_csv=ROOT / "dataset/task3_cislr/splits/test.csv",
    feature_pkl=ROOT / "dataset/task3_cislr/features/I3D_features.pkl",
    batch_size=32,
    shuffle=False,
    num_workers=0,
)

val_metrics = evaluate_retrieval(model, prototype_loader, val_loader, device)
test_metrics = evaluate_retrieval(model, prototype_loader, test_loader, device)

print("Manual val:", val_metrics)
print("Manual test:", test_metrics)

Manual val: {'top1': 94.10050983248361, 'top5': 94.3918426802622, 'top10': 94.3918426802622}
Manual test: {'top1': 16.717724288840262, 'top5': 21.53172866520788, 'top10': 24.595185995623634}

In [11]:
import pandas as pd

val_df = pd.read_csv(ROOT / "dataset/task3_cislr/splits/val_repeated.csv")
proto_df = pd.read_csv(ROOT / "dataset/task3_cislr/splits/prototype.csv")

val_ids = set(val_df["uid"]) if "uid" in val_df.columns else set(val_df.iloc[:, 0])
proto_ids = set(proto_df["uid"]) if "uid" in proto_df.columns else set(proto_df.iloc[:, 0])

overlap = val_ids & proto_ids
print("Exact ID overlap:", len(overlap))
print(list(sorted(overlap))[:20])

Exact ID overlap: 1281
['--7-rCNOiK0_1', '-0XujLX2_9I_2', '-3db5Hhn4mI_1', '-5p4hn8J87A_2', '-65ryXubYjo', '-8CjLUfRlbw_1', '-A1P5WbuNo8', '-DDBcacIfeA_1', '-DHtnmdlaGk', '-Em79Yvwac4_1', '-H_VzAnfyKk', '-It9bwqowig', '-JcpfOHc0nE', '-Jr9EZz7Epo_1', '-NIz596Y27Q', '-NpA8OS_Oj0_1', '-Oq_e89164c_1', '-PGXFLhDfS0_1', '-R02rqkyxHc_1', '-SVSp2VtfRw_1']

In [13]:
import re

def get_base_id(uid: str) -> str:
    return re.sub(r'_(w|d|e\d+)$', '', str(uid))

val_base = set(val_df["uid"].map(get_base_id))
proto_base = set(proto_df["uid"].map(get_base_id))

base_overlap = val_base & proto_base
print("Base ID overlap:", len(base_overlap))
print(list(sorted(base_overlap))[:20])

Base ID overlap: 1281
['--7-rCNOiK0_1', '-0XujLX2_9I_2', '-3db5Hhn4mI_1', '-5p4hn8J87A_2', '-65ryXubYjo', '-8CjLUfRlbw_1', '-A1P5WbuNo8', '-DDBcacIfeA_1', '-DHtnmdlaGk', '-Em79Yvwac4_1', '-H_VzAnfyKk', '-It9bwqowig', '-JcpfOHc0nE', '-Jr9EZz7Epo_1', '-NIz596Y27Q', '-NpA8OS_Oj0_1', '-Oq_e89164c_1', '-PGXFLhDfS0_1', '-R02rqkyxHc_1', '-SVSp2VtfRw_1']

In [14]:
print("Val rows:", len(val_df))
print("Prototype rows:", len(proto_df))
print("Val unique gloss:", val_df["gloss"].nunique())
print("Prototype unique gloss:", proto_df["gloss"].nunique())

proto_counts = proto_df["gloss"].value_counts()
print(proto_counts.describe())

Val rows: 1373
Prototype rows: 4765
Val unique gloss: 1363
Prototype unique gloss: 4764
count    4764.0
mean        1.0
std         0.0
min         1.0
25%         1.0
50%         1.0
75%         1.0
max         1.0
Name: count, dtype: float64

In [15]:
df_val_repeated = pd.read_csv(ROOT / "dataset/task3_cislr/splits/val_repeated.csv")
df_prototype = pd.read_csv(ROOT / "dataset/task3_cislr/splits/prototype.csv")  
print(df_val_repeated.columns)
print(df_prototype.columns)

Index(['uid', 'gloss', 'duration', 'category'], dtype='object')
Index(['uid', 'gloss', 'duration', 'category'], dtype='object')

In [16]:
import pandas as pd

df_val = pd.read_csv(ROOT / "dataset/task3_cislr/splits/val_repeated.csv")
df_proto = pd.read_csv(ROOT / "dataset/task3_cislr/splits/prototype.csv")

proto_uids = set(df_proto["uid"])
df_val_clean = df_val[~df_val["uid"].isin(proto_uids)].copy()

print("Old val rows:", len(df_val))
print("Clean val rows:", len(df_val_clean))
print("Removed rows:", len(df_val) - len(df_val_clean))

df_val_clean.to_csv(ROOT / "dataset/task3_cislr/splits/val_repeated_no_proto_overlap.csv", index=False)

Old val rows: 1373
Clean val rows: 92
Removed rows: 1281

In [18]:
BiGRUPoolEncoder_grid = {
    "input_dim": [1024],
    "hidden_dim": [128, 256, 512],
    "output_dim": [128, 256, 512],
    "dropout": [0.0, 0.1, 0.2],
    "lr": [1e-5, 5e-4, 2e-4],
    "weight_decay": [1e-4, 1e-5],
    "batch_size": [32],
    "temperature": [0.07, 0.1],
    "num_layers": [1, 2],
    "pool": ["max", "mean"],
}

NUM_EPOCHS = 20
configs = expand_grid(BiGRUPoolEncoder_grid)
print(f"Total configs: {len(configs)}")
print("Sample config:", configs[0])

Total configs: 1296
Sample config: {'input_dim': 1024, 'hidden_dim': 128, 'output_dim': 128, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07, 'num_layers': 1, 'pool': 'max'}

In [21]:
from src.tasks.task3_cislr.models.bigru_encoder import BiGRUPoolEncoder, BiGRUAttentionEncoder

BiGRUAttentionEncoder_grid_stage1 = {
    "input_dim": [1024],
    "hidden_dim": [256],
    "output_dim": [256],
    "dropout": [0.0, 0.1],
    "lr": [5e-4, 2e-4],
    "weight_decay": [1e-4],
    "batch_size": [32],
    "temperature": [0.07, 0.1],
    "num_layers": [1,2],
    "pool": None,
    }

BiGRUPoolEncoder_grid_stage1 = {
    "input_dim": [1024],
    "hidden_dim": [256],
    "output_dim": [256],
    "dropout": [0.0, 0.1],
    "lr": [5e-4, 2e-4],
    "weight_decay": [1e-4],
    "batch_size": [32],
    "temperature": [0.07, 0.1],
    "num_layers": [2],
    "pool": ["max", "mean"],
    }

NUM_EPOCHS = 20
results_csv_BiGRUPoolEncoder = "results/task3_cislr/bigru_pool_gridsearch_results.csv"
configs_BiGRUPoolEncoder = expand_grid(BiGRUPoolEncoder_grid_stage1)
results_csv_BiGRUAttentionEncoder = "results/task3_cislr/bigru_attention_gridsearch_results.csv"
configs_BiGRUAttentionEncoder = expand_grid(BiGRUAttentionEncoder_grid_stage1)
print(f"Total configs: {len(configs_BiGRUAttentionEncoder)}")
print("Sample config:", configs_BiGRUAttentionEncoder[0])

all_results = []

for i, cfg in enumerate(configs_BiGRUAttentionEncoder, start=1):
    print("\n" + "=" * 80)
    print(f"[{i}/{len(configs_BiGRUAttentionEncoder)}] Running BiGRUAttentionEncoder with config:")
    print(cfg)

    exp_name = (
        f"bigru_{cfg['pool']}_"
        f"h{cfg['hidden_dim']}_o{cfg['output_dim']}_"
        f"drop{str(cfg['dropout']).replace('.', 'p')}_"
        f"lr{cfg['lr']}_"
        f"wd{cfg['weight_decay']}_"
        f"temp{str(cfg['temperature']).replace('.', 'p')}_"
        f"layers{cfg['num_layers']}"
    )

    try:
        model = BiGRUPoolEncoder(
            input_dim=cfg["input_dim"],
            hidden_dim=cfg["hidden_dim"],
            out_dim=cfg["output_dim"],
            num_layers=cfg["num_layers"],
            pool=cfg["pool"],
            dropout=cfg["dropout"],
        )

        results = run_training(
            train_csv=ROOT / "dataset/task3_cislr/splits/train_repeated.csv",
            val_csv=ROOT / "dataset/task3_cislr/splits/val_repeated_no_proto_overlap.csv",
            prototype_csv=ROOT / "dataset/task3_cislr/splits/prototype.csv",
            test_csv=ROOT / "dataset/task3_cislr/splits/test.csv",
            feature_pkl=ROOT / "dataset/task3_cislr/features/I3D_features.pkl",
            out_dir=ROOT / "results/task3_cislr/BiGRUAttentionEncoder_gridsearch" / exp_name,
            batch_size=cfg["batch_size"],
            num_workers=0,
            pooling=cfg["pool"] if cfg["pool"] in ["max", "mean"] else None,
            lr=cfg["lr"],
            weight_decay=cfg["weight_decay"],
            temperature=cfg["temperature"],
            epochs=NUM_EPOCHS,
            early_stopping_patience=10,
            model=model,
        )

        row = {
            "exp_name": exp_name,
            **cfg,
            "best_val_top1": results["best_val_top1"],
            "val_top1": results["best_val_metrics"]["top1"],
            "val_top5": results["best_val_metrics"]["top5"],
            "val_top10": results["best_val_metrics"]["top10"],
            "test_top1": results["test_metrics"]["top1"],
            "test_top5": results["test_metrics"]["top5"],
            "test_top10": results["test_metrics"]["top10"],
        }
        all_results.append(row)

    except Exception as e:
        print(f"Failed config: {cfg}")
        print("Error:", e)
        all_results.append({
            "exp_name": exp_name,
            **cfg,
            "error": str(e),
        })

    df = pd.DataFrame(all_results)
    df.to_csv(ROOT / results_csv_BiGRUAttentionEncoder, 
              mode = "a", 
              header=not os.path.exists(ROOT / results_csv_BiGRUAttentionEncoder),
              index=False)

display(df.sort_values("test_top1", ascending=False))

Total configs: 16
Sample config: {'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07, 'num_layers': 2, 'pool': 'max'}

================================================================================
[1/16] Running BiGRUPoolEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07, 'num_layers': 2, 'pool': 'max'}
Epoch 01 | loss=1.9499 | val_top1=7.61 | val_top5=13.04 | val_top10=15.22
Epoch 02 | loss=1.0470 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 03 | loss=0.4665 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 04 | loss=0.1758 | val_top1=9.78 | val_top5=14.13 | val_top10=19.57
Epoch 05 | loss=0.0449 | val_top1=10.87 | val_top5=19.57 | val_top10=21.74
Epoch 06 | loss=0.0096 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65
Epoch 07 | loss=0.0024 | val_top1=14.13 | val_top5=18.48 | val_top10=20.65
Epoch 08 | loss=0.0019 | val_top1=14.13 | val_top5=18.48 | val_top10=19.57
Epoch 09 | loss=0.0016 | val_top1=14.13 | val_top5=17.39 | val_top10=19.57
Epoch 10 | loss=0.0014 | val_top1=14.13 | val_top5=17.39 | val_top10=19.57
Epoch 11 | loss=0.0013 | val_top1=14.13 | val_top5=17.39 | val_top10=19.57
Epoch 12 | loss=0.0012 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 13 | loss=0.0011 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 14 | loss=0.0010 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 15 | loss=0.0009 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 16 | loss=0.0009 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 17 | loss=0.0008 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 18 | loss=0.0008 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 19 | loss=0.0007 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 20 | loss=0.0007 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48

Best validation top1: 14.130434782608695
Test metrics: {'top1': 17.592997811816193, 'top5': 23.938730853391686, 'top10': 26.345733041575492}

================================================================================
[2/16] Running BiGRUPoolEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07, 'num_layers': 2, 'pool': 'mean'}
Epoch 01 | loss=2.0092 | val_top1=8.70 | val_top5=10.87 | val_top10=13.04
Epoch 02 | loss=1.1850 | val_top1=11.96 | val_top5=11.96 | val_top10=14.13
Epoch 03 | loss=0.6697 | val_top1=8.70 | val_top5=11.96 | val_top10=13.04
Epoch 04 | loss=0.3120 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 05 | loss=0.1269 | val_top1=9.78 | val_top5=13.04 | val_top10=17.39
Epoch 06 | loss=0.0259 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 07 | loss=0.0184 | val_top1=10.87 | val_top5=18.48 | val_top10=18.48
Epoch 08 | loss=0.0027 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 09 | loss=0.0020 | val_top1=10.87 | val_top5=17.39 | val_top10=19.57
Epoch 10 | loss=0.0017 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 11 | loss=0.0015 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 12 | loss=0.0014 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 13 | loss=0.0013 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 14 | loss=0.0012 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 15 | loss=0.0011 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 16 | loss=0.0010 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 17 | loss=0.0009 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 18 | loss=0.0009 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 19 | loss=0.0008 | val_top1=10.87 | val_top5=16.30 | val_top10=20.65
Epoch 20 | loss=0.0008 | val_top1=10.87 | val_top5=16.30 | val_top10=20.65

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.98030634573304, 'top5': 21.48796498905908, 'top10': 24.463894967177243}

================================================================================
[3/16] Running BiGRUPoolEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'max'}
Epoch 01 | loss=1.8871 | val_top1=6.52 | val_top5=11.96 | val_top10=13.04
Epoch 02 | loss=0.9640 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 03 | loss=0.3939 | val_top1=14.13 | val_top5=16.30 | val_top10=18.48
Epoch 04 | loss=0.1256 | val_top1=13.04 | val_top5=19.57 | val_top10=22.83
Epoch 05 | loss=0.0320 | val_top1=13.04 | val_top5=20.65 | val_top10=23.91
Epoch 06 | loss=0.0132 | val_top1=14.13 | val_top5=22.83 | val_top10=22.83
Epoch 07 | loss=0.0091 | val_top1=13.04 | val_top5=22.83 | val_top10=22.83
Epoch 08 | loss=0.0078 | val_top1=13.04 | val_top5=22.83 | val_top10=22.83
Epoch 09 | loss=0.0069 | val_top1=13.04 | val_top5=22.83 | val_top10=23.91
Epoch 10 | loss=0.0061 | val_top1=14.13 | val_top5=22.83 | val_top10=23.91
Epoch 11 | loss=0.0055 | val_top1=14.13 | val_top5=22.83 | val_top10=23.91
Epoch 12 | loss=0.0050 | val_top1=14.13 | val_top5=22.83 | val_top10=23.91
Epoch 13 | loss=0.0046 | val_top1=14.13 | val_top5=22.83 | val_top10=23.91
Epoch 14 | loss=0.0043 | val_top1=14.13 | val_top5=22.83 | val_top10=23.91
Epoch 15 | loss=0.0040 | val_top1=14.13 | val_top5=22.83 | val_top10=23.91
Epoch 16 | loss=0.0037 | val_top1=15.22 | val_top5=22.83 | val_top10=23.91
Epoch 17 | loss=0.0034 | val_top1=16.30 | val_top5=22.83 | val_top10=23.91
Epoch 18 | loss=0.0032 | val_top1=16.30 | val_top5=22.83 | val_top10=23.91
Epoch 19 | loss=0.0030 | val_top1=16.30 | val_top5=22.83 | val_top10=23.91
Epoch 20 | loss=0.0028 | val_top1=16.30 | val_top5=22.83 | val_top10=23.91

Best validation top1: 16.304347826086957
Test metrics: {'top1': 20.612691466083152, 'top5': 25.295404814004378, 'top10': 27.964989059080963}

================================================================================
[4/16] Running BiGRUPoolEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}
Epoch 01 | loss=1.9912 | val_top1=7.61 | val_top5=13.04 | val_top10=14.13
Epoch 02 | loss=1.2054 | val_top1=8.70 | val_top5=15.22 | val_top10=15.22
Epoch 03 | loss=0.6395 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 04 | loss=0.3146 | val_top1=13.04 | val_top5=18.48 | val_top10=18.48
Epoch 05 | loss=0.1224 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 06 | loss=0.0356 | val_top1=9.78 | val_top5=18.48 | val_top10=21.74
Epoch 07 | loss=0.0140 | val_top1=10.87 | val_top5=20.65 | val_top10=21.74
Epoch 08 | loss=0.0099 | val_top1=11.96 | val_top5=19.57 | val_top10=21.74
Epoch 09 | loss=0.0084 | val_top1=11.96 | val_top5=20.65 | val_top10=21.74
Epoch 10 | loss=0.0074 | val_top1=11.96 | val_top5=19.57 | val_top10=21.74
Epoch 11 | loss=0.0066 | val_top1=11.96 | val_top5=19.57 | val_top10=20.65
Epoch 12 | loss=0.0060 | val_top1=11.96 | val_top5=19.57 | val_top10=20.65
Epoch 13 | loss=0.0055 | val_top1=11.96 | val_top5=19.57 | val_top10=20.65
Epoch 14 | loss=0.0050 | val_top1=11.96 | val_top5=19.57 | val_top10=20.65
Epoch 15 | loss=0.0046 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65
Epoch 16 | loss=0.0043 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65
Epoch 17 | loss=0.0040 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65
Epoch 18 | loss=0.0037 | val_top1=11.96 | val_top5=19.57 | val_top10=20.65
Epoch 19 | loss=0.0035 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 20 | loss=0.0032 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65

Best validation top1: 13.043478260869565
Test metrics: {'top1': 15.75492341356674, 'top5': 20.08752735229759, 'top10': 22.75711159737418}

================================================================================
[5/16] Running BiGRUPoolEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07, 'num_layers': 2, 'pool': 'max'}
Epoch 01 | loss=1.6940 | val_top1=8.70 | val_top5=16.30 | val_top10=16.30
Epoch 02 | loss=0.4538 | val_top1=14.13 | val_top5=18.48 | val_top10=21.74
Epoch 03 | loss=0.0477 | val_top1=14.13 | val_top5=18.48 | val_top10=22.83
Epoch 04 | loss=0.0072 | val_top1=14.13 | val_top5=19.57 | val_top10=22.83
Epoch 05 | loss=0.0050 | val_top1=14.13 | val_top5=19.57 | val_top10=22.83
Epoch 06 | loss=0.0041 | val_top1=14.13 | val_top5=19.57 | val_top10=22.83
Epoch 07 | loss=0.0035 | val_top1=15.22 | val_top5=19.57 | val_top10=22.83
Epoch 08 | loss=0.0031 | val_top1=15.22 | val_top5=19.57 | val_top10=22.83
Epoch 09 | loss=0.0027 | val_top1=16.30 | val_top5=19.57 | val_top10=23.91
Epoch 10 | loss=0.0025 | val_top1=16.30 | val_top5=19.57 | val_top10=23.91
Epoch 11 | loss=0.0022 | val_top1=16.30 | val_top5=19.57 | val_top10=23.91
Epoch 12 | loss=0.0020 | val_top1=16.30 | val_top5=19.57 | val_top10=23.91
Epoch 13 | loss=0.0019 | val_top1=16.30 | val_top5=19.57 | val_top10=23.91
Epoch 14 | loss=0.0017 | val_top1=16.30 | val_top5=19.57 | val_top10=23.91
Epoch 15 | loss=0.0016 | val_top1=16.30 | val_top5=19.57 | val_top10=23.91
Epoch 16 | loss=0.0015 | val_top1=16.30 | val_top5=19.57 | val_top10=23.91
Epoch 17 | loss=0.0014 | val_top1=16.30 | val_top5=19.57 | val_top10=23.91
Epoch 18 | loss=0.0013 | val_top1=16.30 | val_top5=18.48 | val_top10=23.91
Epoch 19 | loss=0.0012 | val_top1=16.30 | val_top5=18.48 | val_top10=23.91
Epoch 20 | loss=0.0011 | val_top1=16.30 | val_top5=18.48 | val_top10=23.91

Best validation top1: 16.304347826086957
Test metrics: {'top1': 19.693654266958426, 'top5': 25.86433260393873, 'top10': 28.796498905908095}

================================================================================
[6/16] Running BiGRUPoolEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07, 'num_layers': 2, 'pool': 'mean'}
Epoch 01 | loss=1.7666 | val_top1=14.13 | val_top5=16.30 | val_top10=17.39
Epoch 02 | loss=0.6622 | val_top1=13.04 | val_top5=15.22 | val_top10=18.48
Epoch 03 | loss=0.1460 | val_top1=11.96 | val_top5=17.39 | val_top10=21.74
Epoch 04 | loss=0.0279 | val_top1=14.13 | val_top5=19.57 | val_top10=22.83
Epoch 05 | loss=0.0079 | val_top1=13.04 | val_top5=18.48 | val_top10=23.91
Epoch 06 | loss=0.0051 | val_top1=11.96 | val_top5=19.57 | val_top10=23.91
Epoch 07 | loss=0.0043 | val_top1=13.04 | val_top5=19.57 | val_top10=23.91
Epoch 08 | loss=0.0037 | val_top1=13.04 | val_top5=19.57 | val_top10=23.91
Epoch 09 | loss=0.0033 | val_top1=13.04 | val_top5=19.57 | val_top10=22.83
Epoch 10 | loss=0.0029 | val_top1=13.04 | val_top5=19.57 | val_top10=22.83
Epoch 11 | loss=0.0027 | val_top1=13.04 | val_top5=19.57 | val_top10=22.83
Epoch 12 | loss=0.0024 | val_top1=13.04 | val_top5=19.57 | val_top10=22.83
Epoch 13 | loss=0.0022 | val_top1=14.13 | val_top5=19.57 | val_top10=22.83
Epoch 14 | loss=0.0020 | val_top1=15.22 | val_top5=19.57 | val_top10=22.83
Epoch 15 | loss=0.0019 | val_top1=15.22 | val_top5=19.57 | val_top10=21.74
Epoch 16 | loss=0.0017 | val_top1=15.22 | val_top5=19.57 | val_top10=22.83
Epoch 17 | loss=0.0016 | val_top1=15.22 | val_top5=19.57 | val_top10=22.83
Epoch 18 | loss=0.0015 | val_top1=15.22 | val_top5=19.57 | val_top10=22.83
Epoch 19 | loss=0.0014 | val_top1=15.22 | val_top5=19.57 | val_top10=22.83
Epoch 20 | loss=0.0013 | val_top1=15.22 | val_top5=19.57 | val_top10=22.83

Best validation top1: 15.217391304347826
Test metrics: {'top1': 19.387308533916848, 'top5': 25.426695842450766, 'top10': 28.665207877461707}

================================================================================
[7/16] Running BiGRUPoolEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'max'}
Epoch 01 | loss=1.7292 | val_top1=9.78 | val_top5=13.04 | val_top10=17.39
Epoch 02 | loss=0.5076 | val_top1=14.13 | val_top5=17.39 | val_top10=20.65
Epoch 03 | loss=0.1073 | val_top1=14.13 | val_top5=21.74 | val_top10=22.83
Epoch 04 | loss=0.0335 | val_top1=16.30 | val_top5=21.74 | val_top10=22.83
Epoch 05 | loss=0.0219 | val_top1=16.30 | val_top5=21.74 | val_top10=22.83
Epoch 06 | loss=0.0175 | val_top1=16.30 | val_top5=21.74 | val_top10=22.83
Epoch 07 | loss=0.0146 | val_top1=16.30 | val_top5=21.74 | val_top10=22.83
Epoch 08 | loss=0.0126 | val_top1=15.22 | val_top5=21.74 | val_top10=22.83
Epoch 09 | loss=0.0109 | val_top1=16.30 | val_top5=21.74 | val_top10=22.83
Epoch 10 | loss=0.0097 | val_top1=17.39 | val_top5=21.74 | val_top10=22.83
Epoch 11 | loss=0.0086 | val_top1=18.48 | val_top5=21.74 | val_top10=22.83
Epoch 12 | loss=0.0078 | val_top1=17.39 | val_top5=21.74 | val_top10=22.83
Epoch 13 | loss=0.0071 | val_top1=17.39 | val_top5=21.74 | val_top10=22.83
Epoch 14 | loss=0.0064 | val_top1=17.39 | val_top5=21.74 | val_top10=22.83
Epoch 15 | loss=0.0059 | val_top1=17.39 | val_top5=21.74 | val_top10=22.83
Epoch 16 | loss=0.0054 | val_top1=17.39 | val_top5=21.74 | val_top10=23.91
Epoch 17 | loss=0.0050 | val_top1=17.39 | val_top5=21.74 | val_top10=23.91
Epoch 18 | loss=0.0047 | val_top1=17.39 | val_top5=21.74 | val_top10=23.91
Epoch 19 | loss=0.0044 | val_top1=17.39 | val_top5=21.74 | val_top10=23.91
Epoch 20 | loss=0.0041 | val_top1=17.39 | val_top5=21.74 | val_top10=23.91

Best validation top1: 18.47826086956522
Test metrics: {'top1': 21.663019693654267, 'top5': 26.477024070021884, 'top10': 28.971553610503282}

================================================================================
[8/16] Running BiGRUPoolEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}
Epoch 01 | loss=1.7417 | val_top1=9.78 | val_top5=13.04 | val_top10=13.04
Epoch 02 | loss=0.6763 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 03 | loss=0.2085 | val_top1=9.78 | val_top5=16.30 | val_top10=17.39
Epoch 04 | loss=0.0568 | val_top1=10.87 | val_top5=16.30 | val_top10=20.65
Epoch 05 | loss=0.0275 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 06 | loss=0.0211 | val_top1=13.04 | val_top5=17.39 | val_top10=20.65
Epoch 07 | loss=0.0175 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 08 | loss=0.0148 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 09 | loss=0.0128 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 10 | loss=0.0113 | val_top1=14.13 | val_top5=18.48 | val_top10=19.57
Epoch 11 | loss=0.0100 | val_top1=14.13 | val_top5=18.48 | val_top10=19.57
Epoch 12 | loss=0.0089 | val_top1=14.13 | val_top5=18.48 | val_top10=19.57
Epoch 13 | loss=0.0080 | val_top1=14.13 | val_top5=18.48 | val_top10=19.57
Epoch 14 | loss=0.0073 | val_top1=14.13 | val_top5=18.48 | val_top10=19.57
Epoch 15 | loss=0.0067 | val_top1=14.13 | val_top5=18.48 | val_top10=19.57
Epoch 16 | loss=0.0061 | val_top1=14.13 | val_top5=18.48 | val_top10=19.57
Epoch 17 | loss=0.0056 | val_top1=14.13 | val_top5=18.48 | val_top10=19.57
Epoch 18 | loss=0.0052 | val_top1=14.13 | val_top5=18.48 | val_top10=19.57
Epoch 19 | loss=0.0048 | val_top1=14.13 | val_top5=18.48 | val_top10=19.57
Epoch 20 | loss=0.0045 | val_top1=14.13 | val_top5=18.48 | val_top10=19.57

Best validation top1: 14.130434782608695
Test metrics: {'top1': 20.35010940919037, 'top5': 25.99562363238512, 'top10': 28.577680525164112}

================================================================================
[9/16] Running BiGRUPoolEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07, 'num_layers': 2, 'pool': 'max'}
Epoch 01 | loss=1.9884 | val_top1=10.87 | val_top5=11.96 | val_top10=11.96
Epoch 02 | loss=1.2300 | val_top1=9.78 | val_top5=13.04 | val_top10=16.30
Epoch 03 | loss=0.6828 | val_top1=8.70 | val_top5=13.04 | val_top10=14.13
Epoch 04 | loss=0.3136 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 05 | loss=0.1011 | val_top1=13.04 | val_top5=14.13 | val_top10=15.22
Epoch 06 | loss=0.0289 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 07 | loss=0.0088 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 08 | loss=0.0044 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 09 | loss=0.0034 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 10 | loss=0.0030 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 11 | loss=0.0026 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 12 | loss=0.0024 | val_top1=13.04 | val_top5=16.30 | val_top10=19.57
Epoch 13 | loss=0.0022 | val_top1=13.04 | val_top5=16.30 | val_top10=20.65
Epoch 14 | loss=0.0020 | val_top1=13.04 | val_top5=16.30 | val_top10=19.57
Epoch 15 | loss=0.0018 | val_top1=13.04 | val_top5=16.30 | val_top10=19.57
Epoch 16 | loss=0.0018 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 17 | loss=0.0016 | val_top1=13.04 | val_top5=16.30 | val_top10=20.65
Epoch 18 | loss=0.0015 | val_top1=13.04 | val_top5=16.30 | val_top10=20.65
Epoch 19 | loss=0.0014 | val_top1=13.04 | val_top5=17.39 | val_top10=20.65
Epoch 20 | loss=0.0013 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.58643326039387, 'top5': 21.050328227571114, 'top10': 24.15754923413567}

================================================================================
[10/16] Running BiGRUPoolEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07, 'num_layers': 2, 'pool': 'mean'}
Epoch 01 | loss=1.9841 | val_top1=9.78 | val_top5=10.87 | val_top10=10.87
Epoch 02 | loss=1.1875 | val_top1=9.78 | val_top5=11.96 | val_top10=11.96
Epoch 03 | loss=0.6739 | val_top1=14.13 | val_top5=16.30 | val_top10=20.65
Epoch 04 | loss=0.2757 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 05 | loss=0.1142 | val_top1=10.87 | val_top5=17.39 | val_top10=20.65
Epoch 06 | loss=0.0328 | val_top1=15.22 | val_top5=17.39 | val_top10=22.83
Epoch 07 | loss=0.0106 | val_top1=14.13 | val_top5=18.48 | val_top10=19.57
Epoch 08 | loss=0.0035 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 09 | loss=0.0030 | val_top1=11.96 | val_top5=19.57 | val_top10=20.65
Epoch 10 | loss=0.0025 | val_top1=11.96 | val_top5=19.57 | val_top10=21.74
Epoch 11 | loss=0.0023 | val_top1=11.96 | val_top5=19.57 | val_top10=21.74
Epoch 12 | loss=0.0020 | val_top1=11.96 | val_top5=19.57 | val_top10=21.74
Epoch 13 | loss=0.0018 | val_top1=11.96 | val_top5=20.65 | val_top10=21.74
Epoch 14 | loss=0.0017 | val_top1=11.96 | val_top5=20.65 | val_top10=21.74
Epoch 15 | loss=0.0016 | val_top1=11.96 | val_top5=20.65 | val_top10=21.74
Epoch 16 | loss=0.0015 | val_top1=11.96 | val_top5=20.65 | val_top10=21.74
Epoch 17 | loss=0.0013 | val_top1=11.96 | val_top5=20.65 | val_top10=22.83
Epoch 18 | loss=0.0013 | val_top1=13.04 | val_top5=20.65 | val_top10=22.83
Epoch 19 | loss=0.0012 | val_top1=13.04 | val_top5=20.65 | val_top10=22.83
Epoch 20 | loss=0.0011 | val_top1=13.04 | val_top5=20.65 | val_top10=22.83

Best validation top1: 15.217391304347826
Test metrics: {'top1': 16.717724288840262, 'top5': 21.2253829321663, 'top10': 24.288840262582056}

================================================================================
[11/16] Running BiGRUPoolEncoder with config:

,exp_name,input_dim,hidden_dim,output_dim,dropout,lr,weight_decay,batch_size,temperature,num_layers,pool,best_val_top1,val_top1,val_top5,val_top10,test_top1,test_top5,test_top10
6,bigru_max_h256_o256_drop0p0_lr0.0002_wd0.0001_...,1024,256,256,0.0,0.0002,0.0001,32,0.10,2,max,18.478261,18.478261,21.739130,22.826087,21.663020,26.477024,28.971554
14,bigru_max_h256_o256_drop0p1_lr0.0002_wd0.0001_...,1024,256,256,0.1,0.0002,0.0001,32,0.10,2,max,15.217391,15.217391,17.391304,20.652174,20.787746,25.601751,27.877462
2,bigru_max_h256_o256_drop0p0_lr0.0005_wd0.0001_...,1024,256,256,0.0,0.0005,0.0001,32,0.10,2,max,16.304348,16.304348,22.826087,23.913043,20.612691,25.295405,27.964989
12,bigru_max_h256_o256_drop0p1_lr0.0002_wd0.0001_...,1024,256,256,0.1,0.0002,0.0001,32,0.07,2,max,16.304348,16.304348,18.478261,20.652174,20.481400,25.645514,28.358862
7,bigru_mean_h256_o256_drop0p0_lr0.0002_wd0.0001...,1024,256,256,0.0,0.0002,0.0001,32,0.10,2,mean,14.130435,14.130435,18.478261,19.565217,20.350109,25.995624,28.577681
15,bigru_mean_h256_o256_drop0p1_lr0.0002_wd0.0001...,1024,256,256,0.1,0.0002,0.0001,32,0.10,2,mean,16.304348,16.304348,18.478261,21.739130,20.087527,25.032823,27.746171
4,bigru_max_h256_o256_drop0p0_lr0.0002_wd0.0001_...,1024,256,256,0.0,0.0002,0.0001,32,0.07,2,max,16.304348,16.304348,19.565217,23.913043,19.693654,25.864333,28.796499
10,bigru_max_h256_o256_drop0p1_lr0.0005_wd0.0001_...,1024,256,256,0.1,0.0005,0.0001,32,0.10,2,max,11.956522,11.956522,18.478261,20.652174,19.474836,24.463895,26.870897
5,bigru_mean_h256_o256_drop0p0_lr0.0002_wd0.0001...,1024,256,256,0.0,0.0002,0.0001,32,0.07,2,mean,15.217391,15.217391,19.565217,22.826087,19.387309,25.426696,28.665208
11,bigru_mean_h256_o256_drop0p1_lr0.0005_wd0.0001...,1024,256,256,0.1,0.0005,0.0001,32,0.10,2,mean,11.956522,11.956522,16.304348,17.391304,17.636761,22.013129,24.201313
0,bigru_max_h256_o256_drop0p0_lr0.0005_wd0.0001_...,1024,256,256,0.0,0.0005,0.0001,32,0.07,2,max,14.130435,14.130435,18.478261,20.652174,17.592998,23.938731,26.345733
1,bigru_mean_h256_o256_drop0p0_lr0.0005_wd0.0001...,1024,256,256,0.0,0.0005,0.0001,32,0.07,2,mean,13.043478,13.043478,17.391304,19.565217,16.980306,21.487965,24.463895
13,bigru_mean_h256_o256_drop0p1_lr0.0002_wd0.0001...,1024,256,256,0.1,0.0002,0.0001,32,0.07,2,mean,14.130435,14.130435,16.304348,16.304348,16.980306,22.144420,25.382932
9,bigru_mean_h256_o256_drop0p1_lr0.0005_wd0.0001...,1024,256,256,0.1,0.0005,0.0001,32,0.07,2,mean,15.217391,15.217391,17.391304,22.826087,16.717724,21.225383,24.288840
8,bigru_max_h256_o256_drop0p1_lr0.0005_wd0.0001_...,1024,256,256,0.1,0.0005,0.0001,32,0.07,2,max,13.043478,13.043478,14.130435,15.217391,16.586433,21.050328,24.157549
3,bigru_mean_h256_o256_drop0p0_lr0.0005_wd0.0001...,1024,256,256,0.0,0.0005,0.0001,32,0.10,2,mean,13.043478,13.043478,18.478261,18.478261,15.754923,20.087527,22.757112

In [23]:
from src.tasks.task3_cislr.models.bigru_encoder import BiGRUPoolEncoder, BiGRUAttentionEncoder
import os
import pandas as pd
BiGRUAttentionEncoder_grid_stage1 = {
    "input_dim": [1024],
    "hidden_dim": [256],
    "output_dim": [256],
    "dropout": [0.0, 0.1],
    "lr": [5e-4, 2e-4],
    "weight_decay": [1e-4],
    "batch_size": [32],
    "temperature": [0.07, 0.1],
    "num_layers": [1,2],
    #"pool": None,
    }

NUM_EPOCHS = 20
patience = 10
results_csv_BiGRUAttentionEncoder = "results/task3_cislr/bigru_attention_gridsearch_results.csv"
configs_BiGRUAttentionEncoder = expand_grid(BiGRUAttentionEncoder_grid_stage1)

print(f"Total configs: {len(configs_BiGRUAttentionEncoder)}")
print("Sample config:", configs_BiGRUAttentionEncoder[0])

all_results = []

for i, cfg in enumerate(configs_BiGRUAttentionEncoder, start=1):
    print("\n" + "=" * 80)
    print(f"[{i}/{len(configs_BiGRUAttentionEncoder)}] Running BiGRUAttentionEncoder with config:")
    print(cfg)

    exp_name = (
        f"bigru_attention_"
        f"h{cfg['hidden_dim']}_o{cfg['output_dim']}_"
        f"drop{str(cfg['dropout']).replace('.', 'p')}_"
        f"lr{cfg['lr']}_"
        f"wd{cfg['weight_decay']}_"
        f"temp{str(cfg['temperature']).replace('.', 'p')}_"
        f"layers{cfg['num_layers']}"
    )

    try:
        model = BiGRUAttentionEncoder(
            input_dim=cfg["input_dim"],
            hidden_dim=cfg["hidden_dim"],
            out_dim=cfg["output_dim"],
            num_layers=cfg["num_layers"],
            dropout=cfg["dropout"],
        )

        results = run_training(
            train_csv=ROOT / "dataset/task3_cislr/splits/train_repeated.csv",
            val_csv=ROOT / "dataset/task3_cislr/splits/val_repeated_no_proto_overlap.csv",
            prototype_csv=ROOT / "dataset/task3_cislr/splits/prototype.csv",
            test_csv=ROOT / "dataset/task3_cislr/splits/test.csv",
            feature_pkl=ROOT / "dataset/task3_cislr/features/I3D_features.pkl",
            out_dir=ROOT / "results/task3_cislr/BiGRUAttentionEncoder_gridsearch" / exp_name,
            batch_size=cfg["batch_size"],
            num_workers=0,
            pooling=None,
            lr=cfg["lr"],
            weight_decay=cfg["weight_decay"],
            temperature=cfg["temperature"],
            epochs=NUM_EPOCHS,
            early_stopping_patience=patience,
            model=model,
        )

        row = {
            "exp_name": exp_name,
            **cfg,
            "best_val_top1": results["best_val_top1"],
            "val_top1": results["best_val_metrics"]["top1"],
            "val_top5": results["best_val_metrics"]["top5"],
            "val_top10": results["best_val_metrics"]["top10"],
            "test_top1": results["test_metrics"]["top1"],
            "test_top5": results["test_metrics"]["top5"],
            "test_top10": results["test_metrics"]["top10"],
        }

    except Exception as e:
        print(f"Failed config: {cfg}")
        print("Error:", e)
        row = {
            "exp_name": exp_name,
            **cfg,
            "error": str(e),
        }

    all_results.append(row)

    pd.DataFrame([row]).to_csv(
        ROOT / results_csv_BiGRUAttentionEncoder,
        mode="a",
        header=not os.path.exists(ROOT / results_csv_BiGRUAttentionEncoder),
        index=False,
    )

df = pd.DataFrame(all_results)
display(df.sort_values("test_top1", ascending=False))

Total configs: 16
Sample config: {'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07, 'num_layers': 1}

================================================================================
[1/16] Running BiGRUAttentionEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07, 'num_layers': 1}
Epoch 01 | loss=1.7869 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 02 | loss=0.7711 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 03 | loss=0.2436 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 04 | loss=0.0354 | val_top1=11.96 | val_top5=19.57 | val_top10=21.74
Epoch 05 | loss=0.0062 | val_top1=11.96 | val_top5=19.57 | val_top10=21.74
Epoch 06 | loss=0.0037 | val_top1=11.96 | val_top5=18.48 | val_top10=22.83
Epoch 07 | loss=0.0031 | val_top1=11.96 | val_top5=18.48 | val_top10=21.74
Epoch 08 | loss=0.0026 | val_top1=11.96 | val_top5=18.48 | val_top10=21.74
Epoch 09 | loss=0.0023 | val_top1=11.96 | val_top5=18.48 | val_top10=21.74
Epoch 10 | loss=0.0021 | val_top1=11.96 | val_top5=18.48 | val_top10=22.83
Epoch 11 | loss=0.0019 | val_top1=11.96 | val_top5=19.57 | val_top10=22.83
Epoch 12 | loss=0.0017 | val_top1=13.04 | val_top5=20.65 | val_top10=22.83
Epoch 13 | loss=0.0015 | val_top1=13.04 | val_top5=20.65 | val_top10=22.83
Epoch 14 | loss=0.0014 | val_top1=14.13 | val_top5=20.65 | val_top10=22.83
Epoch 15 | loss=0.0013 | val_top1=14.13 | val_top5=20.65 | val_top10=22.83
Epoch 16 | loss=0.0012 | val_top1=14.13 | val_top5=20.65 | val_top10=22.83
Epoch 17 | loss=0.0011 | val_top1=14.13 | val_top5=20.65 | val_top10=22.83
Epoch 18 | loss=0.0011 | val_top1=14.13 | val_top5=20.65 | val_top10=22.83
Epoch 19 | loss=0.0010 | val_top1=14.13 | val_top5=20.65 | val_top10=22.83
Epoch 20 | loss=0.0009 | val_top1=14.13 | val_top5=20.65 | val_top10=22.83

Best validation top1: 14.130434782608695
Test metrics: {'top1': 19.037199124726477, 'top5': 25.47045951859956, 'top10': 28.183807439824946}

================================================================================
[2/16] Running BiGRUAttentionEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07, 'num_layers': 2}
Epoch 01 | loss=1.9883 | val_top1=8.70 | val_top5=10.87 | val_top10=14.13
Epoch 02 | loss=1.1573 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 03 | loss=0.6122 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 04 | loss=0.2611 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 05 | loss=0.1212 | val_top1=9.78 | val_top5=17.39 | val_top10=20.65
Epoch 06 | loss=0.0678 | val_top1=14.13 | val_top5=16.30 | val_top10=17.39
Epoch 07 | loss=0.0090 | val_top1=14.13 | val_top5=18.48 | val_top10=21.74
Epoch 08 | loss=0.0027 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 09 | loss=0.0021 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 10 | loss=0.0018 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 11 | loss=0.0016 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 12 | loss=0.0014 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 13 | loss=0.0013 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 14 | loss=0.0012 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 15 | loss=0.0011 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 16 | loss=0.0010 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Early stopping triggered at epoch 16.

Best validation top1: 14.130434782608695
Test metrics: {'top1': 16.49890590809628, 'top5': 21.050328227571114, 'top10': 24.11378555798687}

================================================================================
[3/16] Running BiGRUAttentionEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1}
Epoch 01 | loss=1.8105 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 02 | loss=0.7888 | val_top1=13.04 | val_top5=16.30 | val_top10=16.30
Epoch 03 | loss=0.2480 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 04 | loss=0.0638 | val_top1=14.13 | val_top5=17.39 | val_top10=22.83
Epoch 05 | loss=0.0222 | val_top1=15.22 | val_top5=17.39 | val_top10=22.83
Epoch 06 | loss=0.0150 | val_top1=13.04 | val_top5=17.39 | val_top10=25.00
Epoch 07 | loss=0.0124 | val_top1=13.04 | val_top5=17.39 | val_top10=25.00
Epoch 08 | loss=0.0106 | val_top1=13.04 | val_top5=18.48 | val_top10=23.91
Epoch 09 | loss=0.0093 | val_top1=13.04 | val_top5=20.65 | val_top10=23.91
Epoch 10 | loss=0.0082 | val_top1=13.04 | val_top5=20.65 | val_top10=22.83
Epoch 11 | loss=0.0073 | val_top1=13.04 | val_top5=20.65 | val_top10=22.83
Epoch 12 | loss=0.0066 | val_top1=14.13 | val_top5=20.65 | val_top10=22.83
Epoch 13 | loss=0.0059 | val_top1=14.13 | val_top5=20.65 | val_top10=22.83
Epoch 14 | loss=0.0054 | val_top1=14.13 | val_top5=21.74 | val_top10=22.83
Epoch 15 | loss=0.0049 | val_top1=14.13 | val_top5=21.74 | val_top10=22.83
Early stopping triggered at epoch 15.

Best validation top1: 15.217391304347826
Test metrics: {'top1': 19.037199124726477, 'top5': 25.032822757111596, 'top10': 28.533916849015316}

================================================================================
[4/16] Running BiGRUAttentionEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2}
Epoch 01 | loss=1.9849 | val_top1=7.61 | val_top5=8.70 | val_top10=9.78
Epoch 02 | loss=1.1118 | val_top1=8.70 | val_top5=10.87 | val_top10=13.04
Epoch 03 | loss=0.5397 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 04 | loss=0.2353 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 05 | loss=0.0688 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 06 | loss=0.0182 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 07 | loss=0.0110 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 08 | loss=0.0093 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 09 | loss=0.0081 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 10 | loss=0.0072 | val_top1=11.96 | val_top5=15.22 | val_top10=19.57
Epoch 11 | loss=0.0064 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 12 | loss=0.0058 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 13 | loss=0.0053 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 14 | loss=0.0049 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 15 | loss=0.0045 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 16 | loss=0.0042 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 17 | loss=0.0039 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 18 | loss=0.0036 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 19 | loss=0.0034 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 20 | loss=0.0032 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57

Best validation top1: 13.043478260869565
Test metrics: {'top1': 19.562363238512035, 'top5': 23.676148796498907, 'top10': 25.820568927789935}

================================================================================
[5/16] Running BiGRUAttentionEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07, 'num_layers': 1}
Epoch 01 | loss=1.6897 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 02 | loss=0.5861 | val_top1=11.96 | val_top5=17.39 | val_top10=21.74
Epoch 03 | loss=0.1216 | val_top1=13.04 | val_top5=16.30 | val_top10=17.39
Epoch 04 | loss=0.0252 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 05 | loss=0.0130 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 06 | loss=0.0102 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 07 | loss=0.0084 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 08 | loss=0.0072 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 09 | loss=0.0062 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 10 | loss=0.0054 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 11 | loss=0.0048 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 12 | loss=0.0043 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 13 | loss=0.0039 | val_top1=15.22 | val_top5=18.48 | val_top10=21.74
Epoch 14 | loss=0.0035 | val_top1=15.22 | val_top5=18.48 | val_top10=21.74
Epoch 15 | loss=0.0032 | val_top1=15.22 | val_top5=18.48 | val_top10=21.74
Epoch 16 | loss=0.0029 | val_top1=15.22 | val_top5=18.48 | val_top10=21.74
Epoch 17 | loss=0.0027 | val_top1=15.22 | val_top5=20.65 | val_top10=21.74
Epoch 18 | loss=0.0025 | val_top1=16.30 | val_top5=20.65 | val_top10=21.74
Epoch 19 | loss=0.0023 | val_top1=16.30 | val_top5=20.65 | val_top10=21.74
Epoch 20 | loss=0.0021 | val_top1=16.30 | val_top5=20.65 | val_top10=21.74

Best validation top1: 16.304347826086957
Test metrics: {'top1': 19.73741794310722, 'top5': 26.477024070021884, 'top10': 29.671772428884026}

================================================================================
[6/16] Running BiGRUAttentionEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07, 'num_layers': 2}
Epoch 01 | loss=1.7664 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 02 | loss=0.6445 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 03 | loss=0.1518 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 04 | loss=0.0238 | val_top1=10.87 | val_top5=18.48 | val_top10=22.83
Epoch 05 | loss=0.0074 | val_top1=10.87 | val_top5=19.57 | val_top10=22.83
Epoch 06 | loss=0.0055 | val_top1=10.87 | val_top5=20.65 | val_top10=22.83
Epoch 07 | loss=0.0046 | val_top1=10.87 | val_top5=20.65 | val_top10=22.83
Epoch 08 | loss=0.0039 | val_top1=10.87 | val_top5=20.65 | val_top10=22.83
Epoch 09 | loss=0.0035 | val_top1=10.87 | val_top5=20.65 | val_top10=22.83
Epoch 10 | loss=0.0031 | val_top1=10.87 | val_top5=20.65 | val_top10=22.83
Epoch 11 | loss=0.0028 | val_top1=10.87 | val_top5=20.65 | val_top10=22.83
Epoch 12 | loss=0.0025 | val_top1=10.87 | val_top5=20.65 | val_top10=22.83
Early stopping triggered at epoch 12.

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.673960612691467, 'top5': 21.400437636761488, 'top10': 24.50765864332604}

================================================================================
[7/16] Running BiGRUAttentionEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1}
Epoch 01 | loss=1.7116 | val_top1=11.96 | val_top5=11.96 | val_top10=13.04
Epoch 02 | loss=0.6362 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 03 | loss=0.2088 | val_top1=10.87 | val_top5=17.39 | val_top10=19.57
Epoch 04 | loss=0.0777 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65
Epoch 05 | loss=0.0467 | val_top1=10.87 | val_top5=19.57 | val_top10=20.65
Epoch 06 | loss=0.0349 | val_top1=10.87 | val_top5=20.65 | val_top10=20.65
Epoch 07 | loss=0.0279 | val_top1=11.96 | val_top5=20.65 | val_top10=20.65
Epoch 08 | loss=0.0231 | val_top1=14.13 | val_top5=20.65 | val_top10=20.65
Epoch 09 | loss=0.0195 | val_top1=15.22 | val_top5=20.65 | val_top10=21.74
Epoch 10 | loss=0.0168 | val_top1=16.30 | val_top5=20.65 | val_top10=21.74
Epoch 11 | loss=0.0147 | val_top1=16.30 | val_top5=20.65 | val_top10=21.74
Epoch 12 | loss=0.0130 | val_top1=16.30 | val_top5=20.65 | val_top10=21.74
Epoch 13 | loss=0.0116 | val_top1=16.30 | val_top5=20.65 | val_top10=21.74
Epoch 14 | loss=0.0104 | val_top1=16.30 | val_top5=20.65 | val_top10=21.74
Epoch 15 | loss=0.0094 | val_top1=16.30 | val_top5=21.74 | val_top10=21.74
Epoch 16 | loss=0.0086 | val_top1=16.30 | val_top5=21.74 | val_top10=22.83
Epoch 17 | loss=0.0079 | val_top1=16.30 | val_top5=21.74 | val_top10=22.83
Epoch 18 | loss=0.0073 | val_top1=16.30 | val_top5=21.74 | val_top10=22.83
Epoch 19 | loss=0.0067 | val_top1=16.30 | val_top5=21.74 | val_top10=23.91
Epoch 20 | loss=0.0062 | val_top1=16.30 | val_top5=21.74 | val_top10=23.91
Early stopping triggered at epoch 20.

Best validation top1: 16.304347826086957
Test metrics: {'top1': 21.356673960612692, 'top5': 27.045951859956237, 'top10': 29.36542669584245}

================================================================================
[8/16] Running BiGRUAttentionEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2}
Epoch 01 | loss=1.7818 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 02 | loss=0.6801 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 03 | loss=0.1872 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 04 | loss=0.0537 | val_top1=9.78 | val_top5=17.39 | val_top10=21.74
Epoch 05 | loss=0.0279 | val_top1=9.78 | val_top5=17.39 | val_top10=21.74
Epoch 06 | loss=0.0212 | val_top1=10.87 | val_top5=18.48 | val_top10=22.83
Epoch 07 | loss=0.0175 | val_top1=10.87 | val_top5=18.48 | val_top10=22.83
Epoch 08 | loss=0.0148 | val_top1=10.87 | val_top5=19.57 | val_top10=23.91
Epoch 09 | loss=0.0128 | val_top1=10.87 | val_top5=19.57 | val_top10=23.91
Epoch 10 | loss=0.0112 | val_top1=11.96 | val_top5=19.57 | val_top10=23.91
Epoch 11 | loss=0.0099 | val_top1=11.96 | val_top5=19.57 | val_top10=23.91
Epoch 12 | loss=0.0088 | val_top1=11.96 | val_top5=20.65 | val_top10=23.91
Early stopping triggered at epoch 12.

Best validation top1: 11.956521739130435
Test metrics: {'top1': 17.24288840262582, 'top5': 22.669584245076585, 'top10': 25.339168490153174}

================================================================================
[9/16] Running BiGRUAttentionEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07, 'num_layers': 1}
Epoch 01 | loss=1.8866 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 02 | loss=0.9385 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 03 | loss=0.4204 | val_top1=10.87 | val_top5=17.39 | val_top10=19.57
Epoch 04 | loss=0.1263 | val_top1=11.96 | val_top5=15.22 | val_top10=21.74
Epoch 05 | loss=0.0335 | val_top1=10.87 | val_top5=18.48 | val_top10=21.74
Epoch 06 | loss=0.0110 | val_top1=10.87 | val_top5=17.39 | val_top10=21.74
Epoch 07 | loss=0.0076 | val_top1=10.87 | val_top5=16.30 | val_top10=23.91
Epoch 08 | loss=0.0059 | val_top1=10.87 | val_top5=19.57 | val_top10=23.91
Epoch 09 | loss=0.0050 | val_top1=10.87 | val_top5=19.57 | val_top10=23.91
Epoch 10 | loss=0.0045 | val_top1=13.04 | val_top5=19.57 | val_top10=22.83
Epoch 11 | loss=0.0039 | val_top1=14.13 | val_top5=18.48 | val_top10=23.91
Epoch 12 | loss=0.0035 | val_top1=14.13 | val_top5=18.48 | val_top10=22.83
Epoch 13 | loss=0.0031 | val_top1=14.13 | val_top5=18.48 | val_top10=25.00
Epoch 14 | loss=0.0029 | val_top1=14.13 | val_top5=19.57 | val_top10=25.00
Epoch 15 | loss=0.0026 | val_top1=13.04 | val_top5=18.48 | val_top10=23.91
Epoch 16 | loss=0.0024 | val_top1=13.04 | val_top5=19.57 | val_top10=23.91
Epoch 17 | loss=0.0023 | val_top1=13.04 | val_top5=20.65 | val_top10=23.91
Epoch 18 | loss=0.0020 | val_top1=13.04 | val_top5=20.65 | val_top10=25.00
Epoch 19 | loss=0.0019 | val_top1=13.04 | val_top5=21.74 | val_top10=25.00
Epoch 20 | loss=0.0018 | val_top1=14.13 | val_top5=21.74 | val_top10=25.00

Best validation top1: 14.130434782608695
Test metrics: {'top1': 18.46827133479212, 'top5': 24.551422319474835, 'top10': 27.045951859956237}

================================================================================
[10/16] Running BiGRUAttentionEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.07, 'num_layers': 2}
Epoch 01 | loss=1.9848 | val_top1=11.96 | val_top5=11.96 | val_top10=11.96
Epoch 02 | loss=1.2603 | val_top1=8.70 | val_top5=10.87 | val_top10=13.04
Epoch 03 | loss=0.7444 | val_top1=8.70 | val_top5=11.96 | val_top10=15.22
Epoch 04 | loss=0.3822 | val_top1=9.78 | val_top5=13.04 | val_top10=13.04
Epoch 05 | loss=0.1603 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 06 | loss=0.0818 | val_top1=10.87 | val_top5=17.39 | val_top10=17.39
Epoch 07 | loss=0.0270 | val_top1=10.87 | val_top5=18.48 | val_top10=21.74
Epoch 08 | loss=0.0052 | val_top1=10.87 | val_top5=17.39 | val_top10=20.65
Epoch 09 | loss=0.0030 | val_top1=10.87 | val_top5=17.39 | val_top10=20.65
Epoch 10 | loss=0.0026 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 11 | loss=0.0023 | val_top1=10.87 | val_top5=17.39 | val_top10=19.57
Early stopping triggered at epoch 11.

Best validation top1: 11.956521739130435
Test metrics: {'top1': 15.492341356673961, 'top5': 18.161925601750546, 'top10': 20.13129102844639}

================================================================================
[11/16] Running BiGRUAttentionEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1}
Epoch 01 | loss=1.8253 | val_top1=8.70 | val_top5=11.96 | val_top10=13.04
Epoch 02 | loss=0.9311 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 03 | loss=0.4079 | val_top1=11.96 | val_top5=13.04 | val_top10=15.22
Epoch 04 | loss=0.1572 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 05 | loss=0.0605 | val_top1=10.87 | val_top5=18.48 | val_top10=21.74
Epoch 06 | loss=0.0311 | val_top1=10.87 | val_top5=19.57 | val_top10=21.74
Epoch 07 | loss=0.0249 | val_top1=10.87 | val_top5=19.57 | val_top10=22.83
Epoch 08 | loss=0.0201 | val_top1=11.96 | val_top5=18.48 | val_top10=22.83
Epoch 09 | loss=0.0168 | val_top1=11.96 | val_top5=17.39 | val_top10=25.00
Epoch 10 | loss=0.0149 | val_top1=11.96 | val_top5=17.39 | val_top10=23.91
Epoch 11 | loss=0.0130 | val_top1=11.96 | val_top5=18.48 | val_top10=25.00
Epoch 12 | loss=0.0113 | val_top1=11.96 | val_top5=20.65 | val_top10=23.91
Epoch 13 | loss=0.0102 | val_top1=11.96 | val_top5=19.57 | val_top10=23.91
Early stopping triggered at epoch 13.

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.63019693654267, 'top5': 21.925601750547045, 'top10': 24.945295404814004}

================================================================================
[12/16] Running BiGRUAttentionEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.1, 'lr': 0.0005, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2}
Epoch 01 | loss=2.0021 | val_top1=8.70 | val_top5=10.87 | val_top10=13.04
Epoch 02 | loss=1.2200 | val_top1=9.78 | val_top5=10.87 | val_top10=14.13
Epoch 03 | loss=0.6768 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30
Epoch 04 | loss=0.3113 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 05 | loss=0.1071 | val_top1=9.78 | val_top5=13.04 | val_top10=16.30
Epoch 06 | loss=0.0404 | val_top1=10.87 | val_top5=16.30 | val_top10=20.65
Epoch 07 | loss=0.0171 | val_top1=13.04 | val_top5=17.39 | val_top10=20.65
Epoch 08 | loss=0.0126 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 09 | loss=0.0109 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 10 | loss=0.0094 | val_top1=13.04 | val_top5=17.39 | val_top10=20.65
Epoch 11 | loss=0.0086 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 12 | loss=0.0077 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 13 | loss=0.0069 | val_top1=11.96 | val_top5=17.39 | val_top10=21.74

,exp_name,input_dim,hidden_dim,output_dim,dropout,lr,weight_decay,batch_size,temperature,num_layers,best_val_top1,val_top1,val_top5,val_top10,test_top1,test_top5,test_top10
6,bigru_attention_h256_o256_drop0p0_lr0.0002_wd0...,1024,256,256,0.0,0.0002,0.0001,32,0.10,1,16.304348,16.304348,20.652174,21.739130,21.356674,27.045952,29.365427
14,bigru_attention_h256_o256_drop0p1_lr0.0002_wd0...,1024,256,256,0.1,0.0002,0.0001,32,0.10,1,17.391304,17.391304,19.565217,23.913043,20.393873,25.908096,28.315098
4,bigru_attention_h256_o256_drop0p0_lr0.0002_wd0...,1024,256,256,0.0,0.0002,0.0001,32,0.07,1,16.304348,16.304348,20.652174,21.739130,19.737418,26.477024,29.671772
3,bigru_attention_h256_o256_drop0p0_lr0.0005_wd0...,1024,256,256,0.0,0.0005,0.0001,32,0.10,2,13.043478,13.043478,17.391304,19.565217,19.562363,23.676149,25.820569
12,bigru_attention_h256_o256_drop0p1_lr0.0002_wd0...,1024,256,256,0.1,0.0002,0.0001,32,0.07,1,16.304348,16.304348,21.739130,21.739130,19.387309,26.039387,28.752735
0,bigru_attention_h256_o256_drop0p0_lr0.0005_wd0...,1024,256,256,0.0,0.0005,0.0001,32,0.07,1,14.130435,14.130435,20.652174,22.826087,19.037199,25.470460,28.183807
2,bigru_attention_h256_o256_drop0p0_lr0.0005_wd0...,1024,256,256,0.0,0.0005,0.0001,32,0.10,1,15.217391,15.217391,17.391304,22.826087,19.037199,25.032823,28.533917
15,bigru_attention_h256_o256_drop0p1_lr0.0002_wd0...,1024,256,256,0.1,0.0002,0.0001,32,0.10,2,16.304348,16.304348,21.739130,22.826087,18.862144,24.682713,27.483589
8,bigru_attention_h256_o256_drop0p1_lr0.0005_wd0...,1024,256,256,0.1,0.0005,0.0001,32,0.07,1,14.130435,14.130435,18.478261,23.913043,18.468271,24.551422,27.045952
13,bigru_attention_h256_o256_drop0p1_lr0.0002_wd0...,1024,256,256,0.1,0.0002,0.0001,32,0.07,2,15.217391,15.217391,17.391304,21.739130,18.161926,24.070022,27.527352
7,bigru_attention_h256_o256_drop0p0_lr0.0002_wd0...,1024,256,256,0.0,0.0002,0.0001,32,0.10,2,11.956522,11.956522,15.217391,16.304348,17.242888,22.669584,25.339168
5,bigru_attention_h256_o256_drop0p0_lr0.0002_wd0...,1024,256,256,0.0,0.0002,0.0001,32,0.07,2,11.956522,11.956522,15.217391,16.304348,16.673961,21.400438,24.507659
10,bigru_attention_h256_o256_drop0p1_lr0.0005_wd0...,1024,256,256,0.1,0.0005,0.0001,32,0.10,1,11.956522,11.956522,13.043478,15.217391,16.630197,21.925602,24.945295
1,bigru_attention_h256_o256_drop0p0_lr0.0005_wd0...,1024,256,256,0.0,0.0005,0.0001,32,0.07,2,14.130435,14.130435,16.304348,17.391304,16.498906,21.050328,24.113786
9,bigru_attention_h256_o256_drop0p1_lr0.0005_wd0...,1024,256,256,0.1,0.0005,0.0001,32,0.07,2,11.956522,11.956522,11.956522,11.956522,15.492341,18.161926,20.131291
11,bigru_attention_h256_o256_drop0p1_lr0.0005_wd0...,1024,256,256,0.1,0.0005,0.0001,32,0.10,2,13.043478,13.043478,15.217391,16.304348,15.404814,20.393873,22.713348

In [5]:
from src.utils.set_seeds import set_seed
from src.utils.expand_grid import expand_grid
from src.tasks.task3_cislr.models.bigru_encoder import BiGRUPoolEncoder, BiGRUAttentionEncoder
from src.tasks.task3_cislr.training.train_retreival import run_training

import os
import pandas as pd

seeds = [1990,42,2024]
BiGRUPoolEncoder_grid_stage1 = {
    "input_dim": [1024],
    "hidden_dim": [128,256,512],
    "output_dim": [128,256,512],
    "dropout": [0.0],
    "lr": [2e-4],
    "weight_decay": [1e-4],
    "batch_size": [32],
    "temperature": [0.1],
    "num_layers": [1],
    "pool": ["max"],
    }
NUM_EPOCHS = 20
patience = 10

results_csv_BiGRUPoolEncoder_with_seeds = "results/task3_cislr/bigru_pool_gridsearch_results_with_seeds.csv"
configs_BiGRUPoolEncoder = expand_grid(BiGRUPoolEncoder_grid_stage1)

print(f"Total configs: {len(configs_BiGRUPoolEncoder)}")
print("Sample config:", configs_BiGRUPoolEncoder[0])

all_results = []

for seed in seeds:
    print("\n" + "=" * 80)
    print(f"Running seed: {seed}")
    set_seed(seed)

    for i, cfg in enumerate(configs_BiGRUPoolEncoder, start=1):
        print("\n" + "=" * 80)
        print(f"[{i}/{len(configs_BiGRUPoolEncoder)}] Running BiGRUPoolEncoder with config:")
        print(cfg)

        exp_name = (
            f"bigru_pool_"
            f"h{cfg['hidden_dim']}_o{cfg['output_dim']}_"
            f"drop{str(cfg['dropout']).replace('.', 'p')}_"
            f"lr{cfg['lr']}_"
            f"wd{cfg['weight_decay']}_"
            f"temp{str(cfg['temperature']).replace('.', 'p')}_"
            f"layers{cfg['num_layers']}_"
            f"seed{seed}"
        )

        try:
            model = BiGRUPoolEncoder(
                input_dim=cfg["input_dim"],
                hidden_dim=cfg["hidden_dim"],
                out_dim=cfg["output_dim"],
                num_layers=cfg["num_layers"],
                pool=cfg["pool"],
                dropout=cfg["dropout"],
            )

            results = run_training(
                train_csv=ROOT / "dataset/task3_cislr/splits/train_repeated.csv",
                val_csv=ROOT / "dataset/task3_cislr/splits/val_repeated_no_proto_overlap.csv",
                prototype_csv=ROOT / "dataset/task3_cislr/splits/prototype.csv",
                test_csv=ROOT / "dataset/task3_cislr/splits/test.csv",
                feature_pkl=ROOT / "dataset/task3_cislr/features/I3D_features.pkl",
                out_dir=ROOT / "results/task3_cislr/BiGRUPoolEncoder_gridsearch" / exp_name,
                batch_size=cfg["batch_size"],
                num_workers=0,
                pooling=cfg["pool"] if cfg["pool"] in ["max", "mean"] else None,
                lr=cfg["lr"],
                weight_decay=cfg["weight_decay"],
                temperature=cfg["temperature"],
                epochs=NUM_EPOCHS,
                early_stopping_patience=None,
                model=model,
            )

            row = {
                "exp_name": exp_name,
                **cfg,
                "best_val_top1": results["best_val_top1"],
                "val_top1": results["best_val_metrics"]["top1"],
                "val_top5": results["best_val_metrics"]["top5"],
                "val_top10": results["best_val_metrics"]["top10"],
                "test_top1": results["test_metrics"]["top1"],
                "test_top5": results["test_metrics"]["top5"],
                "test_top10": results["test_metrics"]["top10"],
                "seed": seed,
            }

        except Exception as e:
            print(f"Failed config: {cfg}")
            print("Error:", e)
            row = {
                "exp_name": exp_name,
                **cfg,
                "seed": seed,
                "error": str(e),
            }

        all_results.append(row)

        pd.DataFrame([row]).to_csv(
            ROOT / results_csv_BiGRUPoolEncoder_with_seeds,
            mode="a",
            header=not os.path.exists(ROOT / results_csv_BiGRUPoolEncoder_with_seeds),
            index=False,
        )

df = pd.DataFrame(all_results)
display(df.sort_values("test_top1", ascending=False))

Total configs: 9
Sample config: {'input_dim': 1024, 'hidden_dim': 128, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'max'}

================================================================================
Running seed: 1990

================================================================================
[1/9] Running BiGRUPoolEncoder with config:
{'input_dim': 1024, 'hidden_dim': 128, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'max'}
Epoch 01 | loss=1.8655 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30
Epoch 02 | loss=0.7507 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 03 | loss=0.2738 | val_top1=10.87 | val_top5=19.57 | val_top10=19.57
Epoch 04 | loss=0.1153 | val_top1=13.04 | val_top5=19.57 | val_top10=19.57
Epoch 05 | loss=0.0690 | val_top1=14.13 | val_top5=18.48 | val_top10=19.57
Epoch 06 | loss=0.0506 | val_top1=15.22 | val_top5=18.48 | val_top10=20.65
Epoch 07 | loss=0.0401 | val_top1=15.22 | val_top5=17.39 | val_top10=20.65
Epoch 08 | loss=0.0330 | val_top1=15.22 | val_top5=18.48 | val_top10=21.74
Epoch 09 | loss=0.0279 | val_top1=15.22 | val_top5=18.48 | val_top10=22.83
Epoch 10 | loss=0.0241 | val_top1=15.22 | val_top5=18.48 | val_top10=22.83
Epoch 11 | loss=0.0211 | val_top1=15.22 | val_top5=18.48 | val_top10=22.83
Epoch 12 | loss=0.0187 | val_top1=15.22 | val_top5=18.48 | val_top10=22.83
Epoch 13 | loss=0.0167 | val_top1=15.22 | val_top5=18.48 | val_top10=22.83
Epoch 14 | loss=0.0151 | val_top1=15.22 | val_top5=18.48 | val_top10=22.83
Epoch 15 | loss=0.0137 | val_top1=15.22 | val_top5=19.57 | val_top10=22.83
Epoch 16 | loss=0.0126 | val_top1=15.22 | val_top5=19.57 | val_top10=22.83
Epoch 17 | loss=0.0115 | val_top1=14.13 | val_top5=18.48 | val_top10=22.83
Epoch 18 | loss=0.0107 | val_top1=14.13 | val_top5=18.48 | val_top10=22.83
Epoch 19 | loss=0.0099 | val_top1=14.13 | val_top5=18.48 | val_top10=22.83
Epoch 20 | loss=0.0092 | val_top1=14.13 | val_top5=18.48 | val_top10=22.83

Best validation top1: 15.217391304347826
Test metrics: {'top1': 18.687089715536104, 'top5': 24.37636761487965, 'top10': 27.65864332603939}

================================================================================
[2/9] Running BiGRUPoolEncoder with config:
{'input_dim': 1024, 'hidden_dim': 128, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'max'}
Epoch 01 | loss=1.7511 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 02 | loss=0.7745 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 03 | loss=0.3246 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 04 | loss=0.1485 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 05 | loss=0.0882 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65
Epoch 06 | loss=0.0633 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 07 | loss=0.0494 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 08 | loss=0.0403 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 09 | loss=0.0339 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 10 | loss=0.0291 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 11 | loss=0.0254 | val_top1=14.13 | val_top5=19.57 | val_top10=22.83
Epoch 12 | loss=0.0224 | val_top1=14.13 | val_top5=20.65 | val_top10=22.83
Epoch 13 | loss=0.0201 | val_top1=14.13 | val_top5=20.65 | val_top10=22.83
Epoch 14 | loss=0.0181 | val_top1=14.13 | val_top5=20.65 | val_top10=22.83
Epoch 15 | loss=0.0164 | val_top1=15.22 | val_top5=20.65 | val_top10=22.83
Epoch 16 | loss=0.0150 | val_top1=15.22 | val_top5=20.65 | val_top10=22.83
Epoch 17 | loss=0.0137 | val_top1=15.22 | val_top5=20.65 | val_top10=22.83
Epoch 18 | loss=0.0126 | val_top1=15.22 | val_top5=20.65 | val_top10=22.83
Epoch 19 | loss=0.0117 | val_top1=15.22 | val_top5=21.74 | val_top10=22.83
Epoch 20 | loss=0.0109 | val_top1=16.30 | val_top5=21.74 | val_top10=22.83

Best validation top1: 16.304347826086957
Test metrics: {'top1': 21.00656455142232, 'top5': 26.958424507658645, 'top10': 29.452954048140043}

================================================================================
[3/9] Running BiGRUPoolEncoder with config:
{'input_dim': 1024, 'hidden_dim': 128, 'output_dim': 512, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'max'}
Epoch 01 | loss=1.7633 | val_top1=11.96 | val_top5=13.04 | val_top10=18.48
Epoch 02 | loss=0.7598 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 03 | loss=0.3369 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 04 | loss=0.1658 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 05 | loss=0.1018 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 06 | loss=0.0724 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 07 | loss=0.0562 | val_top1=15.22 | val_top5=19.57 | val_top10=21.74
Epoch 08 | loss=0.0456 | val_top1=15.22 | val_top5=19.57 | val_top10=21.74
Epoch 09 | loss=0.0383 | val_top1=15.22 | val_top5=19.57 | val_top10=22.83
Epoch 10 | loss=0.0328 | val_top1=16.30 | val_top5=19.57 | val_top10=23.91
Epoch 11 | loss=0.0286 | val_top1=16.30 | val_top5=19.57 | val_top10=23.91
Epoch 12 | loss=0.0252 | val_top1=16.30 | val_top5=20.65 | val_top10=23.91
Epoch 13 | loss=0.0225 | val_top1=17.39 | val_top5=20.65 | val_top10=23.91
Epoch 14 | loss=0.0202 | val_top1=17.39 | val_top5=20.65 | val_top10=23.91
Epoch 15 | loss=0.0183 | val_top1=17.39 | val_top5=20.65 | val_top10=23.91
Epoch 16 | loss=0.0167 | val_top1=18.48 | val_top5=21.74 | val_top10=23.91
Epoch 17 | loss=0.0153 | val_top1=18.48 | val_top5=21.74 | val_top10=23.91
Epoch 18 | loss=0.0141 | val_top1=17.39 | val_top5=21.74 | val_top10=23.91
Epoch 19 | loss=0.0130 | val_top1=17.39 | val_top5=21.74 | val_top10=23.91
Epoch 20 | loss=0.0121 | val_top1=17.39 | val_top5=21.74 | val_top10=23.91

Best validation top1: 18.47826086956522
Test metrics: {'top1': 21.050328227571114, 'top5': 26.695842450765863, 'top10': 29.89059080962801}

================================================================================
[4/9] Running BiGRUPoolEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'max'}
Epoch 01 | loss=1.7008 | val_top1=8.70 | val_top5=16.30 | val_top10=17.39
Epoch 02 | loss=0.4817 | val_top1=9.78 | val_top5=17.39 | val_top10=21.74
Epoch 03 | loss=0.0993 | val_top1=14.13 | val_top5=19.57 | val_top10=22.83
Epoch 04 | loss=0.0381 | val_top1=14.13 | val_top5=19.57 | val_top10=22.83
Epoch 05 | loss=0.0271 | val_top1=15.22 | val_top5=19.57 | val_top10=22.83
Epoch 06 | loss=0.0216 | val_top1=15.22 | val_top5=19.57 | val_top10=22.83
Epoch 07 | loss=0.0179 | val_top1=15.22 | val_top5=19.57 | val_top10=23.91
Epoch 08 | loss=0.0152 | val_top1=15.22 | val_top5=20.65 | val_top10=23.91
Epoch 09 | loss=0.0131 | val_top1=16.30 | val_top5=21.74 | val_top10=22.83
Epoch 10 | loss=0.0115 | val_top1=16.30 | val_top5=21.74 | val_top10=22.83
Epoch 11 | loss=0.0102 | val_top1=16.30 | val_top5=21.74 | val_top10=21.74
Epoch 12 | loss=0.0091 | val_top1=16.30 | val_top5=21.74 | val_top10=21.74
Epoch 13 | loss=0.0083 | val_top1=16.30 | val_top5=21.74 | val_top10=21.74
Epoch 14 | loss=0.0075 | val_top1=16.30 | val_top5=21.74 | val_top10=22.83
Epoch 15 | loss=0.0069 | val_top1=16.30 | val_top5=21.74 | val_top10=22.83
Epoch 16 | loss=0.0063 | val_top1=16.30 | val_top5=21.74 | val_top10=22.83
Epoch 17 | loss=0.0058 | val_top1=17.39 | val_top5=21.74 | val_top10=22.83
Epoch 18 | loss=0.0054 | val_top1=17.39 | val_top5=21.74 | val_top10=22.83
Epoch 19 | loss=0.0050 | val_top1=17.39 | val_top5=21.74 | val_top10=22.83
Epoch 20 | loss=0.0047 | val_top1=17.39 | val_top5=21.74 | val_top10=22.83

Best validation top1: 17.391304347826086
Test metrics: {'top1': 21.444201312910284, 'top5': 27.089715536105032, 'top10': 29.759299781181618}

================================================================================
[5/9] Running BiGRUPoolEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'max'}
Epoch 01 | loss=1.6376 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 02 | loss=0.4704 | val_top1=10.87 | val_top5=17.39 | val_top10=20.65
Epoch 03 | loss=0.1184 | val_top1=13.04 | val_top5=20.65 | val_top10=21.74
Epoch 04 | loss=0.0516 | val_top1=14.13 | val_top5=20.65 | val_top10=22.83
Epoch 05 | loss=0.0364 | val_top1=14.13 | val_top5=21.74 | val_top10=22.83
Epoch 06 | loss=0.0285 | val_top1=15.22 | val_top5=21.74 | val_top10=22.83
Epoch 07 | loss=0.0232 | val_top1=15.22 | val_top5=21.74 | val_top10=22.83
Epoch 08 | loss=0.0195 | val_top1=15.22 | val_top5=21.74 | val_top10=22.83
Epoch 09 | loss=0.0167 | val_top1=15.22 | val_top5=21.74 | val_top10=22.83
Epoch 10 | loss=0.0146 | val_top1=15.22 | val_top5=21.74 | val_top10=22.83
Epoch 11 | loss=0.0129 | val_top1=16.30 | val_top5=22.83 | val_top10=22.83
Epoch 12 | loss=0.0115 | val_top1=15.22 | val_top5=22.83 | val_top10=22.83
Epoch 13 | loss=0.0103 | val_top1=15.22 | val_top5=22.83 | val_top10=22.83
Epoch 14 | loss=0.0093 | val_top1=15.22 | val_top5=22.83 | val_top10=22.83
Epoch 15 | loss=0.0085 | val_top1=15.22 | val_top5=22.83 | val_top10=22.83
Epoch 16 | loss=0.0078 | val_top1=16.30 | val_top5=22.83 | val_top10=23.91
Epoch 17 | loss=0.0072 | val_top1=16.30 | val_top5=22.83 | val_top10=23.91
Epoch 18 | loss=0.0066 | val_top1=16.30 | val_top5=22.83 | val_top10=23.91
Epoch 19 | loss=0.0062 | val_top1=16.30 | val_top5=22.83 | val_top10=23.91
Epoch 20 | loss=0.0057 | val_top1=17.39 | val_top5=22.83 | val_top10=23.91

Best validation top1: 17.391304347826086
Test metrics: {'top1': 22.100656455142232, 'top5': 27.177242888402628, 'top10': 30.0218818380744}

================================================================================
[6/9] Running BiGRUPoolEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 512, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'max'}
Epoch 01 | loss=1.6643 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 02 | loss=0.5400 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 03 | loss=0.1556 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 04 | loss=0.0667 | val_top1=14.13 | val_top5=18.48 | val_top10=21.74
Epoch 05 | loss=0.0444 | val_top1=14.13 | val_top5=19.57 | val_top10=22.83
Epoch 06 | loss=0.0341 | val_top1=15.22 | val_top5=20.65 | val_top10=22.83
Epoch 07 | loss=0.0275 | val_top1=15.22 | val_top5=21.74 | val_top10=22.83
Epoch 08 | loss=0.0229 | val_top1=15.22 | val_top5=20.65 | val_top10=22.83
Epoch 09 | loss=0.0196 | val_top1=15.22 | val_top5=20.65 | val_top10=22.83
Epoch 10 | loss=0.0170 | val_top1=16.30 | val_top5=20.65 | val_top10=22.83
Epoch 11 | loss=0.0150 | val_top1=17.39 | val_top5=20.65 | val_top10=22.83
Epoch 12 | loss=0.0133 | val_top1=17.39 | val_top5=20.65 | val_top10=22.83
Epoch 13 | loss=0.0119 | val_top1=17.39 | val_top5=20.65 | val_top10=22.83
Epoch 14 | loss=0.0108 | val_top1=17.39 | val_top5=20.65 | val_top10=22.83
Epoch 15 | loss=0.0098 | val_top1=17.39 | val_top5=20.65 | val_top10=22.83
Epoch 16 | loss=0.0090 | val_top1=17.39 | val_top5=20.65 | val_top10=22.83
Epoch 17 | loss=0.0083 | val_top1=17.39 | val_top5=20.65 | val_top10=22.83
Epoch 18 | loss=0.0077 | val_top1=17.39 | val_top5=20.65 | val_top10=22.83
Epoch 19 | loss=0.0071 | val_top1=17.39 | val_top5=20.65 | val_top10=22.83
Epoch 20 | loss=0.0066 | val_top1=18.48 | val_top5=20.65 | val_top10=22.83

Best validation top1: 18.47826086956522
Test metrics: {'top1': 22.27571115973742, 'top5': 27.65864332603939, 'top10': 30.328227571115974}

================================================================================
[7/9] Running BiGRUPoolEncoder with config:
{'input_dim': 1024, 'hidden_dim': 512, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'max'}
Epoch 01 | loss=1.6873 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 02 | loss=0.4207 | val_top1=13.04 | val_top5=17.39 | val_top10=17.39
Epoch 03 | loss=0.0613 | val_top1=14.13 | val_top5=20.65 | val_top10=21.74
Epoch 04 | loss=0.0185 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 05 | loss=0.0132 | val_top1=16.30 | val_top5=20.65 | val_top10=20.65
Epoch 06 | loss=0.0108 | val_top1=16.30 | val_top5=20.65 | val_top10=20.65
Epoch 07 | loss=0.0091 | val_top1=16.30 | val_top5=19.57 | val_top10=20.65
Epoch 08 | loss=0.0079 | val_top1=16.30 | val_top5=19.57 | val_top10=20.65
Epoch 09 | loss=0.0069 | val_top1=16.30 | val_top5=19.57 | val_top10=20.65
Epoch 10 | loss=0.0062 | val_top1=17.39 | val_top5=19.57 | val_top10=20.65
Epoch 11 | loss=0.0055 | val_top1=17.39 | val_top5=19.57 | val_top10=20.65
Epoch 12 | loss=0.0050 | val_top1=17.39 | val_top5=19.57 | val_top10=20.65
Epoch 13 | loss=0.0046 | val_top1=17.39 | val_top5=19.57 | val_top10=20.65
Epoch 14 | loss=0.0042 | val_top1=17.39 | val_top5=19.57 | val_top10=20.65
Epoch 15 | loss=0.0038 | val_top1=17.39 | val_top5=19.57 | val_top10=20.65
Epoch 16 | loss=0.0036 | val_top1=16.30 | val_top5=19.57 | val_top10=21.74
Epoch 17 | loss=0.0033 | val_top1=16.30 | val_top5=19.57 | val_top10=21.74
Epoch 18 | loss=0.0031 | val_top1=17.39 | val_top5=19.57 | val_top10=21.74
Epoch 19 | loss=0.0029 | val_top1=17.39 | val_top5=19.57 | val_top10=21.74
Epoch 20 | loss=0.0027 | val_top1=17.39 | val_top5=19.57 | val_top10=20.65

Best validation top1: 17.391304347826086
Test metrics: {'top1': 21.838074398249454, 'top5': 27.00218818380744, 'top10': 29.584245076586434}

================================================================================
[8/9] Running BiGRUPoolEncoder with config:
{'input_dim': 1024, 'hidden_dim': 512, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'max'}
Epoch 01 | loss=1.6509 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 02 | loss=0.4263 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 03 | loss=0.0681 | val_top1=17.39 | val_top5=21.74 | val_top10=22.83
Epoch 04 | loss=0.0236 | val_top1=17.39 | val_top5=21.74 | val_top10=22.83
Epoch 05 | loss=0.0172 | val_top1=17.39 | val_top5=21.74 | val_top10=22.83
Epoch 06 | loss=0.0140 | val_top1=17.39 | val_top5=21.74 | val_top10=22.83
Epoch 07 | loss=0.0118 | val_top1=17.39 | val_top5=21.74 | val_top10=22.83
Epoch 08 | loss=0.0101 | val_top1=17.39 | val_top5=21.74 | val_top10=22.83
Epoch 09 | loss=0.0089 | val_top1=17.39 | val_top5=21.74 | val_top10=22.83
Epoch 10 | loss=0.0078 | val_top1=18.48 | val_top5=21.74 | val_top10=22.83
Epoch 11 | loss=0.0070 | val_top1=18.48 | val_top5=21.74 | val_top10=22.83
Epoch 12 | loss=0.0063 | val_top1=18.48 | val_top5=21.74 | val_top10=22.83
Epoch 13 | loss=0.0057 | val_top1=18.48 | val_top5=21.74 | val_top10=23.91
Epoch 14 | loss=0.0052 | val_top1=18.48 | val_top5=21.74 | val_top10=23.91
Epoch 15 | loss=0.0048 | val_top1=18.48 | val_top5=21.74 | val_top10=23.91
Epoch 16 | loss=0.0044 | val_top1=18.48 | val_top5=21.74 | val_top10=25.00
Epoch 17 | loss=0.0041 | val_top1=18.48 | val_top5=22.83 | val_top10=25.00
Epoch 18 | loss=0.0038 | val_top1=18.48 | val_top5=22.83 | val_top10=25.00
Epoch 19 | loss=0.0035 | val_top1=18.48 | val_top5=22.83 | val_top10=25.00
Epoch 20 | loss=0.0033 | val_top1=18.48 | val_top5=22.83 | val_top10=25.00

Best validation top1: 18.47826086956522
Test metrics: {'top1': 22.23194748358862, 'top5': 27.74617067833698, 'top10': 30.37199124726477}

================================================================================
[9/9] Running BiGRUPoolEncoder with config:
{'input_dim': 1024, 'hidden_dim': 512, 'output_dim': 512, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'max'}
Epoch 01 | loss=1.6458 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 02 | loss=0.4324 | val_top1=15.22 | val_top5=17.39 | val_top10=17.39
Epoch 03 | loss=0.0775 | val_top1=16.30 | val_top5=20.65 | val_top10=22.83
Epoch 04 | loss=0.0281 | val_top1=16.30 | val_top5=20.65 | val_top10=23.91
Epoch 05 | loss=0.0208 | val_top1=17.39 | val_top5=20.65 | val_top10=23.91
Epoch 06 | loss=0.0169 | val_top1=17.39 | val_top5=20.65 | val_top10=23.91
Epoch 07 | loss=0.0141 | val_top1=17.39 | val_top5=20.65 | val_top10=23.91
Epoch 08 | loss=0.0121 | val_top1=17.39 | val_top5=21.74 | val_top10=23.91
Epoch 09 | loss=0.0105 | val_top1=17.39 | val_top5=21.74 | val_top10=23.91
Epoch 10 | loss=0.0092 | val_top1=17.39 | val_top5=21.74 | val_top10=23.91
Epoch 11 | loss=0.0082 | val_top1=17.39 | val_top5=21.74 | val_top10=23.91
Epoch 12 | loss=0.0074 | val_top1=17.39 | val_top5=21.74 | val_top10=23.91
Epoch 13 | loss=0.0067 | val_top1=17.39 | val_top5=21.74 | val_top10=23.91
Epoch 14 | loss=0.0061 | val_top1=17.39 | val_top5=21.74 | val_top10=23.91
Epoch 15 | loss=0.0056 | val_top1=17.39 | val_top5=22.83 | val_top10=23.91
Epoch 16 | loss=0.0051 | val_top1=17.39 | val_top5=21.74 | val_top10=23.91
Epoch 17 | loss=0.0048 | val_top1=17.39 | val_top5=21.74 | val_top10=23.91
Epoch 18 | loss=0.0044 | val_top1=17.39 | val_top5=21.74 | val_top10=23.91
Epoch 19 | loss=0.0041 | val_top1=17.39 | val_top5=22.83 | val_top10=23.91
Epoch 20 | loss=0.0038 | val_top1=17.39 | val_top5=22.83 | val_top10=23.91

Best validation top1: 17.391304347826086
Test metrics: {'top1': 21.48796498905908, 'top5': 27.439824945295406, 'top10': 30.0218818380744}

================================================================================
Running seed: 42

================================================================================
[1/9] Running BiGRUPoolEncoder with config:
{'input_dim': 1024, 'hidden_dim': 128, 'output_dim': 128, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'max'}
Epoch 01 | loss=1.8082 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 02 | loss=0.7127 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 03 | loss=0.2394 | val_top1=13.04 | val_top5=17.39 | val_top10=18.48
Epoch 04 | loss=0.1037 | val_top1=14.13 | val_top5=17.39 | val_top10=21.74
Epoch 05 | loss=0.0644 | val_top1=14.13 | val_top5=17.39 | val_top10=19.57
Epoch 06 | loss=0.0480 | val_top1=16.30 | val_top5=18.48 | val_top10=19.57
Epoch 07 | loss=0.0384 | val_top1=16.30 | val_top5=18.48 | val_top10=19.57
Epoch 08 | loss=0.0318 | val_top1=16.30 | val_top5=18.48 | val_top10=19.57
Epoch 09 | loss=0.0270 | val_top1=16.30 | val_top5=18.48 | val_top10=20.65
Epoch 10 | loss=0.0234 | val_top1=16.30 | val_top5=18.48 | val_top10=20.65
Epoch 11 | loss=0.0205 | val_top1=16.30 | val_top5=18.48 | val_top10=20.65
Epoch 12 | loss=0.0182 | val_top1=16.30 | val_top5=18.48 | val_top10=20.65
Epoch 13 | loss=0.0163 | val_top1=17.39 | val_top5=18.48 | val_top10=22.83
Epoch 14 | loss=0.0147 | val_top1=17.39 | val_top5=18.48 | val_top10=22.83
Epoch 15 | loss=0.0134 | val_top1=17.39 | val_top5=19.57 | val_top10=22.83
Epoch 16 | loss=0.0123 | val_top1=17.39 | val_top5=19.57 | val_top10=22.83
Epoch 17 | loss=0.0113 | val_top1=17.39 | val_top5=19.57 | val_top10=22.83
Epoch 18 | loss=0.0104 | val_top1=17.39 | val_top5=19.57 | val_top10=22.83
Epoch 19 | loss=0.0096 | val_top1=17.39 | val_top5=19.57 | val_top10=22.83
Epoch 20 | loss=0.0090 | val_top1=17.39 | val_top5=19.57 | val_top10=22.83

Best validation top1: 17.391304347826086
Test metrics: {'top1': 19.693654266958426, 'top5': 25.076586433260395, 'top10': 27.65864332603939}

================================================================================

,exp_name,input_dim,hidden_dim,output_dim,dropout,lr,weight_decay,batch_size,temperature,num_layers,pool,best_val_top1,val_top1,val_top5,val_top10,test_top1,test_top5,test_top10,seed
26,bigru_pool_h512_o512_drop0p0_lr0.0002_wd0.0001...,1024,512,512,0.0,0.0002,0.0001,32,0.1,1,max,19.565217,19.565217,20.652174,25.000000,23.019694,28.577681,31.422319,2024
15,bigru_pool_h512_o128_drop0p0_lr0.0002_wd0.0001...,1024,512,128,0.0,0.0002,0.0001,32,0.1,1,max,17.391304,17.391304,23.913043,25.000000,22.932166,27.789934,29.759300,42
16,bigru_pool_h512_o256_drop0p0_lr0.0002_wd0.0001...,1024,512,256,0.0,0.0002,0.0001,32,0.1,1,max,18.478261,18.478261,21.739130,23.913043,22.888403,28.315098,30.809628,42
13,bigru_pool_h256_o256_drop0p0_lr0.0002_wd0.0001...,1024,256,256,0.0,0.0002,0.0001,32,0.1,1,max,20.652174,20.652174,22.826087,22.826087,22.450766,27.702407,30.328228,42
22,bigru_pool_h256_o256_drop0p0_lr0.0002_wd0.0001...,1024,256,256,0.0,0.0002,0.0001,32,0.1,1,max,18.478261,18.478261,21.739130,22.826087,22.319475,27.527352,30.109409,2024
23,bigru_pool_h256_o512_drop0p0_lr0.0002_wd0.0001...,1024,256,512,0.0,0.0002,0.0001,32,0.1,1,max,18.478261,18.478261,22.826087,25.000000,22.275711,28.271335,31.072210,2024
5,bigru_pool_h256_o512_drop0p0_lr0.0002_wd0.0001...,1024,256,512,0.0,0.0002,0.0001,32,0.1,1,max,18.478261,18.478261,20.652174,22.826087,22.275711,27.658643,30.328228,1990
7,bigru_pool_h512_o256_drop0p0_lr0.0002_wd0.0001...,1024,512,256,0.0,0.0002,0.0001,32,0.1,1,max,18.478261,18.478261,21.739130,22.826087,22.231947,27.746171,30.371991,1990
14,bigru_pool_h256_o512_drop0p0_lr0.0002_wd0.0001...,1024,256,512,0.0,0.0002,0.0001,32,0.1,1,max,20.652174,20.652174,21.739130,21.739130,22.188184,28.052516,30.722101,42
12,bigru_pool_h256_o128_drop0p0_lr0.0002_wd0.0001...,1024,256,128,0.0,0.0002,0.0001,32,0.1,1,max,17.391304,17.391304,18.478261,21.739130,22.188184,27.133479,29.671772,42
4,bigru_pool_h256_o256_drop0p0_lr0.0002_wd0.0001...,1024,256,256,0.0,0.0002,0.0001,32,0.1,1,max,17.391304,17.391304,22.826087,23.913043,22.100656,27.177243,30.021882,1990
24,bigru_pool_h512_o128_drop0p0_lr0.0002_wd0.0001...,1024,512,128,0.0,0.0002,0.0001,32,0.1,1,max,19.565217,19.565217,21.739130,25.000000,21.969365,27.877462,30.459519,2024
6,bigru_pool_h512_o128_drop0p0_lr0.0002_wd0.0001...,1024,512,128,0.0,0.0002,0.0001,32,0.1,1,max,17.391304,17.391304,19.565217,20.652174,21.838074,27.002188,29.584245,1990
8,bigru_pool_h512_o512_drop0p0_lr0.0002_wd0.0001...,1024,512,512,0.0,0.0002,0.0001,32,0.1,1,max,17.391304,17.391304,20.652174,23.913043,21.487965,27.439825,30.021882,1990
3,bigru_pool_h256_o128_drop0p0_lr0.0002_wd0.0001...,1024,256,128,0.0,0.0002,0.0001,32,0.1,1,max,17.391304,17.391304,21.739130,22.826087,21.444201,27.089716,29.759300,1990
18,bigru_pool_h128_o128_drop0p0_lr0.0002_wd0.0001...,1024,128,128,0.0,0.0002,0.0001,32,0.1,1,max,17.391304,17.391304,18.478261,21.739130,21.094092,26.301969,28.884026,2024
2,bigru_pool_h128_o512_drop0p0_lr0.0002_wd0.0001...,1024,128,512,0.0,0.0002,0.0001,32,0.1,1,max,18.478261,18.478261,21.739130,23.913043,21.050328,26.695842,29.890591,1990
25,bigru_pool_h512_o256_drop0p0_lr0.0002_wd0.0001...,1024,512,256,0.0,0.0002,0.0001,32,0.1,1,max,16.304348,16.304348,21.739130,23.913043,21.050328,26.827133,29.846827,2024
1,bigru_pool_h128_o256_drop0p0_lr0.0002_wd0.0001...,1024,128,256,0.0,0.0002,0.0001,32,0.1,1,max,16.304348,16.304348,21.739130,22.826087,21.006565,26.958425,29.452954,1990
19,bigru_pool_h128_o256_drop0p0_lr0.0002_wd0.0001...,1024,128,256,0.0,0.0002,0.0001,32,0.1,1,max,17.391304,17.391304,20.652174,22.826087,20.743982,26.783370,28.621444,2024
10,bigru_pool_h128_o256_drop0p0_lr0.0002_wd0.0001...,1024,128,256,0.0,0.0002,0.0001,32,0.1,1,max,15.217391,15.217391,21.739130,28.260870,20.568928,26.695842,29.452954,42
17,bigru_pool_h512_o512_drop0p0_lr0.0002_wd0.0001...,1024,512,512,0.0,0.0002,0.0001,32,0.1,1,max,16.304348,16.304348,19.565217,22.826087,20.393873,27.308534,30.371991,42
20,bigru_pool_h128_o512_drop0p0_lr0.0002_wd0.0001...,1024,128,512,0.0,0.0002,0.0001,32,0.1,1,max,14.130435,14.130435,17.391304,19.565217,20.262582,26.170678,29.277899,2024
11,bigru_pool_h128_o512_drop0p0_lr0.0002_wd0.0001...,1024,128,512,0.0,0.0002,0.0001,32,0.1,1,max,15.217391,15.217391,19.565217,20.652174,20.218818,26.258206,28.665208,42
21,bigru_pool_h256_o128_drop0p0_lr0.0002_wd0.0001...,1024,256,128,0.0,0.0002,0.0001,32,0.1,1,max,17.391304,17.391304,18.478261,21.739130,20.175055,26.258206,28.577681,2024
9,bigru_pool_h128_o128_drop0p0_lr0.0002_wd0.0001...,1024,128,128,0.0,0.0002,0.0001,32,0.1,1,max,17.391304,17.391304,18.478261,22.826087,19.693654,25.076586,27.658643,42
0,bigru_pool_h128_o128_drop0p0_lr0.0002_wd0.0001...,1024,128,128,0.0,0.0002,0.0001,32,0.1,1,max,15.217391,15.217391,18.478261,20.652174,18.687090,24.376368,27.658643,1990

In [6]:
import pandas as pd

csv_path = ROOT / "results/task3_cislr/bigru_pool_gridsearch_results_with_seeds.csv"
df = pd.read_csv(csv_path)

group_cols = [
    "input_dim",
    "hidden_dim",
    "output_dim",
    "dropout",
    "lr",
    "weight_decay",
    "batch_size",
    "temperature",
    "num_layers",
    "pool",
]

summary = (
    df.groupby(group_cols)
      .agg(
          runs=("seed", "count"),
          mean_test_top1=("test_top1", "mean"),
          std_test_top1=("test_top1", "std"),
          mean_test_top5=("test_top5", "mean"),
          std_test_top5=("test_top5", "std"),
          mean_test_top10=("test_top10", "mean"),
          std_test_top10=("test_top10", "std"),
          best_single_run=("test_top1", "max"),
      )
      .reset_index()
      .sort_values("mean_test_top1", ascending=False)
)

display(summary)

ParserError: Error tokenizing data. C error: Expected 13 fields in line 29, saw 19

In [ ]:
summary["test_top1_mean_std"] = summary.apply(
    lambda r: f"{r['mean_test_top1']:.2f} ± {0.0 if pd.isna(r['std_test_top1']) else r['std_test_top1']:.2f}",
    axis=1,
)
summary["test_top5_mean_std"] = summary.apply(
    lambda r: f"{r['mean_test_top5']:.2f} ± {0.0 if pd.isna(r['std_test_top5']) else r['std_test_top5']:.2f}",
    axis=1,
)
summary["test_top10_mean_std"] = summary.apply(
    lambda r: f"{r['mean_test_top10']:.2f} ± {0.0 if pd.isna(r['std_test_top10']) else r['std_test_top10']:.2f}",
    axis=1,
)

leaderboard = summary[
    [
        "hidden_dim",
        "output_dim",
        "dropout",
        "lr",
        "weight_decay",
        "temperature",
        "num_layers",
        "pool",
        "n_runs",
        "test_top1_mean_std",
        "test_top5_mean_std",
        "test_top10_mean_std",
        "best_single_test_top1",
    ]
].sort_values("mean_test_top1", ascending=False)

display(leaderboard)

In [7]:
csv_path = ROOT / "results/task3_cislr/bigru_pool_gridsearch_results_with_seeds.csv"

with open(csv_path, "r", encoding="utf-8") as f:
    for i, line in enumerate(f, start=1):
        if i <= 35:
            print(f"LINE {i}: {line.rstrip()}")

LINE 1: exp_name,input_dim,hidden_dim,output_dim,dropout,lr,weight_decay,batch_size,temperature,num_layers,pool,seed,error
LINE 2: bigru_pool_h128_o128_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,128,128,0.0,0.0002,0.0001,32,0.1,1,max,1990,name 'run_training' is not defined
LINE 3: bigru_pool_h128_o256_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,128,256,0.0,0.0002,0.0001,32,0.1,1,max,1990,name 'run_training' is not defined
LINE 4: bigru_pool_h128_o512_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,128,512,0.0,0.0002,0.0001,32,0.1,1,max,1990,name 'run_training' is not defined
LINE 5: bigru_pool_h256_o128_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,256,128,0.0,0.0002,0.0001,32,0.1,1,max,1990,name 'run_training' is not defined
LINE 6: bigru_pool_h256_o256_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,256,256,0.0,0.0002,0.0001,32,0.1,1,max,1990,name 'run_training' is not defined
LINE 7: bigru_pool_h256_o512_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,256,512,0.0,0.0002,0.0001,32,0.1,1,max,1990,name 'run_training' is not defined
LINE 8: bigru_pool_h512_o128_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,512,128,0.0,0.0002,0.0001,32,0.1,1,max,1990,name 'run_training' is not defined
LINE 9: bigru_pool_h512_o256_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,512,256,0.0,0.0002,0.0001,32,0.1,1,max,1990,name 'run_training' is not defined
LINE 10: bigru_pool_h512_o512_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,512,512,0.0,0.0002,0.0001,32,0.1,1,max,1990,name 'run_training' is not defined
LINE 11: bigru_pool_h128_o128_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed42,1024,128,128,0.0,0.0002,0.0001,32,0.1,1,max,42,name 'run_training' is not defined
LINE 12: bigru_pool_h128_o256_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed42,1024,128,256,0.0,0.0002,0.0001,32,0.1,1,max,42,name 'run_training' is not defined
LINE 13: bigru_pool_h128_o512_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed42,1024,128,512,0.0,0.0002,0.0001,32,0.1,1,max,42,name 'run_training' is not defined
LINE 14: bigru_pool_h256_o128_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed42,1024,256,128,0.0,0.0002,0.0001,32,0.1,1,max,42,name 'run_training' is not defined
LINE 15: bigru_pool_h256_o256_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed42,1024,256,256,0.0,0.0002,0.0001,32,0.1,1,max,42,name 'run_training' is not defined
LINE 16: bigru_pool_h256_o512_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed42,1024,256,512,0.0,0.0002,0.0001,32,0.1,1,max,42,name 'run_training' is not defined
LINE 17: bigru_pool_h512_o128_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed42,1024,512,128,0.0,0.0002,0.0001,32,0.1,1,max,42,name 'run_training' is not defined
LINE 18: bigru_pool_h512_o256_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed42,1024,512,256,0.0,0.0002,0.0001,32,0.1,1,max,42,name 'run_training' is not defined
LINE 19: bigru_pool_h512_o512_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed42,1024,512,512,0.0,0.0002,0.0001,32,0.1,1,max,42,name 'run_training' is not defined
LINE 20: bigru_pool_h128_o128_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed2024,1024,128,128,0.0,0.0002,0.0001,32,0.1,1,max,2024,name 'run_training' is not defined
LINE 21: bigru_pool_h128_o256_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed2024,1024,128,256,0.0,0.0002,0.0001,32,0.1,1,max,2024,name 'run_training' is not defined
LINE 22: bigru_pool_h128_o512_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed2024,1024,128,512,0.0,0.0002,0.0001,32,0.1,1,max,2024,name 'run_training' is not defined
LINE 23: bigru_pool_h256_o128_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed2024,1024,256,128,0.0,0.0002,0.0001,32,0.1,1,max,2024,name 'run_training' is not defined
LINE 24: bigru_pool_h256_o256_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed2024,1024,256,256,0.0,0.0002,0.0001,32,0.1,1,max,2024,name 'run_training' is not defined
LINE 25: bigru_pool_h256_o512_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed2024,1024,256,512,0.0,0.0002,0.0001,32,0.1,1,max,2024,name 'run_training' is not defined
LINE 26: bigru_pool_h512_o128_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed2024,1024,512,128,0.0,0.0002,0.0001,32,0.1,1,max,2024,name 'run_training' is not defined
LINE 27: bigru_pool_h512_o256_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed2024,1024,512,256,0.0,0.0002,0.0001,32,0.1,1,max,2024,name 'run_training' is not defined
LINE 28: bigru_pool_h512_o512_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed2024,1024,512,512,0.0,0.0002,0.0001,32,0.1,1,max,2024,name 'run_training' is not defined
LINE 29: bigru_pool_h128_o128_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,128,128,0.0,0.0002,0.0001,32,0.1,1,max,15.217391304347826,15.217391304347826,18.47826086956522,20.652173913043477,18.687089715536104,24.37636761487965,27.65864332603939,1990
LINE 30: bigru_pool_h128_o256_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,128,256,0.0,0.0002,0.0001,32,0.1,1,max,16.304347826086957,16.304347826086957,21.73913043478261,22.82608695652174,21.00656455142232,26.958424507658645,29.452954048140043,1990
LINE 31: bigru_pool_h128_o512_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,128,512,0.0,0.0002,0.0001,32,0.1,1,max,18.47826086956522,18.47826086956522,21.73913043478261,23.91304347826087,21.050328227571114,26.695842450765863,29.89059080962801,1990
LINE 32: bigru_pool_h256_o128_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,256,128,0.0,0.0002,0.0001,32,0.1,1,max,17.391304347826086,17.391304347826086,21.73913043478261,22.82608695652174,21.444201312910284,27.089715536105032,29.759299781181618,1990
LINE 33: bigru_pool_h256_o256_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,256,256,0.0,0.0002,0.0001,32,0.1,1,max,17.391304347826086,17.391304347826086,22.82608695652174,23.91304347826087,22.100656455142232,27.177242888402628,30.0218818380744,1990
LINE 34: bigru_pool_h256_o512_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,256,512,0.0,0.0002,0.0001,32,0.1,1,max,18.47826086956522,18.47826086956522,20.652173913043477,22.82608695652174,22.27571115973742,27.65864332603939,30.328227571115974,1990
LINE 35: bigru_pool_h512_o128_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,512,128,0.0,0.0002,0.0001,32,0.1,1,max,17.391304347826086,17.391304347826086,19.565217391304348,20.652173913043477,21.838074398249454,27.00218818380744,29.584245076586434,1990

In [8]:
csv_path = ROOT / "results/task3_cislr/bigru_pool_gridsearch_results_with_seeds.csv"

with open(csv_path, "r", encoding="utf-8") as f:
    for i, line in enumerate(f, start=1):
        n_fields = len(line.rstrip("\n").split(","))
        print(f"Line {i}: {n_fields} fields")

Line 1: 13 fields
Line 2: 13 fields
Line 3: 13 fields
Line 4: 13 fields
Line 5: 13 fields
Line 6: 13 fields
Line 7: 13 fields
Line 8: 13 fields
Line 9: 13 fields
Line 10: 13 fields
Line 11: 13 fields
Line 12: 13 fields
Line 13: 13 fields
Line 14: 13 fields
Line 15: 13 fields
Line 16: 13 fields
Line 17: 13 fields
Line 18: 13 fields
Line 19: 13 fields
Line 20: 13 fields
Line 21: 13 fields
Line 22: 13 fields
Line 23: 13 fields
Line 24: 13 fields
Line 25: 13 fields
Line 26: 13 fields
Line 27: 13 fields
Line 28: 13 fields
Line 29: 19 fields
Line 30: 19 fields
Line 31: 19 fields
Line 32: 19 fields
Line 33: 19 fields
Line 34: 19 fields
Line 35: 19 fields
Line 36: 19 fields
Line 37: 19 fields
Line 38: 19 fields
Line 39: 19 fields
Line 40: 19 fields
Line 41: 19 fields
Line 42: 19 fields
Line 43: 19 fields
Line 44: 19 fields
Line 45: 19 fields
Line 46: 19 fields
Line 47: 19 fields
Line 48: 19 fields
Line 49: 19 fields
Line 50: 19 fields
Line 51: 19 fields
Line 52: 19 fields
Line 53: 19 fields
Line 54: 19 fields
Line 55: 19 fields

In [9]:
from pathlib import Path

csv_path = ROOT / "results/task3_cislr/bigru_pool_gridsearch_results_with_seeds.csv"
clean_path = ROOT / "results/task3_cislr/bigru_pool_gridsearch_results_with_seeds_clean.csv"

with open(csv_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

# Keep only the correct 19-column header + 19-column rows
new_header = (
    "exp_name,input_dim,hidden_dim,output_dim,dropout,lr,weight_decay,"
    "batch_size,temperature,num_layers,pool,best_val_top1,val_top1,val_top5,"
    "val_top10,test_top1,test_top5,test_top10,seed\n"
)

clean_lines = [new_header]

for line in lines[1:]:
    if len(line.rstrip("\n").split(",")) == 19:
        clean_lines.append(line)

with open(clean_path, "w", encoding="utf-8") as f:
    f.writelines(clean_lines)

print(f"Clean file saved to: {clean_path}")
print(f"Rows kept: {len(clean_lines) - 1}")

Clean file saved to: /Users/lokeshkumar/eMasters/EE964_Projects/results/task3_cislr/bigru_pool_gridsearch_results_with_seeds_clean.csv
Rows kept: 27

In [11]:
df = pd.read_csv(clean_path)
display(df.head())
print(df.shape)

,exp_name,input_dim,hidden_dim,output_dim,dropout,lr,weight_decay,batch_size,temperature,num_layers,pool,best_val_top1,val_top1,val_top5,val_top10,test_top1,test_top5,test_top10,seed
0,bigru_pool_h128_o128_drop0p0_lr0.0002_wd0.0001...,1024,128,128,0.0,0.0002,0.0001,32,0.1,1,max,15.217391,15.217391,18.478261,20.652174,18.687090,24.376368,27.658643,1990
1,bigru_pool_h128_o256_drop0p0_lr0.0002_wd0.0001...,1024,128,256,0.0,0.0002,0.0001,32,0.1,1,max,16.304348,16.304348,21.739130,22.826087,21.006565,26.958425,29.452954,1990
2,bigru_pool_h128_o512_drop0p0_lr0.0002_wd0.0001...,1024,128,512,0.0,0.0002,0.0001,32,0.1,1,max,18.478261,18.478261,21.739130,23.913043,21.050328,26.695842,29.890591,1990
3,bigru_pool_h256_o128_drop0p0_lr0.0002_wd0.0001...,1024,256,128,0.0,0.0002,0.0001,32,0.1,1,max,17.391304,17.391304,21.739130,22.826087,21.444201,27.089716,29.759300,1990
4,bigru_pool_h256_o256_drop0p0_lr0.0002_wd0.0001...,1024,256,256,0.0,0.0002,0.0001,32,0.1,1,max,17.391304,17.391304,22.826087,23.913043,22.100656,27.177243,30.021882,1990

(27, 19)

In [12]:
group_cols = [
    "input_dim",
    "hidden_dim",
    "output_dim",
    "dropout",
    "lr",
    "weight_decay",
    "batch_size",
    "temperature",
    "num_layers",
    "pool",
]

summary = (
    df.groupby(group_cols)
      .agg(
          runs=("seed", "count"),
          mean_test_top1=("test_top1", "mean"),
          std_test_top1=("test_top1", "std"),
          mean_test_top5=("test_top5", "mean"),
          std_test_top5=("test_top5", "std"),
          mean_test_top10=("test_top10", "mean"),
          std_test_top10=("test_top10", "std"),
          best_single_run=("test_top1", "max"),
      )
      .reset_index()
      .sort_values("mean_test_top1", ascending=False)
)

display(summary)

,input_dim,hidden_dim,output_dim,dropout,lr,weight_decay,batch_size,temperature,num_layers,pool,runs,mean_test_top1,std_test_top1,mean_test_top5,std_test_top5,mean_test_top10,std_test_top10,best_single_run
4,1024,256,256,0.0,0.0002,0.0001,32,0.1,1,max,3,22.290299,0.176869,27.469001,0.267400,30.153173,0.157792,22.450766
5,1024,256,512,0.0,0.0002,0.0001,32,0.1,1,max,3,22.246535,0.050534,27.994165,0.310486,30.707513,0.372206,22.275711
6,1024,512,128,0.0,0.0002,0.0001,32,0.1,1,max,3,22.246535,0.597392,27.556528,0.482063,29.934354,0.463151,22.932166
7,1024,512,256,0.0,0.0002,0.0001,32,0.1,1,max,3,22.056893,0.931457,27.629468,0.750816,30.342815,0.482063,22.888403
8,1024,512,512,0.0,0.0002,0.0001,32,0.1,1,max,3,21.633844,1.318975,27.775346,0.697936,30.605398,0.728811,23.019694
3,1024,256,128,0.0,0.0002,0.0001,32,0.1,1,max,3,21.269147,1.017917,26.827133,0.493192,29.336251,0.658397,22.188184
1,1024,128,256,0.0,0.0002,0.0001,32,0.1,1,max,3,20.773158,0.220272,26.812546,0.133700,29.175784,0.480072,21.006565
2,1024,128,512,0.0,0.0002,0.0001,32,0.1,1,max,3,20.510576,0.467951,26.374909,0.281361,29.277899,0.612691,21.050328
0,1024,128,128,0.0,0.0002,0.0001,32,0.1,1,max,3,19.824945,1.208860,25.251641,0.974663,28.067104,0.707475,21.094092

In [13]:
from src.tasks.task3_cislr.models.bigru_encoder import BiGRUAttentionEncoder
from src.utils.set_seeds import set_seed
import pandas as pd
import os

seeds = [1990, 42, 2024]

BiGRUAttentionEncoder_grid = {
    "input_dim": [1024],
    "hidden_dim": [256],
    "output_dim": [256],
    "dropout": [0.0],
    "lr": [2e-4],
    "weight_decay": [1e-4],
    "batch_size": [32],
    "temperature": [0.1],
    "num_layers": [1],
}

NUM_EPOCHS = 20

results_csv_BiGRUAttentionEncoder_with_seeds = (
    "results/task3_cislr/bigru_attention_gridsearch_results_with_seeds.csv"
)

configs_BiGRUAttentionEncoder = expand_grid(BiGRUAttentionEncoder_grid)

print(f"Total configs: {len(configs_BiGRUAttentionEncoder)}")
print("Sample config:", configs_BiGRUAttentionEncoder[0])

all_results = []

for seed in seeds:
    print("\n" + "=" * 80)
    print(f"Running seed: {seed}")
    set_seed(seed)

    for i, cfg in enumerate(configs_BiGRUAttentionEncoder, start=1):
        print("\n" + "=" * 80)
        print(f"[{i}/{len(configs_BiGRUAttentionEncoder)}] Running BiGRUAttentionEncoder with config:")
        print(cfg)

        exp_name = (
            f"bigru_attention_"
            f"h{cfg['hidden_dim']}_o{cfg['output_dim']}_"
            f"drop{str(cfg['dropout']).replace('.', 'p')}_"
            f"lr{cfg['lr']}_"
            f"wd{cfg['weight_decay']}_"
            f"temp{str(cfg['temperature']).replace('.', 'p')}_"
            f"layers{cfg['num_layers']}_"
            f"seed{seed}"
        )

        try:
            model = BiGRUAttentionEncoder(
                input_dim=cfg["input_dim"],
                hidden_dim=cfg["hidden_dim"],
                out_dim=cfg["output_dim"],
                num_layers=cfg["num_layers"],
                dropout=cfg["dropout"],
            )

            results = run_training(
                train_csv=ROOT / "dataset/task3_cislr/splits/train_repeated.csv",
                val_csv=ROOT / "dataset/task3_cislr/splits/val_repeated_no_proto_overlap.csv",
                prototype_csv=ROOT / "dataset/task3_cislr/splits/prototype.csv",
                test_csv=ROOT / "dataset/task3_cislr/splits/test.csv",
                feature_pkl=ROOT / "dataset/task3_cislr/features/I3D_features.pkl",
                out_dir=ROOT / "results/task3_cislr/BiGRUAttentionEncoder_gridsearch" / exp_name,
                batch_size=cfg["batch_size"],
                num_workers=0,
                pooling="attention",
                lr=cfg["lr"],
                weight_decay=cfg["weight_decay"],
                temperature=cfg["temperature"],
                epochs=NUM_EPOCHS,
                early_stopping_patience=None,
                model=model,
            )

            row = {
                "exp_name": exp_name,
                **cfg,
                "pool": "attention",
                "best_val_top1": results["best_val_top1"],
                "val_top1": results["best_val_metrics"]["top1"],
                "val_top5": results["best_val_metrics"]["top5"],
                "val_top10": results["best_val_metrics"]["top10"],
                "test_top1": results["test_metrics"]["top1"],
                "test_top5": results["test_metrics"]["top5"],
                "test_top10": results["test_metrics"]["top10"],
                "seed": seed,
            }

        except Exception as e:
            print(f"Failed config: {cfg}")
            print("Error:", e)
            row = {
                "exp_name": exp_name,
                **cfg,
                "pool": "attention",
                "seed": seed,
                "error": str(e),
            }

        all_results.append(row)

        pd.DataFrame([row]).to_csv(
            ROOT / results_csv_BiGRUAttentionEncoder_with_seeds,
            mode="a",
            header=not os.path.exists(ROOT / results_csv_BiGRUAttentionEncoder_with_seeds),
            index=False,
        )

df = pd.DataFrame(all_results)
display(df.sort_values("test_top1", ascending=False))

Total configs: 1
Sample config: {'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1}

================================================================================
Running seed: 1990

================================================================================
[1/1] Running BiGRUAttentionEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1}
Epoch 01 | loss=1.7295 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 02 | loss=0.6731 | val_top1=13.04 | val_top5=16.30 | val_top10=17.39
Epoch 03 | loss=0.2254 | val_top1=14.13 | val_top5=17.39 | val_top10=21.74
Epoch 04 | loss=0.0840 | val_top1=14.13 | val_top5=19.57 | val_top10=23.91
Epoch 05 | loss=0.0481 | val_top1=14.13 | val_top5=20.65 | val_top10=23.91
Epoch 06 | loss=0.0357 | val_top1=14.13 | val_top5=20.65 | val_top10=25.00
Epoch 07 | loss=0.0284 | val_top1=15.22 | val_top5=21.74 | val_top10=25.00
Epoch 08 | loss=0.0234 | val_top1=16.30 | val_top5=21.74 | val_top10=25.00
Epoch 09 | loss=0.0198 | val_top1=17.39 | val_top5=22.83 | val_top10=25.00
Epoch 10 | loss=0.0170 | val_top1=17.39 | val_top5=22.83 | val_top10=25.00
Epoch 11 | loss=0.0148 | val_top1=17.39 | val_top5=21.74 | val_top10=26.09
Epoch 12 | loss=0.0131 | val_top1=17.39 | val_top5=21.74 | val_top10=26.09
Epoch 13 | loss=0.0117 | val_top1=17.39 | val_top5=21.74 | val_top10=26.09
Epoch 14 | loss=0.0105 | val_top1=17.39 | val_top5=21.74 | val_top10=26.09
Epoch 15 | loss=0.0095 | val_top1=17.39 | val_top5=21.74 | val_top10=26.09
Epoch 16 | loss=0.0087 | val_top1=17.39 | val_top5=21.74 | val_top10=26.09
Epoch 17 | loss=0.0079 | val_top1=17.39 | val_top5=22.83 | val_top10=26.09
Epoch 18 | loss=0.0073 | val_top1=18.48 | val_top5=22.83 | val_top10=26.09
Epoch 19 | loss=0.0067 | val_top1=18.48 | val_top5=22.83 | val_top10=25.00
Epoch 20 | loss=0.0062 | val_top1=18.48 | val_top5=22.83 | val_top10=25.00

Best validation top1: 18.47826086956522
Test metrics: {'top1': 21.61925601750547, 'top5': 27.571115973741794, 'top10': 30.0218818380744}

================================================================================
Running seed: 42

================================================================================
[1/1] Running BiGRUAttentionEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1}
Epoch 01 | loss=1.7330 | val_top1=10.87 | val_top5=13.04 | val_top10=13.04
Epoch 02 | loss=0.6430 | val_top1=10.87 | val_top5=13.04 | val_top10=18.48
Epoch 03 | loss=0.2061 | val_top1=13.04 | val_top5=16.30 | val_top10=19.57
Epoch 04 | loss=0.0795 | val_top1=15.22 | val_top5=18.48 | val_top10=22.83
Epoch 05 | loss=0.0474 | val_top1=15.22 | val_top5=20.65 | val_top10=22.83
Epoch 06 | loss=0.0354 | val_top1=15.22 | val_top5=20.65 | val_top10=22.83
Epoch 07 | loss=0.0282 | val_top1=15.22 | val_top5=20.65 | val_top10=22.83
Epoch 08 | loss=0.0233 | val_top1=16.30 | val_top5=20.65 | val_top10=22.83
Epoch 09 | loss=0.0197 | val_top1=17.39 | val_top5=20.65 | val_top10=23.91
Epoch 10 | loss=0.0170 | val_top1=17.39 | val_top5=20.65 | val_top10=23.91
Epoch 11 | loss=0.0149 | val_top1=16.30 | val_top5=20.65 | val_top10=23.91
Epoch 12 | loss=0.0132 | val_top1=16.30 | val_top5=20.65 | val_top10=23.91
Epoch 13 | loss=0.0118 | val_top1=17.39 | val_top5=20.65 | val_top10=23.91
Epoch 14 | loss=0.0106 | val_top1=17.39 | val_top5=20.65 | val_top10=25.00
Epoch 15 | loss=0.0096 | val_top1=17.39 | val_top5=21.74 | val_top10=25.00
Epoch 16 | loss=0.0088 | val_top1=17.39 | val_top5=22.83 | val_top10=25.00
Epoch 17 | loss=0.0080 | val_top1=17.39 | val_top5=23.91 | val_top10=25.00
Epoch 18 | loss=0.0074 | val_top1=17.39 | val_top5=23.91 | val_top10=25.00
Epoch 19 | loss=0.0068 | val_top1=17.39 | val_top5=23.91 | val_top10=25.00
Epoch 20 | loss=0.0063 | val_top1=17.39 | val_top5=23.91 | val_top10=25.00

Best validation top1: 17.391304347826086
Test metrics: {'top1': 20.525164113785557, 'top5': 26.2582056892779, 'top10': 29.49671772428884}

================================================================================
Running seed: 2024

================================================================================
[1/1] Running BiGRUAttentionEncoder with config:
{'input_dim': 1024, 'hidden_dim': 256, 'output_dim': 256, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1}
Epoch 01 | loss=1.7224 | val_top1=9.78 | val_top5=13.04 | val_top10=13.04
Epoch 02 | loss=0.6885 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 03 | loss=0.2300 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 04 | loss=0.0850 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 05 | loss=0.0486 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 06 | loss=0.0357 | val_top1=13.04 | val_top5=17.39 | val_top10=20.65
Epoch 07 | loss=0.0284 | val_top1=13.04 | val_top5=18.48 | val_top10=21.74
Epoch 08 | loss=0.0235 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 09 | loss=0.0199 | val_top1=13.04 | val_top5=19.57 | val_top10=22.83
Epoch 10 | loss=0.0171 | val_top1=13.04 | val_top5=19.57 | val_top10=22.83
Epoch 11 | loss=0.0149 | val_top1=11.96 | val_top5=19.57 | val_top10=22.83
Epoch 12 | loss=0.0132 | val_top1=11.96 | val_top5=19.57 | val_top10=22.83
Epoch 13 | loss=0.0118 | val_top1=11.96 | val_top5=19.57 | val_top10=22.83
Epoch 14 | loss=0.0106 | val_top1=11.96 | val_top5=20.65 | val_top10=22.83
Epoch 15 | loss=0.0096 | val_top1=11.96 | val_top5=20.65 | val_top10=22.83
Epoch 16 | loss=0.0087 | val_top1=13.04 | val_top5=20.65 | val_top10=22.83
Epoch 17 | loss=0.0080 | val_top1=13.04 | val_top5=20.65 | val_top10=22.83
Epoch 18 | loss=0.0073 | val_top1=16.30 | val_top5=20.65 | val_top10=22.83
Epoch 19 | loss=0.0068 | val_top1=16.30 | val_top5=20.65 | val_top10=22.83
Epoch 20 | loss=0.0063 | val_top1=16.30 | val_top5=21.74 | val_top10=22.83

Best validation top1: 16.304347826086957
Test metrics: {'top1': 22.056892778993436, 'top5': 27.65864332603939, 'top10': 30.45951859956236}

,exp_name,input_dim,hidden_dim,output_dim,dropout,lr,weight_decay,batch_size,temperature,num_layers,pool,best_val_top1,val_top1,val_top5,val_top10,test_top1,test_top5,test_top10,seed
2,bigru_attention_h256_o256_drop0p0_lr0.0002_wd0...,1024,256,256,0.0,0.0002,0.0001,32,0.1,1,attention,16.304348,16.304348,20.652174,22.826087,22.056893,27.658643,30.459519,2024
0,bigru_attention_h256_o256_drop0p0_lr0.0002_wd0...,1024,256,256,0.0,0.0002,0.0001,32,0.1,1,attention,18.478261,18.478261,22.826087,26.086957,21.619256,27.571116,30.021882,1990
1,bigru_attention_h256_o256_drop0p0_lr0.0002_wd0...,1024,256,256,0.0,0.0002,0.0001,32,0.1,1,attention,17.391304,17.391304,20.652174,23.913043,20.525164,26.258206,29.496718,42

In [3]:
from src.tasks.task3_cislr.models.transformer_encoder import TemporalTransformerEncoder
from src.utils.set_seeds import set_seed
from src.utils.expand_grid import expand_grid
from src.tasks.task3_cislr.training.train_retreival import run_training
from src.scripts.get_device import get_device
import pandas as pd
import os

seeds = [1990, 42, 2024]

TemporalTransformerEncoder_grid = {
    "input_dim": [1024],
    "model_dim": [256, 512],
    "output_dim": [256],
    "num_heads": [4, 8],
    "ff_multiplier": [2, 4],
    "dropout": [0.0, 0.1],
    "lr": [2e-4, 1e-5],
    "weight_decay": [1e-4],
    "batch_size": [32],
    "temperature": [0.1],
    "num_layers": [1, 2],
    "pool": ["mean"]
}

NUM_EPOCHS = 20

results_csv_TemporalTransformerEncoder_with_seeds = (
    "results/task3_cislr/temporal_transformer_encoder_gridsearch_results_with_seeds.csv"
)

configs_TemporalTransformerEncoder = expand_grid(TemporalTransformerEncoder_grid)

print(f"Total configs: {len(configs_TemporalTransformerEncoder)}")
print("Sample config:", configs_TemporalTransformerEncoder[0])

all_results = []

for seed in seeds:
    print("\n" + "=" * 80)
    print(f"Running seed: {seed}")
    set_seed(seed)

    for i, cfg in enumerate(configs_TemporalTransformerEncoder, start=1):
        print("\n" + "=" * 80)
        print(f"[{i}/{len(configs_TemporalTransformerEncoder)}] Running TemporalTransformerEncoder with config:")
        print(cfg)

        exp_name = (
            f"temporal_transformer_encoder_"
            f"dim{cfg['model_dim']}_o{cfg['output_dim']}_"
            f"heads{cfg['num_heads']}_"
            f"ff{cfg['ff_multiplier']}_"
            f"drop{str(cfg['dropout']).replace('.', 'p')}_"
            f"lr{cfg['lr']}_"
            f"wd{cfg['weight_decay']}_"
            f"temp{str(cfg['temperature']).replace('.', 'p')}_"
            f"layers{cfg['num_layers']}_"
            f"seed{seed}"
        )

        try:
            model = TemporalTransformerEncoder(
                input_dim=cfg["input_dim"],
                model_dim=cfg["model_dim"],
                out_dim=cfg["output_dim"],
                num_heads=cfg["num_heads"],
                num_layers=cfg["num_layers"],
                ff_mult=cfg["ff_multiplier"],
                dropout=cfg["dropout"],
                pool=cfg["pool"],
            )

            results = run_training(
                train_csv=ROOT / "dataset/task3_cislr/splits/train_repeated.csv",
                val_csv=ROOT / "dataset/task3_cislr/splits/val_repeated_no_proto_overlap.csv",
                prototype_csv=ROOT / "dataset/task3_cislr/splits/prototype.csv",
                test_csv=ROOT / "dataset/task3_cislr/splits/test.csv",
                feature_pkl=ROOT / "dataset/task3_cislr/features/I3D_features.pkl",
                out_dir=ROOT / "results/task3_cislr/TemporalTransformerEncoder_gridsearch" / exp_name,
                batch_size=cfg["batch_size"],
                num_workers=0,
                pooling="mean",
                lr=cfg["lr"],
                weight_decay=cfg["weight_decay"],
                temperature=cfg["temperature"],
                epochs=NUM_EPOCHS,
                early_stopping_patience=None,
                model=model,
            )

            row = {
                "exp_name": exp_name,
                **cfg,
                "pool": "mean",
                "best_val_top1": results["best_val_top1"],
                "val_top1": results["best_val_metrics"]["top1"],
                "val_top5": results["best_val_metrics"]["top5"],
                "val_top10": results["best_val_metrics"]["top10"],
                "test_top1": results["test_metrics"]["top1"],
                "test_top5": results["test_metrics"]["top5"],
                "test_top10": results["test_metrics"]["top10"],
                "seed": seed,
            }

        except Exception as e:
            print(f"Failed config: {cfg}")
            print("Error:", e)
            row = {
                "exp_name": exp_name,
                **cfg,
                "pool": "mean",
                "seed": seed,
                "error": str(e),
            }

        all_results.append(row)

        pd.DataFrame([row]).to_csv(
            ROOT / results_csv_TemporalTransformerEncoder_with_seeds,
            mode="a",
            header=not os.path.exists(ROOT / results_csv_TemporalTransformerEncoder_with_seeds),
            index=False,
        )

df = pd.DataFrame(all_results)
display(df.sort_values("test_top1", ascending=False))

Total configs: 64
Sample config: {'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

================================================================================
Running seed: 1990

================================================================================
[1/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.8647 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 02 | loss=0.9954 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30
Epoch 03 | loss=0.4617 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 04 | loss=0.1962 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 05 | loss=0.0755 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 06 | loss=0.0421 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 07 | loss=0.0306 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 08 | loss=0.0248 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 09 | loss=0.0209 | val_top1=14.13 | val_top5=20.65 | val_top10=20.65
Epoch 10 | loss=0.0180 | val_top1=14.13 | val_top5=20.65 | val_top10=20.65
Epoch 11 | loss=0.0157 | val_top1=14.13 | val_top5=20.65 | val_top10=21.74
Epoch 12 | loss=0.0139 | val_top1=14.13 | val_top5=20.65 | val_top10=21.74
Epoch 13 | loss=0.0124 | val_top1=15.22 | val_top5=20.65 | val_top10=21.74
Epoch 14 | loss=0.0111 | val_top1=15.22 | val_top5=20.65 | val_top10=21.74
Epoch 15 | loss=0.0101 | val_top1=15.22 | val_top5=20.65 | val_top10=21.74
Epoch 16 | loss=0.0092 | val_top1=15.22 | val_top5=20.65 | val_top10=22.83
Epoch 17 | loss=0.0084 | val_top1=14.13 | val_top5=19.57 | val_top10=22.83
Epoch 18 | loss=0.0077 | val_top1=14.13 | val_top5=19.57 | val_top10=22.83
Epoch 19 | loss=0.0071 | val_top1=14.13 | val_top5=19.57 | val_top10=22.83
Epoch 20 | loss=0.0066 | val_top1=14.13 | val_top5=19.57 | val_top10=22.83

Best validation top1: 15.217391304347826
Test metrics: {'top1': 19.12472647702407, 'top5': 24.50765864332604, 'top10': 26.958424507658645}

================================================================================
[2/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9592 | val_top1=8.70 | val_top5=11.96 | val_top10=13.04
Epoch 02 | loss=1.1678 | val_top1=8.70 | val_top5=11.96 | val_top10=15.22
Epoch 03 | loss=0.6080 | val_top1=8.70 | val_top5=13.04 | val_top10=16.30
Epoch 04 | loss=0.2416 | val_top1=8.70 | val_top5=15.22 | val_top10=17.39
Epoch 05 | loss=0.0897 | val_top1=10.87 | val_top5=20.65 | val_top10=22.83
Epoch 06 | loss=0.0393 | val_top1=10.87 | val_top5=18.48 | val_top10=22.83
Epoch 07 | loss=0.0253 | val_top1=10.87 | val_top5=17.39 | val_top10=23.91
Epoch 08 | loss=0.0204 | val_top1=10.87 | val_top5=17.39 | val_top10=25.00
Epoch 09 | loss=0.0173 | val_top1=10.87 | val_top5=18.48 | val_top10=25.00
Epoch 10 | loss=0.0151 | val_top1=10.87 | val_top5=18.48 | val_top10=25.00
Epoch 11 | loss=0.0133 | val_top1=11.96 | val_top5=18.48 | val_top10=25.00
Epoch 12 | loss=0.0118 | val_top1=13.04 | val_top5=18.48 | val_top10=25.00
Epoch 13 | loss=0.0106 | val_top1=13.04 | val_top5=18.48 | val_top10=23.91
Epoch 14 | loss=0.0096 | val_top1=13.04 | val_top5=18.48 | val_top10=23.91
Epoch 15 | loss=0.0087 | val_top1=13.04 | val_top5=18.48 | val_top10=22.83
Epoch 16 | loss=0.0080 | val_top1=13.04 | val_top5=18.48 | val_top10=22.83
Epoch 17 | loss=0.0073 | val_top1=14.13 | val_top5=18.48 | val_top10=22.83
Epoch 18 | loss=0.0067 | val_top1=14.13 | val_top5=18.48 | val_top10=22.83
Epoch 19 | loss=0.0062 | val_top1=14.13 | val_top5=18.48 | val_top10=22.83
Epoch 20 | loss=0.0058 | val_top1=15.22 | val_top5=18.48 | val_top10=21.74

Best validation top1: 15.217391304347826
Test metrics: {'top1': 18.643326039387308, 'top5': 23.150984682713347, 'top10': 25.601750547045953}

================================================================================
[3/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1759 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 02 | loss=1.8083 | val_top1=8.70 | val_top5=16.30 | val_top10=16.30
Epoch 03 | loss=1.5679 | val_top1=8.70 | val_top5=15.22 | val_top10=16.30
Epoch 04 | loss=1.3811 | val_top1=8.70 | val_top5=14.13 | val_top10=15.22
Epoch 05 | loss=1.2252 | val_top1=8.70 | val_top5=13.04 | val_top10=15.22
Epoch 06 | loss=1.0927 | val_top1=8.70 | val_top5=13.04 | val_top10=15.22
Epoch 07 | loss=0.9794 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 08 | loss=0.8817 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 09 | loss=0.7967 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 10 | loss=0.7223 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 11 | loss=0.6566 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 12 | loss=0.5984 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 13 | loss=0.5466 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 14 | loss=0.5003 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 15 | loss=0.4587 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30
Epoch 16 | loss=0.4214 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30
Epoch 17 | loss=0.3877 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30
Epoch 18 | loss=0.3572 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30
Epoch 19 | loss=0.3296 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30
Epoch 20 | loss=0.3047 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30

Best validation top1: 10.869565217391305
Test metrics: {'top1': 16.192560175054705, 'top5': 19.956236323851204, 'top10': 22.01312910284464}

================================================================================
[4/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1316 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 02 | loss=1.7469 | val_top1=11.96 | val_top5=13.04 | val_top10=15.22
Epoch 03 | loss=1.4923 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 04 | loss=1.2860 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 05 | loss=1.1121 | val_top1=9.78 | val_top5=11.96 | val_top10=16.30
Epoch 06 | loss=0.9655 | val_top1=10.87 | val_top5=11.96 | val_top10=15.22
Epoch 07 | loss=0.8419 | val_top1=10.87 | val_top5=11.96 | val_top10=15.22
Epoch 08 | loss=0.7366 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 09 | loss=0.6462 | val_top1=10.87 | val_top5=10.87 | val_top10=14.13
Epoch 10 | loss=0.5681 | val_top1=10.87 | val_top5=11.96 | val_top10=11.96
Epoch 11 | loss=0.5007 | val_top1=10.87 | val_top5=11.96 | val_top10=11.96
Epoch 12 | loss=0.4426 | val_top1=10.87 | val_top5=11.96 | val_top10=11.96
Epoch 13 | loss=0.3924 | val_top1=10.87 | val_top5=11.96 | val_top10=11.96
Epoch 14 | loss=0.3491 | val_top1=10.87 | val_top5=11.96 | val_top10=13.04
Epoch 15 | loss=0.3116 | val_top1=10.87 | val_top5=11.96 | val_top10=13.04
Epoch 16 | loss=0.2791 | val_top1=10.87 | val_top5=11.96 | val_top10=13.04
Epoch 17 | loss=0.2509 | val_top1=10.87 | val_top5=11.96 | val_top10=13.04
Epoch 18 | loss=0.2264 | val_top1=10.87 | val_top5=11.96 | val_top10=13.04
Epoch 19 | loss=0.2051 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 20 | loss=0.1865 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22

Best validation top1: 11.956521739130435
Test metrics: {'top1': 15.886214442013129, 'top5': 20.13129102844639, 'top10': 22.188183807439824}

================================================================================
[5/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9558 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 02 | loss=1.1724 | val_top1=9.78 | val_top5=14.13 | val_top10=14.13
Epoch 03 | loss=0.6742 | val_top1=9.78 | val_top5=14.13 | val_top10=14.13
Epoch 04 | loss=0.3961 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 05 | loss=0.2303 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 06 | loss=0.1305 | val_top1=10.87 | val_top5=16.30 | val_top10=21.74
Epoch 07 | loss=0.0794 | val_top1=10.87 | val_top5=15.22 | val_top10=21.74
Epoch 08 | loss=0.0599 | val_top1=11.96 | val_top5=15.22 | val_top10=19.57
Epoch 09 | loss=0.0465 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 10 | loss=0.0395 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 11 | loss=0.0329 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 12 | loss=0.0283 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 13 | loss=0.0244 | val_top1=13.04 | val_top5=16.30 | val_top10=18.48
Epoch 14 | loss=0.0217 | val_top1=13.04 | val_top5=17.39 | val_top10=18.48
Epoch 15 | loss=0.0212 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 16 | loss=0.0177 | val_top1=10.87 | val_top5=16.30 | val_top10=20.65
Epoch 17 | loss=0.0168 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 18 | loss=0.0158 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 19 | loss=0.0135 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 20 | loss=0.0131 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65

Best validation top1: 13.043478260869565
Test metrics: {'top1': 17.330415754923415, 'top5': 23.150984682713347, 'top10': 26.2582056892779}

================================================================================
[6/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0333 | val_top1=9.78 | val_top5=10.87 | val_top10=10.87
Epoch 02 | loss=1.3440 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 03 | loss=0.8577 | val_top1=11.96 | val_top5=11.96 | val_top10=13.04
Epoch 04 | loss=0.4869 | val_top1=10.87 | val_top5=13.04 | val_top10=13.04
Epoch 05 | loss=0.2663 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 06 | loss=0.1445 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 07 | loss=0.0872 | val_top1=13.04 | val_top5=15.22 | val_top10=19.57
Epoch 08 | loss=0.0579 | val_top1=14.13 | val_top5=16.30 | val_top10=18.48
Epoch 09 | loss=0.0403 | val_top1=14.13 | val_top5=17.39 | val_top10=19.57
Epoch 10 | loss=0.0327 | val_top1=13.04 | val_top5=16.30 | val_top10=19.57
Epoch 11 | loss=0.0266 | val_top1=14.13 | val_top5=17.39 | val_top10=19.57
Epoch 12 | loss=0.0246 | val_top1=15.22 | val_top5=17.39 | val_top10=19.57
Epoch 13 | loss=0.0205 | val_top1=16.30 | val_top5=17.39 | val_top10=19.57
Epoch 14 | loss=0.0188 | val_top1=16.30 | val_top5=16.30 | val_top10=18.48
Epoch 15 | loss=0.0167 | val_top1=13.04 | val_top5=16.30 | val_top10=18.48
Epoch 16 | loss=0.0154 | val_top1=13.04 | val_top5=16.30 | val_top10=19.57
Epoch 17 | loss=0.0135 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 18 | loss=0.0125 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 19 | loss=0.0119 | val_top1=13.04 | val_top5=17.39 | val_top10=20.65
Epoch 20 | loss=0.0105 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65

Best validation top1: 16.304347826086957
Test metrics: {'top1': 16.63019693654267, 'top5': 21.61925601750547, 'top10': 24.24507658643326}

================================================================================
[7/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.3690 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 02 | loss=2.1053 | val_top1=13.04 | val_top5=14.13 | val_top10=18.48
Epoch 03 | loss=1.8680 | val_top1=13.04 | val_top5=14.13 | val_top10=17.39
Epoch 04 | loss=1.7019 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 05 | loss=1.5766 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 06 | loss=1.4510 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 07 | loss=1.3384 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 08 | loss=1.2591 | val_top1=10.87 | val_top5=17.39 | val_top10=19.57
Epoch 09 | loss=1.1468 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 10 | loss=1.0585 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 11 | loss=1.0162 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 12 | loss=0.9663 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 13 | loss=0.8888 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 14 | loss=0.8108 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 15 | loss=0.7812 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 16 | loss=0.7105 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 17 | loss=0.6811 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 18 | loss=0.6625 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 19 | loss=0.6136 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 20 | loss=0.5630 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30

Best validation top1: 13.043478260869565
Test metrics: {'top1': 15.886214442013129, 'top5': 19.60612691466083, 'top10': 21.444201312910284}

================================================================================
[8/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2863 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 02 | loss=1.9871 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 03 | loss=1.7775 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30
Epoch 04 | loss=1.5758 | val_top1=8.70 | val_top5=15.22 | val_top10=15.22
Epoch 05 | loss=1.4729 | val_top1=8.70 | val_top5=13.04 | val_top10=15.22
Epoch 06 | loss=1.3177 | val_top1=8.70 | val_top5=14.13 | val_top10=15.22
Epoch 07 | loss=1.1923 | val_top1=8.70 | val_top5=13.04 | val_top10=15.22
Epoch 08 | loss=1.0961 | val_top1=8.70 | val_top5=13.04 | val_top10=15.22
Epoch 09 | loss=1.0376 | val_top1=8.70 | val_top5=13.04 | val_top10=15.22
Epoch 10 | loss=0.9719 | val_top1=8.70 | val_top5=11.96 | val_top10=14.13
Epoch 11 | loss=0.9013 | val_top1=8.70 | val_top5=11.96 | val_top10=14.13
Epoch 12 | loss=0.8286 | val_top1=8.70 | val_top5=11.96 | val_top10=14.13
Epoch 13 | loss=0.7846 | val_top1=8.70 | val_top5=11.96 | val_top10=14.13
Epoch 14 | loss=0.7169 | val_top1=8.70 | val_top5=11.96 | val_top10=14.13
Epoch 15 | loss=0.6773 | val_top1=8.70 | val_top5=11.96 | val_top10=14.13
Epoch 16 | loss=0.6029 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 17 | loss=0.5583 | val_top1=9.78 | val_top5=10.87 | val_top10=14.13
Epoch 18 | loss=0.5334 | val_top1=9.78 | val_top5=10.87 | val_top10=11.96
Epoch 19 | loss=0.4918 | val_top1=9.78 | val_top5=10.87 | val_top10=13.04
Epoch 20 | loss=0.4496 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13

Best validation top1: 11.956521739130435
Test metrics: {'top1': 15.75492341356674, 'top5': 19.212253829321664, 'top10': 21.13785557986871}

================================================================================
[9/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.8963 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 02 | loss=1.0572 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 03 | loss=0.5119 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 04 | loss=0.2042 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 05 | loss=0.0736 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 06 | loss=0.0391 | val_top1=14.13 | val_top5=17.39 | val_top10=19.57
Epoch 07 | loss=0.0265 | val_top1=14.13 | val_top5=17.39 | val_top10=19.57
Epoch 08 | loss=0.0214 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 09 | loss=0.0181 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 10 | loss=0.0156 | val_top1=14.13 | val_top5=18.48 | val_top10=19.57
Epoch 11 | loss=0.0137 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 12 | loss=0.0122 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 13 | loss=0.0109 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 14 | loss=0.0098 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 15 | loss=0.0089 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 16 | loss=0.0081 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 17 | loss=0.0074 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 18 | loss=0.0068 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 19 | loss=0.0063 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 20 | loss=0.0059 | val_top1=14.13 | val_top5=18.48 | val_top10=19.57

Best validation top1: 14.130434782608695
Test metrics: {'top1': 16.805251641137854, 'top5': 23.10722100656455, 'top10': 26.652078774617067}

================================================================================
[10/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9740 | val_top1=9.78 | val_top5=13.04 | val_top10=13.04
Epoch 02 | loss=1.2799 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 03 | loss=0.7432 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 04 | loss=0.3558 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 05 | loss=0.1301 | val_top1=9.78 | val_top5=13.04 | val_top10=17.39
Epoch 06 | loss=0.0440 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 07 | loss=0.0227 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 08 | loss=0.0178 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 09 | loss=0.0152 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 10 | loss=0.0132 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 11 | loss=0.0117 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 12 | loss=0.0104 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 13 | loss=0.0094 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 14 | loss=0.0085 | val_top1=13.04 | val_top5=18.48 | val_top10=21.74
Epoch 15 | loss=0.0078 | val_top1=13.04 | val_top5=17.39 | val_top10=20.65
Epoch 16 | loss=0.0071 | val_top1=13.04 | val_top5=17.39 | val_top10=21.74
Epoch 17 | loss=0.0066 | val_top1=13.04 | val_top5=17.39 | val_top10=21.74
Epoch 18 | loss=0.0061 | val_top1=13.04 | val_top5=17.39 | val_top10=21.74
Epoch 19 | loss=0.0056 | val_top1=13.04 | val_top5=17.39 | val_top10=22.83
Epoch 20 | loss=0.0052 | val_top1=13.04 | val_top5=17.39 | val_top10=22.83

Best validation top1: 13.043478260869565
Test metrics: {'top1': 17.505470459518598, 'top5': 22.669584245076585, 'top10': 24.945295404814004}

================================================================================
[11/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1011 | val_top1=13.04 | val_top5=14.13 | val_top10=15.22
Epoch 02 | loss=1.7312 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 03 | loss=1.4952 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 04 | loss=1.3027 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 05 | loss=1.1406 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 06 | loss=1.0030 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 07 | loss=0.8852 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 08 | loss=0.7839 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 09 | loss=0.6966 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 10 | loss=0.6214 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 11 | loss=0.5564 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 12 | loss=0.5000 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 13 | loss=0.4509 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 14 | loss=0.4078 | val_top1=14.13 | val_top5=14.13 | val_top10=17.39
Epoch 15 | loss=0.3699 | val_top1=14.13 | val_top5=14.13 | val_top10=17.39
Epoch 16 | loss=0.3365 | val_top1=14.13 | val_top5=14.13 | val_top10=17.39
Epoch 17 | loss=0.3069 | val_top1=13.04 | val_top5=14.13 | val_top10=17.39
Epoch 18 | loss=0.2807 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 19 | loss=0.2573 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 20 | loss=0.2366 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39

Best validation top1: 14.130434782608695
Test metrics: {'top1': 17.111597374179432, 'top5': 22.494529540481402, 'top10': 24.9890590809628}

================================================================================
[12/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1056 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 02 | loss=1.6957 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 03 | loss=1.4216 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 04 | loss=1.1938 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 05 | loss=1.0068 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 06 | loss=0.8549 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 07 | loss=0.7305 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 08 | loss=0.6278 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 09 | loss=0.5425 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 10 | loss=0.4713 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 11 | loss=0.4113 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 12 | loss=0.3605 | val_top1=9.78 | val_top5=11.96 | val_top10=15.22
Epoch 13 | loss=0.3171 | val_top1=9.78 | val_top5=11.96 | val_top10=15.22
Epoch 14 | loss=0.2799 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 15 | loss=0.2480 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 16 | loss=0.2207 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 17 | loss=0.1975 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 18 | loss=0.1777 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 19 | loss=0.1608 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 20 | loss=0.1463 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04

Best validation top1: 10.869565217391305
Test metrics: {'top1': 16.14879649890591, 'top5': 19.781181619256017, 'top10': 21.61925601750547}

================================================================================
[13/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9808 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 02 | loss=1.2434 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 03 | loss=0.7249 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 04 | loss=0.4046 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 05 | loss=0.1987 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 06 | loss=0.1105 | val_top1=9.78 | val_top5=17.39 | val_top10=19.57
Epoch 07 | loss=0.0704 | val_top1=9.78 | val_top5=18.48 | val_top10=20.65
Epoch 08 | loss=0.0520 | val_top1=9.78 | val_top5=18.48 | val_top10=20.65
Epoch 09 | loss=0.0390 | val_top1=9.78 | val_top5=19.57 | val_top10=20.65
Epoch 10 | loss=0.0322 | val_top1=10.87 | val_top5=19.57 | val_top10=22.83
Epoch 11 | loss=0.0278 | val_top1=11.96 | val_top5=19.57 | val_top10=22.83
Epoch 12 | loss=0.0247 | val_top1=11.96 | val_top5=20.65 | val_top10=22.83
Epoch 13 | loss=0.0224 | val_top1=11.96 | val_top5=20.65 | val_top10=22.83
Epoch 14 | loss=0.0194 | val_top1=11.96 | val_top5=20.65 | val_top10=21.74
Epoch 15 | loss=0.0190 | val_top1=10.87 | val_top5=19.57 | val_top10=22.83
Epoch 16 | loss=0.0167 | val_top1=11.96 | val_top5=19.57 | val_top10=22.83
Epoch 17 | loss=0.0161 | val_top1=11.96 | val_top5=21.74 | val_top10=22.83
Epoch 18 | loss=0.0139 | val_top1=10.87 | val_top5=20.65 | val_top10=22.83
Epoch 19 | loss=0.0123 | val_top1=10.87 | val_top5=21.74 | val_top10=22.83
Epoch 20 | loss=0.0116 | val_top1=10.87 | val_top5=20.65 | val_top10=22.83

Best validation top1: 11.956521739130435
Test metrics: {'top1': 15.886214442013129, 'top5': 19.693654266958426, 'top10': 21.575492341356675}

================================================================================
[14/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0600 | val_top1=9.78 | val_top5=11.96 | val_top10=11.96
Epoch 02 | loss=1.3620 | val_top1=9.78 | val_top5=10.87 | val_top10=14.13
Epoch 03 | loss=0.9213 | val_top1=9.78 | val_top5=11.96 | val_top10=15.22
Epoch 04 | loss=0.5457 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30
Epoch 05 | loss=0.2824 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 06 | loss=0.1450 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 07 | loss=0.0715 | val_top1=13.04 | val_top5=16.30 | val_top10=18.48
Epoch 08 | loss=0.0463 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 09 | loss=0.0348 | val_top1=14.13 | val_top5=16.30 | val_top10=18.48
Epoch 10 | loss=0.0277 | val_top1=14.13 | val_top5=16.30 | val_top10=21.74
Epoch 11 | loss=0.0240 | val_top1=13.04 | val_top5=16.30 | val_top10=18.48
Epoch 12 | loss=0.0220 | val_top1=13.04 | val_top5=16.30 | val_top10=18.48
Epoch 13 | loss=0.0182 | val_top1=13.04 | val_top5=17.39 | val_top10=18.48
Epoch 14 | loss=0.0167 | val_top1=14.13 | val_top5=18.48 | val_top10=19.57
Epoch 15 | loss=0.0151 | val_top1=15.22 | val_top5=17.39 | val_top10=19.57
Epoch 16 | loss=0.0139 | val_top1=15.22 | val_top5=17.39 | val_top10=20.65
Epoch 17 | loss=0.0126 | val_top1=13.04 | val_top5=17.39 | val_top10=20.65
Epoch 18 | loss=0.0112 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 19 | loss=0.0105 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 20 | loss=0.0098 | val_top1=15.22 | val_top5=17.39 | val_top10=19.57

Best validation top1: 15.217391304347826
Test metrics: {'top1': 17.505470459518598, 'top5': 22.450765864332602, 'top10': 24.9890590809628}

================================================================================
[15/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2868 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 02 | loss=2.0429 | val_top1=8.70 | val_top5=14.13 | val_top10=15.22
Epoch 03 | loss=1.8284 | val_top1=8.70 | val_top5=13.04 | val_top10=16.30
Epoch 04 | loss=1.6659 | val_top1=8.70 | val_top5=13.04 | val_top10=16.30
Epoch 05 | loss=1.5212 | val_top1=8.70 | val_top5=14.13 | val_top10=16.30
Epoch 06 | loss=1.4040 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 07 | loss=1.3020 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 08 | loss=1.2084 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 09 | loss=1.0946 | val_top1=9.78 | val_top5=16.30 | val_top10=17.39
Epoch 10 | loss=1.0152 | val_top1=9.78 | val_top5=16.30 | val_top10=17.39
Epoch 11 | loss=0.9489 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 12 | loss=0.8681 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 13 | loss=0.8352 | val_top1=9.78 | val_top5=16.30 | val_top10=17.39
Epoch 14 | loss=0.7592 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 15 | loss=0.7315 | val_top1=8.70 | val_top5=15.22 | val_top10=17.39
Epoch 16 | loss=0.6589 | val_top1=8.70 | val_top5=15.22 | val_top10=18.48
Epoch 17 | loss=0.6291 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 18 | loss=0.6008 | val_top1=9.78 | val_top5=15.22 | val_top10=19.57
Epoch 19 | loss=0.5378 | val_top1=9.78 | val_top5=15.22 | val_top10=19.57
Epoch 20 | loss=0.5049 | val_top1=9.78 | val_top5=15.22 | val_top10=19.57

Best validation top1: 10.869565217391305
Test metrics: {'top1': 15.711159737417944, 'top5': 19.299781181619256, 'top10': 21.53172866520788}

================================================================================
[16/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2620 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 02 | loss=1.9496 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 03 | loss=1.7084 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 04 | loss=1.5774 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 05 | loss=1.4342 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 06 | loss=1.2852 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 07 | loss=1.1648 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 08 | loss=1.0479 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 09 | loss=0.9577 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 10 | loss=0.8682 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 11 | loss=0.8249 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 12 | loss=0.7587 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 13 | loss=0.6981 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 14 | loss=0.6216 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 15 | loss=0.5940 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 16 | loss=0.5356 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 17 | loss=0.5133 | val_top1=9.78 | val_top5=13.04 | val_top10=16.30
Epoch 18 | loss=0.4575 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 19 | loss=0.4472 | val_top1=9.78 | val_top5=13.04 | val_top10=16.30
Epoch 20 | loss=0.4068 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22

Best validation top1: 10.869565217391305
Test metrics: {'top1': 15.536105032822757, 'top5': 19.91247264770241, 'top10': 22.144420131291028}

================================================================================
[17/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.8202 | val_top1=9.78 | val_top5=11.96 | val_top10=16.30
Epoch 02 | loss=0.9563 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 03 | loss=0.4349 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 04 | loss=0.1613 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 05 | loss=0.0641 | val_top1=11.96 | val_top5=18.48 | val_top10=21.74
Epoch 06 | loss=0.0378 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65
Epoch 07 | loss=0.0288 | val_top1=11.96 | val_top5=19.57 | val_top10=20.65
Epoch 08 | loss=0.0237 | val_top1=11.96 | val_top5=19.57 | val_top10=20.65
Epoch 09 | loss=0.0201 | val_top1=11.96 | val_top5=19.57 | val_top10=22.83
Epoch 10 | loss=0.0174 | val_top1=11.96 | val_top5=19.57 | val_top10=22.83
Epoch 11 | loss=0.0152 | val_top1=11.96 | val_top5=20.65 | val_top10=21.74
Epoch 12 | loss=0.0134 | val_top1=11.96 | val_top5=20.65 | val_top10=21.74
Epoch 13 | loss=0.0120 | val_top1=11.96 | val_top5=20.65 | val_top10=21.74
Epoch 14 | loss=0.0108 | val_top1=11.96 | val_top5=20.65 | val_top10=21.74
Epoch 15 | loss=0.0098 | val_top1=11.96 | val_top5=20.65 | val_top10=21.74
Epoch 16 | loss=0.0089 | val_top1=11.96 | val_top5=20.65 | val_top10=21.74
Epoch 17 | loss=0.0081 | val_top1=11.96 | val_top5=20.65 | val_top10=21.74
Epoch 18 | loss=0.0075 | val_top1=13.04 | val_top5=20.65 | val_top10=21.74
Epoch 19 | loss=0.0069 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 20 | loss=0.0064 | val_top1=14.13 | val_top5=20.65 | val_top10=21.74

Best validation top1: 14.130434782608695
Test metrics: {'top1': 18.949671772428886, 'top5': 24.770240700218817, 'top10': 26.87089715536105}

================================================================================
[18/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9549 | val_top1=9.78 | val_top5=10.87 | val_top10=11.96
Epoch 02 | loss=1.2176 | val_top1=8.70 | val_top5=11.96 | val_top10=16.30
Epoch 03 | loss=0.6840 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 04 | loss=0.2817 | val_top1=8.70 | val_top5=16.30 | val_top10=18.48
Epoch 05 | loss=0.1050 | val_top1=11.96 | val_top5=14.13 | val_top10=21.74
Epoch 06 | loss=0.0406 | val_top1=10.87 | val_top5=20.65 | val_top10=23.91
Epoch 07 | loss=0.0254 | val_top1=11.96 | val_top5=21.74 | val_top10=25.00
Epoch 08 | loss=0.0197 | val_top1=14.13 | val_top5=21.74 | val_top10=25.00
Epoch 09 | loss=0.0166 | val_top1=14.13 | val_top5=20.65 | val_top10=26.09
Epoch 10 | loss=0.0144 | val_top1=13.04 | val_top5=19.57 | val_top10=27.17
Epoch 11 | loss=0.0126 | val_top1=13.04 | val_top5=19.57 | val_top10=26.09
Epoch 12 | loss=0.0112 | val_top1=11.96 | val_top5=19.57 | val_top10=26.09
Epoch 13 | loss=0.0101 | val_top1=11.96 | val_top5=19.57 | val_top10=26.09
Epoch 14 | loss=0.0091 | val_top1=11.96 | val_top5=19.57 | val_top10=26.09
Epoch 15 | loss=0.0082 | val_top1=11.96 | val_top5=19.57 | val_top10=26.09
Epoch 16 | loss=0.0075 | val_top1=11.96 | val_top5=19.57 | val_top10=26.09
Epoch 17 | loss=0.0069 | val_top1=11.96 | val_top5=18.48 | val_top10=25.00
Epoch 18 | loss=0.0064 | val_top1=11.96 | val_top5=18.48 | val_top10=25.00
Epoch 19 | loss=0.0059 | val_top1=11.96 | val_top5=19.57 | val_top10=25.00
Epoch 20 | loss=0.0054 | val_top1=11.96 | val_top5=18.48 | val_top10=23.91

Best validation top1: 14.130434782608695
Test metrics: {'top1': 17.549234135667398, 'top5': 23.23851203501094, 'top10': 26.52078774617068}

================================================================================
[19/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1303 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 02 | loss=1.7705 | val_top1=9.78 | val_top5=13.04 | val_top10=16.30
Epoch 03 | loss=1.5363 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 04 | loss=1.3525 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 05 | loss=1.1979 | val_top1=9.78 | val_top5=14.13 | val_top10=14.13
Epoch 06 | loss=1.0650 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 07 | loss=0.9501 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 08 | loss=0.8506 | val_top1=11.96 | val_top5=14.13 | val_top10=14.13
Epoch 09 | loss=0.7643 | val_top1=11.96 | val_top5=14.13 | val_top10=14.13
Epoch 10 | loss=0.6891 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 11 | loss=0.6233 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 12 | loss=0.5654 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 13 | loss=0.5142 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 14 | loss=0.4687 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 15 | loss=0.4282 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 16 | loss=0.3919 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 17 | loss=0.3593 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 18 | loss=0.3300 | val_top1=11.96 | val_top5=14.13 | val_top10=18.48
Epoch 19 | loss=0.3037 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 20 | loss=0.2799 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48

Best validation top1: 11.956521739130435
Test metrics: {'top1': 17.067833698030636, 'top5': 21.094091903719914, 'top10': 23.544857768052516}

================================================================================
[20/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0966 | val_top1=11.96 | val_top5=16.30 | val_top10=16.30
Epoch 02 | loss=1.7065 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 03 | loss=1.4490 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 04 | loss=1.2382 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 05 | loss=1.0642 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 06 | loss=0.9195 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 07 | loss=0.7983 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 08 | loss=0.6964 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 09 | loss=0.6107 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 10 | loss=0.5380 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 11 | loss=0.4760 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 12 | loss=0.4228 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 13 | loss=0.3769 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 14 | loss=0.3370 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 15 | loss=0.3023 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 16 | loss=0.2722 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 17 | loss=0.2458 | val_top1=11.96 | val_top5=14.13 | val_top10=18.48
Epoch 18 | loss=0.2228 | val_top1=11.96 | val_top5=14.13 | val_top10=18.48
Epoch 19 | loss=0.2026 | val_top1=11.96 | val_top5=14.13 | val_top10=18.48
Epoch 20 | loss=0.1849 | val_top1=11.96 | val_top5=14.13 | val_top10=19.57

Best validation top1: 11.956521739130435
Test metrics: {'top1': 15.62363238512035, 'top5': 19.693654266958426, 'top10': 22.056892778993436}

================================================================================
[21/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9343 | val_top1=10.87 | val_top5=13.04 | val_top10=13.04
Epoch 02 | loss=1.1778 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 03 | loss=0.7110 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 04 | loss=0.3868 | val_top1=9.78 | val_top5=14.13 | val_top10=18.48
Epoch 05 | loss=0.2286 | val_top1=9.78 | val_top5=16.30 | val_top10=21.74
Epoch 06 | loss=0.1311 | val_top1=9.78 | val_top5=17.39 | val_top10=18.48
Epoch 07 | loss=0.0785 | val_top1=9.78 | val_top5=18.48 | val_top10=19.57
Epoch 08 | loss=0.0568 | val_top1=10.87 | val_top5=18.48 | val_top10=19.57
Epoch 09 | loss=0.0467 | val_top1=10.87 | val_top5=19.57 | val_top10=19.57
Epoch 10 | loss=0.0391 | val_top1=11.96 | val_top5=18.48 | val_top10=19.57
Epoch 11 | loss=0.0328 | val_top1=11.96 | val_top5=19.57 | val_top10=19.57
Epoch 12 | loss=0.0284 | val_top1=11.96 | val_top5=19.57 | val_top10=19.57
Epoch 13 | loss=0.0250 | val_top1=11.96 | val_top5=18.48 | val_top10=19.57
Epoch 14 | loss=0.0226 | val_top1=11.96 | val_top5=18.48 | val_top10=19.57
Epoch 15 | loss=0.0207 | val_top1=14.13 | val_top5=18.48 | val_top10=18.48
Epoch 16 | loss=0.0178 | val_top1=14.13 | val_top5=18.48 | val_top10=19.57
Epoch 17 | loss=0.0158 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 18 | loss=0.0148 | val_top1=15.22 | val_top5=18.48 | val_top10=20.65
Epoch 19 | loss=0.0145 | val_top1=15.22 | val_top5=18.48 | val_top10=20.65
Epoch 20 | loss=0.0130 | val_top1=17.39 | val_top5=18.48 | val_top10=19.57

Best validation top1: 17.391304347826086
Test metrics: {'top1': 19.080962800875273, 'top5': 24.026258205689278, 'top10': 25.951859956236323}

================================================================================
[22/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0533 | val_top1=8.70 | val_top5=13.04 | val_top10=14.13
Epoch 02 | loss=1.3489 | val_top1=8.70 | val_top5=11.96 | val_top10=14.13
Epoch 03 | loss=0.8437 | val_top1=8.70 | val_top5=11.96 | val_top10=13.04
Epoch 04 | loss=0.5185 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 05 | loss=0.2924 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 06 | loss=0.1554 | val_top1=8.70 | val_top5=11.96 | val_top10=16.30
Epoch 07 | loss=0.0799 | val_top1=7.61 | val_top5=13.04 | val_top10=16.30
Epoch 08 | loss=0.0490 | val_top1=8.70 | val_top5=15.22 | val_top10=16.30
Epoch 09 | loss=0.0365 | val_top1=8.70 | val_top5=15.22 | val_top10=15.22
Epoch 10 | loss=0.0299 | val_top1=8.70 | val_top5=17.39 | val_top10=17.39
Epoch 11 | loss=0.0275 | val_top1=8.70 | val_top5=15.22 | val_top10=17.39
Epoch 12 | loss=0.0227 | val_top1=9.78 | val_top5=16.30 | val_top10=17.39
Epoch 13 | loss=0.0203 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 14 | loss=0.0168 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 15 | loss=0.0159 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 16 | loss=0.0155 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 17 | loss=0.0139 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 18 | loss=0.0118 | val_top1=10.87 | val_top5=18.48 | val_top10=21.74
Epoch 19 | loss=0.0112 | val_top1=10.87 | val_top5=17.39 | val_top10=20.65
Epoch 20 | loss=0.0104 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65

Best validation top1: 10.869565217391305
Test metrics: {'top1': 16.936542669584245, 'top5': 22.188183807439824, 'top10': 24.332603938730852}

================================================================================
[23/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.3205 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 02 | loss=2.0639 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 03 | loss=1.8505 | val_top1=11.96 | val_top5=13.04 | val_top10=15.22
Epoch 04 | loss=1.6813 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39
Epoch 05 | loss=1.5442 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39
Epoch 06 | loss=1.4243 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39
Epoch 07 | loss=1.3535 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 08 | loss=1.2040 | val_top1=10.87 | val_top5=11.96 | val_top10=17.39
Epoch 09 | loss=1.1745 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 10 | loss=1.0846 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 11 | loss=0.9967 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 12 | loss=0.9242 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 13 | loss=0.9010 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 14 | loss=0.8296 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 15 | loss=0.7800 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 16 | loss=0.7288 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 17 | loss=0.6851 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 18 | loss=0.6340 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 19 | loss=0.5973 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39
Epoch 20 | loss=0.5577 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.01750547045952, 'top5': 19.693654266958426, 'top10': 21.13785557986871}

================================================================================
[24/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2718 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 02 | loss=1.9737 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 03 | loss=1.7431 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 04 | loss=1.5694 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 05 | loss=1.4025 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 06 | loss=1.3372 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 07 | loss=1.1939 | val_top1=10.87 | val_top5=15.22 | val_top10=20.65
Epoch 08 | loss=1.1160 | val_top1=10.87 | val_top5=15.22 | val_top10=21.74
Epoch 09 | loss=1.0061 | val_top1=10.87 | val_top5=15.22 | val_top10=20.65
Epoch 10 | loss=0.9391 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 11 | loss=0.8683 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 12 | loss=0.7979 | val_top1=10.87 | val_top5=15.22 | val_top10=20.65
Epoch 13 | loss=0.7534 | val_top1=10.87 | val_top5=14.13 | val_top10=19.57
Epoch 14 | loss=0.6942 | val_top1=10.87 | val_top5=13.04 | val_top10=20.65
Epoch 15 | loss=0.6580 | val_top1=9.78 | val_top5=11.96 | val_top10=21.74
Epoch 16 | loss=0.5823 | val_top1=9.78 | val_top5=11.96 | val_top10=21.74
Epoch 17 | loss=0.5451 | val_top1=9.78 | val_top5=13.04 | val_top10=21.74
Epoch 18 | loss=0.5182 | val_top1=9.78 | val_top5=14.13 | val_top10=21.74
Epoch 19 | loss=0.4743 | val_top1=9.78 | val_top5=14.13 | val_top10=21.74
Epoch 20 | loss=0.4469 | val_top1=9.78 | val_top5=15.22 | val_top10=21.74

Best validation top1: 11.956521739130435
Test metrics: {'top1': 15.711159737417944, 'top5': 20.0, 'top10': 22.188183807439824}

================================================================================
[25/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9040 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 02 | loss=1.0829 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 03 | loss=0.5252 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 04 | loss=0.2065 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 05 | loss=0.0770 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 06 | loss=0.0372 | val_top1=9.78 | val_top5=17.39 | val_top10=22.83
Epoch 07 | loss=0.0263 | val_top1=10.87 | val_top5=18.48 | val_top10=22.83
Epoch 08 | loss=0.0214 | val_top1=10.87 | val_top5=18.48 | val_top10=22.83
Epoch 09 | loss=0.0181 | val_top1=10.87 | val_top5=18.48 | val_top10=22.83
Epoch 10 | loss=0.0157 | val_top1=10.87 | val_top5=18.48 | val_top10=22.83
Epoch 11 | loss=0.0137 | val_top1=10.87 | val_top5=19.57 | val_top10=23.91
Epoch 12 | loss=0.0122 | val_top1=11.96 | val_top5=20.65 | val_top10=23.91
Epoch 13 | loss=0.0109 | val_top1=13.04 | val_top5=20.65 | val_top10=23.91
Epoch 14 | loss=0.0098 | val_top1=13.04 | val_top5=20.65 | val_top10=22.83
Epoch 15 | loss=0.0089 | val_top1=13.04 | val_top5=19.57 | val_top10=22.83
Epoch 16 | loss=0.0081 | val_top1=13.04 | val_top5=19.57 | val_top10=22.83
Epoch 17 | loss=0.0075 | val_top1=13.04 | val_top5=19.57 | val_top10=22.83
Epoch 18 | loss=0.0069 | val_top1=13.04 | val_top5=19.57 | val_top10=22.83
Epoch 19 | loss=0.0063 | val_top1=14.13 | val_top5=19.57 | val_top10=22.83
Epoch 20 | loss=0.0059 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74

Best validation top1: 14.130434782608695
Test metrics: {'top1': 19.64989059080963, 'top5': 24.551422319474835, 'top10': 27.308533916849015}

================================================================================
[26/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9818 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 02 | loss=1.2842 | val_top1=8.70 | val_top5=11.96 | val_top10=16.30
Epoch 03 | loss=0.8632 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 04 | loss=0.4812 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 05 | loss=0.1953 | val_top1=8.70 | val_top5=16.30 | val_top10=18.48
Epoch 06 | loss=0.0714 | val_top1=9.78 | val_top5=16.30 | val_top10=19.57
Epoch 07 | loss=0.0327 | val_top1=9.78 | val_top5=19.57 | val_top10=22.83
Epoch 08 | loss=0.0217 | val_top1=10.87 | val_top5=20.65 | val_top10=22.83
Epoch 09 | loss=0.0178 | val_top1=10.87 | val_top5=20.65 | val_top10=22.83
Epoch 10 | loss=0.0152 | val_top1=11.96 | val_top5=21.74 | val_top10=22.83
Epoch 11 | loss=0.0132 | val_top1=11.96 | val_top5=21.74 | val_top10=22.83
Epoch 12 | loss=0.0117 | val_top1=11.96 | val_top5=20.65 | val_top10=22.83
Epoch 13 | loss=0.0104 | val_top1=11.96 | val_top5=20.65 | val_top10=22.83
Epoch 14 | loss=0.0094 | val_top1=11.96 | val_top5=20.65 | val_top10=22.83
Epoch 15 | loss=0.0085 | val_top1=11.96 | val_top5=20.65 | val_top10=23.91
Epoch 16 | loss=0.0077 | val_top1=13.04 | val_top5=19.57 | val_top10=23.91
Epoch 17 | loss=0.0071 | val_top1=13.04 | val_top5=18.48 | val_top10=23.91
Epoch 18 | loss=0.0065 | val_top1=13.04 | val_top5=18.48 | val_top10=23.91
Epoch 19 | loss=0.0060 | val_top1=13.04 | val_top5=18.48 | val_top10=23.91
Epoch 20 | loss=0.0055 | val_top1=14.13 | val_top5=18.48 | val_top10=23.91

Best validation top1: 14.130434782608695
Test metrics: {'top1': 18.424507658643325, 'top5': 23.150984682713347, 'top10': 25.339168490153174}

================================================================================
[27/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1320 | val_top1=10.87 | val_top5=11.96 | val_top10=19.57
Epoch 02 | loss=1.7555 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 03 | loss=1.5166 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 04 | loss=1.3235 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 05 | loss=1.1595 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 06 | loss=1.0189 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 07 | loss=0.8980 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 08 | loss=0.7938 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 09 | loss=0.7037 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 10 | loss=0.6257 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 11 | loss=0.5580 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 12 | loss=0.4994 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 13 | loss=0.4485 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 14 | loss=0.4042 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 15 | loss=0.3654 | val_top1=13.04 | val_top5=14.13 | val_top10=18.48
Epoch 16 | loss=0.3315 | val_top1=13.04 | val_top5=14.13 | val_top10=18.48
Epoch 17 | loss=0.3016 | val_top1=13.04 | val_top5=14.13 | val_top10=18.48
Epoch 18 | loss=0.2752 | val_top1=13.04 | val_top5=14.13 | val_top10=18.48
Epoch 19 | loss=0.2519 | val_top1=13.04 | val_top5=15.22 | val_top10=18.48
Epoch 20 | loss=0.2313 | val_top1=13.04 | val_top5=15.22 | val_top10=18.48

Best validation top1: 13.043478260869565
Test metrics: {'top1': 17.199124726477024, 'top5': 21.400437636761488, 'top10': 24.37636761487965}

================================================================================
[28/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0491 | val_top1=8.70 | val_top5=15.22 | val_top10=16.30
Epoch 02 | loss=1.6455 | val_top1=8.70 | val_top5=15.22 | val_top10=17.39
Epoch 03 | loss=1.3821 | val_top1=11.96 | val_top5=16.30 | val_top10=16.30
Epoch 04 | loss=1.1720 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 05 | loss=0.9988 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 06 | loss=0.8563 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 07 | loss=0.7386 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 08 | loss=0.6407 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 09 | loss=0.5583 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 10 | loss=0.4885 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 11 | loss=0.4287 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 12 | loss=0.3774 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 13 | loss=0.3334 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 14 | loss=0.2957 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 15 | loss=0.2635 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 16 | loss=0.2359 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 17 | loss=0.2122 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 18 | loss=0.1918 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 19 | loss=0.1742 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 20 | loss=0.1588 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.061269146608314, 'top5': 20.568927789934353, 'top10': 22.888402625820568}

================================================================================
[29/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9942 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 02 | loss=1.2250 | val_top1=10.87 | val_top5=11.96 | val_top10=13.04
Epoch 03 | loss=0.7743 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 04 | loss=0.4427 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 05 | loss=0.2273 | val_top1=9.78 | val_top5=17.39 | val_top10=19.57
Epoch 06 | loss=0.1220 | val_top1=9.78 | val_top5=18.48 | val_top10=19.57
Epoch 07 | loss=0.0800 | val_top1=10.87 | val_top5=18.48 | val_top10=19.57
Epoch 08 | loss=0.0568 | val_top1=9.78 | val_top5=19.57 | val_top10=20.65
Epoch 09 | loss=0.0439 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 10 | loss=0.0350 | val_top1=13.04 | val_top5=20.65 | val_top10=20.65
Epoch 11 | loss=0.0299 | val_top1=14.13 | val_top5=20.65 | val_top10=21.74
Epoch 12 | loss=0.0255 | val_top1=14.13 | val_top5=20.65 | val_top10=23.91
Epoch 13 | loss=0.0226 | val_top1=14.13 | val_top5=21.74 | val_top10=25.00
Epoch 14 | loss=0.0206 | val_top1=16.30 | val_top5=20.65 | val_top10=25.00
Epoch 15 | loss=0.0184 | val_top1=14.13 | val_top5=19.57 | val_top10=26.09
Epoch 16 | loss=0.0171 | val_top1=15.22 | val_top5=21.74 | val_top10=26.09
Epoch 17 | loss=0.0150 | val_top1=15.22 | val_top5=22.83 | val_top10=25.00
Epoch 18 | loss=0.0140 | val_top1=15.22 | val_top5=21.74 | val_top10=25.00
Epoch 19 | loss=0.0130 | val_top1=15.22 | val_top5=21.74 | val_top10=25.00
Epoch 20 | loss=0.0120 | val_top1=15.22 | val_top5=21.74 | val_top10=23.91

Best validation top1: 16.304347826086957
Test metrics: {'top1': 18.11816192560175, 'top5': 23.23851203501094, 'top10': 26.433260393873084}

================================================================================
[30/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0564 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 02 | loss=1.4402 | val_top1=8.70 | val_top5=11.96 | val_top10=13.04
Epoch 03 | loss=0.9626 | val_top1=8.70 | val_top5=10.87 | val_top10=14.13
Epoch 04 | loss=0.6016 | val_top1=10.87 | val_top5=11.96 | val_top10=16.30
Epoch 05 | loss=0.3425 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 06 | loss=0.1785 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 07 | loss=0.0862 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 08 | loss=0.0485 | val_top1=9.78 | val_top5=16.30 | val_top10=19.57
Epoch 09 | loss=0.0332 | val_top1=11.96 | val_top5=18.48 | val_top10=19.57
Epoch 10 | loss=0.0274 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 11 | loss=0.0222 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65
Epoch 12 | loss=0.0206 | val_top1=11.96 | val_top5=19.57 | val_top10=22.83
Epoch 13 | loss=0.0180 | val_top1=10.87 | val_top5=19.57 | val_top10=21.74
Epoch 14 | loss=0.0168 | val_top1=10.87 | val_top5=19.57 | val_top10=22.83
Epoch 15 | loss=0.0148 | val_top1=10.87 | val_top5=19.57 | val_top10=22.83
Epoch 16 | loss=0.0132 | val_top1=10.87 | val_top5=19.57 | val_top10=23.91
Epoch 17 | loss=0.0119 | val_top1=10.87 | val_top5=21.74 | val_top10=22.83
Epoch 18 | loss=0.0108 | val_top1=11.96 | val_top5=20.65 | val_top10=22.83
Epoch 19 | loss=0.0101 | val_top1=10.87 | val_top5=20.65 | val_top10=22.83
Epoch 20 | loss=0.0093 | val_top1=10.87 | val_top5=20.65 | val_top10=21.74

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.805251641137854, 'top5': 22.01312910284464, 'top10': 24.026258205689278}

================================================================================
[31/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.3262 | val_top1=10.87 | val_top5=11.96 | val_top10=16.30
Epoch 02 | loss=2.0673 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 03 | loss=1.8734 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 04 | loss=1.7072 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 05 | loss=1.5645 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 06 | loss=1.4306 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 07 | loss=1.3277 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 08 | loss=1.2257 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 09 | loss=1.1645 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 10 | loss=1.0516 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 11 | loss=0.9996 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 12 | loss=0.9127 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 13 | loss=0.8684 | val_top1=9.78 | val_top5=16.30 | val_top10=18.48
Epoch 14 | loss=0.8080 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 15 | loss=0.7426 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 16 | loss=0.7015 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 17 | loss=0.6722 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 18 | loss=0.6206 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 19 | loss=0.5705 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 20 | loss=0.5484 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.323851203501093, 'top5': 21.48796498905908, 'top10': 24.15754923413567}

================================================================================
[32/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2973 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 02 | loss=1.9842 | val_top1=9.78 | val_top5=11.96 | val_top10=17.39
Epoch 03 | loss=1.7588 | val_top1=9.78 | val_top5=13.04 | val_top10=17.39
Epoch 04 | loss=1.5665 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 05 | loss=1.4569 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 06 | loss=1.2946 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 07 | loss=1.1694 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 08 | loss=1.0642 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 09 | loss=0.9942 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 10 | loss=0.9187 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 11 | loss=0.8267 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 12 | loss=0.7600 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 13 | loss=0.7031 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 14 | loss=0.6646 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 15 | loss=0.6052 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 16 | loss=0.5759 | val_top1=13.04 | val_top5=15.22 | val_top10=18.48
Epoch 17 | loss=0.5028 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 18 | loss=0.4933 | val_top1=13.04 | val_top5=15.22 | val_top10=18.48
Epoch 19 | loss=0.4650 | val_top1=13.04 | val_top5=16.30 | val_top10=17.39
Epoch 20 | loss=0.4167 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.49890590809628, 'top5': 20.612691466083152, 'top10': 23.36980306345733}

================================================================================
[33/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9138 | val_top1=9.78 | val_top5=13.04 | val_top10=16.30
Epoch 02 | loss=1.0538 | val_top1=11.96 | val_top5=16.30 | val_top10=16.30
Epoch 03 | loss=0.4961 | val_top1=13.04 | val_top5=15.22 | val_top10=15.22
Epoch 04 | loss=0.1811 | val_top1=11.96 | val_top5=19.57 | val_top10=20.65
Epoch 05 | loss=0.0630 | val_top1=13.04 | val_top5=16.30 | val_top10=21.74
Epoch 06 | loss=0.0244 | val_top1=14.13 | val_top5=17.39 | val_top10=23.91
Epoch 07 | loss=0.0165 | val_top1=14.13 | val_top5=19.57 | val_top10=23.91
Epoch 08 | loss=0.0136 | val_top1=14.13 | val_top5=19.57 | val_top10=25.00
Epoch 09 | loss=0.0117 | val_top1=14.13 | val_top5=20.65 | val_top10=25.00
Epoch 10 | loss=0.0103 | val_top1=13.04 | val_top5=20.65 | val_top10=23.91
Epoch 11 | loss=0.0091 | val_top1=13.04 | val_top5=18.48 | val_top10=23.91
Epoch 12 | loss=0.0081 | val_top1=13.04 | val_top5=18.48 | val_top10=23.91
Epoch 13 | loss=0.0073 | val_top1=13.04 | val_top5=18.48 | val_top10=23.91
Epoch 14 | loss=0.0066 | val_top1=13.04 | val_top5=18.48 | val_top10=22.83
Epoch 15 | loss=0.0060 | val_top1=13.04 | val_top5=18.48 | val_top10=22.83
Epoch 16 | loss=0.0055 | val_top1=14.13 | val_top5=18.48 | val_top10=22.83
Epoch 17 | loss=0.0051 | val_top1=13.04 | val_top5=19.57 | val_top10=22.83
Epoch 18 | loss=0.0047 | val_top1=13.04 | val_top5=19.57 | val_top10=22.83
Epoch 19 | loss=0.0043 | val_top1=13.04 | val_top5=18.48 | val_top10=22.83
Epoch 20 | loss=0.0040 | val_top1=13.04 | val_top5=18.48 | val_top10=21.74

Best validation top1: 14.130434782608695
Test metrics: {'top1': 18.38074398249453, 'top5': 23.588621444201312, 'top10': 26.783369803063458}

================================================================================
[34/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1023 | val_top1=8.70 | val_top5=8.70 | val_top10=9.78
Epoch 02 | loss=1.4935 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 03 | loss=0.9652 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 04 | loss=0.5387 | val_top1=8.70 | val_top5=13.04 | val_top10=14.13
Epoch 05 | loss=0.2834 | val_top1=10.87 | val_top5=10.87 | val_top10=13.04
Epoch 06 | loss=0.1247 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 07 | loss=0.0377 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 08 | loss=0.0165 | val_top1=11.96 | val_top5=17.39 | val_top10=17.39
Epoch 09 | loss=0.0124 | val_top1=11.96 | val_top5=17.39 | val_top10=17.39
Epoch 10 | loss=0.0106 | val_top1=11.96 | val_top5=17.39 | val_top10=17.39
Epoch 11 | loss=0.0093 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 12 | loss=0.0083 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 13 | loss=0.0075 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 14 | loss=0.0068 | val_top1=13.04 | val_top5=16.30 | val_top10=19.57
Epoch 15 | loss=0.0063 | val_top1=13.04 | val_top5=16.30 | val_top10=20.65
Epoch 16 | loss=0.0058 | val_top1=13.04 | val_top5=16.30 | val_top10=20.65
Epoch 17 | loss=0.0053 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 18 | loss=0.0049 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 19 | loss=0.0046 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 20 | loss=0.0043 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.14879649890591, 'top5': 20.568927789934353, 'top10': 23.632385120350108}

================================================================================
[35/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0161 | val_top1=9.78 | val_top5=16.30 | val_top10=17.39
Epoch 02 | loss=1.5612 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 03 | loss=1.2788 | val_top1=9.78 | val_top5=14.13 | val_top10=18.48
Epoch 04 | loss=1.0570 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 05 | loss=0.8817 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 06 | loss=0.7426 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 07 | loss=0.6304 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 08 | loss=0.5380 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 09 | loss=0.4613 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 10 | loss=0.3973 | val_top1=10.87 | val_top5=17.39 | val_top10=17.39
Epoch 11 | loss=0.3438 | val_top1=10.87 | val_top5=17.39 | val_top10=17.39
Epoch 12 | loss=0.2988 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 13 | loss=0.2609 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 14 | loss=0.2290 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 15 | loss=0.2021 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 16 | loss=0.1794 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 17 | loss=0.1603 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 18 | loss=0.1441 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 19 | loss=0.1302 | val_top1=11.96 | val_top5=17.39 | val_top10=21.74
Epoch 20 | loss=0.1184 | val_top1=11.96 | val_top5=17.39 | val_top10=21.74

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.717724288840262, 'top5': 22.450765864332602, 'top10': 25.38293216630197}

================================================================================
[36/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9864 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 02 | loss=1.4824 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 03 | loss=1.1496 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 04 | loss=0.8973 | val_top1=11.96 | val_top5=13.04 | val_top10=15.22
Epoch 05 | loss=0.7044 | val_top1=11.96 | val_top5=13.04 | val_top10=15.22
Epoch 06 | loss=0.5580 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39
Epoch 07 | loss=0.4471 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 08 | loss=0.3624 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 09 | loss=0.2971 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 10 | loss=0.2464 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 11 | loss=0.2068 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 12 | loss=0.1755 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 13 | loss=0.1507 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 14 | loss=0.1308 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 15 | loss=0.1147 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 16 | loss=0.1017 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 17 | loss=0.0910 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 18 | loss=0.0820 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 19 | loss=0.0743 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 20 | loss=0.0678 | val_top1=11.96 | val_top5=18.48 | val_top10=18.48

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.936542669584245, 'top5': 21.794310722100658, 'top10': 23.676148796498907}

================================================================================
[37/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9550 | val_top1=9.78 | val_top5=9.78 | val_top10=11.96
Epoch 02 | loss=1.1965 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 03 | loss=0.6701 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 04 | loss=0.3398 | val_top1=13.04 | val_top5=14.13 | val_top10=17.39
Epoch 05 | loss=0.1496 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 06 | loss=0.0732 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 07 | loss=0.0356 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 08 | loss=0.0285 | val_top1=13.04 | val_top5=16.30 | val_top10=21.74
Epoch 09 | loss=0.0213 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 10 | loss=0.0181 | val_top1=14.13 | val_top5=18.48 | val_top10=20.65
Epoch 11 | loss=0.0164 | val_top1=15.22 | val_top5=18.48 | val_top10=20.65
Epoch 12 | loss=0.0143 | val_top1=15.22 | val_top5=18.48 | val_top10=20.65
Epoch 13 | loss=0.0128 | val_top1=14.13 | val_top5=17.39 | val_top10=20.65
Epoch 14 | loss=0.0118 | val_top1=15.22 | val_top5=18.48 | val_top10=21.74
Epoch 15 | loss=0.0106 | val_top1=14.13 | val_top5=17.39 | val_top10=21.74
Epoch 16 | loss=0.0095 | val_top1=15.22 | val_top5=18.48 | val_top10=21.74
Epoch 17 | loss=0.0087 | val_top1=14.13 | val_top5=18.48 | val_top10=21.74
Epoch 18 | loss=0.0081 | val_top1=15.22 | val_top5=19.57 | val_top10=21.74
Epoch 19 | loss=0.0075 | val_top1=15.22 | val_top5=18.48 | val_top10=21.74
Epoch 20 | loss=0.0070 | val_top1=15.22 | val_top5=17.39 | val_top10=21.74

Best validation top1: 15.217391304347826
Test metrics: {'top1': 17.899343544857768, 'top5': 23.41356673960613, 'top10': 25.689277899343544}

================================================================================
[38/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0684 | val_top1=8.70 | val_top5=11.96 | val_top10=14.13
Epoch 02 | loss=1.4688 | val_top1=10.87 | val_top5=10.87 | val_top10=13.04
Epoch 03 | loss=1.0391 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 04 | loss=0.6893 | val_top1=8.70 | val_top5=10.87 | val_top10=14.13
Epoch 05 | loss=0.3706 | val_top1=8.70 | val_top5=13.04 | val_top10=13.04
Epoch 06 | loss=0.1842 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 07 | loss=0.0749 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 08 | loss=0.0401 | val_top1=9.78 | val_top5=11.96 | val_top10=18.48
Epoch 09 | loss=0.0244 | val_top1=10.87 | val_top5=13.04 | val_top10=18.48
Epoch 10 | loss=0.0188 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 11 | loss=0.0166 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 12 | loss=0.0144 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 13 | loss=0.0131 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 14 | loss=0.0113 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 15 | loss=0.0103 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 16 | loss=0.0093 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 17 | loss=0.0086 | val_top1=11.96 | val_top5=18.48 | val_top10=18.48
Epoch 18 | loss=0.0081 | val_top1=11.96 | val_top5=18.48 | val_top10=18.48
Epoch 19 | loss=0.0075 | val_top1=10.87 | val_top5=18.48 | val_top10=18.48
Epoch 20 | loss=0.0069 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.849015317286653, 'top5': 20.700218818380744, 'top10': 23.150984682713347}

================================================================================
[39/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2210 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 02 | loss=1.8524 | val_top1=8.70 | val_top5=14.13 | val_top10=16.30
Epoch 03 | loss=1.6844 | val_top1=8.70 | val_top5=13.04 | val_top10=16.30
Epoch 04 | loss=1.5022 | val_top1=8.70 | val_top5=13.04 | val_top10=17.39
Epoch 05 | loss=1.3827 | val_top1=8.70 | val_top5=13.04 | val_top10=17.39
Epoch 06 | loss=1.2231 | val_top1=8.70 | val_top5=13.04 | val_top10=16.30
Epoch 07 | loss=1.1304 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 08 | loss=1.0049 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 09 | loss=0.9261 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 10 | loss=0.8349 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39
Epoch 11 | loss=0.7521 | val_top1=11.96 | val_top5=13.04 | val_top10=18.48
Epoch 12 | loss=0.6987 | val_top1=11.96 | val_top5=14.13 | val_top10=18.48
Epoch 13 | loss=0.6262 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 14 | loss=0.5683 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 15 | loss=0.5224 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 16 | loss=0.4713 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 17 | loss=0.4425 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 18 | loss=0.4048 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 19 | loss=0.3746 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 20 | loss=0.3359 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.10503282275711, 'top5': 21.53172866520788, 'top10': 24.551422319474835}

================================================================================
[40/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1744 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 02 | loss=1.7640 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 03 | loss=1.5190 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 04 | loss=1.3443 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 05 | loss=1.1508 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 06 | loss=0.9999 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 07 | loss=0.9088 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 08 | loss=0.7935 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 09 | loss=0.6873 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 10 | loss=0.6061 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 11 | loss=0.5669 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 12 | loss=0.4886 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 13 | loss=0.4490 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 14 | loss=0.4220 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 15 | loss=0.3684 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 16 | loss=0.3193 | val_top1=9.78 | val_top5=14.13 | val_top10=18.48
Epoch 17 | loss=0.2959 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 18 | loss=0.2692 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 19 | loss=0.2415 | val_top1=9.78 | val_top5=14.13 | val_top10=18.48
Epoch 20 | loss=0.2225 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39

Best validation top1: 10.869565217391305
Test metrics: {'top1': 16.367614879649892, 'top5': 20.525164113785557, 'top10': 22.75711159737418}

================================================================================
[41/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9588 | val_top1=8.70 | val_top5=13.04 | val_top10=15.22
Epoch 02 | loss=1.2361 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 03 | loss=0.6628 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 04 | loss=0.2812 | val_top1=13.04 | val_top5=16.30 | val_top10=17.39
Epoch 05 | loss=0.0969 | val_top1=11.96 | val_top5=19.57 | val_top10=21.74
Epoch 06 | loss=0.0310 | val_top1=13.04 | val_top5=18.48 | val_top10=23.91
Epoch 07 | loss=0.0162 | val_top1=14.13 | val_top5=18.48 | val_top10=23.91
Epoch 08 | loss=0.0127 | val_top1=15.22 | val_top5=18.48 | val_top10=23.91
Epoch 09 | loss=0.0108 | val_top1=15.22 | val_top5=19.57 | val_top10=23.91
Epoch 10 | loss=0.0095 | val_top1=15.22 | val_top5=19.57 | val_top10=23.91
Epoch 11 | loss=0.0084 | val_top1=15.22 | val_top5=19.57 | val_top10=25.00
Epoch 12 | loss=0.0075 | val_top1=16.30 | val_top5=19.57 | val_top10=25.00
Epoch 13 | loss=0.0068 | val_top1=16.30 | val_top5=20.65 | val_top10=25.00
Epoch 14 | loss=0.0062 | val_top1=16.30 | val_top5=20.65 | val_top10=25.00
Epoch 15 | loss=0.0056 | val_top1=16.30 | val_top5=20.65 | val_top10=25.00
Epoch 16 | loss=0.0052 | val_top1=16.30 | val_top5=20.65 | val_top10=25.00
Epoch 17 | loss=0.0048 | val_top1=16.30 | val_top5=20.65 | val_top10=23.91
Epoch 18 | loss=0.0044 | val_top1=16.30 | val_top5=20.65 | val_top10=23.91
Epoch 19 | loss=0.0041 | val_top1=16.30 | val_top5=20.65 | val_top10=23.91
Epoch 20 | loss=0.0038 | val_top1=16.30 | val_top5=20.65 | val_top10=23.91

Best validation top1: 16.304347826086957
Test metrics: {'top1': 18.424507658643325, 'top5': 23.676148796498907, 'top10': 26.2582056892779}

================================================================================
[42/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1282 | val_top1=9.78 | val_top5=10.87 | val_top10=13.04
Epoch 02 | loss=1.6770 | val_top1=8.70 | val_top5=9.78 | val_top10=11.96
Epoch 03 | loss=1.3056 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 04 | loss=0.8804 | val_top1=9.78 | val_top5=10.87 | val_top10=10.87
Epoch 05 | loss=0.6157 | val_top1=9.78 | val_top5=9.78 | val_top10=10.87
Epoch 06 | loss=0.3438 | val_top1=8.70 | val_top5=10.87 | val_top10=14.13
Epoch 07 | loss=0.1483 | val_top1=8.70 | val_top5=13.04 | val_top10=15.22
Epoch 08 | loss=0.0582 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30
Epoch 09 | loss=0.0238 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30
Epoch 10 | loss=0.0145 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30
Epoch 11 | loss=0.0118 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30
Epoch 12 | loss=0.0102 | val_top1=8.70 | val_top5=15.22 | val_top10=16.30
Epoch 13 | loss=0.0090 | val_top1=8.70 | val_top5=15.22 | val_top10=16.30
Epoch 14 | loss=0.0081 | val_top1=8.70 | val_top5=15.22 | val_top10=16.30
Epoch 15 | loss=0.0073 | val_top1=8.70 | val_top5=15.22 | val_top10=16.30
Epoch 16 | loss=0.0067 | val_top1=8.70 | val_top5=15.22 | val_top10=16.30
Epoch 17 | loss=0.0061 | val_top1=8.70 | val_top5=15.22 | val_top10=16.30
Epoch 18 | loss=0.0056 | val_top1=8.70 | val_top5=14.13 | val_top10=16.30
Epoch 19 | loss=0.0052 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 20 | loss=0.0048 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39

Best validation top1: 10.869565217391305
Test metrics: {'top1': 14.266958424507658, 'top5': 19.25601750547046, 'top10': 21.356673960612692}

================================================================================
[43/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0083 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 02 | loss=1.5682 | val_top1=11.96 | val_top5=16.30 | val_top10=16.30
Epoch 03 | loss=1.2734 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 04 | loss=1.0403 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 05 | loss=0.8572 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 06 | loss=0.7121 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 07 | loss=0.5950 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 08 | loss=0.4995 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 09 | loss=0.4213 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 10 | loss=0.3568 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 11 | loss=0.3037 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 12 | loss=0.2599 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 13 | loss=0.2239 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 14 | loss=0.1945 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 15 | loss=0.1703 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 16 | loss=0.1505 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 17 | loss=0.1342 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 18 | loss=0.1205 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 19 | loss=0.1089 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 20 | loss=0.0991 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.63019693654267, 'top5': 21.00656455142232, 'top10': 23.326039387308533}

================================================================================
[44/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9431 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 02 | loss=1.4083 | val_top1=9.78 | val_top5=15.22 | val_top10=19.57
Epoch 03 | loss=1.0684 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 04 | loss=0.8210 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 05 | loss=0.6373 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 06 | loss=0.4979 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 07 | loss=0.3909 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 08 | loss=0.3087 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 09 | loss=0.2462 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 10 | loss=0.1993 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 11 | loss=0.1641 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 12 | loss=0.1376 | val_top1=9.78 | val_top5=16.30 | val_top10=18.48
Epoch 13 | loss=0.1174 | val_top1=9.78 | val_top5=16.30 | val_top10=18.48
Epoch 14 | loss=0.1017 | val_top1=9.78 | val_top5=16.30 | val_top10=19.57
Epoch 15 | loss=0.0892 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 16 | loss=0.0790 | val_top1=10.87 | val_top5=17.39 | val_top10=19.57
Epoch 17 | loss=0.0706 | val_top1=10.87 | val_top5=18.48 | val_top10=19.57
Epoch 18 | loss=0.0635 | val_top1=10.87 | val_top5=18.48 | val_top10=19.57
Epoch 19 | loss=0.0575 | val_top1=10.87 | val_top5=18.48 | val_top10=19.57
Epoch 20 | loss=0.0523 | val_top1=10.87 | val_top5=18.48 | val_top10=19.57

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.805251641137854, 'top5': 21.2253829321663, 'top10': 23.807439824945295}

================================================================================
[45/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0049 | val_top1=9.78 | val_top5=13.04 | val_top10=13.04
Epoch 02 | loss=1.2711 | val_top1=11.96 | val_top5=11.96 | val_top10=14.13
Epoch 03 | loss=0.8071 | val_top1=13.04 | val_top5=15.22 | val_top10=15.22
Epoch 04 | loss=0.4129 | val_top1=13.04 | val_top5=13.04 | val_top10=15.22
Epoch 05 | loss=0.1898 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 06 | loss=0.0857 | val_top1=13.04 | val_top5=16.30 | val_top10=19.57
Epoch 07 | loss=0.0428 | val_top1=14.13 | val_top5=18.48 | val_top10=21.74
Epoch 08 | loss=0.0268 | val_top1=14.13 | val_top5=19.57 | val_top10=22.83
Epoch 09 | loss=0.0199 | val_top1=14.13 | val_top5=18.48 | val_top10=21.74
Epoch 10 | loss=0.0174 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 11 | loss=0.0145 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 12 | loss=0.0130 | val_top1=15.22 | val_top5=19.57 | val_top10=20.65
Epoch 13 | loss=0.0115 | val_top1=15.22 | val_top5=19.57 | val_top10=20.65
Epoch 14 | loss=0.0103 | val_top1=15.22 | val_top5=20.65 | val_top10=20.65
Epoch 15 | loss=0.0095 | val_top1=16.30 | val_top5=20.65 | val_top10=20.65
Epoch 16 | loss=0.0089 | val_top1=16.30 | val_top5=20.65 | val_top10=20.65
Epoch 17 | loss=0.0081 | val_top1=16.30 | val_top5=20.65 | val_top10=20.65
Epoch 18 | loss=0.0075 | val_top1=16.30 | val_top5=20.65 | val_top10=20.65
Epoch 19 | loss=0.0068 | val_top1=16.30 | val_top5=20.65 | val_top10=20.65
Epoch 20 | loss=0.0064 | val_top1=16.30 | val_top5=20.65 | val_top10=21.74

Best validation top1: 16.304347826086957
Test metrics: {'top1': 18.46827133479212, 'top5': 22.888402625820568, 'top10': 24.857768052516413}

================================================================================
[46/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1410 | val_top1=10.87 | val_top5=11.96 | val_top10=13.04
Epoch 02 | loss=1.6599 | val_top1=9.78 | val_top5=10.87 | val_top10=11.96
Epoch 03 | loss=1.2366 | val_top1=9.78 | val_top5=10.87 | val_top10=10.87
Epoch 04 | loss=0.9013 | val_top1=8.70 | val_top5=9.78 | val_top10=10.87
Epoch 05 | loss=0.6135 | val_top1=8.70 | val_top5=10.87 | val_top10=11.96
Epoch 06 | loss=0.3516 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 07 | loss=0.1593 | val_top1=10.87 | val_top5=13.04 | val_top10=18.48
Epoch 08 | loss=0.0972 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 09 | loss=0.0379 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 10 | loss=0.0254 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 11 | loss=0.0178 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 12 | loss=0.0147 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 13 | loss=0.0133 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 14 | loss=0.0119 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 15 | loss=0.0106 | val_top1=9.78 | val_top5=16.30 | val_top10=17.39
Epoch 16 | loss=0.0095 | val_top1=9.78 | val_top5=15.22 | val_top10=19.57
Epoch 17 | loss=0.0087 | val_top1=9.78 | val_top5=15.22 | val_top10=19.57
Epoch 18 | loss=0.0078 | val_top1=11.96 | val_top5=14.13 | val_top10=19.57
Epoch 19 | loss=0.0074 | val_top1=10.87 | val_top5=14.13 | val_top10=19.57
Epoch 20 | loss=0.0068 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48

Best validation top1: 11.956521739130435
Test metrics: {'top1': 15.22975929978118, 'top5': 19.781181619256017, 'top10': 22.23194748358862}

================================================================================
[47/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2757 | val_top1=8.70 | val_top5=16.30 | val_top10=17.39
Epoch 02 | loss=1.8678 | val_top1=8.70 | val_top5=15.22 | val_top10=18.48
Epoch 03 | loss=1.6188 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 04 | loss=1.4419 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 05 | loss=1.2628 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30
Epoch 06 | loss=1.1313 | val_top1=9.78 | val_top5=16.30 | val_top10=16.30
Epoch 07 | loss=1.0225 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30
Epoch 08 | loss=0.9186 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30
Epoch 09 | loss=0.8179 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 10 | loss=0.7324 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 11 | loss=0.6588 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 12 | loss=0.5864 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 13 | loss=0.5524 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 14 | loss=0.5024 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 15 | loss=0.4403 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 16 | loss=0.4101 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 17 | loss=0.3717 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 18 | loss=0.3430 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 19 | loss=0.3090 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 20 | loss=0.2739 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.717724288840262, 'top5': 22.01312910284464, 'top10': 24.9890590809628}

================================================================================
[48/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1133 | val_top1=9.78 | val_top5=11.96 | val_top10=11.96
Epoch 02 | loss=1.7265 | val_top1=9.78 | val_top5=11.96 | val_top10=11.96
Epoch 03 | loss=1.4458 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 04 | loss=1.2098 | val_top1=9.78 | val_top5=13.04 | val_top10=13.04
Epoch 05 | loss=1.0329 | val_top1=9.78 | val_top5=13.04 | val_top10=13.04
Epoch 06 | loss=0.8998 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 07 | loss=0.7949 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 08 | loss=0.7160 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 09 | loss=0.5863 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 10 | loss=0.5251 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 11 | loss=0.4683 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 12 | loss=0.4167 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 13 | loss=0.3648 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 14 | loss=0.3424 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 15 | loss=0.2978 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 16 | loss=0.2604 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 17 | loss=0.2342 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 18 | loss=0.2085 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 19 | loss=0.1857 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 20 | loss=0.1780 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.49890590809628, 'top5': 21.61925601750547, 'top10': 24.90153172866521}

================================================================================
[49/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9135 | val_top1=9.78 | val_top5=13.04 | val_top10=16.30
Epoch 02 | loss=1.1124 | val_top1=13.04 | val_top5=13.04 | val_top10=14.13
Epoch 03 | loss=0.5615 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 04 | loss=0.1824 | val_top1=9.78 | val_top5=16.30 | val_top10=19.57
Epoch 05 | loss=0.0634 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 06 | loss=0.0238 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 07 | loss=0.0166 | val_top1=15.22 | val_top5=19.57 | val_top10=20.65
Epoch 08 | loss=0.0138 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 09 | loss=0.0118 | val_top1=15.22 | val_top5=19.57 | val_top10=20.65
Epoch 10 | loss=0.0103 | val_top1=15.22 | val_top5=19.57 | val_top10=20.65
Epoch 11 | loss=0.0091 | val_top1=15.22 | val_top5=19.57 | val_top10=20.65
Epoch 12 | loss=0.0081 | val_top1=15.22 | val_top5=19.57 | val_top10=20.65
Epoch 13 | loss=0.0073 | val_top1=15.22 | val_top5=19.57 | val_top10=20.65
Epoch 14 | loss=0.0066 | val_top1=15.22 | val_top5=19.57 | val_top10=21.74
Epoch 15 | loss=0.0060 | val_top1=15.22 | val_top5=19.57 | val_top10=21.74
Epoch 16 | loss=0.0055 | val_top1=15.22 | val_top5=19.57 | val_top10=21.74
Epoch 17 | loss=0.0051 | val_top1=15.22 | val_top5=19.57 | val_top10=20.65
Epoch 18 | loss=0.0047 | val_top1=15.22 | val_top5=19.57 | val_top10=20.65
Epoch 19 | loss=0.0043 | val_top1=15.22 | val_top5=19.57 | val_top10=20.65
Epoch 20 | loss=0.0040 | val_top1=16.30 | val_top5=19.57 | val_top10=20.65

Best validation top1: 16.304347826086957
Test metrics: {'top1': 19.824945295404813, 'top5': 24.63894967177243, 'top10': 26.695842450765863}

================================================================================
[50/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1688 | val_top1=9.78 | val_top5=9.78 | val_top10=10.87
Epoch 02 | loss=1.6323 | val_top1=8.70 | val_top5=13.04 | val_top10=14.13
Epoch 03 | loss=1.2158 | val_top1=6.52 | val_top5=11.96 | val_top10=13.04
Epoch 04 | loss=0.7575 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 05 | loss=0.3990 | val_top1=10.87 | val_top5=13.04 | val_top10=13.04
Epoch 06 | loss=0.1853 | val_top1=9.78 | val_top5=11.96 | val_top10=16.30
Epoch 07 | loss=0.0624 | val_top1=10.87 | val_top5=17.39 | val_top10=19.57
Epoch 08 | loss=0.0226 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 09 | loss=0.0145 | val_top1=10.87 | val_top5=17.39 | val_top10=20.65
Epoch 10 | loss=0.0119 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65
Epoch 11 | loss=0.0103 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65
Epoch 12 | loss=0.0091 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65
Epoch 13 | loss=0.0081 | val_top1=10.87 | val_top5=19.57 | val_top10=21.74
Epoch 14 | loss=0.0073 | val_top1=10.87 | val_top5=19.57 | val_top10=20.65
Epoch 15 | loss=0.0067 | val_top1=9.78 | val_top5=19.57 | val_top10=20.65
Epoch 16 | loss=0.0061 | val_top1=11.96 | val_top5=20.65 | val_top10=21.74
Epoch 17 | loss=0.0056 | val_top1=11.96 | val_top5=20.65 | val_top10=21.74
Epoch 18 | loss=0.0051 | val_top1=11.96 | val_top5=20.65 | val_top10=22.83
Epoch 19 | loss=0.0047 | val_top1=11.96 | val_top5=20.65 | val_top10=22.83
Epoch 20 | loss=0.0044 | val_top1=13.04 | val_top5=20.65 | val_top10=22.83

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.98030634573304, 'top5': 22.100656455142232, 'top10': 24.551422319474835}

================================================================================
[51/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0465 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 02 | loss=1.5594 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 03 | loss=1.2699 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 04 | loss=1.0455 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 05 | loss=0.8701 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 06 | loss=0.7332 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 07 | loss=0.6241 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 08 | loss=0.5350 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 09 | loss=0.4612 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 10 | loss=0.3993 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 11 | loss=0.3473 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 12 | loss=0.3034 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 13 | loss=0.2664 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 14 | loss=0.2350 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 15 | loss=0.2085 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 16 | loss=0.1859 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 17 | loss=0.1665 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 18 | loss=0.1500 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 19 | loss=0.1357 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 20 | loss=0.1233 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30

Best validation top1: 10.869565217391305
Test metrics: {'top1': 16.89277899343545, 'top5': 20.65645514223195, 'top10': 23.150984682713347}

================================================================================
[52/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9783 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 02 | loss=1.5075 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 03 | loss=1.1863 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 04 | loss=0.9373 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 05 | loss=0.7458 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 06 | loss=0.5977 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 07 | loss=0.4822 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 08 | loss=0.3916 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 09 | loss=0.3204 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 10 | loss=0.2645 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 11 | loss=0.2207 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 12 | loss=0.1862 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 13 | loss=0.1592 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 14 | loss=0.1376 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 15 | loss=0.1203 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 16 | loss=0.1062 | val_top1=10.87 | val_top5=17.39 | val_top10=17.39
Epoch 17 | loss=0.0946 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 18 | loss=0.0850 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 19 | loss=0.0768 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 20 | loss=0.0698 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.936542669584245, 'top5': 21.181619256017505, 'top10': 24.026258205689278}

================================================================================
[53/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9780 | val_top1=10.87 | val_top5=11.96 | val_top10=11.96
Epoch 02 | loss=1.2266 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 03 | loss=0.7050 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 04 | loss=0.3475 | val_top1=13.04 | val_top5=15.22 | val_top10=19.57
Epoch 05 | loss=0.1412 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 06 | loss=0.0668 | val_top1=14.13 | val_top5=17.39 | val_top10=21.74
Epoch 07 | loss=0.0380 | val_top1=13.04 | val_top5=17.39 | val_top10=21.74
Epoch 08 | loss=0.0260 | val_top1=13.04 | val_top5=16.30 | val_top10=21.74
Epoch 09 | loss=0.0216 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 10 | loss=0.0177 | val_top1=16.30 | val_top5=17.39 | val_top10=19.57
Epoch 11 | loss=0.0151 | val_top1=15.22 | val_top5=17.39 | val_top10=18.48
Epoch 12 | loss=0.0134 | val_top1=16.30 | val_top5=17.39 | val_top10=21.74
Epoch 13 | loss=0.0119 | val_top1=15.22 | val_top5=18.48 | val_top10=20.65
Epoch 14 | loss=0.0107 | val_top1=15.22 | val_top5=18.48 | val_top10=20.65
Epoch 15 | loss=0.0098 | val_top1=15.22 | val_top5=18.48 | val_top10=20.65
Epoch 16 | loss=0.0090 | val_top1=16.30 | val_top5=18.48 | val_top10=19.57
Epoch 17 | loss=0.0083 | val_top1=14.13 | val_top5=18.48 | val_top10=20.65
Epoch 18 | loss=0.0074 | val_top1=16.30 | val_top5=18.48 | val_top10=20.65
Epoch 19 | loss=0.0070 | val_top1=14.13 | val_top5=18.48 | val_top10=20.65
Epoch 20 | loss=0.0066 | val_top1=14.13 | val_top5=18.48 | val_top10=20.65

Best validation top1: 16.304347826086957
Test metrics: {'top1': 18.11816192560175, 'top5': 22.975929978118163, 'top10': 25.73304157549234}

================================================================================
[54/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0927 | val_top1=9.78 | val_top5=13.04 | val_top10=13.04
Epoch 02 | loss=1.5204 | val_top1=9.78 | val_top5=10.87 | val_top10=11.96
Epoch 03 | loss=1.0946 | val_top1=9.78 | val_top5=11.96 | val_top10=11.96
Epoch 04 | loss=0.7239 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 05 | loss=0.4167 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 06 | loss=0.1932 | val_top1=8.70 | val_top5=13.04 | val_top10=15.22
Epoch 07 | loss=0.1067 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 08 | loss=0.0469 | val_top1=13.04 | val_top5=16.30 | val_top10=18.48
Epoch 09 | loss=0.0263 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 10 | loss=0.0196 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 11 | loss=0.0165 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 12 | loss=0.0140 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 13 | loss=0.0124 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 14 | loss=0.0110 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 15 | loss=0.0102 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 16 | loss=0.0091 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 17 | loss=0.0086 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 18 | loss=0.0074 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 19 | loss=0.0070 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 20 | loss=0.0064 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39

Best validation top1: 13.043478260869565
Test metrics: {'top1': 15.886214442013129, 'top5': 20.13129102844639, 'top10': 22.932166301969364}

================================================================================
[55/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2775 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 02 | loss=1.8553 | val_top1=8.70 | val_top5=14.13 | val_top10=18.48
Epoch 03 | loss=1.6314 | val_top1=9.78 | val_top5=14.13 | val_top10=18.48
Epoch 04 | loss=1.4582 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 05 | loss=1.3038 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 06 | loss=1.1621 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 07 | loss=1.0626 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 08 | loss=0.9680 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 09 | loss=0.8928 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 10 | loss=0.7964 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 11 | loss=0.7460 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 12 | loss=0.6645 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 13 | loss=0.6007 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 14 | loss=0.5589 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 15 | loss=0.5129 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 16 | loss=0.4599 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 17 | loss=0.4199 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 18 | loss=0.3944 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 19 | loss=0.3617 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 20 | loss=0.3344 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13

Best validation top1: 10.869565217391305
Test metrics: {'top1': 16.76148796498906, 'top5': 20.39387308533917, 'top10': 22.669584245076585}

================================================================================
[56/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1533 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 02 | loss=1.7914 | val_top1=10.87 | val_top5=11.96 | val_top10=16.30
Epoch 03 | loss=1.5381 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 04 | loss=1.3155 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 05 | loss=1.1531 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 06 | loss=1.0048 | val_top1=11.96 | val_top5=16.30 | val_top10=16.30
Epoch 07 | loss=0.8891 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 08 | loss=0.7904 | val_top1=13.04 | val_top5=14.13 | val_top10=17.39
Epoch 09 | loss=0.7130 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 10 | loss=0.6227 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 11 | loss=0.5533 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 12 | loss=0.4893 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 13 | loss=0.4660 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 14 | loss=0.4074 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 15 | loss=0.3539 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 16 | loss=0.3246 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 17 | loss=0.2852 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 18 | loss=0.2735 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 19 | loss=0.2519 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 20 | loss=0.2182 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.280087527352297, 'top5': 20.568927789934353, 'top10': 23.50109409190372}

================================================================================
[57/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9417 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 02 | loss=1.2170 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 03 | loss=0.6410 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 04 | loss=0.2727 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 05 | loss=0.0877 | val_top1=13.04 | val_top5=16.30 | val_top10=16.30
Epoch 06 | loss=0.0293 | val_top1=13.04 | val_top5=17.39 | val_top10=20.65
Epoch 07 | loss=0.0150 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 08 | loss=0.0119 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 09 | loss=0.0101 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 10 | loss=0.0089 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 11 | loss=0.0079 | val_top1=13.04 | val_top5=18.48 | val_top10=21.74
Epoch 12 | loss=0.0070 | val_top1=14.13 | val_top5=18.48 | val_top10=21.74
Epoch 13 | loss=0.0064 | val_top1=15.22 | val_top5=18.48 | val_top10=22.83
Epoch 14 | loss=0.0058 | val_top1=15.22 | val_top5=18.48 | val_top10=22.83
Epoch 15 | loss=0.0053 | val_top1=15.22 | val_top5=18.48 | val_top10=22.83
Epoch 16 | loss=0.0049 | val_top1=15.22 | val_top5=18.48 | val_top10=22.83
Epoch 17 | loss=0.0045 | val_top1=15.22 | val_top5=19.57 | val_top10=22.83
Epoch 18 | loss=0.0041 | val_top1=15.22 | val_top5=19.57 | val_top10=22.83
Epoch 19 | loss=0.0038 | val_top1=15.22 | val_top5=19.57 | val_top10=22.83
Epoch 20 | loss=0.0036 | val_top1=16.30 | val_top5=20.65 | val_top10=22.83

Best validation top1: 16.304347826086957
Test metrics: {'top1': 19.168490153172865, 'top5': 23.676148796498907, 'top10': 26.52078774617068}

================================================================================
[58/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0792 | val_top1=9.78 | val_top5=10.87 | val_top10=14.13
Epoch 02 | loss=1.6571 | val_top1=10.87 | val_top5=11.96 | val_top10=11.96
Epoch 03 | loss=1.1763 | val_top1=9.78 | val_top5=13.04 | val_top10=13.04
Epoch 04 | loss=0.7714 | val_top1=8.70 | val_top5=16.30 | val_top10=16.30
Epoch 05 | loss=0.4182 | val_top1=11.96 | val_top5=13.04 | val_top10=15.22
Epoch 06 | loss=0.2214 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 07 | loss=0.0823 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30
Epoch 08 | loss=0.0315 | val_top1=11.96 | val_top5=15.22 | val_top10=19.57
Epoch 09 | loss=0.0151 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 10 | loss=0.0113 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 11 | loss=0.0097 | val_top1=10.87 | val_top5=17.39 | val_top10=19.57
Epoch 12 | loss=0.0085 | val_top1=10.87 | val_top5=17.39 | val_top10=20.65
Epoch 13 | loss=0.0076 | val_top1=10.87 | val_top5=17.39 | val_top10=19.57
Epoch 14 | loss=0.0068 | val_top1=10.87 | val_top5=18.48 | val_top10=19.57
Epoch 15 | loss=0.0062 | val_top1=10.87 | val_top5=18.48 | val_top10=19.57
Epoch 16 | loss=0.0057 | val_top1=10.87 | val_top5=17.39 | val_top10=19.57
Epoch 17 | loss=0.0052 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 18 | loss=0.0048 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 19 | loss=0.0044 | val_top1=10.87 | val_top5=16.30 | val_top10=20.65
Epoch 20 | loss=0.0041 | val_top1=10.87 | val_top5=17.39 | val_top10=20.65

Best validation top1: 11.956521739130435
Test metrics: {'top1': 13.566739606126914, 'top5': 16.89277899343545, 'top10': 19.51859956236324}

================================================================================
[59/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0248 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 02 | loss=1.5567 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 03 | loss=1.2698 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 04 | loss=1.0394 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 05 | loss=0.8581 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 06 | loss=0.7155 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 07 | loss=0.6012 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 08 | loss=0.5080 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 09 | loss=0.4312 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 10 | loss=0.3672 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 11 | loss=0.3137 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 12 | loss=0.2689 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 13 | loss=0.2317 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 14 | loss=0.2010 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 15 | loss=0.1756 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 16 | loss=0.1547 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 17 | loss=0.1374 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 18 | loss=0.1229 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 19 | loss=0.1107 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 20 | loss=0.1004 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57

Best validation top1: 11.956521739130435
Test metrics: {'top1': 17.286652078774615, 'top5': 22.538293216630198, 'top10': 25.47045951859956}

================================================================================
[60/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9435 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 02 | loss=1.4124 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 03 | loss=1.0613 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 04 | loss=0.8042 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 05 | loss=0.6155 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 06 | loss=0.4753 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 07 | loss=0.3706 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 08 | loss=0.2920 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39
Epoch 09 | loss=0.2329 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 10 | loss=0.1887 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 11 | loss=0.1555 | val_top1=11.96 | val_top5=14.13 | val_top10=18.48
Epoch 12 | loss=0.1305 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 13 | loss=0.1116 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 14 | loss=0.0968 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 15 | loss=0.0851 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 16 | loss=0.0755 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 17 | loss=0.0676 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 18 | loss=0.0610 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 19 | loss=0.0553 | val_top1=10.87 | val_top5=15.22 | val_top10=20.65
Epoch 20 | loss=0.0505 | val_top1=10.87 | val_top5=15.22 | val_top10=21.74

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.805251641137854, 'top5': 22.056892778993436, 'top10': 24.945295404814004}

================================================================================
[61/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0076 | val_top1=13.04 | val_top5=14.13 | val_top10=15.22
Epoch 02 | loss=1.2803 | val_top1=11.96 | val_top5=14.13 | val_top10=14.13
Epoch 03 | loss=0.7952 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 04 | loss=0.3476 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 05 | loss=0.1524 | val_top1=11.96 | val_top5=16.30 | val_top10=16.30
Epoch 06 | loss=0.0654 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 07 | loss=0.0323 | val_top1=15.22 | val_top5=18.48 | val_top10=20.65
Epoch 08 | loss=0.0221 | val_top1=14.13 | val_top5=18.48 | val_top10=20.65
Epoch 09 | loss=0.0184 | val_top1=13.04 | val_top5=20.65 | val_top10=20.65
Epoch 10 | loss=0.0159 | val_top1=13.04 | val_top5=20.65 | val_top10=20.65
Epoch 11 | loss=0.0136 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 12 | loss=0.0122 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 13 | loss=0.0110 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 14 | loss=0.0098 | val_top1=14.13 | val_top5=20.65 | val_top10=20.65
Epoch 15 | loss=0.0088 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 16 | loss=0.0080 | val_top1=13.04 | val_top5=20.65 | val_top10=21.74
Epoch 17 | loss=0.0075 | val_top1=15.22 | val_top5=20.65 | val_top10=21.74
Epoch 18 | loss=0.0068 | val_top1=14.13 | val_top5=19.57 | val_top10=22.83
Epoch 19 | loss=0.0063 | val_top1=14.13 | val_top5=20.65 | val_top10=20.65
Epoch 20 | loss=0.0061 | val_top1=14.13 | val_top5=20.65 | val_top10=21.74

Best validation top1: 15.217391304347826
Test metrics: {'top1': 17.417943107221006, 'top5': 22.407002188183807, 'top10': 25.64551422319475}

================================================================================
[62/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0603 | val_top1=8.70 | val_top5=11.96 | val_top10=14.13
Epoch 02 | loss=1.5422 | val_top1=8.70 | val_top5=13.04 | val_top10=14.13
Epoch 03 | loss=1.2423 | val_top1=9.78 | val_top5=9.78 | val_top10=11.96
Epoch 04 | loss=0.8470 | val_top1=8.70 | val_top5=8.70 | val_top10=14.13
Epoch 05 | loss=0.6030 | val_top1=8.70 | val_top5=10.87 | val_top10=11.96
Epoch 06 | loss=0.3384 | val_top1=7.61 | val_top5=11.96 | val_top10=14.13
Epoch 07 | loss=0.1773 | val_top1=9.78 | val_top5=11.96 | val_top10=15.22
Epoch 08 | loss=0.0740 | val_top1=7.61 | val_top5=10.87 | val_top10=16.30
Epoch 09 | loss=0.0324 | val_top1=8.70 | val_top5=13.04 | val_top10=16.30
Epoch 10 | loss=0.0212 | val_top1=7.61 | val_top5=14.13 | val_top10=16.30
Epoch 11 | loss=0.0159 | val_top1=8.70 | val_top5=13.04 | val_top10=16.30
Epoch 12 | loss=0.0141 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 13 | loss=0.0128 | val_top1=8.70 | val_top5=14.13 | val_top10=18.48
Epoch 14 | loss=0.0115 | val_top1=8.70 | val_top5=15.22 | val_top10=18.48
Epoch 15 | loss=0.0104 | val_top1=8.70 | val_top5=14.13 | val_top10=17.39
Epoch 16 | loss=0.0095 | val_top1=9.78 | val_top5=14.13 | val_top10=18.48
Epoch 17 | loss=0.0084 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 18 | loss=0.0078 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 19 | loss=0.0074 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 20 | loss=0.0066 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39

Best validation top1: 9.782608695652174
Test metrics: {'top1': 12.647702407002189, 'top5': 14.74835886214442, 'top10': 16.2363238512035}

================================================================================
[63/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2226 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 02 | loss=1.8250 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 03 | loss=1.5998 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39
Epoch 04 | loss=1.4294 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 05 | loss=1.2431 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 06 | loss=1.1428 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 07 | loss=1.0068 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 08 | loss=0.8999 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 09 | loss=0.7991 | val_top1=9.78 | val_top5=16.30 | val_top10=18.48
Epoch 10 | loss=0.7257 | val_top1=9.78 | val_top5=16.30 | val_top10=18.48
Epoch 11 | loss=0.6636 | val_top1=9.78 | val_top5=17.39 | val_top10=18.48
Epoch 12 | loss=0.5941 | val_top1=9.78 | val_top5=17.39 | val_top10=19.57
Epoch 13 | loss=0.5452 | val_top1=9.78 | val_top5=18.48 | val_top10=19.57
Epoch 14 | loss=0.4862 | val_top1=9.78 | val_top5=18.48 | val_top10=20.65
Epoch 15 | loss=0.4414 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65
Epoch 16 | loss=0.3909 | val_top1=10.87 | val_top5=18.48 | val_top10=19.57
Epoch 17 | loss=0.3642 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65
Epoch 18 | loss=0.3220 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65
Epoch 19 | loss=0.3089 | val_top1=10.87 | val_top5=18.48 | val_top10=19.57
Epoch 20 | loss=0.2789 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.849015317286653, 'top5': 20.568927789934353, 'top10': 23.282275711159738}

================================================================================
[64/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1554 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30
Epoch 02 | loss=1.7013 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 03 | loss=1.4346 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 04 | loss=1.2589 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 05 | loss=1.0762 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 06 | loss=0.9247 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 07 | loss=0.8055 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 08 | loss=0.7073 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 09 | loss=0.6253 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 10 | loss=0.5399 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 11 | loss=0.4713 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 12 | loss=0.4300 | val_top1=11.96 | val_top5=15.22 | val_top10=19.57
Epoch 13 | loss=0.3774 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 14 | loss=0.3366 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 15 | loss=0.2917 | val_top1=11.96 | val_top5=14.13 | val_top10=18.48
Epoch 16 | loss=0.2715 | val_top1=11.96 | val_top5=15.22 | val_top10=19.57
Epoch 17 | loss=0.2354 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 18 | loss=0.2203 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 19 | loss=0.1902 | val_top1=11.96 | val_top5=15.22 | val_top10=19.57
Epoch 20 | loss=0.1794 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.717724288840262, 'top5': 21.663019693654267, 'top10': 24.50765864332604}

================================================================================
Running seed: 42

================================================================================
[1/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.8735 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 02 | loss=0.9997 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 03 | loss=0.4801 | val_top1=11.96 | val_top5=14.13 | val_top10=18.48
Epoch 04 | loss=0.1894 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 05 | loss=0.0737 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 06 | loss=0.0415 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65
Epoch 07 | loss=0.0308 | val_top1=11.96 | val_top5=18.48 | val_top10=21.74
Epoch 08 | loss=0.0251 | val_top1=10.87 | val_top5=19.57 | val_top10=21.74
Epoch 09 | loss=0.0212 | val_top1=10.87 | val_top5=20.65 | val_top10=20.65
Epoch 10 | loss=0.0182 | val_top1=10.87 | val_top5=20.65 | val_top10=20.65
Epoch 11 | loss=0.0159 | val_top1=10.87 | val_top5=20.65 | val_top10=21.74
Epoch 12 | loss=0.0141 | val_top1=10.87 | val_top5=20.65 | val_top10=21.74
Epoch 13 | loss=0.0126 | val_top1=11.96 | val_top5=20.65 | val_top10=21.74
Epoch 14 | loss=0.0113 | val_top1=11.96 | val_top5=20.65 | val_top10=20.65
Epoch 15 | loss=0.0102 | val_top1=11.96 | val_top5=19.57 | val_top10=20.65
Epoch 16 | loss=0.0093 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 17 | loss=0.0085 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 18 | loss=0.0078 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 19 | loss=0.0072 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 20 | loss=0.0067 | val_top1=14.13 | val_top5=19.57 | val_top10=22.83

Best validation top1: 14.130434782608695
Test metrics: {'top1': 19.60612691466083, 'top5': 24.72647702407002, 'top10': 27.089715536105032}

================================================================================
[2/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9452 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 02 | loss=1.1629 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 03 | loss=0.6202 | val_top1=9.78 | val_top5=16.30 | val_top10=17.39
Epoch 04 | loss=0.2740 | val_top1=11.96 | val_top5=17.39 | val_top10=21.74
Epoch 05 | loss=0.0979 | val_top1=11.96 | val_top5=17.39 | val_top10=22.83
Epoch 06 | loss=0.0444 | val_top1=11.96 | val_top5=20.65 | val_top10=22.83
Epoch 07 | loss=0.0272 | val_top1=11.96 | val_top5=20.65 | val_top10=21.74
Epoch 08 | loss=0.0210 | val_top1=13.04 | val_top5=20.65 | val_top10=22.83
Epoch 09 | loss=0.0177 | val_top1=14.13 | val_top5=20.65 | val_top10=22.83
Epoch 10 | loss=0.0153 | val_top1=14.13 | val_top5=20.65 | val_top10=22.83
Epoch 11 | loss=0.0134 | val_top1=15.22 | val_top5=20.65 | val_top10=22.83
Epoch 12 | loss=0.0119 | val_top1=15.22 | val_top5=20.65 | val_top10=22.83
Epoch 13 | loss=0.0106 | val_top1=16.30 | val_top5=20.65 | val_top10=21.74
Epoch 14 | loss=0.0095 | val_top1=17.39 | val_top5=20.65 | val_top10=21.74
Epoch 15 | loss=0.0086 | val_top1=17.39 | val_top5=20.65 | val_top10=21.74
Epoch 16 | loss=0.0079 | val_top1=18.48 | val_top5=20.65 | val_top10=21.74
Epoch 17 | loss=0.0072 | val_top1=18.48 | val_top5=20.65 | val_top10=21.74
Epoch 18 | loss=0.0066 | val_top1=18.48 | val_top5=20.65 | val_top10=21.74
Epoch 19 | loss=0.0061 | val_top1=18.48 | val_top5=20.65 | val_top10=21.74
Epoch 20 | loss=0.0056 | val_top1=18.48 | val_top5=19.57 | val_top10=21.74

Best validation top1: 18.47826086956522
Test metrics: {'top1': 17.899343544857768, 'top5': 23.326039387308533, 'top10': 25.426695842450766}

================================================================================
[3/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2279 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 02 | loss=1.8420 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 03 | loss=1.5945 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 04 | loss=1.4047 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 05 | loss=1.2463 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 06 | loss=1.1104 | val_top1=11.96 | val_top5=15.22 | val_top10=19.57
Epoch 07 | loss=0.9925 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 08 | loss=0.8898 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 09 | loss=0.8004 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 10 | loss=0.7224 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 11 | loss=0.6544 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 12 | loss=0.5947 | val_top1=11.96 | val_top5=15.22 | val_top10=19.57
Epoch 13 | loss=0.5422 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 14 | loss=0.4956 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 15 | loss=0.4541 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 16 | loss=0.4168 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 17 | loss=0.3832 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 18 | loss=0.3528 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 19 | loss=0.3253 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 20 | loss=0.3003 | val_top1=11.96 | val_top5=16.30 | val_top10=16.30

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.849015317286653, 'top5': 21.00656455142232, 'top10': 23.282275711159738}

================================================================================
[4/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1722 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 02 | loss=1.8021 | val_top1=10.87 | val_top5=11.96 | val_top10=13.04
Epoch 03 | loss=1.5423 | val_top1=10.87 | val_top5=13.04 | val_top10=13.04
Epoch 04 | loss=1.3252 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 05 | loss=1.1404 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 06 | loss=0.9842 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 07 | loss=0.8526 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 08 | loss=0.7413 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 09 | loss=0.6467 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 10 | loss=0.5661 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 11 | loss=0.4974 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 12 | loss=0.4388 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 13 | loss=0.3887 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 14 | loss=0.3456 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 15 | loss=0.3085 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 16 | loss=0.2764 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 17 | loss=0.2486 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 18 | loss=0.2245 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 19 | loss=0.2035 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 20 | loss=0.1851 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.717724288840262, 'top5': 21.00656455142232, 'top10': 23.457330415754925}

================================================================================
[5/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9661 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 02 | loss=1.2043 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 03 | loss=0.7351 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 04 | loss=0.4061 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 05 | loss=0.2111 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 06 | loss=0.1188 | val_top1=10.87 | val_top5=16.30 | val_top10=21.74
Epoch 07 | loss=0.0788 | val_top1=11.96 | val_top5=19.57 | val_top10=21.74
Epoch 08 | loss=0.0619 | val_top1=10.87 | val_top5=16.30 | val_top10=20.65
Epoch 09 | loss=0.0464 | val_top1=10.87 | val_top5=19.57 | val_top10=21.74
Epoch 10 | loss=0.0371 | val_top1=11.96 | val_top5=17.39 | val_top10=21.74
Epoch 11 | loss=0.0324 | val_top1=11.96 | val_top5=19.57 | val_top10=21.74
Epoch 12 | loss=0.0291 | val_top1=10.87 | val_top5=17.39 | val_top10=21.74
Epoch 13 | loss=0.0256 | val_top1=11.96 | val_top5=18.48 | val_top10=21.74
Epoch 14 | loss=0.0223 | val_top1=13.04 | val_top5=18.48 | val_top10=22.83
Epoch 15 | loss=0.0215 | val_top1=13.04 | val_top5=18.48 | val_top10=22.83
Epoch 16 | loss=0.0185 | val_top1=11.96 | val_top5=18.48 | val_top10=22.83
Epoch 17 | loss=0.0163 | val_top1=13.04 | val_top5=17.39 | val_top10=21.74
Epoch 18 | loss=0.0147 | val_top1=13.04 | val_top5=17.39 | val_top10=21.74
Epoch 19 | loss=0.0137 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 20 | loss=0.0128 | val_top1=14.13 | val_top5=18.48 | val_top10=21.74

Best validation top1: 14.130434782608695
Test metrics: {'top1': 18.643326039387308, 'top5': 23.194748358862146, 'top10': 25.820568927789935}

================================================================================
[6/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0709 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 02 | loss=1.3981 | val_top1=9.78 | val_top5=10.87 | val_top10=15.22
Epoch 03 | loss=0.8971 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 04 | loss=0.5518 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 05 | loss=0.3067 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 06 | loss=0.1778 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 07 | loss=0.0977 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 08 | loss=0.0582 | val_top1=14.13 | val_top5=17.39 | val_top10=19.57
Epoch 09 | loss=0.0414 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 10 | loss=0.0342 | val_top1=10.87 | val_top5=19.57 | val_top10=19.57
Epoch 11 | loss=0.0265 | val_top1=10.87 | val_top5=18.48 | val_top10=19.57
Epoch 12 | loss=0.0235 | val_top1=10.87 | val_top5=16.30 | val_top10=20.65
Epoch 13 | loss=0.0219 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65
Epoch 14 | loss=0.0190 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65
Epoch 15 | loss=0.0178 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 16 | loss=0.0159 | val_top1=11.96 | val_top5=18.48 | val_top10=19.57
Epoch 17 | loss=0.0135 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 18 | loss=0.0133 | val_top1=11.96 | val_top5=18.48 | val_top10=19.57
Epoch 19 | loss=0.0116 | val_top1=13.04 | val_top5=18.48 | val_top10=18.48
Epoch 20 | loss=0.0109 | val_top1=13.04 | val_top5=18.48 | val_top10=18.48

Best validation top1: 14.130434782608695
Test metrics: {'top1': 17.155361050328228, 'top5': 22.01312910284464, 'top10': 24.551422319474835}

================================================================================
[7/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2997 | val_top1=8.70 | val_top5=15.22 | val_top10=17.39
Epoch 02 | loss=2.0578 | val_top1=8.70 | val_top5=16.30 | val_top10=18.48
Epoch 03 | loss=1.8331 | val_top1=9.78 | val_top5=14.13 | val_top10=18.48
Epoch 04 | loss=1.6955 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 05 | loss=1.5828 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 06 | loss=1.4676 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 07 | loss=1.3649 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 08 | loss=1.2720 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 09 | loss=1.1891 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 10 | loss=1.1054 | val_top1=9.78 | val_top5=13.04 | val_top10=16.30
Epoch 11 | loss=1.0116 | val_top1=9.78 | val_top5=13.04 | val_top10=16.30
Epoch 12 | loss=0.9643 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 13 | loss=0.9052 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 14 | loss=0.8435 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 15 | loss=0.7922 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 16 | loss=0.7521 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 17 | loss=0.7079 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 18 | loss=0.6708 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 19 | loss=0.6311 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 20 | loss=0.5767 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22

Best validation top1: 9.782608695652174
Test metrics: {'top1': 15.973741794310722, 'top5': 20.175054704595187, 'top10': 22.538293216630198}

================================================================================
[8/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2245 | val_top1=9.78 | val_top5=10.87 | val_top10=13.04
Epoch 02 | loss=1.9736 | val_top1=9.78 | val_top5=10.87 | val_top10=11.96
Epoch 03 | loss=1.7941 | val_top1=9.78 | val_top5=10.87 | val_top10=13.04
Epoch 04 | loss=1.6101 | val_top1=8.70 | val_top5=10.87 | val_top10=11.96
Epoch 05 | loss=1.4606 | val_top1=9.78 | val_top5=9.78 | val_top10=10.87
Epoch 06 | loss=1.3590 | val_top1=9.78 | val_top5=9.78 | val_top10=10.87
Epoch 07 | loss=1.2499 | val_top1=9.78 | val_top5=9.78 | val_top10=11.96
Epoch 08 | loss=1.1449 | val_top1=9.78 | val_top5=9.78 | val_top10=13.04
Epoch 09 | loss=1.0512 | val_top1=9.78 | val_top5=9.78 | val_top10=13.04
Epoch 10 | loss=0.9575 | val_top1=9.78 | val_top5=9.78 | val_top10=13.04
Epoch 11 | loss=0.8969 | val_top1=9.78 | val_top5=9.78 | val_top10=13.04
Epoch 12 | loss=0.8108 | val_top1=9.78 | val_top5=9.78 | val_top10=14.13
Epoch 13 | loss=0.7511 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 14 | loss=0.7240 | val_top1=8.70 | val_top5=10.87 | val_top10=14.13
Epoch 15 | loss=0.6457 | val_top1=8.70 | val_top5=10.87 | val_top10=14.13
Epoch 16 | loss=0.6191 | val_top1=8.70 | val_top5=11.96 | val_top10=14.13
Epoch 17 | loss=0.5656 | val_top1=8.70 | val_top5=11.96 | val_top10=13.04
Epoch 18 | loss=0.5208 | val_top1=8.70 | val_top5=11.96 | val_top10=13.04
Epoch 19 | loss=0.4928 | val_top1=8.70 | val_top5=11.96 | val_top10=13.04
Epoch 20 | loss=0.4638 | val_top1=8.70 | val_top5=13.04 | val_top10=13.04

Best validation top1: 9.782608695652174
Test metrics: {'top1': 16.061269146608314, 'top5': 19.299781181619256, 'top10': 21.00656455142232}

================================================================================
[9/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.8843 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 02 | loss=1.0335 | val_top1=11.96 | val_top5=13.04 | val_top10=15.22
Epoch 03 | loss=0.5009 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 04 | loss=0.2032 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 05 | loss=0.0709 | val_top1=14.13 | val_top5=20.65 | val_top10=22.83
Epoch 06 | loss=0.0353 | val_top1=13.04 | val_top5=20.65 | val_top10=22.83
Epoch 07 | loss=0.0260 | val_top1=11.96 | val_top5=21.74 | val_top10=22.83
Epoch 08 | loss=0.0213 | val_top1=11.96 | val_top5=22.83 | val_top10=22.83
Epoch 09 | loss=0.0180 | val_top1=11.96 | val_top5=22.83 | val_top10=22.83
Epoch 10 | loss=0.0156 | val_top1=11.96 | val_top5=22.83 | val_top10=22.83
Epoch 11 | loss=0.0136 | val_top1=11.96 | val_top5=22.83 | val_top10=22.83
Epoch 12 | loss=0.0121 | val_top1=13.04 | val_top5=22.83 | val_top10=22.83
Epoch 13 | loss=0.0108 | val_top1=11.96 | val_top5=22.83 | val_top10=22.83
Epoch 14 | loss=0.0097 | val_top1=13.04 | val_top5=22.83 | val_top10=22.83
Epoch 15 | loss=0.0088 | val_top1=13.04 | val_top5=22.83 | val_top10=22.83
Epoch 16 | loss=0.0080 | val_top1=13.04 | val_top5=22.83 | val_top10=22.83
Epoch 17 | loss=0.0073 | val_top1=13.04 | val_top5=22.83 | val_top10=22.83
Epoch 18 | loss=0.0068 | val_top1=13.04 | val_top5=22.83 | val_top10=22.83
Epoch 19 | loss=0.0062 | val_top1=13.04 | val_top5=21.74 | val_top10=22.83
Epoch 20 | loss=0.0058 | val_top1=14.13 | val_top5=21.74 | val_top10=22.83

Best validation top1: 14.130434782608695
Test metrics: {'top1': 16.76148796498906, 'top5': 22.75711159737418, 'top10': 25.207877461706783}

================================================================================
[10/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9978 | val_top1=10.87 | val_top5=11.96 | val_top10=15.22
Epoch 02 | loss=1.2631 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 03 | loss=0.7526 | val_top1=10.87 | val_top5=13.04 | val_top10=18.48
Epoch 04 | loss=0.3539 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 05 | loss=0.1594 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 06 | loss=0.0634 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 07 | loss=0.0302 | val_top1=11.96 | val_top5=18.48 | val_top10=19.57
Epoch 08 | loss=0.0198 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 09 | loss=0.0161 | val_top1=13.04 | val_top5=17.39 | val_top10=20.65
Epoch 10 | loss=0.0138 | val_top1=13.04 | val_top5=15.22 | val_top10=20.65
Epoch 11 | loss=0.0121 | val_top1=13.04 | val_top5=15.22 | val_top10=19.57
Epoch 12 | loss=0.0107 | val_top1=13.04 | val_top5=15.22 | val_top10=19.57
Epoch 13 | loss=0.0096 | val_top1=13.04 | val_top5=16.30 | val_top10=19.57
Epoch 14 | loss=0.0086 | val_top1=13.04 | val_top5=16.30 | val_top10=18.48
Epoch 15 | loss=0.0079 | val_top1=13.04 | val_top5=16.30 | val_top10=18.48
Epoch 16 | loss=0.0072 | val_top1=13.04 | val_top5=16.30 | val_top10=18.48
Epoch 17 | loss=0.0066 | val_top1=13.04 | val_top5=16.30 | val_top10=18.48
Epoch 18 | loss=0.0060 | val_top1=13.04 | val_top5=16.30 | val_top10=18.48
Epoch 19 | loss=0.0056 | val_top1=13.04 | val_top5=16.30 | val_top10=19.57
Epoch 20 | loss=0.0052 | val_top1=13.04 | val_top5=16.30 | val_top10=19.57

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.367614879649892, 'top5': 22.23194748358862, 'top10': 24.814004376367613}

================================================================================
[11/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1604 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 02 | loss=1.7792 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 03 | loss=1.5300 | val_top1=13.04 | val_top5=15.22 | val_top10=15.22
Epoch 04 | loss=1.3315 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 05 | loss=1.1691 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 06 | loss=1.0340 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 07 | loss=0.9196 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 08 | loss=0.8213 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 09 | loss=0.7359 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 10 | loss=0.6610 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 11 | loss=0.5952 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 12 | loss=0.5370 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 13 | loss=0.4856 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 14 | loss=0.4399 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 15 | loss=0.3994 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 16 | loss=0.3633 | val_top1=13.04 | val_top5=13.04 | val_top10=16.30
Epoch 17 | loss=0.3312 | val_top1=13.04 | val_top5=13.04 | val_top10=15.22
Epoch 18 | loss=0.3027 | val_top1=13.04 | val_top5=13.04 | val_top10=15.22
Epoch 19 | loss=0.2773 | val_top1=13.04 | val_top5=13.04 | val_top10=15.22
Epoch 20 | loss=0.2545 | val_top1=13.04 | val_top5=13.04 | val_top10=15.22

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.10503282275711, 'top5': 20.568927789934353, 'top10': 23.150984682713347}

================================================================================
[12/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1202 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 02 | loss=1.7120 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 03 | loss=1.4464 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 04 | loss=1.2358 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 05 | loss=1.0618 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30
Epoch 06 | loss=0.9153 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30
Epoch 07 | loss=0.7909 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 08 | loss=0.6849 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 09 | loss=0.5943 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 10 | loss=0.5169 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 11 | loss=0.4510 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 12 | loss=0.3949 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 13 | loss=0.3472 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 14 | loss=0.3065 | val_top1=11.96 | val_top5=11.96 | val_top10=17.39
Epoch 15 | loss=0.2718 | val_top1=11.96 | val_top5=11.96 | val_top10=17.39
Epoch 16 | loss=0.2422 | val_top1=11.96 | val_top5=11.96 | val_top10=18.48
Epoch 17 | loss=0.2167 | val_top1=11.96 | val_top5=11.96 | val_top10=18.48
Epoch 18 | loss=0.1948 | val_top1=11.96 | val_top5=11.96 | val_top10=18.48
Epoch 19 | loss=0.1758 | val_top1=11.96 | val_top5=11.96 | val_top10=19.57
Epoch 20 | loss=0.1593 | val_top1=11.96 | val_top5=11.96 | val_top10=19.57

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.192560175054705, 'top5': 20.962800875273523, 'top10': 23.544857768052516}

================================================================================
[13/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0000 | val_top1=8.70 | val_top5=10.87 | val_top10=13.04
Epoch 02 | loss=1.2155 | val_top1=9.78 | val_top5=11.96 | val_top10=11.96
Epoch 03 | loss=0.7129 | val_top1=9.78 | val_top5=10.87 | val_top10=13.04
Epoch 04 | loss=0.4073 | val_top1=10.87 | val_top5=10.87 | val_top10=14.13
Epoch 05 | loss=0.2100 | val_top1=8.70 | val_top5=13.04 | val_top10=20.65
Epoch 06 | loss=0.1252 | val_top1=8.70 | val_top5=13.04 | val_top10=19.57
Epoch 07 | loss=0.0785 | val_top1=8.70 | val_top5=17.39 | val_top10=20.65
Epoch 08 | loss=0.0524 | val_top1=8.70 | val_top5=15.22 | val_top10=19.57
Epoch 09 | loss=0.0415 | val_top1=8.70 | val_top5=14.13 | val_top10=19.57
Epoch 10 | loss=0.0331 | val_top1=8.70 | val_top5=14.13 | val_top10=18.48
Epoch 11 | loss=0.0288 | val_top1=8.70 | val_top5=15.22 | val_top10=20.65
Epoch 12 | loss=0.0251 | val_top1=8.70 | val_top5=15.22 | val_top10=19.57
Epoch 13 | loss=0.0229 | val_top1=8.70 | val_top5=17.39 | val_top10=20.65
Epoch 14 | loss=0.0200 | val_top1=9.78 | val_top5=15.22 | val_top10=20.65
Epoch 15 | loss=0.0182 | val_top1=9.78 | val_top5=16.30 | val_top10=20.65
Epoch 16 | loss=0.0170 | val_top1=9.78 | val_top5=18.48 | val_top10=20.65
Epoch 17 | loss=0.0151 | val_top1=9.78 | val_top5=18.48 | val_top10=20.65
Epoch 18 | loss=0.0138 | val_top1=9.78 | val_top5=19.57 | val_top10=21.74
Epoch 19 | loss=0.0128 | val_top1=9.78 | val_top5=17.39 | val_top10=20.65
Epoch 20 | loss=0.0115 | val_top1=9.78 | val_top5=18.48 | val_top10=20.65

Best validation top1: 10.869565217391305
Test metrics: {'top1': 15.536105032822757, 'top5': 19.212253829321664, 'top10': 22.450765864332602}

================================================================================
[14/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0887 | val_top1=9.78 | val_top5=9.78 | val_top10=11.96
Epoch 02 | loss=1.3363 | val_top1=6.52 | val_top5=13.04 | val_top10=13.04
Epoch 03 | loss=0.9255 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 04 | loss=0.5350 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 05 | loss=0.3017 | val_top1=9.78 | val_top5=16.30 | val_top10=17.39
Epoch 06 | loss=0.1413 | val_top1=9.78 | val_top5=17.39 | val_top10=20.65
Epoch 07 | loss=0.0864 | val_top1=9.78 | val_top5=16.30 | val_top10=19.57
Epoch 08 | loss=0.0530 | val_top1=10.87 | val_top5=18.48 | val_top10=21.74
Epoch 09 | loss=0.0370 | val_top1=10.87 | val_top5=15.22 | val_top10=21.74
Epoch 10 | loss=0.0298 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 11 | loss=0.0257 | val_top1=10.87 | val_top5=17.39 | val_top10=20.65
Epoch 12 | loss=0.0232 | val_top1=9.78 | val_top5=16.30 | val_top10=21.74
Epoch 13 | loss=0.0204 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 14 | loss=0.0178 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 15 | loss=0.0165 | val_top1=13.04 | val_top5=18.48 | val_top10=22.83
Epoch 16 | loss=0.0137 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65
Epoch 17 | loss=0.0130 | val_top1=11.96 | val_top5=17.39 | val_top10=21.74
Epoch 18 | loss=0.0118 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 19 | loss=0.0110 | val_top1=13.04 | val_top5=17.39 | val_top10=22.83
Epoch 20 | loss=0.0100 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65

Best validation top1: 13.043478260869565
Test metrics: {'top1': 15.973741794310722, 'top5': 21.706783369803063, 'top10': 23.85120350109409}

================================================================================
[15/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.3315 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 02 | loss=2.0608 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 03 | loss=1.8739 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 04 | loss=1.7349 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 05 | loss=1.5791 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 06 | loss=1.4250 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 07 | loss=1.3291 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 08 | loss=1.2559 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 09 | loss=1.1662 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 10 | loss=1.0571 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 11 | loss=0.9704 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 12 | loss=0.9132 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 13 | loss=0.8558 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 14 | loss=0.7795 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 15 | loss=0.7255 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 16 | loss=0.7011 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 17 | loss=0.6769 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 18 | loss=0.5846 | val_top1=10.87 | val_top5=11.96 | val_top10=15.22
Epoch 19 | loss=0.5532 | val_top1=10.87 | val_top5=11.96 | val_top10=15.22
Epoch 20 | loss=0.5428 | val_top1=10.87 | val_top5=10.87 | val_top10=16.30

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.411378555798688, 'top5': 20.525164113785557, 'top10': 22.36323851203501}

================================================================================
[16/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2231 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 02 | loss=1.9173 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 03 | loss=1.7343 | val_top1=11.96 | val_top5=13.04 | val_top10=15.22
Epoch 04 | loss=1.5652 | val_top1=11.96 | val_top5=13.04 | val_top10=15.22
Epoch 05 | loss=1.4046 | val_top1=11.96 | val_top5=13.04 | val_top10=15.22
Epoch 06 | loss=1.2944 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 07 | loss=1.1542 | val_top1=11.96 | val_top5=13.04 | val_top10=15.22
Epoch 08 | loss=1.0647 | val_top1=11.96 | val_top5=13.04 | val_top10=15.22
Epoch 09 | loss=0.9801 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 10 | loss=0.8984 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 11 | loss=0.8351 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 12 | loss=0.7455 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 13 | loss=0.6877 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 14 | loss=0.6666 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 15 | loss=0.5945 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 16 | loss=0.5507 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 17 | loss=0.5267 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 18 | loss=0.4865 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 19 | loss=0.4527 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 20 | loss=0.3996 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30

Best validation top1: 11.956521739130435
Test metrics: {'top1': 15.536105032822757, 'top5': 20.08752735229759, 'top10': 22.538293216630198}

================================================================================
[17/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.8923 | val_top1=8.70 | val_top5=13.04 | val_top10=14.13
Epoch 02 | loss=1.0176 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 03 | loss=0.4750 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 04 | loss=0.1897 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 05 | loss=0.0737 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 06 | loss=0.0393 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 07 | loss=0.0288 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 08 | loss=0.0236 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65
Epoch 09 | loss=0.0200 | val_top1=11.96 | val_top5=19.57 | val_top10=20.65
Epoch 10 | loss=0.0173 | val_top1=11.96 | val_top5=19.57 | val_top10=20.65
Epoch 11 | loss=0.0152 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 12 | loss=0.0134 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 13 | loss=0.0120 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 14 | loss=0.0108 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 15 | loss=0.0098 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 16 | loss=0.0089 | val_top1=15.22 | val_top5=19.57 | val_top10=21.74
Epoch 17 | loss=0.0082 | val_top1=15.22 | val_top5=19.57 | val_top10=21.74
Epoch 18 | loss=0.0075 | val_top1=15.22 | val_top5=18.48 | val_top10=21.74
Epoch 19 | loss=0.0069 | val_top1=15.22 | val_top5=18.48 | val_top10=21.74
Epoch 20 | loss=0.0064 | val_top1=15.22 | val_top5=18.48 | val_top10=21.74

Best validation top1: 15.217391304347826
Test metrics: {'top1': 19.34354485776805, 'top5': 25.032822757111596, 'top10': 27.396061269146607}

================================================================================
[18/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9778 | val_top1=11.96 | val_top5=13.04 | val_top10=13.04
Epoch 02 | loss=1.2757 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 03 | loss=0.7128 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 04 | loss=0.3369 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30
Epoch 05 | loss=0.1339 | val_top1=10.87 | val_top5=17.39 | val_top10=19.57
Epoch 06 | loss=0.0536 | val_top1=13.04 | val_top5=17.39 | val_top10=20.65
Epoch 07 | loss=0.0282 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 08 | loss=0.0208 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 09 | loss=0.0174 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 10 | loss=0.0150 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 11 | loss=0.0132 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 12 | loss=0.0117 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 13 | loss=0.0105 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 14 | loss=0.0095 | val_top1=13.04 | val_top5=20.65 | val_top10=20.65
Epoch 15 | loss=0.0087 | val_top1=13.04 | val_top5=20.65 | val_top10=20.65
Epoch 16 | loss=0.0079 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 17 | loss=0.0073 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 18 | loss=0.0067 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 19 | loss=0.0062 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 20 | loss=0.0057 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65

Best validation top1: 14.130434782608695
Test metrics: {'top1': 17.549234135667398, 'top5': 22.669584245076585, 'top10': 25.12035010940919}

================================================================================
[19/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1448 | val_top1=13.04 | val_top5=16.30 | val_top10=19.57
Epoch 02 | loss=1.7712 | val_top1=13.04 | val_top5=15.22 | val_top10=19.57
Epoch 03 | loss=1.5492 | val_top1=13.04 | val_top5=16.30 | val_top10=18.48
Epoch 04 | loss=1.3699 | val_top1=13.04 | val_top5=16.30 | val_top10=18.48
Epoch 05 | loss=1.2140 | val_top1=13.04 | val_top5=15.22 | val_top10=18.48
Epoch 06 | loss=1.0777 | val_top1=13.04 | val_top5=15.22 | val_top10=18.48
Epoch 07 | loss=0.9595 | val_top1=14.13 | val_top5=15.22 | val_top10=18.48
Epoch 08 | loss=0.8575 | val_top1=14.13 | val_top5=15.22 | val_top10=18.48
Epoch 09 | loss=0.7693 | val_top1=14.13 | val_top5=15.22 | val_top10=18.48
Epoch 10 | loss=0.6930 | val_top1=13.04 | val_top5=15.22 | val_top10=18.48
Epoch 11 | loss=0.6265 | val_top1=13.04 | val_top5=15.22 | val_top10=19.57
Epoch 12 | loss=0.5684 | val_top1=13.04 | val_top5=15.22 | val_top10=18.48
Epoch 13 | loss=0.5173 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 14 | loss=0.4720 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 15 | loss=0.4318 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 16 | loss=0.3960 | val_top1=13.04 | val_top5=16.30 | val_top10=17.39
Epoch 17 | loss=0.3639 | val_top1=13.04 | val_top5=16.30 | val_top10=17.39
Epoch 18 | loss=0.3351 | val_top1=13.04 | val_top5=16.30 | val_top10=16.30
Epoch 19 | loss=0.3092 | val_top1=13.04 | val_top5=16.30 | val_top10=16.30
Epoch 20 | loss=0.2858 | val_top1=13.04 | val_top5=16.30 | val_top10=16.30

Best validation top1: 14.130434782608695
Test metrics: {'top1': 16.849015317286653, 'top5': 21.400437636761488, 'top10': 23.588621444201312}

================================================================================
[20/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1540 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 02 | loss=1.8217 | val_top1=8.70 | val_top5=13.04 | val_top10=14.13
Epoch 03 | loss=1.5668 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 04 | loss=1.3461 | val_top1=11.96 | val_top5=11.96 | val_top10=13.04
Epoch 05 | loss=1.1553 | val_top1=11.96 | val_top5=11.96 | val_top10=13.04
Epoch 06 | loss=0.9917 | val_top1=11.96 | val_top5=11.96 | val_top10=15.22
Epoch 07 | loss=0.8531 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39
Epoch 08 | loss=0.7370 | val_top1=11.96 | val_top5=11.96 | val_top10=17.39
Epoch 09 | loss=0.6400 | val_top1=11.96 | val_top5=11.96 | val_top10=17.39
Epoch 10 | loss=0.5588 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 11 | loss=0.4904 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 12 | loss=0.4326 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 13 | loss=0.3834 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 14 | loss=0.3413 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 15 | loss=0.3051 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 16 | loss=0.2739 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 17 | loss=0.2468 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 18 | loss=0.2232 | val_top1=11.96 | val_top5=14.13 | val_top10=18.48
Epoch 19 | loss=0.2026 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 20 | loss=0.1846 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48

Best validation top1: 11.956521739130435
Test metrics: {'top1': 15.973741794310722, 'top5': 20.48140043763676, 'top10': 22.27571115973742}

================================================================================
[21/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9448 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 02 | loss=1.1803 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 03 | loss=0.7277 | val_top1=11.96 | val_top5=13.04 | val_top10=14.13
Epoch 04 | loss=0.4178 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 05 | loss=0.2312 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 06 | loss=0.1233 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 07 | loss=0.0864 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 08 | loss=0.0595 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 09 | loss=0.0485 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 10 | loss=0.0377 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 11 | loss=0.0319 | val_top1=13.04 | val_top5=19.57 | val_top10=19.57
Epoch 12 | loss=0.0282 | val_top1=13.04 | val_top5=17.39 | val_top10=20.65
Epoch 13 | loss=0.0250 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 14 | loss=0.0221 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 15 | loss=0.0199 | val_top1=14.13 | val_top5=18.48 | val_top10=20.65
Epoch 16 | loss=0.0177 | val_top1=14.13 | val_top5=18.48 | val_top10=20.65
Epoch 17 | loss=0.0163 | val_top1=14.13 | val_top5=18.48 | val_top10=21.74
Epoch 18 | loss=0.0151 | val_top1=15.22 | val_top5=19.57 | val_top10=21.74
Epoch 19 | loss=0.0131 | val_top1=15.22 | val_top5=19.57 | val_top10=21.74
Epoch 20 | loss=0.0124 | val_top1=15.22 | val_top5=19.57 | val_top10=22.83

Best validation top1: 15.217391304347826
Test metrics: {'top1': 17.855579868708972, 'top5': 23.10722100656455, 'top10': 25.908096280087527}

================================================================================
[22/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0352 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 02 | loss=1.3114 | val_top1=8.70 | val_top5=9.78 | val_top10=10.87
Epoch 03 | loss=0.8656 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 04 | loss=0.5144 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 05 | loss=0.2880 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 06 | loss=0.1497 | val_top1=10.87 | val_top5=11.96 | val_top10=15.22
Epoch 07 | loss=0.0793 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 08 | loss=0.0533 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 09 | loss=0.0380 | val_top1=11.96 | val_top5=17.39 | val_top10=17.39
Epoch 10 | loss=0.0294 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 11 | loss=0.0268 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 12 | loss=0.0227 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 13 | loss=0.0193 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 14 | loss=0.0183 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 15 | loss=0.0157 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 16 | loss=0.0146 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 17 | loss=0.0138 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 18 | loss=0.0118 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 19 | loss=0.0113 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 20 | loss=0.0108 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.323851203501093, 'top5': 22.407002188183807, 'top10': 25.339168490153174}

================================================================================
[23/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.3729 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 02 | loss=2.0742 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 03 | loss=1.8592 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 04 | loss=1.6952 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 05 | loss=1.5528 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 06 | loss=1.4512 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 07 | loss=1.3256 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 08 | loss=1.2135 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 09 | loss=1.1462 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 10 | loss=1.0901 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 11 | loss=1.0217 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 12 | loss=0.9554 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 13 | loss=0.8977 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 14 | loss=0.8174 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 15 | loss=0.7701 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 16 | loss=0.7346 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 17 | loss=0.6795 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 18 | loss=0.6375 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 19 | loss=0.5921 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 20 | loss=0.5736 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.49890590809628, 'top5': 21.181619256017505, 'top10': 23.50109409190372}

================================================================================
[24/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.3113 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 02 | loss=1.9778 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 03 | loss=1.7575 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 04 | loss=1.5826 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 05 | loss=1.4609 | val_top1=11.96 | val_top5=14.13 | val_top10=18.48
Epoch 06 | loss=1.3273 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 07 | loss=1.1964 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 08 | loss=1.0883 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 09 | loss=1.0048 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 10 | loss=0.9225 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39
Epoch 11 | loss=0.8569 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 12 | loss=0.7849 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 13 | loss=0.7385 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 14 | loss=0.6767 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 15 | loss=0.6336 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 16 | loss=0.6022 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 17 | loss=0.5420 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 18 | loss=0.5150 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 19 | loss=0.4848 | val_top1=9.78 | val_top5=16.30 | val_top10=18.48
Epoch 20 | loss=0.4571 | val_top1=9.78 | val_top5=14.13 | val_top10=18.48

Best validation top1: 11.956521739130435
Test metrics: {'top1': 15.536105032822757, 'top5': 19.037199124726477, 'top10': 21.312910284463896}

================================================================================
[25/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.8934 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 02 | loss=1.0325 | val_top1=13.04 | val_top5=17.39 | val_top10=17.39
Epoch 03 | loss=0.5011 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 04 | loss=0.2031 | val_top1=11.96 | val_top5=17.39 | val_top10=17.39
Epoch 05 | loss=0.0723 | val_top1=10.87 | val_top5=16.30 | val_top10=20.65
Epoch 06 | loss=0.0389 | val_top1=13.04 | val_top5=17.39 | val_top10=22.83
Epoch 07 | loss=0.0280 | val_top1=13.04 | val_top5=17.39 | val_top10=22.83
Epoch 08 | loss=0.0225 | val_top1=11.96 | val_top5=17.39 | val_top10=23.91
Epoch 09 | loss=0.0188 | val_top1=11.96 | val_top5=17.39 | val_top10=22.83
Epoch 10 | loss=0.0161 | val_top1=11.96 | val_top5=18.48 | val_top10=22.83
Epoch 11 | loss=0.0140 | val_top1=11.96 | val_top5=18.48 | val_top10=22.83
Epoch 12 | loss=0.0123 | val_top1=11.96 | val_top5=19.57 | val_top10=22.83
Epoch 13 | loss=0.0110 | val_top1=11.96 | val_top5=19.57 | val_top10=22.83
Epoch 14 | loss=0.0099 | val_top1=15.22 | val_top5=19.57 | val_top10=22.83
Epoch 15 | loss=0.0089 | val_top1=15.22 | val_top5=20.65 | val_top10=22.83
Epoch 16 | loss=0.0081 | val_top1=15.22 | val_top5=20.65 | val_top10=22.83
Epoch 17 | loss=0.0074 | val_top1=15.22 | val_top5=21.74 | val_top10=21.74
Epoch 18 | loss=0.0068 | val_top1=15.22 | val_top5=21.74 | val_top10=21.74
Epoch 19 | loss=0.0063 | val_top1=15.22 | val_top5=21.74 | val_top10=21.74
Epoch 20 | loss=0.0058 | val_top1=14.13 | val_top5=21.74 | val_top10=21.74

Best validation top1: 15.217391304347826
Test metrics: {'top1': 18.643326039387308, 'top5': 24.37636761487965, 'top10': 26.827133479212254}

================================================================================
[26/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0380 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 02 | loss=1.3321 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 03 | loss=0.8160 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 04 | loss=0.4190 | val_top1=9.78 | val_top5=11.96 | val_top10=11.96
Epoch 05 | loss=0.1621 | val_top1=9.78 | val_top5=10.87 | val_top10=11.96
Epoch 06 | loss=0.0639 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30
Epoch 07 | loss=0.0305 | val_top1=11.96 | val_top5=16.30 | val_top10=16.30
Epoch 08 | loss=0.0193 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 09 | loss=0.0160 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 10 | loss=0.0139 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 11 | loss=0.0122 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 12 | loss=0.0109 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 13 | loss=0.0098 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 14 | loss=0.0088 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 15 | loss=0.0080 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 16 | loss=0.0073 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 17 | loss=0.0067 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 18 | loss=0.0062 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 19 | loss=0.0057 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 20 | loss=0.0053 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48

Best validation top1: 11.956521739130435
Test metrics: {'top1': 14.74835886214442, 'top5': 18.38074398249453, 'top10': 20.700218818380744}

================================================================================
[27/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2182 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 02 | loss=1.8340 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 03 | loss=1.5762 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 04 | loss=1.3665 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 05 | loss=1.1885 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 06 | loss=1.0379 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 07 | loss=0.9111 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 08 | loss=0.8042 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 09 | loss=0.7133 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 10 | loss=0.6352 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 11 | loss=0.5676 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 12 | loss=0.5088 | val_top1=13.04 | val_top5=15.22 | val_top10=18.48
Epoch 13 | loss=0.4573 | val_top1=13.04 | val_top5=14.13 | val_top10=19.57
Epoch 14 | loss=0.4122 | val_top1=13.04 | val_top5=14.13 | val_top10=20.65
Epoch 15 | loss=0.3725 | val_top1=13.04 | val_top5=14.13 | val_top10=20.65
Epoch 16 | loss=0.3377 | val_top1=13.04 | val_top5=15.22 | val_top10=20.65
Epoch 17 | loss=0.3070 | val_top1=13.04 | val_top5=15.22 | val_top10=20.65
Epoch 18 | loss=0.2798 | val_top1=13.04 | val_top5=15.22 | val_top10=20.65
Epoch 19 | loss=0.2558 | val_top1=13.04 | val_top5=15.22 | val_top10=20.65
Epoch 20 | loss=0.2346 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.542669584245075, 'top5': 20.525164113785557, 'top10': 23.632385120350108}

================================================================================
[28/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1077 | val_top1=10.87 | val_top5=10.87 | val_top10=11.96
Epoch 02 | loss=1.7059 | val_top1=10.87 | val_top5=10.87 | val_top10=11.96
Epoch 03 | loss=1.4355 | val_top1=10.87 | val_top5=10.87 | val_top10=11.96
Epoch 04 | loss=1.2128 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 05 | loss=1.0286 | val_top1=9.78 | val_top5=11.96 | val_top10=15.22
Epoch 06 | loss=0.8783 | val_top1=9.78 | val_top5=11.96 | val_top10=16.30
Epoch 07 | loss=0.7549 | val_top1=9.78 | val_top5=10.87 | val_top10=16.30
Epoch 08 | loss=0.6520 | val_top1=9.78 | val_top5=10.87 | val_top10=16.30
Epoch 09 | loss=0.5652 | val_top1=9.78 | val_top5=10.87 | val_top10=16.30
Epoch 10 | loss=0.4913 | val_top1=9.78 | val_top5=10.87 | val_top10=15.22
Epoch 11 | loss=0.4283 | val_top1=9.78 | val_top5=10.87 | val_top10=15.22
Epoch 12 | loss=0.3745 | val_top1=9.78 | val_top5=10.87 | val_top10=15.22
Epoch 13 | loss=0.3286 | val_top1=9.78 | val_top5=10.87 | val_top10=15.22
Epoch 14 | loss=0.2894 | val_top1=9.78 | val_top5=11.96 | val_top10=15.22
Epoch 15 | loss=0.2559 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 16 | loss=0.2274 | val_top1=9.78 | val_top5=13.04 | val_top10=13.04
Epoch 17 | loss=0.2030 | val_top1=9.78 | val_top5=13.04 | val_top10=13.04
Epoch 18 | loss=0.1822 | val_top1=9.78 | val_top5=13.04 | val_top10=13.04
Epoch 19 | loss=0.1644 | val_top1=9.78 | val_top5=13.04 | val_top10=13.04
Epoch 20 | loss=0.1491 | val_top1=9.78 | val_top5=13.04 | val_top10=13.04

Best validation top1: 10.869565217391305
Test metrics: {'top1': 16.10503282275711, 'top5': 19.387308533916848, 'top10': 21.663019693654267}

================================================================================
[29/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9608 | val_top1=9.78 | val_top5=9.78 | val_top10=10.87
Epoch 02 | loss=1.2247 | val_top1=9.78 | val_top5=11.96 | val_top10=11.96
Epoch 03 | loss=0.7591 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 04 | loss=0.4108 | val_top1=9.78 | val_top5=10.87 | val_top10=13.04
Epoch 05 | loss=0.2343 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 06 | loss=0.1253 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 07 | loss=0.0771 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 08 | loss=0.0555 | val_top1=9.78 | val_top5=13.04 | val_top10=18.48
Epoch 09 | loss=0.0409 | val_top1=8.70 | val_top5=11.96 | val_top10=18.48
Epoch 10 | loss=0.0345 | val_top1=8.70 | val_top5=14.13 | val_top10=19.57
Epoch 11 | loss=0.0310 | val_top1=8.70 | val_top5=16.30 | val_top10=19.57
Epoch 12 | loss=0.0254 | val_top1=8.70 | val_top5=18.48 | val_top10=20.65
Epoch 13 | loss=0.0220 | val_top1=8.70 | val_top5=16.30 | val_top10=19.57
Epoch 14 | loss=0.0203 | val_top1=8.70 | val_top5=17.39 | val_top10=19.57
Epoch 15 | loss=0.0187 | val_top1=8.70 | val_top5=16.30 | val_top10=18.48
Epoch 16 | loss=0.0161 | val_top1=8.70 | val_top5=16.30 | val_top10=20.65
Epoch 17 | loss=0.0147 | val_top1=8.70 | val_top5=18.48 | val_top10=19.57
Epoch 18 | loss=0.0137 | val_top1=8.70 | val_top5=18.48 | val_top10=19.57
Epoch 19 | loss=0.0126 | val_top1=10.87 | val_top5=18.48 | val_top10=19.57
Epoch 20 | loss=0.0112 | val_top1=10.87 | val_top5=17.39 | val_top10=19.57

Best validation top1: 10.869565217391305
Test metrics: {'top1': 16.061269146608314, 'top5': 20.831509846827135, 'top10': 24.201312910284464}

================================================================================
[30/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0205 | val_top1=10.87 | val_top5=10.87 | val_top10=10.87
Epoch 02 | loss=1.3984 | val_top1=9.78 | val_top5=9.78 | val_top10=13.04
Epoch 03 | loss=0.9414 | val_top1=10.87 | val_top5=10.87 | val_top10=10.87
Epoch 04 | loss=0.5692 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 05 | loss=0.3117 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 06 | loss=0.1980 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 07 | loss=0.0988 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 08 | loss=0.0640 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 09 | loss=0.0415 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 10 | loss=0.0298 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 11 | loss=0.0243 | val_top1=10.87 | val_top5=17.39 | val_top10=19.57
Epoch 12 | loss=0.0207 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 13 | loss=0.0186 | val_top1=13.04 | val_top5=17.39 | val_top10=20.65
Epoch 14 | loss=0.0170 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 15 | loss=0.0155 | val_top1=13.04 | val_top5=17.39 | val_top10=20.65
Epoch 16 | loss=0.0140 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65
Epoch 17 | loss=0.0124 | val_top1=13.04 | val_top5=17.39 | val_top10=20.65
Epoch 18 | loss=0.0119 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 19 | loss=0.0103 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 20 | loss=0.0096 | val_top1=13.04 | val_top5=17.39 | val_top10=20.65

Best validation top1: 13.043478260869565
Test metrics: {'top1': 17.024070021881837, 'top5': 21.663019693654267, 'top10': 24.201312910284464}

================================================================================
[31/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.3703 | val_top1=13.04 | val_top5=16.30 | val_top10=17.39
Epoch 02 | loss=2.0761 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 03 | loss=1.7967 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 04 | loss=1.6410 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 05 | loss=1.5111 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 06 | loss=1.4047 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 07 | loss=1.3010 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 08 | loss=1.2182 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 09 | loss=1.1020 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 10 | loss=1.0312 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 11 | loss=0.9609 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 12 | loss=0.9043 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 13 | loss=0.8270 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 14 | loss=0.7804 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 15 | loss=0.7262 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 16 | loss=0.6667 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 17 | loss=0.6298 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 18 | loss=0.5740 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 19 | loss=0.5511 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 20 | loss=0.5284 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.061269146608314, 'top5': 19.73741794310722, 'top10': 22.100656455142232}

================================================================================
[32/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2594 | val_top1=9.78 | val_top5=13.04 | val_top10=16.30
Epoch 02 | loss=1.9944 | val_top1=9.78 | val_top5=13.04 | val_top10=17.39
Epoch 03 | loss=1.7888 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 04 | loss=1.5957 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 05 | loss=1.4337 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 06 | loss=1.3104 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 07 | loss=1.1805 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30
Epoch 08 | loss=1.0884 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 09 | loss=0.9886 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 10 | loss=0.9036 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 11 | loss=0.8339 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 12 | loss=0.7593 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 13 | loss=0.7026 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 14 | loss=0.6451 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 15 | loss=0.5828 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 16 | loss=0.5379 | val_top1=9.78 | val_top5=13.04 | val_top10=17.39
Epoch 17 | loss=0.5114 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 18 | loss=0.4773 | val_top1=9.78 | val_top5=11.96 | val_top10=16.30
Epoch 19 | loss=0.4496 | val_top1=9.78 | val_top5=11.96 | val_top10=16.30
Epoch 20 | loss=0.4011 | val_top1=9.78 | val_top5=11.96 | val_top10=16.30

Best validation top1: 10.869565217391305
Test metrics: {'top1': 16.323851203501093, 'top5': 20.568927789934353, 'top10': 22.62582056892779}

================================================================================
[33/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.8837 | val_top1=9.78 | val_top5=13.04 | val_top10=16.30
Epoch 02 | loss=1.0485 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 03 | loss=0.4789 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30
Epoch 04 | loss=0.1629 | val_top1=9.78 | val_top5=13.04 | val_top10=17.39
Epoch 05 | loss=0.0494 | val_top1=11.96 | val_top5=18.48 | val_top10=19.57
Epoch 06 | loss=0.0217 | val_top1=13.04 | val_top5=18.48 | val_top10=18.48
Epoch 07 | loss=0.0160 | val_top1=11.96 | val_top5=18.48 | val_top10=18.48
Epoch 08 | loss=0.0134 | val_top1=11.96 | val_top5=18.48 | val_top10=18.48
Epoch 09 | loss=0.0116 | val_top1=11.96 | val_top5=18.48 | val_top10=18.48
Epoch 10 | loss=0.0102 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 11 | loss=0.0091 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 12 | loss=0.0081 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 13 | loss=0.0073 | val_top1=15.22 | val_top5=17.39 | val_top10=19.57
Epoch 14 | loss=0.0067 | val_top1=15.22 | val_top5=17.39 | val_top10=20.65
Epoch 15 | loss=0.0061 | val_top1=15.22 | val_top5=17.39 | val_top10=20.65
Epoch 16 | loss=0.0056 | val_top1=16.30 | val_top5=17.39 | val_top10=19.57
Epoch 17 | loss=0.0051 | val_top1=16.30 | val_top5=17.39 | val_top10=19.57
Epoch 18 | loss=0.0047 | val_top1=16.30 | val_top5=18.48 | val_top10=19.57
Epoch 19 | loss=0.0044 | val_top1=16.30 | val_top5=18.48 | val_top10=19.57
Epoch 20 | loss=0.0041 | val_top1=16.30 | val_top5=18.48 | val_top10=19.57

Best validation top1: 16.304347826086957
Test metrics: {'top1': 19.299781181619256, 'top5': 24.72647702407002, 'top10': 27.221006564551423}

================================================================================
[34/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0615 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 02 | loss=1.4225 | val_top1=9.78 | val_top5=9.78 | val_top10=11.96
Epoch 03 | loss=0.9672 | val_top1=8.70 | val_top5=11.96 | val_top10=13.04
Epoch 04 | loss=0.6655 | val_top1=11.96 | val_top5=11.96 | val_top10=14.13
Epoch 05 | loss=0.2757 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 06 | loss=0.1200 | val_top1=13.04 | val_top5=17.39 | val_top10=18.48
Epoch 07 | loss=0.0614 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 08 | loss=0.0202 | val_top1=14.13 | val_top5=18.48 | val_top10=18.48
Epoch 09 | loss=0.0130 | val_top1=14.13 | val_top5=18.48 | val_top10=18.48
Epoch 10 | loss=0.0108 | val_top1=15.22 | val_top5=18.48 | val_top10=18.48
Epoch 11 | loss=0.0093 | val_top1=15.22 | val_top5=18.48 | val_top10=18.48
Epoch 12 | loss=0.0083 | val_top1=15.22 | val_top5=18.48 | val_top10=18.48
Epoch 13 | loss=0.0074 | val_top1=15.22 | val_top5=18.48 | val_top10=18.48
Epoch 14 | loss=0.0067 | val_top1=15.22 | val_top5=16.30 | val_top10=18.48
Epoch 15 | loss=0.0061 | val_top1=15.22 | val_top5=16.30 | val_top10=18.48
Epoch 16 | loss=0.0056 | val_top1=15.22 | val_top5=16.30 | val_top10=18.48
Epoch 17 | loss=0.0051 | val_top1=14.13 | val_top5=16.30 | val_top10=18.48
Epoch 18 | loss=0.0047 | val_top1=14.13 | val_top5=16.30 | val_top10=18.48
Epoch 19 | loss=0.0044 | val_top1=14.13 | val_top5=16.30 | val_top10=18.48
Epoch 20 | loss=0.0041 | val_top1=14.13 | val_top5=16.30 | val_top10=18.48

Best validation top1: 15.217391304347826
Test metrics: {'top1': 16.455142231947484, 'top5': 21.925601750547045, 'top10': 24.463894967177243}

================================================================================
[35/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0576 | val_top1=11.96 | val_top5=11.96 | val_top10=16.30
Epoch 02 | loss=1.5854 | val_top1=10.87 | val_top5=13.04 | val_top10=13.04
Epoch 03 | loss=1.3033 | val_top1=10.87 | val_top5=11.96 | val_top10=13.04
Epoch 04 | loss=1.0794 | val_top1=10.87 | val_top5=11.96 | val_top10=11.96
Epoch 05 | loss=0.9019 | val_top1=11.96 | val_top5=11.96 | val_top10=13.04
Epoch 06 | loss=0.7621 | val_top1=11.96 | val_top5=11.96 | val_top10=13.04
Epoch 07 | loss=0.6499 | val_top1=11.96 | val_top5=11.96 | val_top10=13.04
Epoch 08 | loss=0.5575 | val_top1=11.96 | val_top5=11.96 | val_top10=13.04
Epoch 09 | loss=0.4802 | val_top1=11.96 | val_top5=13.04 | val_top10=14.13
Epoch 10 | loss=0.4151 | val_top1=11.96 | val_top5=13.04 | val_top10=14.13
Epoch 11 | loss=0.3601 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 12 | loss=0.3135 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 13 | loss=0.2739 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 14 | loss=0.2403 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 15 | loss=0.2117 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 16 | loss=0.1876 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 17 | loss=0.1672 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 18 | loss=0.1500 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 19 | loss=0.1353 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 20 | loss=0.1228 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.49890590809628, 'top5': 20.525164113785557, 'top10': 22.75711159737418}

================================================================================
[36/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9994 | val_top1=11.96 | val_top5=16.30 | val_top10=16.30
Epoch 02 | loss=1.5127 | val_top1=11.96 | val_top5=16.30 | val_top10=16.30
Epoch 03 | loss=1.1960 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 04 | loss=0.9540 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 05 | loss=0.7683 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 06 | loss=0.6236 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 07 | loss=0.5088 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 08 | loss=0.4171 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 09 | loss=0.3436 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 10 | loss=0.2849 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 11 | loss=0.2382 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 12 | loss=0.2011 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 13 | loss=0.1716 | val_top1=11.96 | val_top5=15.22 | val_top10=19.57
Epoch 14 | loss=0.1481 | val_top1=10.87 | val_top5=14.13 | val_top10=19.57
Epoch 15 | loss=0.1293 | val_top1=10.87 | val_top5=14.13 | val_top10=20.65
Epoch 16 | loss=0.1140 | val_top1=11.96 | val_top5=15.22 | val_top10=21.74
Epoch 17 | loss=0.1015 | val_top1=11.96 | val_top5=16.30 | val_top10=21.74
Epoch 18 | loss=0.0910 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 19 | loss=0.0821 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 20 | loss=0.0745 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.411378555798688, 'top5': 20.612691466083152, 'top10': 22.75711159737418}

================================================================================
[37/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9479 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 02 | loss=1.2067 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 03 | loss=0.7447 | val_top1=10.87 | val_top5=13.04 | val_top10=13.04
Epoch 04 | loss=0.3712 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 05 | loss=0.1602 | val_top1=13.04 | val_top5=15.22 | val_top10=18.48
Epoch 06 | loss=0.0767 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 07 | loss=0.0412 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 08 | loss=0.0263 | val_top1=14.13 | val_top5=18.48 | val_top10=19.57
Epoch 09 | loss=0.0205 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 10 | loss=0.0187 | val_top1=14.13 | val_top5=18.48 | val_top10=20.65
Epoch 11 | loss=0.0165 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 12 | loss=0.0139 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65
Epoch 13 | loss=0.0126 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 14 | loss=0.0113 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65
Epoch 15 | loss=0.0101 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 16 | loss=0.0092 | val_top1=13.04 | val_top5=18.48 | val_top10=21.74
Epoch 17 | loss=0.0089 | val_top1=13.04 | val_top5=17.39 | val_top10=20.65
Epoch 18 | loss=0.0081 | val_top1=15.22 | val_top5=17.39 | val_top10=20.65
Epoch 19 | loss=0.0075 | val_top1=13.04 | val_top5=17.39 | val_top10=20.65
Epoch 20 | loss=0.0071 | val_top1=13.04 | val_top5=17.39 | val_top10=21.74

Best validation top1: 15.217391304347826
Test metrics: {'top1': 18.38074398249453, 'top5': 23.23851203501094, 'top10': 24.857768052516413}

================================================================================
[38/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1135 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 02 | loss=1.5163 | val_top1=8.70 | val_top5=14.13 | val_top10=16.30
Epoch 03 | loss=1.0615 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 04 | loss=0.6478 | val_top1=11.96 | val_top5=11.96 | val_top10=13.04
Epoch 05 | loss=0.4070 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 06 | loss=0.2143 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 07 | loss=0.0921 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 08 | loss=0.0473 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 09 | loss=0.0275 | val_top1=13.04 | val_top5=17.39 | val_top10=18.48
Epoch 10 | loss=0.0213 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 11 | loss=0.0169 | val_top1=10.87 | val_top5=18.48 | val_top10=19.57
Epoch 12 | loss=0.0150 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 13 | loss=0.0131 | val_top1=9.78 | val_top5=17.39 | val_top10=19.57
Epoch 14 | loss=0.0115 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 15 | loss=0.0108 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 16 | loss=0.0098 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 17 | loss=0.0089 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 18 | loss=0.0081 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 19 | loss=0.0073 | val_top1=11.96 | val_top5=18.48 | val_top10=19.57
Epoch 20 | loss=0.0070 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57

Best validation top1: 13.043478260869565
Test metrics: {'top1': 15.492341356673961, 'top5': 20.306345733041574, 'top10': 22.975929978118163}

================================================================================
[39/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2662 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 02 | loss=1.8663 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 03 | loss=1.6790 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30
Epoch 04 | loss=1.5118 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30
Epoch 05 | loss=1.3510 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 06 | loss=1.2205 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 07 | loss=1.1281 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 08 | loss=1.0319 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 09 | loss=0.9360 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30
Epoch 10 | loss=0.8377 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 11 | loss=0.7677 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 12 | loss=0.7064 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 13 | loss=0.6460 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 14 | loss=0.5880 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 15 | loss=0.5334 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 16 | loss=0.4933 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 17 | loss=0.4636 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 18 | loss=0.4186 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 19 | loss=0.3804 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 20 | loss=0.3465 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.76148796498906, 'top5': 21.88183807439825, 'top10': 24.682713347921226}

================================================================================
[40/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1436 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 02 | loss=1.7794 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 03 | loss=1.5250 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 04 | loss=1.3336 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 05 | loss=1.1809 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 06 | loss=1.0007 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 07 | loss=0.9198 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 08 | loss=0.8015 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 09 | loss=0.7107 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 10 | loss=0.6505 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 11 | loss=0.5817 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 12 | loss=0.5366 | val_top1=9.78 | val_top5=13.04 | val_top10=17.39
Epoch 13 | loss=0.4726 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 14 | loss=0.4167 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 15 | loss=0.3760 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 16 | loss=0.3352 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 17 | loss=0.3166 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 18 | loss=0.2804 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 19 | loss=0.2558 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 20 | loss=0.2357 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30

Best validation top1: 10.869565217391305
Test metrics: {'top1': 16.673960612691467, 'top5': 20.175054704595187, 'top10': 22.713347921225385}

================================================================================
[41/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9688 | val_top1=8.70 | val_top5=10.87 | val_top10=13.04
Epoch 02 | loss=1.2675 | val_top1=9.78 | val_top5=10.87 | val_top10=11.96
Epoch 03 | loss=0.6653 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 04 | loss=0.2586 | val_top1=11.96 | val_top5=13.04 | val_top10=15.22
Epoch 05 | loss=0.0891 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 06 | loss=0.0308 | val_top1=13.04 | val_top5=17.39 | val_top10=20.65
Epoch 07 | loss=0.0160 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 08 | loss=0.0127 | val_top1=15.22 | val_top5=19.57 | val_top10=20.65
Epoch 09 | loss=0.0107 | val_top1=15.22 | val_top5=19.57 | val_top10=20.65
Epoch 10 | loss=0.0093 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 11 | loss=0.0082 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 12 | loss=0.0073 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 13 | loss=0.0066 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 14 | loss=0.0060 | val_top1=14.13 | val_top5=20.65 | val_top10=21.74
Epoch 15 | loss=0.0054 | val_top1=13.04 | val_top5=20.65 | val_top10=21.74
Epoch 16 | loss=0.0050 | val_top1=13.04 | val_top5=20.65 | val_top10=21.74
Epoch 17 | loss=0.0046 | val_top1=13.04 | val_top5=20.65 | val_top10=21.74
Epoch 18 | loss=0.0042 | val_top1=13.04 | val_top5=20.65 | val_top10=21.74
Epoch 19 | loss=0.0039 | val_top1=13.04 | val_top5=20.65 | val_top10=21.74
Epoch 20 | loss=0.0036 | val_top1=13.04 | val_top5=20.65 | val_top10=21.74

Best validation top1: 15.217391304347826
Test metrics: {'top1': 18.24945295404814, 'top5': 22.932166301969364, 'top10': 26.38949671772429}

================================================================================
[42/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1893 | val_top1=9.78 | val_top5=10.87 | val_top10=10.87
Epoch 02 | loss=1.6539 | val_top1=7.61 | val_top5=9.78 | val_top10=10.87
Epoch 03 | loss=1.2793 | val_top1=8.70 | val_top5=10.87 | val_top10=11.96
Epoch 04 | loss=0.9012 | val_top1=7.61 | val_top5=8.70 | val_top10=8.70
Epoch 05 | loss=0.7062 | val_top1=8.70 | val_top5=10.87 | val_top10=15.22
Epoch 06 | loss=0.3583 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 07 | loss=0.2001 | val_top1=8.70 | val_top5=13.04 | val_top10=16.30
Epoch 08 | loss=0.0666 | val_top1=8.70 | val_top5=10.87 | val_top10=16.30
Epoch 09 | loss=0.0256 | val_top1=7.61 | val_top5=15.22 | val_top10=16.30
Epoch 10 | loss=0.0149 | val_top1=8.70 | val_top5=14.13 | val_top10=16.30
Epoch 11 | loss=0.0122 | val_top1=7.61 | val_top5=14.13 | val_top10=16.30
Epoch 12 | loss=0.0106 | val_top1=7.61 | val_top5=14.13 | val_top10=16.30
Epoch 13 | loss=0.0093 | val_top1=7.61 | val_top5=14.13 | val_top10=16.30
Epoch 14 | loss=0.0084 | val_top1=7.61 | val_top5=14.13 | val_top10=15.22
Epoch 15 | loss=0.0076 | val_top1=7.61 | val_top5=14.13 | val_top10=15.22
Epoch 16 | loss=0.0069 | val_top1=7.61 | val_top5=14.13 | val_top10=15.22
Epoch 17 | loss=0.0063 | val_top1=7.61 | val_top5=14.13 | val_top10=15.22
Epoch 18 | loss=0.0058 | val_top1=8.70 | val_top5=15.22 | val_top10=15.22
Epoch 19 | loss=0.0054 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30
Epoch 20 | loss=0.0050 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30

Best validation top1: 9.782608695652174
Test metrics: {'top1': 13.435448577680525, 'top5': 16.10503282275711, 'top10': 17.98687089715536}

================================================================================
[43/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0326 | val_top1=11.96 | val_top5=15.22 | val_top10=20.65
Epoch 02 | loss=1.5568 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 03 | loss=1.2534 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 04 | loss=1.0190 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 05 | loss=0.8372 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30
Epoch 06 | loss=0.6939 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 07 | loss=0.5785 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 08 | loss=0.4843 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 09 | loss=0.4071 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 10 | loss=0.3437 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 11 | loss=0.2918 | val_top1=10.87 | val_top5=17.39 | val_top10=17.39
Epoch 12 | loss=0.2494 | val_top1=10.87 | val_top5=17.39 | val_top10=17.39
Epoch 13 | loss=0.2148 | val_top1=10.87 | val_top5=17.39 | val_top10=17.39
Epoch 14 | loss=0.1865 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 15 | loss=0.1634 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 16 | loss=0.1444 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 17 | loss=0.1287 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 18 | loss=0.1155 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 19 | loss=0.1044 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 20 | loss=0.0950 | val_top1=10.87 | val_top5=17.39 | val_top10=19.57

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.542669584245075, 'top5': 20.48140043763676, 'top10': 23.50109409190372}

================================================================================
[44/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9360 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 02 | loss=1.4209 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 03 | loss=1.0762 | val_top1=10.87 | val_top5=11.96 | val_top10=17.39
Epoch 04 | loss=0.8194 | val_top1=10.87 | val_top5=11.96 | val_top10=17.39
Epoch 05 | loss=0.6281 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 06 | loss=0.4872 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 07 | loss=0.3822 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 08 | loss=0.3028 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 09 | loss=0.2427 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 10 | loss=0.1971 | val_top1=11.96 | val_top5=14.13 | val_top10=18.48
Epoch 11 | loss=0.1625 | val_top1=11.96 | val_top5=14.13 | val_top10=20.65
Epoch 12 | loss=0.1361 | val_top1=11.96 | val_top5=14.13 | val_top10=20.65
Epoch 13 | loss=0.1159 | val_top1=11.96 | val_top5=15.22 | val_top10=19.57
Epoch 14 | loss=0.1001 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 15 | loss=0.0876 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 16 | loss=0.0775 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 17 | loss=0.0692 | val_top1=11.96 | val_top5=17.39 | val_top10=21.74
Epoch 18 | loss=0.0623 | val_top1=11.96 | val_top5=17.39 | val_top10=21.74
Epoch 19 | loss=0.0564 | val_top1=11.96 | val_top5=17.39 | val_top10=21.74
Epoch 20 | loss=0.0514 | val_top1=11.96 | val_top5=18.48 | val_top10=21.74

Best validation top1: 11.956521739130435
Test metrics: {'top1': 17.37417943107221, 'top5': 21.794310722100658, 'top10': 25.25164113785558}

================================================================================
[45/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9687 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 02 | loss=1.2701 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 03 | loss=0.7308 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 04 | loss=0.3884 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 05 | loss=0.1878 | val_top1=14.13 | val_top5=18.48 | val_top10=21.74
Epoch 06 | loss=0.0808 | val_top1=13.04 | val_top5=21.74 | val_top10=22.83
Epoch 07 | loss=0.0360 | val_top1=14.13 | val_top5=21.74 | val_top10=21.74
Epoch 08 | loss=0.0245 | val_top1=11.96 | val_top5=21.74 | val_top10=22.83
Epoch 09 | loss=0.0189 | val_top1=11.96 | val_top5=21.74 | val_top10=22.83
Epoch 10 | loss=0.0169 | val_top1=14.13 | val_top5=22.83 | val_top10=22.83
Epoch 11 | loss=0.0148 | val_top1=16.30 | val_top5=22.83 | val_top10=22.83
Epoch 12 | loss=0.0134 | val_top1=14.13 | val_top5=21.74 | val_top10=23.91
Epoch 13 | loss=0.0120 | val_top1=15.22 | val_top5=21.74 | val_top10=22.83
Epoch 14 | loss=0.0114 | val_top1=15.22 | val_top5=21.74 | val_top10=22.83
Epoch 15 | loss=0.0097 | val_top1=17.39 | val_top5=20.65 | val_top10=22.83
Epoch 16 | loss=0.0089 | val_top1=16.30 | val_top5=21.74 | val_top10=23.91
Epoch 17 | loss=0.0083 | val_top1=17.39 | val_top5=20.65 | val_top10=21.74
Epoch 18 | loss=0.0076 | val_top1=17.39 | val_top5=20.65 | val_top10=22.83
Epoch 19 | loss=0.0069 | val_top1=17.39 | val_top5=20.65 | val_top10=22.83
Epoch 20 | loss=0.0063 | val_top1=17.39 | val_top5=19.57 | val_top10=23.91

Best validation top1: 17.391304347826086
Test metrics: {'top1': 17.63676148796499, 'top5': 22.36323851203501, 'top10': 25.032822757111596}

================================================================================
[46/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0936 | val_top1=7.61 | val_top5=9.78 | val_top10=9.78
Epoch 02 | loss=1.5012 | val_top1=9.78 | val_top5=9.78 | val_top10=10.87
Epoch 03 | loss=1.1603 | val_top1=9.78 | val_top5=9.78 | val_top10=9.78
Epoch 04 | loss=0.7430 | val_top1=9.78 | val_top5=9.78 | val_top10=11.96
Epoch 05 | loss=0.4786 | val_top1=10.87 | val_top5=13.04 | val_top10=13.04
Epoch 06 | loss=0.2514 | val_top1=9.78 | val_top5=11.96 | val_top10=16.30
Epoch 07 | loss=0.1369 | val_top1=9.78 | val_top5=10.87 | val_top10=13.04
Epoch 08 | loss=0.0616 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 09 | loss=0.0295 | val_top1=10.87 | val_top5=11.96 | val_top10=16.30
Epoch 10 | loss=0.0212 | val_top1=9.78 | val_top5=13.04 | val_top10=17.39
Epoch 11 | loss=0.0169 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 12 | loss=0.0139 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 13 | loss=0.0121 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 14 | loss=0.0106 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 15 | loss=0.0099 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 16 | loss=0.0088 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 17 | loss=0.0082 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 18 | loss=0.0075 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 19 | loss=0.0070 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 20 | loss=0.0065 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39

Best validation top1: 11.956521739130435
Test metrics: {'top1': 15.842450765864333, 'top5': 20.919037199124727, 'top10': 23.194748358862146}

================================================================================
[47/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1361 | val_top1=8.70 | val_top5=14.13 | val_top10=17.39
Epoch 02 | loss=1.7805 | val_top1=9.78 | val_top5=16.30 | val_top10=17.39
Epoch 03 | loss=1.6007 | val_top1=9.78 | val_top5=13.04 | val_top10=17.39
Epoch 04 | loss=1.4155 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 05 | loss=1.2552 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 06 | loss=1.1320 | val_top1=11.96 | val_top5=14.13 | val_top10=18.48
Epoch 07 | loss=1.0048 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 08 | loss=0.9269 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 09 | loss=0.8106 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 10 | loss=0.7286 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 11 | loss=0.6751 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 12 | loss=0.5784 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 13 | loss=0.5343 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 14 | loss=0.4892 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 15 | loss=0.4484 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 16 | loss=0.4000 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 17 | loss=0.3570 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 18 | loss=0.3416 | val_top1=11.96 | val_top5=15.22 | val_top10=19.57
Epoch 19 | loss=0.2885 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 20 | loss=0.2856 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.367614879649892, 'top5': 21.794310722100658, 'top10': 23.807439824945295}

================================================================================
[48/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1393 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 02 | loss=1.7179 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 03 | loss=1.4645 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 04 | loss=1.2623 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 05 | loss=1.0939 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 06 | loss=0.9681 | val_top1=11.96 | val_top5=14.13 | val_top10=14.13
Epoch 07 | loss=0.8148 | val_top1=11.96 | val_top5=14.13 | val_top10=14.13
Epoch 08 | loss=0.7235 | val_top1=11.96 | val_top5=13.04 | val_top10=14.13
Epoch 09 | loss=0.6393 | val_top1=11.96 | val_top5=13.04 | val_top10=13.04
Epoch 10 | loss=0.5702 | val_top1=11.96 | val_top5=13.04 | val_top10=13.04
Epoch 11 | loss=0.5092 | val_top1=11.96 | val_top5=13.04 | val_top10=13.04
Epoch 12 | loss=0.4353 | val_top1=11.96 | val_top5=13.04 | val_top10=14.13
Epoch 13 | loss=0.3973 | val_top1=11.96 | val_top5=13.04 | val_top10=13.04
Epoch 14 | loss=0.3486 | val_top1=11.96 | val_top5=13.04 | val_top10=15.22
Epoch 15 | loss=0.3151 | val_top1=11.96 | val_top5=13.04 | val_top10=15.22
Epoch 16 | loss=0.2734 | val_top1=11.96 | val_top5=13.04 | val_top10=15.22
Epoch 17 | loss=0.2493 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 18 | loss=0.2245 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39
Epoch 19 | loss=0.2070 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39
Epoch 20 | loss=0.1817 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.805251641137854, 'top5': 21.53172866520788, 'top10': 23.676148796498907}

================================================================================
[49/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.8989 | val_top1=9.78 | val_top5=10.87 | val_top10=11.96
Epoch 02 | loss=1.1034 | val_top1=10.87 | val_top5=11.96 | val_top10=15.22
Epoch 03 | loss=0.5382 | val_top1=9.78 | val_top5=11.96 | val_top10=11.96
Epoch 04 | loss=0.1871 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 05 | loss=0.0491 | val_top1=8.70 | val_top5=15.22 | val_top10=17.39
Epoch 06 | loss=0.0215 | val_top1=8.70 | val_top5=16.30 | val_top10=19.57
Epoch 07 | loss=0.0157 | val_top1=9.78 | val_top5=16.30 | val_top10=19.57
Epoch 08 | loss=0.0131 | val_top1=9.78 | val_top5=17.39 | val_top10=20.65
Epoch 09 | loss=0.0113 | val_top1=9.78 | val_top5=17.39 | val_top10=20.65
Epoch 10 | loss=0.0099 | val_top1=9.78 | val_top5=17.39 | val_top10=20.65
Epoch 11 | loss=0.0087 | val_top1=9.78 | val_top5=18.48 | val_top10=20.65
Epoch 12 | loss=0.0078 | val_top1=9.78 | val_top5=18.48 | val_top10=20.65
Epoch 13 | loss=0.0070 | val_top1=9.78 | val_top5=19.57 | val_top10=20.65
Epoch 14 | loss=0.0064 | val_top1=9.78 | val_top5=19.57 | val_top10=20.65
Epoch 15 | loss=0.0058 | val_top1=9.78 | val_top5=20.65 | val_top10=21.74
Epoch 16 | loss=0.0053 | val_top1=10.87 | val_top5=20.65 | val_top10=21.74
Epoch 17 | loss=0.0049 | val_top1=10.87 | val_top5=20.65 | val_top10=21.74
Epoch 18 | loss=0.0045 | val_top1=11.96 | val_top5=20.65 | val_top10=21.74
Epoch 19 | loss=0.0042 | val_top1=13.04 | val_top5=20.65 | val_top10=21.74
Epoch 20 | loss=0.0039 | val_top1=14.13 | val_top5=20.65 | val_top10=21.74

Best validation top1: 14.130434782608695
Test metrics: {'top1': 18.730853391684903, 'top5': 24.50765864332604, 'top10': 27.045951859956237}

================================================================================
[50/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0451 | val_top1=9.78 | val_top5=10.87 | val_top10=14.13
Epoch 02 | loss=1.4415 | val_top1=9.78 | val_top5=10.87 | val_top10=13.04
Epoch 03 | loss=0.9796 | val_top1=11.96 | val_top5=14.13 | val_top10=14.13
Epoch 04 | loss=0.5372 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 05 | loss=0.2586 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 06 | loss=0.0774 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 07 | loss=0.0288 | val_top1=11.96 | val_top5=15.22 | val_top10=19.57
Epoch 08 | loss=0.0151 | val_top1=11.96 | val_top5=17.39 | val_top10=21.74
Epoch 09 | loss=0.0121 | val_top1=11.96 | val_top5=18.48 | val_top10=21.74
Epoch 10 | loss=0.0104 | val_top1=11.96 | val_top5=18.48 | val_top10=21.74
Epoch 11 | loss=0.0091 | val_top1=11.96 | val_top5=18.48 | val_top10=21.74
Epoch 12 | loss=0.0081 | val_top1=11.96 | val_top5=19.57 | val_top10=21.74
Epoch 13 | loss=0.0073 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 14 | loss=0.0066 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 15 | loss=0.0061 | val_top1=13.04 | val_top5=20.65 | val_top10=21.74
Epoch 16 | loss=0.0055 | val_top1=13.04 | val_top5=21.74 | val_top10=21.74
Epoch 17 | loss=0.0051 | val_top1=13.04 | val_top5=21.74 | val_top10=21.74
Epoch 18 | loss=0.0047 | val_top1=15.22 | val_top5=20.65 | val_top10=21.74
Epoch 19 | loss=0.0044 | val_top1=16.30 | val_top5=20.65 | val_top10=21.74
Epoch 20 | loss=0.0041 | val_top1=16.30 | val_top5=20.65 | val_top10=21.74

Best validation top1: 16.304347826086957
Test metrics: {'top1': 17.505470459518598, 'top5': 22.319474835886215, 'top10': 24.63894967177243}

================================================================================
[51/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0710 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 02 | loss=1.5855 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 03 | loss=1.2842 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 04 | loss=1.0516 | val_top1=11.96 | val_top5=16.30 | val_top10=16.30
Epoch 05 | loss=0.8725 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 06 | loss=0.7331 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 07 | loss=0.6222 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 08 | loss=0.5320 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 09 | loss=0.4573 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 10 | loss=0.3949 | val_top1=10.87 | val_top5=17.39 | val_top10=17.39
Epoch 11 | loss=0.3425 | val_top1=10.87 | val_top5=17.39 | val_top10=17.39
Epoch 12 | loss=0.2983 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 13 | loss=0.2611 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 14 | loss=0.2298 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 15 | loss=0.2034 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 16 | loss=0.1809 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 17 | loss=0.1619 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 18 | loss=0.1456 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 19 | loss=0.1317 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 20 | loss=0.1198 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39

Best validation top1: 11.956521739130435
Test metrics: {'top1': 17.111597374179432, 'top5': 21.88183807439825, 'top10': 24.11378555798687}

================================================================================
[52/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9779 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 02 | loss=1.4895 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 03 | loss=1.1687 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 04 | loss=0.9224 | val_top1=13.04 | val_top5=14.13 | val_top10=15.22
Epoch 05 | loss=0.7348 | val_top1=13.04 | val_top5=14.13 | val_top10=14.13
Epoch 06 | loss=0.5921 | val_top1=13.04 | val_top5=13.04 | val_top10=14.13
Epoch 07 | loss=0.4824 | val_top1=13.04 | val_top5=13.04 | val_top10=14.13
Epoch 08 | loss=0.3965 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 09 | loss=0.3282 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 10 | loss=0.2736 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 11 | loss=0.2299 | val_top1=11.96 | val_top5=11.96 | val_top10=17.39
Epoch 12 | loss=0.1951 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39
Epoch 13 | loss=0.1670 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 14 | loss=0.1443 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 15 | loss=0.1259 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 16 | loss=0.1109 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 17 | loss=0.0985 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 18 | loss=0.0883 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 19 | loss=0.0798 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 20 | loss=0.0724 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39

Best validation top1: 13.043478260869565
Test metrics: {'top1': 17.199124726477024, 'top5': 21.663019693654267, 'top10': 24.026258205689278}

================================================================================
[53/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9418 | val_top1=9.78 | val_top5=9.78 | val_top10=10.87
Epoch 02 | loss=1.2119 | val_top1=8.70 | val_top5=10.87 | val_top10=11.96
Epoch 03 | loss=0.7034 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 04 | loss=0.3205 | val_top1=10.87 | val_top5=11.96 | val_top10=15.22
Epoch 05 | loss=0.1434 | val_top1=10.87 | val_top5=13.04 | val_top10=18.48
Epoch 06 | loss=0.0620 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 07 | loss=0.0338 | val_top1=10.87 | val_top5=15.22 | val_top10=20.65
Epoch 08 | loss=0.0247 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 09 | loss=0.0212 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 10 | loss=0.0179 | val_top1=13.04 | val_top5=16.30 | val_top10=19.57
Epoch 11 | loss=0.0149 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 12 | loss=0.0134 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 13 | loss=0.0118 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 14 | loss=0.0109 | val_top1=11.96 | val_top5=19.57 | val_top10=19.57
Epoch 15 | loss=0.0096 | val_top1=11.96 | val_top5=19.57 | val_top10=19.57
Epoch 16 | loss=0.0090 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65
Epoch 17 | loss=0.0081 | val_top1=11.96 | val_top5=19.57 | val_top10=20.65
Epoch 18 | loss=0.0077 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 19 | loss=0.0069 | val_top1=14.13 | val_top5=18.48 | val_top10=20.65
Epoch 20 | loss=0.0065 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65

Best validation top1: 14.130434782608695
Test metrics: {'top1': 18.51203501094092, 'top5': 23.01969365426696, 'top10': 25.164113785557987}

================================================================================
[54/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0137 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 02 | loss=1.4751 | val_top1=8.70 | val_top5=10.87 | val_top10=11.96
Epoch 03 | loss=1.0681 | val_top1=8.70 | val_top5=13.04 | val_top10=15.22
Epoch 04 | loss=0.6135 | val_top1=8.70 | val_top5=11.96 | val_top10=15.22
Epoch 05 | loss=0.3902 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 06 | loss=0.2305 | val_top1=8.70 | val_top5=13.04 | val_top10=14.13
Epoch 07 | loss=0.0986 | val_top1=8.70 | val_top5=11.96 | val_top10=14.13
Epoch 08 | loss=0.0396 | val_top1=8.70 | val_top5=11.96 | val_top10=13.04
Epoch 09 | loss=0.0230 | val_top1=8.70 | val_top5=13.04 | val_top10=14.13
Epoch 10 | loss=0.0174 | val_top1=8.70 | val_top5=13.04 | val_top10=15.22
Epoch 11 | loss=0.0147 | val_top1=8.70 | val_top5=14.13 | val_top10=15.22
Epoch 12 | loss=0.0136 | val_top1=8.70 | val_top5=13.04 | val_top10=15.22
Epoch 13 | loss=0.0119 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 14 | loss=0.0105 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 15 | loss=0.0095 | val_top1=9.78 | val_top5=15.22 | val_top10=15.22
Epoch 16 | loss=0.0087 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 17 | loss=0.0079 | val_top1=9.78 | val_top5=15.22 | val_top10=15.22
Epoch 18 | loss=0.0073 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 19 | loss=0.0069 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 20 | loss=0.0064 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22

Best validation top1: 9.782608695652174
Test metrics: {'top1': 13.916849015317286, 'top5': 17.024070021881837, 'top10': 18.643326039387308}

================================================================================
[55/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2401 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 02 | loss=1.8572 | val_top1=9.78 | val_top5=16.30 | val_top10=18.48
Epoch 03 | loss=1.6443 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 04 | loss=1.4855 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 05 | loss=1.3432 | val_top1=9.78 | val_top5=16.30 | val_top10=18.48
Epoch 06 | loss=1.2164 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 07 | loss=1.1002 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 08 | loss=0.9985 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 09 | loss=0.9105 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 10 | loss=0.8255 | val_top1=10.87 | val_top5=17.39 | val_top10=17.39
Epoch 11 | loss=0.7449 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 12 | loss=0.6944 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 13 | loss=0.6272 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 14 | loss=0.5734 | val_top1=9.78 | val_top5=16.30 | val_top10=18.48
Epoch 15 | loss=0.5178 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 16 | loss=0.4778 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 17 | loss=0.4375 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 18 | loss=0.4130 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 19 | loss=0.3707 | val_top1=9.78 | val_top5=17.39 | val_top10=18.48
Epoch 20 | loss=0.3345 | val_top1=9.78 | val_top5=17.39 | val_top10=18.48

Best validation top1: 10.869565217391305
Test metrics: {'top1': 16.10503282275711, 'top5': 19.91247264770241, 'top10': 22.494529540481402}

================================================================================
[56/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1398 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 02 | loss=1.7441 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 03 | loss=1.4579 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 04 | loss=1.2729 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 05 | loss=1.0975 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 06 | loss=0.9914 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 07 | loss=0.8518 | val_top1=9.78 | val_top5=13.04 | val_top10=16.30
Epoch 08 | loss=0.7719 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 09 | loss=0.6712 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 10 | loss=0.6017 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 11 | loss=0.5221 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 12 | loss=0.4815 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 13 | loss=0.4177 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 14 | loss=0.3876 | val_top1=9.78 | val_top5=16.30 | val_top10=18.48
Epoch 15 | loss=0.3517 | val_top1=9.78 | val_top5=17.39 | val_top10=18.48
Epoch 16 | loss=0.3102 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 17 | loss=0.2848 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 18 | loss=0.2657 | val_top1=11.96 | val_top5=17.39 | val_top10=17.39
Epoch 19 | loss=0.2374 | val_top1=11.96 | val_top5=17.39 | val_top10=17.39
Epoch 20 | loss=0.2142 | val_top1=11.96 | val_top5=17.39 | val_top10=17.39

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.01750547045952, 'top5': 21.48796498905908, 'top10': 24.15754923413567}

================================================================================
[57/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9539 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 02 | loss=1.2263 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 03 | loss=0.6107 | val_top1=10.87 | val_top5=10.87 | val_top10=13.04
Epoch 04 | loss=0.2221 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 05 | loss=0.0866 | val_top1=11.96 | val_top5=16.30 | val_top10=21.74
Epoch 06 | loss=0.0292 | val_top1=11.96 | val_top5=19.57 | val_top10=22.83
Epoch 07 | loss=0.0146 | val_top1=11.96 | val_top5=19.57 | val_top10=20.65
Epoch 08 | loss=0.0118 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65
Epoch 09 | loss=0.0101 | val_top1=11.96 | val_top5=19.57 | val_top10=21.74
Epoch 10 | loss=0.0089 | val_top1=13.04 | val_top5=19.57 | val_top10=22.83
Epoch 11 | loss=0.0079 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 12 | loss=0.0071 | val_top1=13.04 | val_top5=19.57 | val_top10=22.83
Epoch 13 | loss=0.0064 | val_top1=13.04 | val_top5=18.48 | val_top10=23.91
Epoch 14 | loss=0.0058 | val_top1=13.04 | val_top5=19.57 | val_top10=23.91
Epoch 15 | loss=0.0053 | val_top1=13.04 | val_top5=20.65 | val_top10=23.91
Epoch 16 | loss=0.0049 | val_top1=13.04 | val_top5=20.65 | val_top10=23.91
Epoch 17 | loss=0.0045 | val_top1=14.13 | val_top5=20.65 | val_top10=22.83
Epoch 18 | loss=0.0041 | val_top1=14.13 | val_top5=20.65 | val_top10=22.83
Epoch 19 | loss=0.0038 | val_top1=14.13 | val_top5=20.65 | val_top10=22.83
Epoch 20 | loss=0.0036 | val_top1=14.13 | val_top5=20.65 | val_top10=22.83

Best validation top1: 14.130434782608695
Test metrics: {'top1': 19.387308533916848, 'top5': 24.24507658643326, 'top10': 26.433260393873084}

================================================================================
[58/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1144 | val_top1=8.70 | val_top5=9.78 | val_top10=11.96
Epoch 02 | loss=1.6048 | val_top1=8.70 | val_top5=10.87 | val_top10=10.87
Epoch 03 | loss=1.1891 | val_top1=8.70 | val_top5=9.78 | val_top10=11.96
Epoch 04 | loss=0.7680 | val_top1=8.70 | val_top5=9.78 | val_top10=11.96
Epoch 05 | loss=0.4874 | val_top1=8.70 | val_top5=11.96 | val_top10=14.13
Epoch 06 | loss=0.2106 | val_top1=11.96 | val_top5=13.04 | val_top10=13.04
Epoch 07 | loss=0.1080 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 08 | loss=0.0322 | val_top1=14.13 | val_top5=15.22 | val_top10=18.48
Epoch 09 | loss=0.0137 | val_top1=14.13 | val_top5=16.30 | val_top10=16.30
Epoch 10 | loss=0.0107 | val_top1=13.04 | val_top5=16.30 | val_top10=16.30
Epoch 11 | loss=0.0092 | val_top1=13.04 | val_top5=16.30 | val_top10=17.39
Epoch 12 | loss=0.0081 | val_top1=14.13 | val_top5=16.30 | val_top10=17.39
Epoch 13 | loss=0.0072 | val_top1=14.13 | val_top5=16.30 | val_top10=17.39
Epoch 14 | loss=0.0065 | val_top1=14.13 | val_top5=16.30 | val_top10=17.39
Epoch 15 | loss=0.0059 | val_top1=14.13 | val_top5=16.30 | val_top10=18.48
Epoch 16 | loss=0.0054 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 17 | loss=0.0050 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 18 | loss=0.0046 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 19 | loss=0.0043 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 20 | loss=0.0040 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57

Best validation top1: 14.130434782608695
Test metrics: {'top1': 15.448577680525164, 'top5': 20.26258205689278, 'top10': 23.326039387308533}

================================================================================
[59/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0070 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 02 | loss=1.5287 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 03 | loss=1.2158 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30
Epoch 04 | loss=0.9731 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30
Epoch 05 | loss=0.7889 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 06 | loss=0.6475 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 07 | loss=0.5365 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 08 | loss=0.4480 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 09 | loss=0.3766 | val_top1=9.78 | val_top5=16.30 | val_top10=19.57
Epoch 10 | loss=0.3188 | val_top1=9.78 | val_top5=17.39 | val_top10=21.74
Epoch 11 | loss=0.2717 | val_top1=9.78 | val_top5=17.39 | val_top10=21.74
Epoch 12 | loss=0.2334 | val_top1=9.78 | val_top5=17.39 | val_top10=20.65
Epoch 13 | loss=0.2019 | val_top1=9.78 | val_top5=18.48 | val_top10=20.65
Epoch 14 | loss=0.1760 | val_top1=9.78 | val_top5=18.48 | val_top10=20.65
Epoch 15 | loss=0.1546 | val_top1=9.78 | val_top5=18.48 | val_top10=20.65
Epoch 16 | loss=0.1370 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65
Epoch 17 | loss=0.1224 | val_top1=10.87 | val_top5=18.48 | val_top10=21.74
Epoch 18 | loss=0.1101 | val_top1=10.87 | val_top5=18.48 | val_top10=22.83
Epoch 19 | loss=0.0998 | val_top1=10.87 | val_top5=18.48 | val_top10=23.91
Epoch 20 | loss=0.0910 | val_top1=10.87 | val_top5=17.39 | val_top10=23.91

Best validation top1: 11.956521739130435
Test metrics: {'top1': 17.024070021881837, 'top5': 20.962800875273523, 'top10': 22.888402625820568}

================================================================================
[60/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9995 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 02 | loss=1.4403 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 03 | loss=1.0686 | val_top1=10.87 | val_top5=13.04 | val_top10=18.48
Epoch 04 | loss=0.8016 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 05 | loss=0.6103 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 06 | loss=0.4708 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 07 | loss=0.3670 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 08 | loss=0.2894 | val_top1=10.87 | val_top5=17.39 | val_top10=19.57
Epoch 09 | loss=0.2314 | val_top1=10.87 | val_top5=18.48 | val_top10=19.57
Epoch 10 | loss=0.1881 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65
Epoch 11 | loss=0.1558 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65
Epoch 12 | loss=0.1314 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65
Epoch 13 | loss=0.1127 | val_top1=10.87 | val_top5=19.57 | val_top10=20.65
Epoch 14 | loss=0.0981 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65
Epoch 15 | loss=0.0863 | val_top1=10.87 | val_top5=19.57 | val_top10=20.65
Epoch 16 | loss=0.0768 | val_top1=10.87 | val_top5=19.57 | val_top10=20.65
Epoch 17 | loss=0.0688 | val_top1=11.96 | val_top5=19.57 | val_top10=20.65
Epoch 18 | loss=0.0621 | val_top1=11.96 | val_top5=19.57 | val_top10=20.65
Epoch 19 | loss=0.0564 | val_top1=11.96 | val_top5=19.57 | val_top10=20.65
Epoch 20 | loss=0.0515 | val_top1=11.96 | val_top5=19.57 | val_top10=20.65

Best validation top1: 11.956521739130435
Test metrics: {'top1': 17.024070021881837, 'top5': 24.11378555798687, 'top10': 26.433260393873084}

================================================================================
[61/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9843 | val_top1=10.87 | val_top5=13.04 | val_top10=13.04
Epoch 02 | loss=1.2611 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 03 | loss=0.7869 | val_top1=10.87 | val_top5=11.96 | val_top10=13.04
Epoch 04 | loss=0.3976 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 05 | loss=0.1815 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 06 | loss=0.0750 | val_top1=8.70 | val_top5=14.13 | val_top10=15.22
Epoch 07 | loss=0.0389 | val_top1=9.78 | val_top5=16.30 | val_top10=17.39
Epoch 08 | loss=0.0244 | val_top1=9.78 | val_top5=16.30 | val_top10=17.39
Epoch 09 | loss=0.0187 | val_top1=8.70 | val_top5=16.30 | val_top10=17.39
Epoch 10 | loss=0.0163 | val_top1=9.78 | val_top5=16.30 | val_top10=17.39
Epoch 11 | loss=0.0144 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 12 | loss=0.0122 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 13 | loss=0.0116 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 14 | loss=0.0101 | val_top1=10.87 | val_top5=18.48 | val_top10=18.48
Epoch 15 | loss=0.0093 | val_top1=11.96 | val_top5=18.48 | val_top10=18.48
Epoch 16 | loss=0.0085 | val_top1=13.04 | val_top5=18.48 | val_top10=18.48
Epoch 17 | loss=0.0079 | val_top1=13.04 | val_top5=18.48 | val_top10=18.48
Epoch 18 | loss=0.0071 | val_top1=14.13 | val_top5=17.39 | val_top10=18.48
Epoch 19 | loss=0.0065 | val_top1=14.13 | val_top5=17.39 | val_top10=18.48
Epoch 20 | loss=0.0061 | val_top1=14.13 | val_top5=17.39 | val_top10=18.48

Best validation top1: 14.130434782608695
Test metrics: {'top1': 18.336980306345733, 'top5': 22.888402625820568, 'top10': 25.164113785557987}

================================================================================
[62/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1322 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 02 | loss=1.5666 | val_top1=9.78 | val_top5=10.87 | val_top10=11.96
Epoch 03 | loss=1.1786 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 04 | loss=0.7931 | val_top1=13.04 | val_top5=13.04 | val_top10=14.13
Epoch 05 | loss=0.4078 | val_top1=11.96 | val_top5=13.04 | val_top10=13.04
Epoch 06 | loss=0.2311 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 07 | loss=0.1308 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 08 | loss=0.0693 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 09 | loss=0.0291 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 10 | loss=0.0183 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 11 | loss=0.0145 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 12 | loss=0.0132 | val_top1=11.96 | val_top5=15.22 | val_top10=19.57
Epoch 13 | loss=0.0114 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 14 | loss=0.0103 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 15 | loss=0.0088 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 16 | loss=0.0086 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 17 | loss=0.0077 | val_top1=10.87 | val_top5=17.39 | val_top10=19.57
Epoch 18 | loss=0.0071 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 19 | loss=0.0066 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 20 | loss=0.0063 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65

Best validation top1: 13.043478260869565
Test metrics: {'top1': 13.172866520787746, 'top5': 16.805251641137854, 'top10': 18.905908096280086}

================================================================================
[63/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2303 | val_top1=10.87 | val_top5=11.96 | val_top10=16.30
Epoch 02 | loss=1.8334 | val_top1=9.78 | val_top5=10.87 | val_top10=16.30
Epoch 03 | loss=1.5761 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 04 | loss=1.4108 | val_top1=10.87 | val_top5=13.04 | val_top10=13.04
Epoch 05 | loss=1.2537 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 06 | loss=1.1258 | val_top1=10.87 | val_top5=13.04 | val_top10=13.04
Epoch 07 | loss=1.0105 | val_top1=10.87 | val_top5=13.04 | val_top10=13.04
Epoch 08 | loss=0.9039 | val_top1=10.87 | val_top5=13.04 | val_top10=13.04
Epoch 09 | loss=0.7827 | val_top1=10.87 | val_top5=13.04 | val_top10=13.04
Epoch 10 | loss=0.7172 | val_top1=10.87 | val_top5=13.04 | val_top10=13.04
Epoch 11 | loss=0.6411 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 12 | loss=0.5804 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 13 | loss=0.5299 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 14 | loss=0.4761 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 15 | loss=0.4150 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 16 | loss=0.3874 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 17 | loss=0.3513 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 18 | loss=0.3209 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 19 | loss=0.2886 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 20 | loss=0.2693 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30

Best validation top1: 10.869565217391305
Test metrics: {'top1': 16.280087527352297, 'top5': 20.0, 'top10': 22.27571115973742}

================================================================================
[64/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1428 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 02 | loss=1.7140 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 03 | loss=1.4328 | val_top1=9.78 | val_top5=13.04 | val_top10=16.30
Epoch 04 | loss=1.2306 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 05 | loss=1.0652 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 06 | loss=0.9253 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 07 | loss=0.7880 | val_top1=10.87 | val_top5=11.96 | val_top10=16.30
Epoch 08 | loss=0.6970 | val_top1=10.87 | val_top5=11.96 | val_top10=15.22
Epoch 09 | loss=0.6144 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 10 | loss=0.5222 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 11 | loss=0.4781 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 12 | loss=0.4163 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 13 | loss=0.3709 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 14 | loss=0.3312 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 15 | loss=0.2989 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 16 | loss=0.2636 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 17 | loss=0.2294 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 18 | loss=0.2092 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 19 | loss=0.1868 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 20 | loss=0.1743 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.849015317286653, 'top5': 22.100656455142232, 'top10': 24.770240700218817}

================================================================================
Running seed: 2024

================================================================================
[1/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.8757 | val_top1=9.78 | val_top5=11.96 | val_top10=11.96
Epoch 02 | loss=1.0105 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 03 | loss=0.4954 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 04 | loss=0.2007 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 05 | loss=0.0715 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 06 | loss=0.0399 | val_top1=10.87 | val_top5=17.39 | val_top10=20.65
Epoch 07 | loss=0.0298 | val_top1=10.87 | val_top5=17.39 | val_top10=20.65
Epoch 08 | loss=0.0245 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65
Epoch 09 | loss=0.0209 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 10 | loss=0.0181 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 11 | loss=0.0159 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 12 | loss=0.0141 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 13 | loss=0.0126 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 14 | loss=0.0113 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 15 | loss=0.0103 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 16 | loss=0.0094 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 17 | loss=0.0086 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 18 | loss=0.0079 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 19 | loss=0.0073 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 20 | loss=0.0067 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65

Best validation top1: 13.043478260869565
Test metrics: {'top1': 17.855579868708972, 'top5': 24.11378555798687, 'top10': 26.477024070021884}

================================================================================
[2/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0053 | val_top1=9.78 | val_top5=10.87 | val_top10=13.04
Epoch 02 | loss=1.2425 | val_top1=9.78 | val_top5=10.87 | val_top10=13.04
Epoch 03 | loss=0.7105 | val_top1=10.87 | val_top5=11.96 | val_top10=13.04
Epoch 04 | loss=0.3677 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 05 | loss=0.1565 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 06 | loss=0.0620 | val_top1=13.04 | val_top5=16.30 | val_top10=18.48
Epoch 07 | loss=0.0329 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 08 | loss=0.0229 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 09 | loss=0.0190 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 10 | loss=0.0162 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 11 | loss=0.0141 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 12 | loss=0.0125 | val_top1=11.96 | val_top5=19.57 | val_top10=20.65
Epoch 13 | loss=0.0111 | val_top1=11.96 | val_top5=19.57 | val_top10=20.65
Epoch 14 | loss=0.0100 | val_top1=11.96 | val_top5=19.57 | val_top10=19.57
Epoch 15 | loss=0.0091 | val_top1=11.96 | val_top5=19.57 | val_top10=19.57
Epoch 16 | loss=0.0083 | val_top1=13.04 | val_top5=19.57 | val_top10=19.57
Epoch 17 | loss=0.0075 | val_top1=13.04 | val_top5=19.57 | val_top10=19.57
Epoch 18 | loss=0.0069 | val_top1=13.04 | val_top5=19.57 | val_top10=19.57
Epoch 19 | loss=0.0064 | val_top1=13.04 | val_top5=19.57 | val_top10=19.57
Epoch 20 | loss=0.0059 | val_top1=13.04 | val_top5=19.57 | val_top10=19.57

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.2363238512035, 'top5': 22.319474835886215, 'top10': 25.25164113785558}

================================================================================
[3/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1772 | val_top1=9.78 | val_top5=11.96 | val_top10=19.57
Epoch 02 | loss=1.8280 | val_top1=9.78 | val_top5=14.13 | val_top10=20.65
Epoch 03 | loss=1.5896 | val_top1=9.78 | val_top5=16.30 | val_top10=20.65
Epoch 04 | loss=1.3984 | val_top1=9.78 | val_top5=16.30 | val_top10=19.57
Epoch 05 | loss=1.2352 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 06 | loss=1.0946 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 07 | loss=0.9738 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 08 | loss=0.8698 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 09 | loss=0.7800 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 10 | loss=0.7021 | val_top1=11.96 | val_top5=15.22 | val_top10=19.57
Epoch 11 | loss=0.6342 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 12 | loss=0.5746 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 13 | loss=0.5221 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 14 | loss=0.4756 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 15 | loss=0.4342 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 16 | loss=0.3972 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 17 | loss=0.3641 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 18 | loss=0.3344 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 19 | loss=0.3077 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 20 | loss=0.2837 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.89277899343545, 'top5': 21.269146608315097, 'top10': 23.938730853391686}

================================================================================
[4/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1448 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 02 | loss=1.7645 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 03 | loss=1.5097 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 04 | loss=1.3048 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 05 | loss=1.1307 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 06 | loss=0.9822 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 07 | loss=0.8560 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 08 | loss=0.7490 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 09 | loss=0.6577 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 10 | loss=0.5794 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 11 | loss=0.5121 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 12 | loss=0.4538 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 13 | loss=0.4034 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 14 | loss=0.3596 | val_top1=10.87 | val_top5=11.96 | val_top10=15.22
Epoch 15 | loss=0.3215 | val_top1=10.87 | val_top5=11.96 | val_top10=15.22
Epoch 16 | loss=0.2884 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 17 | loss=0.2595 | val_top1=10.87 | val_top5=11.96 | val_top10=15.22
Epoch 18 | loss=0.2344 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 19 | loss=0.2125 | val_top1=10.87 | val_top5=11.96 | val_top10=15.22
Epoch 20 | loss=0.1934 | val_top1=10.87 | val_top5=11.96 | val_top10=15.22

Best validation top1: 10.869565217391305
Test metrics: {'top1': 15.886214442013129, 'top5': 20.043763676148796, 'top10': 21.53172866520788}

================================================================================
[5/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9675 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 02 | loss=1.1817 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 03 | loss=0.6647 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 04 | loss=0.3682 | val_top1=10.87 | val_top5=11.96 | val_top10=17.39
Epoch 05 | loss=0.2078 | val_top1=9.78 | val_top5=16.30 | val_top10=19.57
Epoch 06 | loss=0.1173 | val_top1=9.78 | val_top5=16.30 | val_top10=19.57
Epoch 07 | loss=0.0763 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 08 | loss=0.0547 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65
Epoch 09 | loss=0.0475 | val_top1=10.87 | val_top5=18.48 | val_top10=19.57
Epoch 10 | loss=0.0381 | val_top1=9.78 | val_top5=18.48 | val_top10=19.57
Epoch 11 | loss=0.0335 | val_top1=10.87 | val_top5=18.48 | val_top10=19.57
Epoch 12 | loss=0.0276 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 13 | loss=0.0249 | val_top1=11.96 | val_top5=18.48 | val_top10=19.57
Epoch 14 | loss=0.0225 | val_top1=8.70 | val_top5=19.57 | val_top10=20.65
Epoch 15 | loss=0.0206 | val_top1=9.78 | val_top5=18.48 | val_top10=20.65
Epoch 16 | loss=0.0171 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65
Epoch 17 | loss=0.0157 | val_top1=10.87 | val_top5=18.48 | val_top10=19.57
Epoch 18 | loss=0.0150 | val_top1=11.96 | val_top5=18.48 | val_top10=19.57
Epoch 19 | loss=0.0133 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 20 | loss=0.0125 | val_top1=14.13 | val_top5=18.48 | val_top10=20.65

Best validation top1: 14.130434782608695
Test metrics: {'top1': 18.643326039387308, 'top5': 23.50109409190372, 'top10': 25.689277899343544}

================================================================================
[6/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0076 | val_top1=9.78 | val_top5=10.87 | val_top10=13.04
Epoch 02 | loss=1.2729 | val_top1=9.78 | val_top5=9.78 | val_top10=11.96
Epoch 03 | loss=0.7850 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 04 | loss=0.4919 | val_top1=9.78 | val_top5=10.87 | val_top10=11.96
Epoch 05 | loss=0.2732 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 06 | loss=0.1563 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 07 | loss=0.0883 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 08 | loss=0.0518 | val_top1=13.04 | val_top5=16.30 | val_top10=18.48
Epoch 09 | loss=0.0395 | val_top1=10.87 | val_top5=17.39 | val_top10=19.57
Epoch 10 | loss=0.0328 | val_top1=10.87 | val_top5=16.30 | val_top10=20.65
Epoch 11 | loss=0.0258 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 12 | loss=0.0230 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 13 | loss=0.0199 | val_top1=10.87 | val_top5=17.39 | val_top10=19.57
Epoch 14 | loss=0.0181 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 15 | loss=0.0170 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 16 | loss=0.0151 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 17 | loss=0.0139 | val_top1=10.87 | val_top5=17.39 | val_top10=19.57
Epoch 18 | loss=0.0126 | val_top1=11.96 | val_top5=18.48 | val_top10=19.57
Epoch 19 | loss=0.0118 | val_top1=11.96 | val_top5=18.48 | val_top10=19.57
Epoch 20 | loss=0.0105 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.061269146608314, 'top5': 21.269146608315097, 'top10': 23.85120350109409}

================================================================================
[7/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.3131 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 02 | loss=2.0685 | val_top1=11.96 | val_top5=16.30 | val_top10=16.30
Epoch 03 | loss=1.8239 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 04 | loss=1.6645 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 05 | loss=1.5414 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 06 | loss=1.4855 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 07 | loss=1.3698 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 08 | loss=1.2983 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 09 | loss=1.1888 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 10 | loss=1.1222 | val_top1=9.78 | val_top5=14.13 | val_top10=14.13
Epoch 11 | loss=1.0290 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 12 | loss=0.9704 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 13 | loss=0.9231 | val_top1=9.78 | val_top5=13.04 | val_top10=13.04
Epoch 14 | loss=0.8559 | val_top1=9.78 | val_top5=13.04 | val_top10=13.04
Epoch 15 | loss=0.8079 | val_top1=9.78 | val_top5=13.04 | val_top10=13.04
Epoch 16 | loss=0.7331 | val_top1=9.78 | val_top5=13.04 | val_top10=13.04
Epoch 17 | loss=0.7082 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 18 | loss=0.6597 | val_top1=9.78 | val_top5=13.04 | val_top10=13.04
Epoch 19 | loss=0.6601 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 20 | loss=0.5968 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13

Best validation top1: 11.956521739130435
Test metrics: {'top1': 15.886214442013129, 'top5': 19.693654266958426, 'top10': 21.88183807439825}

================================================================================
[8/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.3054 | val_top1=9.78 | val_top5=13.04 | val_top10=17.39
Epoch 02 | loss=1.9540 | val_top1=9.78 | val_top5=11.96 | val_top10=16.30
Epoch 03 | loss=1.7702 | val_top1=9.78 | val_top5=10.87 | val_top10=16.30
Epoch 04 | loss=1.5386 | val_top1=9.78 | val_top5=10.87 | val_top10=16.30
Epoch 05 | loss=1.4425 | val_top1=10.87 | val_top5=10.87 | val_top10=13.04
Epoch 06 | loss=1.2785 | val_top1=10.87 | val_top5=10.87 | val_top10=14.13
Epoch 07 | loss=1.2089 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 08 | loss=1.0933 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 09 | loss=1.0257 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 10 | loss=0.9293 | val_top1=9.78 | val_top5=13.04 | val_top10=16.30
Epoch 11 | loss=0.8552 | val_top1=9.78 | val_top5=11.96 | val_top10=15.22
Epoch 12 | loss=0.8126 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 13 | loss=0.7503 | val_top1=9.78 | val_top5=11.96 | val_top10=15.22
Epoch 14 | loss=0.6773 | val_top1=9.78 | val_top5=11.96 | val_top10=15.22
Epoch 15 | loss=0.6604 | val_top1=9.78 | val_top5=11.96 | val_top10=15.22
Epoch 16 | loss=0.6143 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 17 | loss=0.5668 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 18 | loss=0.5238 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 19 | loss=0.4881 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 20 | loss=0.4565 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13

Best validation top1: 10.869565217391305
Test metrics: {'top1': 15.448577680525164, 'top5': 19.51859956236324, 'top10': 22.23194748358862}

================================================================================
[9/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.8771 | val_top1=9.78 | val_top5=11.96 | val_top10=11.96
Epoch 02 | loss=1.0530 | val_top1=9.78 | val_top5=10.87 | val_top10=14.13
Epoch 03 | loss=0.4905 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 04 | loss=0.1872 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 05 | loss=0.0689 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 06 | loss=0.0356 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 07 | loss=0.0262 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 08 | loss=0.0215 | val_top1=13.04 | val_top5=17.39 | val_top10=20.65
Epoch 09 | loss=0.0183 | val_top1=14.13 | val_top5=17.39 | val_top10=20.65
Epoch 10 | loss=0.0158 | val_top1=14.13 | val_top5=17.39 | val_top10=20.65
Epoch 11 | loss=0.0139 | val_top1=14.13 | val_top5=17.39 | val_top10=20.65
Epoch 12 | loss=0.0123 | val_top1=16.30 | val_top5=17.39 | val_top10=20.65
Epoch 13 | loss=0.0110 | val_top1=16.30 | val_top5=17.39 | val_top10=20.65
Epoch 14 | loss=0.0099 | val_top1=16.30 | val_top5=17.39 | val_top10=21.74
Epoch 15 | loss=0.0090 | val_top1=16.30 | val_top5=17.39 | val_top10=21.74
Epoch 16 | loss=0.0082 | val_top1=16.30 | val_top5=17.39 | val_top10=22.83
Epoch 17 | loss=0.0075 | val_top1=16.30 | val_top5=17.39 | val_top10=22.83
Epoch 18 | loss=0.0069 | val_top1=16.30 | val_top5=17.39 | val_top10=22.83
Epoch 19 | loss=0.0064 | val_top1=16.30 | val_top5=17.39 | val_top10=23.91
Epoch 20 | loss=0.0059 | val_top1=16.30 | val_top5=17.39 | val_top10=23.91

Best validation top1: 16.304347826086957
Test metrics: {'top1': 18.205689277899342, 'top5': 23.676148796498907, 'top10': 26.38949671772429}

================================================================================
[10/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9753 | val_top1=11.96 | val_top5=16.30 | val_top10=16.30
Epoch 02 | loss=1.2195 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 03 | loss=0.7026 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 04 | loss=0.3283 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 05 | loss=0.1346 | val_top1=13.04 | val_top5=17.39 | val_top10=22.83
Epoch 06 | loss=0.0456 | val_top1=15.22 | val_top5=20.65 | val_top10=22.83
Epoch 07 | loss=0.0232 | val_top1=11.96 | val_top5=20.65 | val_top10=21.74
Epoch 08 | loss=0.0175 | val_top1=10.87 | val_top5=19.57 | val_top10=22.83
Epoch 09 | loss=0.0148 | val_top1=10.87 | val_top5=18.48 | val_top10=22.83
Epoch 10 | loss=0.0129 | val_top1=10.87 | val_top5=18.48 | val_top10=21.74
Epoch 11 | loss=0.0114 | val_top1=10.87 | val_top5=18.48 | val_top10=21.74
Epoch 12 | loss=0.0101 | val_top1=11.96 | val_top5=18.48 | val_top10=21.74
Epoch 13 | loss=0.0091 | val_top1=13.04 | val_top5=18.48 | val_top10=21.74
Epoch 14 | loss=0.0083 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 15 | loss=0.0075 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 16 | loss=0.0069 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 17 | loss=0.0063 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 18 | loss=0.0058 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 19 | loss=0.0054 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 20 | loss=0.0050 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57

Best validation top1: 15.217391304347826
Test metrics: {'top1': 16.367614879649892, 'top5': 22.188183807439824, 'top10': 24.420131291028447}

================================================================================
[11/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1826 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 02 | loss=1.8081 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 03 | loss=1.5538 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 04 | loss=1.3525 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 05 | loss=1.1845 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 06 | loss=1.0415 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 07 | loss=0.9193 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 08 | loss=0.8151 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 09 | loss=0.7260 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 10 | loss=0.6493 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 11 | loss=0.5829 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 12 | loss=0.5250 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 13 | loss=0.4742 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 14 | loss=0.4295 | val_top1=13.04 | val_top5=14.13 | val_top10=15.22
Epoch 15 | loss=0.3900 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 16 | loss=0.3549 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 17 | loss=0.3237 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 18 | loss=0.2959 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 19 | loss=0.2711 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 20 | loss=0.2489 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.673960612691467, 'top5': 21.356673960612692, 'top10': 23.719912472647703}

================================================================================
[12/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1580 | val_top1=8.70 | val_top5=11.96 | val_top10=13.04
Epoch 02 | loss=1.7288 | val_top1=8.70 | val_top5=11.96 | val_top10=11.96
Epoch 03 | loss=1.4363 | val_top1=8.70 | val_top5=13.04 | val_top10=14.13
Epoch 04 | loss=1.2108 | val_top1=8.70 | val_top5=11.96 | val_top10=14.13
Epoch 05 | loss=1.0308 | val_top1=8.70 | val_top5=10.87 | val_top10=13.04
Epoch 06 | loss=0.8828 | val_top1=8.70 | val_top5=10.87 | val_top10=14.13
Epoch 07 | loss=0.7592 | val_top1=8.70 | val_top5=10.87 | val_top10=13.04
Epoch 08 | loss=0.6552 | val_top1=8.70 | val_top5=10.87 | val_top10=14.13
Epoch 09 | loss=0.5673 | val_top1=8.70 | val_top5=11.96 | val_top10=14.13
Epoch 10 | loss=0.4928 | val_top1=8.70 | val_top5=10.87 | val_top10=14.13
Epoch 11 | loss=0.4298 | val_top1=8.70 | val_top5=11.96 | val_top10=14.13
Epoch 12 | loss=0.3763 | val_top1=8.70 | val_top5=11.96 | val_top10=14.13
Epoch 13 | loss=0.3309 | val_top1=8.70 | val_top5=13.04 | val_top10=14.13
Epoch 14 | loss=0.2922 | val_top1=8.70 | val_top5=11.96 | val_top10=14.13
Epoch 15 | loss=0.2592 | val_top1=8.70 | val_top5=11.96 | val_top10=14.13
Epoch 16 | loss=0.2309 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 17 | loss=0.2066 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 18 | loss=0.1857 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 19 | loss=0.1675 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 20 | loss=0.1518 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13

Best validation top1: 9.782608695652174
Test metrics: {'top1': 16.367614879649892, 'top5': 20.700218818380744, 'top10': 23.36980306345733}

================================================================================
[13/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9707 | val_top1=9.78 | val_top5=13.04 | val_top10=16.30
Epoch 02 | loss=1.1980 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 03 | loss=0.7155 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 04 | loss=0.4165 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 05 | loss=0.2269 | val_top1=13.04 | val_top5=16.30 | val_top10=19.57
Epoch 06 | loss=0.1229 | val_top1=14.13 | val_top5=17.39 | val_top10=18.48
Epoch 07 | loss=0.0747 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 08 | loss=0.0512 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 09 | loss=0.0398 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 10 | loss=0.0329 | val_top1=13.04 | val_top5=18.48 | val_top10=21.74
Epoch 11 | loss=0.0296 | val_top1=11.96 | val_top5=18.48 | val_top10=21.74
Epoch 12 | loss=0.0247 | val_top1=10.87 | val_top5=19.57 | val_top10=21.74
Epoch 13 | loss=0.0214 | val_top1=10.87 | val_top5=19.57 | val_top10=20.65
Epoch 14 | loss=0.0192 | val_top1=11.96 | val_top5=19.57 | val_top10=21.74
Epoch 15 | loss=0.0177 | val_top1=11.96 | val_top5=18.48 | val_top10=21.74
Epoch 16 | loss=0.0160 | val_top1=11.96 | val_top5=19.57 | val_top10=21.74
Epoch 17 | loss=0.0154 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65
Epoch 18 | loss=0.0133 | val_top1=11.96 | val_top5=19.57 | val_top10=20.65
Epoch 19 | loss=0.0128 | val_top1=10.87 | val_top5=19.57 | val_top10=20.65
Epoch 20 | loss=0.0117 | val_top1=10.87 | val_top5=17.39 | val_top10=20.65

Best validation top1: 14.130434782608695
Test metrics: {'top1': 16.323851203501093, 'top5': 21.575492341356675, 'top10': 24.595185995623634}

================================================================================
[14/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0372 | val_top1=10.87 | val_top5=10.87 | val_top10=10.87
Epoch 02 | loss=1.4037 | val_top1=10.87 | val_top5=11.96 | val_top10=11.96
Epoch 03 | loss=0.9205 | val_top1=10.87 | val_top5=10.87 | val_top10=11.96
Epoch 04 | loss=0.6328 | val_top1=10.87 | val_top5=13.04 | val_top10=13.04
Epoch 05 | loss=0.3375 | val_top1=11.96 | val_top5=13.04 | val_top10=15.22
Epoch 06 | loss=0.1782 | val_top1=10.87 | val_top5=11.96 | val_top10=13.04
Epoch 07 | loss=0.1011 | val_top1=11.96 | val_top5=14.13 | val_top10=14.13
Epoch 08 | loss=0.0564 | val_top1=13.04 | val_top5=14.13 | val_top10=15.22
Epoch 09 | loss=0.0415 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 10 | loss=0.0323 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 11 | loss=0.0262 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 12 | loss=0.0211 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 13 | loss=0.0188 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 14 | loss=0.0176 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 15 | loss=0.0162 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 16 | loss=0.0139 | val_top1=15.22 | val_top5=16.30 | val_top10=17.39
Epoch 17 | loss=0.0126 | val_top1=15.22 | val_top5=16.30 | val_top10=17.39
Epoch 18 | loss=0.0116 | val_top1=14.13 | val_top5=16.30 | val_top10=17.39
Epoch 19 | loss=0.0106 | val_top1=15.22 | val_top5=16.30 | val_top10=17.39
Epoch 20 | loss=0.0105 | val_top1=15.22 | val_top5=16.30 | val_top10=17.39

Best validation top1: 15.217391304347826
Test metrics: {'top1': 17.330415754923415, 'top5': 22.01312910284464, 'top10': 24.420131291028447}

================================================================================
[15/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.3586 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 02 | loss=2.0274 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 03 | loss=1.7983 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 04 | loss=1.6207 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 05 | loss=1.4749 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 06 | loss=1.4049 | val_top1=9.78 | val_top5=16.30 | val_top10=17.39
Epoch 07 | loss=1.3007 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 08 | loss=1.1834 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 09 | loss=1.1331 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 10 | loss=1.0421 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 11 | loss=0.9708 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 12 | loss=0.9139 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 13 | loss=0.8556 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 14 | loss=0.7964 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 15 | loss=0.7429 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 16 | loss=0.6853 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 17 | loss=0.6634 | val_top1=13.04 | val_top5=16.30 | val_top10=20.65
Epoch 18 | loss=0.6122 | val_top1=11.96 | val_top5=15.22 | val_top10=20.65
Epoch 19 | loss=0.5622 | val_top1=13.04 | val_top5=14.13 | val_top10=20.65
Epoch 20 | loss=0.5442 | val_top1=13.04 | val_top5=15.22 | val_top10=20.65

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.2363238512035, 'top5': 21.181619256017505, 'top10': 23.544857768052516}

================================================================================
[16/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1966 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 02 | loss=1.9163 | val_top1=9.78 | val_top5=13.04 | val_top10=13.04
Epoch 03 | loss=1.6911 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 04 | loss=1.5244 | val_top1=10.87 | val_top5=11.96 | val_top10=15.22
Epoch 05 | loss=1.3887 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 06 | loss=1.2440 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 07 | loss=1.1316 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 08 | loss=1.0058 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 09 | loss=0.9419 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 10 | loss=0.8585 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 11 | loss=0.7811 | val_top1=14.13 | val_top5=15.22 | val_top10=16.30
Epoch 12 | loss=0.7090 | val_top1=13.04 | val_top5=15.22 | val_top10=15.22
Epoch 13 | loss=0.6861 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 14 | loss=0.6148 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 15 | loss=0.5847 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 16 | loss=0.5193 | val_top1=13.04 | val_top5=15.22 | val_top10=15.22
Epoch 17 | loss=0.5127 | val_top1=13.04 | val_top5=15.22 | val_top10=15.22
Epoch 18 | loss=0.4593 | val_top1=13.04 | val_top5=15.22 | val_top10=15.22
Epoch 19 | loss=0.4293 | val_top1=13.04 | val_top5=15.22 | val_top10=15.22
Epoch 20 | loss=0.3997 | val_top1=13.04 | val_top5=15.22 | val_top10=15.22

Best validation top1: 14.130434782608695
Test metrics: {'top1': 16.2363238512035, 'top5': 20.787746170678336, 'top10': 23.36980306345733}

================================================================================
[17/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.8574 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 02 | loss=0.9733 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 03 | loss=0.4545 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 04 | loss=0.1859 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 05 | loss=0.0734 | val_top1=10.87 | val_top5=19.57 | val_top10=21.74
Epoch 06 | loss=0.0400 | val_top1=13.04 | val_top5=20.65 | val_top10=21.74
Epoch 07 | loss=0.0291 | val_top1=13.04 | val_top5=20.65 | val_top10=21.74
Epoch 08 | loss=0.0238 | val_top1=13.04 | val_top5=20.65 | val_top10=21.74
Epoch 09 | loss=0.0201 | val_top1=14.13 | val_top5=20.65 | val_top10=21.74
Epoch 10 | loss=0.0174 | val_top1=15.22 | val_top5=20.65 | val_top10=21.74
Epoch 11 | loss=0.0153 | val_top1=16.30 | val_top5=20.65 | val_top10=21.74
Epoch 12 | loss=0.0135 | val_top1=16.30 | val_top5=20.65 | val_top10=22.83
Epoch 13 | loss=0.0121 | val_top1=17.39 | val_top5=20.65 | val_top10=22.83
Epoch 14 | loss=0.0109 | val_top1=17.39 | val_top5=20.65 | val_top10=22.83
Epoch 15 | loss=0.0099 | val_top1=17.39 | val_top5=20.65 | val_top10=22.83
Epoch 16 | loss=0.0090 | val_top1=17.39 | val_top5=20.65 | val_top10=22.83
Epoch 17 | loss=0.0082 | val_top1=17.39 | val_top5=20.65 | val_top10=22.83
Epoch 18 | loss=0.0076 | val_top1=18.48 | val_top5=20.65 | val_top10=22.83
Epoch 19 | loss=0.0070 | val_top1=17.39 | val_top5=20.65 | val_top10=22.83
Epoch 20 | loss=0.0064 | val_top1=17.39 | val_top5=20.65 | val_top10=22.83

Best validation top1: 18.47826086956522
Test metrics: {'top1': 19.51859956236324, 'top5': 24.24507658643326, 'top10': 26.433260393873084}

================================================================================
[18/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9741 | val_top1=8.70 | val_top5=10.87 | val_top10=13.04
Epoch 02 | loss=1.1583 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 03 | loss=0.6542 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 04 | loss=0.2938 | val_top1=9.78 | val_top5=13.04 | val_top10=17.39
Epoch 05 | loss=0.1089 | val_top1=9.78 | val_top5=15.22 | val_top10=19.57
Epoch 06 | loss=0.0477 | val_top1=13.04 | val_top5=20.65 | val_top10=21.74
Epoch 07 | loss=0.0240 | val_top1=11.96 | val_top5=19.57 | val_top10=21.74
Epoch 08 | loss=0.0186 | val_top1=11.96 | val_top5=19.57 | val_top10=21.74
Epoch 09 | loss=0.0158 | val_top1=11.96 | val_top5=20.65 | val_top10=21.74
Epoch 10 | loss=0.0137 | val_top1=11.96 | val_top5=19.57 | val_top10=21.74
Epoch 11 | loss=0.0121 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 12 | loss=0.0108 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 13 | loss=0.0098 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 14 | loss=0.0089 | val_top1=15.22 | val_top5=19.57 | val_top10=21.74
Epoch 15 | loss=0.0081 | val_top1=15.22 | val_top5=19.57 | val_top10=21.74
Epoch 16 | loss=0.0074 | val_top1=15.22 | val_top5=19.57 | val_top10=21.74
Epoch 17 | loss=0.0068 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 18 | loss=0.0063 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 19 | loss=0.0058 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 20 | loss=0.0054 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74

Best validation top1: 15.217391304347826
Test metrics: {'top1': 18.03063457330416, 'top5': 23.544857768052516, 'top10': 26.477024070021884}

================================================================================
[19/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1997 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 02 | loss=1.7717 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 03 | loss=1.5254 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 04 | loss=1.3418 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 05 | loss=1.1904 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 06 | loss=1.0618 | val_top1=11.96 | val_top5=11.96 | val_top10=15.22
Epoch 07 | loss=0.9510 | val_top1=10.87 | val_top5=11.96 | val_top10=16.30
Epoch 08 | loss=0.8550 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 09 | loss=0.7712 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 10 | loss=0.6978 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 11 | loss=0.6330 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 12 | loss=0.5758 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 13 | loss=0.5249 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 14 | loss=0.4795 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 15 | loss=0.4389 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 16 | loss=0.4024 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 17 | loss=0.3696 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 18 | loss=0.3401 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 19 | loss=0.3134 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 20 | loss=0.2893 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22

Best validation top1: 11.956521739130435
Test metrics: {'top1': 17.067833698030636, 'top5': 21.181619256017505, 'top10': 23.36980306345733}

================================================================================
[20/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1176 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 02 | loss=1.7171 | val_top1=9.78 | val_top5=10.87 | val_top10=13.04
Epoch 03 | loss=1.4485 | val_top1=9.78 | val_top5=10.87 | val_top10=11.96
Epoch 04 | loss=1.2344 | val_top1=9.78 | val_top5=10.87 | val_top10=11.96
Epoch 05 | loss=1.0619 | val_top1=9.78 | val_top5=9.78 | val_top10=14.13
Epoch 06 | loss=0.9215 | val_top1=9.78 | val_top5=10.87 | val_top10=14.13
Epoch 07 | loss=0.8049 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 08 | loss=0.7061 | val_top1=9.78 | val_top5=10.87 | val_top10=15.22
Epoch 09 | loss=0.6216 | val_top1=9.78 | val_top5=10.87 | val_top10=15.22
Epoch 10 | loss=0.5488 | val_top1=9.78 | val_top5=10.87 | val_top10=15.22
Epoch 11 | loss=0.4858 | val_top1=9.78 | val_top5=10.87 | val_top10=14.13
Epoch 12 | loss=0.4310 | val_top1=9.78 | val_top5=10.87 | val_top10=15.22
Epoch 13 | loss=0.3835 | val_top1=9.78 | val_top5=11.96 | val_top10=15.22
Epoch 14 | loss=0.3422 | val_top1=9.78 | val_top5=11.96 | val_top10=15.22
Epoch 15 | loss=0.3063 | val_top1=10.87 | val_top5=11.96 | val_top10=16.30
Epoch 16 | loss=0.2751 | val_top1=10.87 | val_top5=11.96 | val_top10=15.22
Epoch 17 | loss=0.2480 | val_top1=10.87 | val_top5=11.96 | val_top10=15.22
Epoch 18 | loss=0.2245 | val_top1=10.87 | val_top5=11.96 | val_top10=15.22
Epoch 19 | loss=0.2039 | val_top1=10.87 | val_top5=11.96 | val_top10=16.30
Epoch 20 | loss=0.1860 | val_top1=10.87 | val_top5=11.96 | val_top10=16.30

Best validation top1: 10.869565217391305
Test metrics: {'top1': 16.63019693654267, 'top5': 20.87527352297593, 'top10': 23.194748358862146}

================================================================================
[21/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9663 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 02 | loss=1.2340 | val_top1=9.78 | val_top5=13.04 | val_top10=16.30
Epoch 03 | loss=0.7423 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 04 | loss=0.4300 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 05 | loss=0.2261 | val_top1=11.96 | val_top5=14.13 | val_top10=18.48
Epoch 06 | loss=0.1453 | val_top1=10.87 | val_top5=18.48 | val_top10=19.57
Epoch 07 | loss=0.0829 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 08 | loss=0.0599 | val_top1=14.13 | val_top5=18.48 | val_top10=20.65
Epoch 09 | loss=0.0449 | val_top1=15.22 | val_top5=19.57 | val_top10=20.65
Epoch 10 | loss=0.0400 | val_top1=13.04 | val_top5=17.39 | val_top10=21.74
Epoch 11 | loss=0.0327 | val_top1=13.04 | val_top5=18.48 | val_top10=21.74
Epoch 12 | loss=0.0286 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 13 | loss=0.0243 | val_top1=11.96 | val_top5=18.48 | val_top10=21.74
Epoch 14 | loss=0.0225 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 15 | loss=0.0198 | val_top1=14.13 | val_top5=19.57 | val_top10=22.83
Epoch 16 | loss=0.0177 | val_top1=15.22 | val_top5=19.57 | val_top10=22.83
Epoch 17 | loss=0.0160 | val_top1=13.04 | val_top5=19.57 | val_top10=22.83
Epoch 18 | loss=0.0145 | val_top1=13.04 | val_top5=19.57 | val_top10=22.83
Epoch 19 | loss=0.0128 | val_top1=13.04 | val_top5=19.57 | val_top10=22.83
Epoch 20 | loss=0.0119 | val_top1=14.13 | val_top5=19.57 | val_top10=22.83

Best validation top1: 15.217391304347826
Test metrics: {'top1': 17.286652078774615, 'top5': 22.669584245076585, 'top10': 25.426695842450766}

================================================================================
[22/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0340 | val_top1=8.70 | val_top5=10.87 | val_top10=11.96
Epoch 02 | loss=1.3825 | val_top1=10.87 | val_top5=11.96 | val_top10=17.39
Epoch 03 | loss=0.8756 | val_top1=9.78 | val_top5=13.04 | val_top10=16.30
Epoch 04 | loss=0.5224 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 05 | loss=0.3084 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 06 | loss=0.1909 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 07 | loss=0.0823 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 08 | loss=0.0477 | val_top1=10.87 | val_top5=17.39 | val_top10=19.57
Epoch 09 | loss=0.0374 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65
Epoch 10 | loss=0.0340 | val_top1=10.87 | val_top5=18.48 | val_top10=19.57
Epoch 11 | loss=0.0281 | val_top1=10.87 | val_top5=18.48 | val_top10=19.57
Epoch 12 | loss=0.0222 | val_top1=10.87 | val_top5=18.48 | val_top10=19.57
Epoch 13 | loss=0.0213 | val_top1=10.87 | val_top5=17.39 | val_top10=19.57
Epoch 14 | loss=0.0191 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 15 | loss=0.0169 | val_top1=10.87 | val_top5=18.48 | val_top10=18.48
Epoch 16 | loss=0.0152 | val_top1=10.87 | val_top5=18.48 | val_top10=19.57
Epoch 17 | loss=0.0140 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 18 | loss=0.0121 | val_top1=11.96 | val_top5=15.22 | val_top10=19.57
Epoch 19 | loss=0.0116 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 20 | loss=0.0105 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48

Best validation top1: 13.043478260869565
Test metrics: {'top1': 15.798687089715536, 'top5': 21.400437636761488, 'top10': 23.85120350109409}

================================================================================
[23/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.3045 | val_top1=9.78 | val_top5=13.04 | val_top10=16.30
Epoch 02 | loss=2.0810 | val_top1=9.78 | val_top5=11.96 | val_top10=11.96
Epoch 03 | loss=1.8755 | val_top1=9.78 | val_top5=10.87 | val_top10=11.96
Epoch 04 | loss=1.7342 | val_top1=9.78 | val_top5=10.87 | val_top10=13.04
Epoch 05 | loss=1.6095 | val_top1=9.78 | val_top5=10.87 | val_top10=13.04
Epoch 06 | loss=1.4908 | val_top1=9.78 | val_top5=10.87 | val_top10=13.04
Epoch 07 | loss=1.4038 | val_top1=9.78 | val_top5=10.87 | val_top10=13.04
Epoch 08 | loss=1.2942 | val_top1=9.78 | val_top5=10.87 | val_top10=13.04
Epoch 09 | loss=1.2163 | val_top1=9.78 | val_top5=10.87 | val_top10=14.13
Epoch 10 | loss=1.1149 | val_top1=9.78 | val_top5=10.87 | val_top10=15.22
Epoch 11 | loss=1.0426 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 12 | loss=0.9887 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 13 | loss=0.9249 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 14 | loss=0.8610 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 15 | loss=0.7811 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 16 | loss=0.7581 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 17 | loss=0.7254 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 18 | loss=0.6646 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 19 | loss=0.6219 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 20 | loss=0.5907 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39

Best validation top1: 10.869565217391305
Test metrics: {'top1': 16.411378555798688, 'top5': 21.181619256017505, 'top10': 23.85120350109409}

================================================================================
[24/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.3141 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 02 | loss=1.9777 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 03 | loss=1.7695 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 04 | loss=1.6135 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 05 | loss=1.4849 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 06 | loss=1.3543 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 07 | loss=1.2518 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 08 | loss=1.1367 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 09 | loss=1.0776 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 10 | loss=0.9665 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 11 | loss=0.9054 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 12 | loss=0.8485 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 13 | loss=0.7778 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 14 | loss=0.7226 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 15 | loss=0.6875 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 16 | loss=0.6186 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 17 | loss=0.6028 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 18 | loss=0.5463 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 19 | loss=0.5071 | val_top1=11.96 | val_top5=13.04 | val_top10=13.04
Epoch 20 | loss=0.4745 | val_top1=11.96 | val_top5=13.04 | val_top10=13.04

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.01750547045952, 'top5': 19.037199124726477, 'top10': 20.831509846827135}

================================================================================
[25/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9020 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 02 | loss=1.0123 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 03 | loss=0.4787 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 04 | loss=0.1724 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 05 | loss=0.0666 | val_top1=7.61 | val_top5=18.48 | val_top10=20.65
Epoch 06 | loss=0.0373 | val_top1=7.61 | val_top5=19.57 | val_top10=20.65
Epoch 07 | loss=0.0269 | val_top1=7.61 | val_top5=19.57 | val_top10=19.57
Epoch 08 | loss=0.0219 | val_top1=8.70 | val_top5=19.57 | val_top10=19.57
Epoch 09 | loss=0.0185 | val_top1=8.70 | val_top5=19.57 | val_top10=19.57
Epoch 10 | loss=0.0159 | val_top1=8.70 | val_top5=19.57 | val_top10=19.57
Epoch 11 | loss=0.0139 | val_top1=8.70 | val_top5=19.57 | val_top10=19.57
Epoch 12 | loss=0.0123 | val_top1=8.70 | val_top5=18.48 | val_top10=19.57
Epoch 13 | loss=0.0110 | val_top1=8.70 | val_top5=19.57 | val_top10=19.57
Epoch 14 | loss=0.0099 | val_top1=8.70 | val_top5=19.57 | val_top10=19.57
Epoch 15 | loss=0.0089 | val_top1=8.70 | val_top5=18.48 | val_top10=19.57
Epoch 16 | loss=0.0081 | val_top1=8.70 | val_top5=18.48 | val_top10=19.57
Epoch 17 | loss=0.0074 | val_top1=8.70 | val_top5=17.39 | val_top10=20.65
Epoch 18 | loss=0.0068 | val_top1=9.78 | val_top5=17.39 | val_top10=20.65
Epoch 19 | loss=0.0062 | val_top1=9.78 | val_top5=17.39 | val_top10=20.65
Epoch 20 | loss=0.0058 | val_top1=10.87 | val_top5=16.30 | val_top10=20.65

Best validation top1: 10.869565217391305
Test metrics: {'top1': 15.62363238512035, 'top5': 19.91247264770241, 'top10': 22.494529540481402}

================================================================================
[26/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0242 | val_top1=8.70 | val_top5=10.87 | val_top10=11.96
Epoch 02 | loss=1.3269 | val_top1=10.87 | val_top5=13.04 | val_top10=13.04
Epoch 03 | loss=0.8290 | val_top1=8.70 | val_top5=10.87 | val_top10=13.04
Epoch 04 | loss=0.3530 | val_top1=9.78 | val_top5=11.96 | val_top10=11.96
Epoch 05 | loss=0.1384 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 06 | loss=0.0617 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 07 | loss=0.0256 | val_top1=11.96 | val_top5=16.30 | val_top10=16.30
Epoch 08 | loss=0.0182 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30
Epoch 09 | loss=0.0152 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30
Epoch 10 | loss=0.0131 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30
Epoch 11 | loss=0.0116 | val_top1=9.78 | val_top5=16.30 | val_top10=16.30
Epoch 12 | loss=0.0103 | val_top1=9.78 | val_top5=16.30 | val_top10=16.30
Epoch 13 | loss=0.0093 | val_top1=9.78 | val_top5=16.30 | val_top10=17.39
Epoch 14 | loss=0.0084 | val_top1=8.70 | val_top5=16.30 | val_top10=18.48
Epoch 15 | loss=0.0077 | val_top1=8.70 | val_top5=16.30 | val_top10=18.48
Epoch 16 | loss=0.0070 | val_top1=8.70 | val_top5=16.30 | val_top10=19.57
Epoch 17 | loss=0.0064 | val_top1=8.70 | val_top5=17.39 | val_top10=19.57
Epoch 18 | loss=0.0059 | val_top1=8.70 | val_top5=17.39 | val_top10=19.57
Epoch 19 | loss=0.0055 | val_top1=8.70 | val_top5=17.39 | val_top10=19.57
Epoch 20 | loss=0.0051 | val_top1=8.70 | val_top5=17.39 | val_top10=19.57

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.58643326039387, 'top5': 22.144420131291028, 'top10': 25.514223194748357}

================================================================================
[27/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1585 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 02 | loss=1.7669 | val_top1=11.96 | val_top5=16.30 | val_top10=16.30
Epoch 03 | loss=1.5229 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 04 | loss=1.3265 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 05 | loss=1.1611 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 06 | loss=1.0212 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 07 | loss=0.9024 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 08 | loss=0.8006 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 09 | loss=0.7127 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 10 | loss=0.6366 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 11 | loss=0.5705 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 12 | loss=0.5130 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39
Epoch 13 | loss=0.4629 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39
Epoch 14 | loss=0.4189 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 15 | loss=0.3803 | val_top1=11.96 | val_top5=13.04 | val_top10=14.13
Epoch 16 | loss=0.3462 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 17 | loss=0.3160 | val_top1=11.96 | val_top5=13.04 | val_top10=15.22
Epoch 18 | loss=0.2892 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 19 | loss=0.2653 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 20 | loss=0.2440 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.323851203501093, 'top5': 20.043763676148796, 'top10': 21.706783369803063}

================================================================================
[28/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1110 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 02 | loss=1.7011 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 03 | loss=1.4374 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 04 | loss=1.2232 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 05 | loss=1.0449 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 06 | loss=0.8976 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 07 | loss=0.7753 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 08 | loss=0.6725 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 09 | loss=0.5854 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 10 | loss=0.5110 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 11 | loss=0.4473 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 12 | loss=0.3926 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 13 | loss=0.3456 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 14 | loss=0.3053 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 15 | loss=0.2707 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 16 | loss=0.2411 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 17 | loss=0.2156 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 18 | loss=0.1937 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 19 | loss=0.1748 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 20 | loss=0.1585 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39

Best validation top1: 11.956521739130435
Test metrics: {'top1': 15.929978118161925, 'top5': 20.700218818380744, 'top10': 23.150984682713347}

================================================================================
[29/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9583 | val_top1=9.78 | val_top5=10.87 | val_top10=13.04
Epoch 02 | loss=1.1901 | val_top1=11.96 | val_top5=13.04 | val_top10=15.22
Epoch 03 | loss=0.7174 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 04 | loss=0.4147 | val_top1=9.78 | val_top5=11.96 | val_top10=18.48
Epoch 05 | loss=0.2491 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 06 | loss=0.1247 | val_top1=9.78 | val_top5=15.22 | val_top10=19.57
Epoch 07 | loss=0.0775 | val_top1=8.70 | val_top5=15.22 | val_top10=21.74
Epoch 08 | loss=0.0539 | val_top1=8.70 | val_top5=18.48 | val_top10=19.57
Epoch 09 | loss=0.0419 | val_top1=8.70 | val_top5=17.39 | val_top10=19.57
Epoch 10 | loss=0.0357 | val_top1=9.78 | val_top5=19.57 | val_top10=19.57
Epoch 11 | loss=0.0284 | val_top1=8.70 | val_top5=18.48 | val_top10=21.74
Epoch 12 | loss=0.0276 | val_top1=9.78 | val_top5=19.57 | val_top10=21.74
Epoch 13 | loss=0.0224 | val_top1=9.78 | val_top5=19.57 | val_top10=20.65
Epoch 14 | loss=0.0195 | val_top1=10.87 | val_top5=16.30 | val_top10=20.65
Epoch 15 | loss=0.0184 | val_top1=9.78 | val_top5=16.30 | val_top10=20.65
Epoch 16 | loss=0.0171 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65
Epoch 17 | loss=0.0147 | val_top1=10.87 | val_top5=19.57 | val_top10=19.57
Epoch 18 | loss=0.0136 | val_top1=11.96 | val_top5=19.57 | val_top10=19.57
Epoch 19 | loss=0.0124 | val_top1=10.87 | val_top5=19.57 | val_top10=19.57
Epoch 20 | loss=0.0119 | val_top1=10.87 | val_top5=19.57 | val_top10=19.57

Best validation top1: 11.956521739130435
Test metrics: {'top1': 15.75492341356674, 'top5': 19.431072210065647, 'top10': 21.838074398249454}

================================================================================
[30/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0462 | val_top1=8.70 | val_top5=11.96 | val_top10=11.96
Epoch 02 | loss=1.3748 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 03 | loss=0.8973 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 04 | loss=0.5553 | val_top1=9.78 | val_top5=10.87 | val_top10=11.96
Epoch 05 | loss=0.2875 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 06 | loss=0.1532 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 07 | loss=0.0866 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 08 | loss=0.0503 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 09 | loss=0.0335 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 10 | loss=0.0279 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65
Epoch 11 | loss=0.0256 | val_top1=13.04 | val_top5=17.39 | val_top10=18.48
Epoch 12 | loss=0.0210 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 13 | loss=0.0191 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65
Epoch 14 | loss=0.0164 | val_top1=13.04 | val_top5=17.39 | val_top10=20.65
Epoch 15 | loss=0.0156 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65
Epoch 16 | loss=0.0138 | val_top1=11.96 | val_top5=18.48 | val_top10=19.57
Epoch 17 | loss=0.0126 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65
Epoch 18 | loss=0.0117 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 19 | loss=0.0108 | val_top1=15.22 | val_top5=19.57 | val_top10=20.65
Epoch 20 | loss=0.0099 | val_top1=15.22 | val_top5=18.48 | val_top10=20.65

Best validation top1: 15.217391304347826
Test metrics: {'top1': 17.155361050328228, 'top5': 22.100656455142232, 'top10': 24.288840262582056}

================================================================================
[31/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.3633 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 02 | loss=2.0541 | val_top1=8.70 | val_top5=13.04 | val_top10=15.22
Epoch 03 | loss=1.8368 | val_top1=8.70 | val_top5=11.96 | val_top10=16.30
Epoch 04 | loss=1.6401 | val_top1=9.78 | val_top5=13.04 | val_top10=17.39
Epoch 05 | loss=1.5289 | val_top1=9.78 | val_top5=11.96 | val_top10=17.39
Epoch 06 | loss=1.3943 | val_top1=9.78 | val_top5=10.87 | val_top10=16.30
Epoch 07 | loss=1.2949 | val_top1=9.78 | val_top5=11.96 | val_top10=16.30
Epoch 08 | loss=1.2069 | val_top1=9.78 | val_top5=11.96 | val_top10=16.30
Epoch 09 | loss=1.0988 | val_top1=9.78 | val_top5=11.96 | val_top10=16.30
Epoch 10 | loss=1.0575 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 11 | loss=0.9747 | val_top1=9.78 | val_top5=11.96 | val_top10=15.22
Epoch 12 | loss=0.8866 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 13 | loss=0.8464 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 14 | loss=0.7972 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 15 | loss=0.7229 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 16 | loss=0.6867 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 17 | loss=0.6527 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 18 | loss=0.6086 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 19 | loss=0.5785 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 20 | loss=0.5361 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22

Best validation top1: 10.869565217391305
Test metrics: {'top1': 16.323851203501093, 'top5': 20.919037199124727, 'top10': 23.676148796498907}

================================================================================
[32/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 256, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2427 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 02 | loss=1.9832 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 03 | loss=1.7671 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 04 | loss=1.5762 | val_top1=9.78 | val_top5=15.22 | val_top10=19.57
Epoch 05 | loss=1.4512 | val_top1=9.78 | val_top5=14.13 | val_top10=19.57
Epoch 06 | loss=1.3143 | val_top1=10.87 | val_top5=14.13 | val_top10=19.57
Epoch 07 | loss=1.2011 | val_top1=11.96 | val_top5=14.13 | val_top10=18.48
Epoch 08 | loss=1.0995 | val_top1=11.96 | val_top5=14.13 | val_top10=18.48
Epoch 09 | loss=1.0079 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 10 | loss=0.9237 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 11 | loss=0.8651 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 12 | loss=0.7871 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 13 | loss=0.7097 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 14 | loss=0.6574 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 15 | loss=0.6322 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 16 | loss=0.5988 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 17 | loss=0.5495 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 18 | loss=0.5018 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39
Epoch 19 | loss=0.4689 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39
Epoch 20 | loss=0.4558 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.2363238512035, 'top5': 20.437636761487965, 'top10': 23.01969365426696}

================================================================================
[33/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9444 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 02 | loss=1.1459 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 03 | loss=0.5567 | val_top1=10.87 | val_top5=13.04 | val_top10=18.48
Epoch 04 | loss=0.1993 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 05 | loss=0.0625 | val_top1=10.87 | val_top5=17.39 | val_top10=22.83
Epoch 06 | loss=0.0257 | val_top1=11.96 | val_top5=20.65 | val_top10=23.91
Epoch 07 | loss=0.0171 | val_top1=11.96 | val_top5=19.57 | val_top10=23.91
Epoch 08 | loss=0.0142 | val_top1=11.96 | val_top5=20.65 | val_top10=23.91
Epoch 09 | loss=0.0122 | val_top1=10.87 | val_top5=20.65 | val_top10=23.91
Epoch 10 | loss=0.0107 | val_top1=10.87 | val_top5=20.65 | val_top10=25.00
Epoch 11 | loss=0.0095 | val_top1=11.96 | val_top5=21.74 | val_top10=25.00
Epoch 12 | loss=0.0085 | val_top1=11.96 | val_top5=21.74 | val_top10=26.09
Epoch 13 | loss=0.0076 | val_top1=11.96 | val_top5=22.83 | val_top10=26.09
Epoch 14 | loss=0.0069 | val_top1=11.96 | val_top5=22.83 | val_top10=26.09
Epoch 15 | loss=0.0063 | val_top1=11.96 | val_top5=22.83 | val_top10=26.09
Epoch 16 | loss=0.0057 | val_top1=13.04 | val_top5=22.83 | val_top10=26.09
Epoch 17 | loss=0.0053 | val_top1=11.96 | val_top5=22.83 | val_top10=26.09
Epoch 18 | loss=0.0049 | val_top1=11.96 | val_top5=22.83 | val_top10=27.17
Epoch 19 | loss=0.0045 | val_top1=11.96 | val_top5=22.83 | val_top10=27.17
Epoch 20 | loss=0.0042 | val_top1=11.96 | val_top5=22.83 | val_top10=25.00

Best validation top1: 13.043478260869565
Test metrics: {'top1': 18.949671772428886, 'top5': 23.98249452954048, 'top10': 26.170678336980306}

================================================================================
[34/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0607 | val_top1=7.61 | val_top5=9.78 | val_top10=11.96
Epoch 02 | loss=1.4662 | val_top1=10.87 | val_top5=11.96 | val_top10=11.96
Epoch 03 | loss=0.9768 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 04 | loss=0.6272 | val_top1=11.96 | val_top5=13.04 | val_top10=14.13
Epoch 05 | loss=0.3210 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 06 | loss=0.1413 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 07 | loss=0.0591 | val_top1=8.70 | val_top5=14.13 | val_top10=17.39
Epoch 08 | loss=0.0209 | val_top1=8.70 | val_top5=15.22 | val_top10=19.57
Epoch 09 | loss=0.0140 | val_top1=9.78 | val_top5=14.13 | val_top10=19.57
Epoch 10 | loss=0.0117 | val_top1=9.78 | val_top5=15.22 | val_top10=19.57
Epoch 11 | loss=0.0102 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 12 | loss=0.0091 | val_top1=9.78 | val_top5=14.13 | val_top10=18.48
Epoch 13 | loss=0.0082 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 14 | loss=0.0074 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 15 | loss=0.0067 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 16 | loss=0.0062 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 17 | loss=0.0057 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 18 | loss=0.0053 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 19 | loss=0.0049 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 20 | loss=0.0045 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39

Best validation top1: 11.956521739130435
Test metrics: {'top1': 14.223194748358862, 'top5': 17.680525164113785, 'top10': 19.91247264770241}

================================================================================
[35/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0358 | val_top1=9.78 | val_top5=17.39 | val_top10=19.57
Epoch 02 | loss=1.5770 | val_top1=8.70 | val_top5=13.04 | val_top10=19.57
Epoch 03 | loss=1.2924 | val_top1=9.78 | val_top5=13.04 | val_top10=19.57
Epoch 04 | loss=1.0675 | val_top1=10.87 | val_top5=11.96 | val_top10=16.30
Epoch 05 | loss=0.8875 | val_top1=10.87 | val_top5=11.96 | val_top10=17.39
Epoch 06 | loss=0.7454 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 07 | loss=0.6322 | val_top1=10.87 | val_top5=13.04 | val_top10=18.48
Epoch 08 | loss=0.5401 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 09 | loss=0.4641 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 10 | loss=0.4007 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 11 | loss=0.3474 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 12 | loss=0.3025 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 13 | loss=0.2646 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 14 | loss=0.2325 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 15 | loss=0.2054 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 16 | loss=0.1826 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 17 | loss=0.1632 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 18 | loss=0.1468 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 19 | loss=0.1328 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 20 | loss=0.1207 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39

Best validation top1: 10.869565217391305
Test metrics: {'top1': 16.89277899343545, 'top5': 21.444201312910284, 'top10': 24.026258205689278}

================================================================================
[36/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9636 | val_top1=9.78 | val_top5=14.13 | val_top10=18.48
Epoch 02 | loss=1.4842 | val_top1=8.70 | val_top5=15.22 | val_top10=16.30
Epoch 03 | loss=1.1674 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 04 | loss=0.9240 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 05 | loss=0.7355 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 06 | loss=0.5904 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 07 | loss=0.4788 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 08 | loss=0.3925 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 09 | loss=0.3249 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 10 | loss=0.2712 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 11 | loss=0.2283 | val_top1=11.96 | val_top5=15.22 | val_top10=19.57
Epoch 12 | loss=0.1940 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 13 | loss=0.1665 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 14 | loss=0.1443 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 15 | loss=0.1264 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 16 | loss=0.1117 | val_top1=11.96 | val_top5=15.22 | val_top10=20.65
Epoch 17 | loss=0.0995 | val_top1=11.96 | val_top5=15.22 | val_top10=20.65
Epoch 18 | loss=0.0893 | val_top1=11.96 | val_top5=15.22 | val_top10=19.57
Epoch 19 | loss=0.0806 | val_top1=11.96 | val_top5=15.22 | val_top10=20.65
Epoch 20 | loss=0.0732 | val_top1=10.87 | val_top5=15.22 | val_top10=20.65

Best validation top1: 11.956521739130435
Test metrics: {'top1': 17.024070021881837, 'top5': 21.706783369803063, 'top10': 24.24507658643326}

================================================================================
[37/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9474 | val_top1=10.87 | val_top5=11.96 | val_top10=16.30
Epoch 02 | loss=1.2299 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 03 | loss=0.6745 | val_top1=11.96 | val_top5=13.04 | val_top10=15.22
Epoch 04 | loss=0.3451 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 05 | loss=0.1617 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 06 | loss=0.0659 | val_top1=10.87 | val_top5=18.48 | val_top10=20.65
Epoch 07 | loss=0.0367 | val_top1=11.96 | val_top5=18.48 | val_top10=21.74
Epoch 08 | loss=0.0253 | val_top1=11.96 | val_top5=19.57 | val_top10=22.83
Epoch 09 | loss=0.0204 | val_top1=14.13 | val_top5=21.74 | val_top10=22.83
Epoch 10 | loss=0.0178 | val_top1=11.96 | val_top5=20.65 | val_top10=21.74
Epoch 11 | loss=0.0156 | val_top1=13.04 | val_top5=21.74 | val_top10=22.83
Epoch 12 | loss=0.0141 | val_top1=14.13 | val_top5=21.74 | val_top10=22.83
Epoch 13 | loss=0.0126 | val_top1=14.13 | val_top5=21.74 | val_top10=22.83
Epoch 14 | loss=0.0112 | val_top1=13.04 | val_top5=21.74 | val_top10=22.83
Epoch 15 | loss=0.0104 | val_top1=11.96 | val_top5=20.65 | val_top10=22.83
Epoch 16 | loss=0.0094 | val_top1=13.04 | val_top5=20.65 | val_top10=22.83
Epoch 17 | loss=0.0085 | val_top1=11.96 | val_top5=20.65 | val_top10=22.83
Epoch 18 | loss=0.0080 | val_top1=13.04 | val_top5=20.65 | val_top10=22.83
Epoch 19 | loss=0.0073 | val_top1=13.04 | val_top5=20.65 | val_top10=22.83
Epoch 20 | loss=0.0069 | val_top1=13.04 | val_top5=20.65 | val_top10=22.83

Best validation top1: 14.130434782608695
Test metrics: {'top1': 17.592997811816193, 'top5': 23.632385120350108, 'top10': 25.951859956236323}

================================================================================
[38/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0700 | val_top1=9.78 | val_top5=9.78 | val_top10=10.87
Epoch 02 | loss=1.4630 | val_top1=8.70 | val_top5=9.78 | val_top10=11.96
Epoch 03 | loss=1.0701 | val_top1=10.87 | val_top5=13.04 | val_top10=13.04
Epoch 04 | loss=0.6886 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 05 | loss=0.4055 | val_top1=11.96 | val_top5=13.04 | val_top10=13.04
Epoch 06 | loss=0.2021 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 07 | loss=0.0955 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 08 | loss=0.0366 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 09 | loss=0.0247 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 10 | loss=0.0209 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 11 | loss=0.0164 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 12 | loss=0.0133 | val_top1=13.04 | val_top5=16.30 | val_top10=18.48
Epoch 13 | loss=0.0118 | val_top1=13.04 | val_top5=16.30 | val_top10=17.39
Epoch 14 | loss=0.0110 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 15 | loss=0.0100 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 16 | loss=0.0091 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 17 | loss=0.0085 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 18 | loss=0.0078 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 19 | loss=0.0072 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 20 | loss=0.0065 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.411378555798688, 'top5': 21.794310722100658, 'top10': 24.24507658643326}

================================================================================
[39/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2623 | val_top1=13.04 | val_top5=15.22 | val_top10=16.30
Epoch 02 | loss=1.8831 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 03 | loss=1.6765 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 04 | loss=1.4742 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 05 | loss=1.3390 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 06 | loss=1.1820 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 07 | loss=1.0542 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 08 | loss=0.9678 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 09 | loss=0.8686 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 10 | loss=0.7783 | val_top1=11.96 | val_top5=13.04 | val_top10=15.22
Epoch 11 | loss=0.7125 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 12 | loss=0.6403 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 13 | loss=0.5866 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 14 | loss=0.5466 | val_top1=13.04 | val_top5=14.13 | val_top10=16.30
Epoch 15 | loss=0.4914 | val_top1=13.04 | val_top5=14.13 | val_top10=17.39
Epoch 16 | loss=0.4533 | val_top1=13.04 | val_top5=14.13 | val_top10=17.39
Epoch 17 | loss=0.4309 | val_top1=13.04 | val_top5=14.13 | val_top10=17.39
Epoch 18 | loss=0.3783 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 19 | loss=0.3491 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 20 | loss=0.3218 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39

Best validation top1: 13.043478260869565
Test metrics: {'top1': 15.75492341356674, 'top5': 20.218818380743983, 'top10': 22.407002188183807}

================================================================================
[40/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1949 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 02 | loss=1.7894 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 03 | loss=1.5386 | val_top1=9.78 | val_top5=13.04 | val_top10=18.48
Epoch 04 | loss=1.2946 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 05 | loss=1.1215 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 06 | loss=0.9639 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 07 | loss=0.8713 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 08 | loss=0.7659 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 09 | loss=0.6924 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 10 | loss=0.5991 | val_top1=11.96 | val_top5=14.13 | val_top10=15.22
Epoch 11 | loss=0.5393 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 12 | loss=0.4862 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 13 | loss=0.4345 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 14 | loss=0.3944 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 15 | loss=0.3419 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 16 | loss=0.3189 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 17 | loss=0.2933 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 18 | loss=0.2618 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 19 | loss=0.2423 | val_top1=13.04 | val_top5=17.39 | val_top10=18.48
Epoch 20 | loss=0.2148 | val_top1=13.04 | val_top5=17.39 | val_top10=18.48

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.411378555798688, 'top5': 21.925601750547045, 'top10': 24.9890590809628}

================================================================================
[41/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9238 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 02 | loss=1.0997 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 03 | loss=0.4879 | val_top1=9.78 | val_top5=11.96 | val_top10=11.96
Epoch 04 | loss=0.1811 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 05 | loss=0.0530 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 06 | loss=0.0206 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 07 | loss=0.0140 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 08 | loss=0.0117 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 09 | loss=0.0101 | val_top1=11.96 | val_top5=15.22 | val_top10=19.57
Epoch 10 | loss=0.0089 | val_top1=11.96 | val_top5=15.22 | val_top10=19.57
Epoch 11 | loss=0.0079 | val_top1=11.96 | val_top5=15.22 | val_top10=20.65
Epoch 12 | loss=0.0071 | val_top1=11.96 | val_top5=15.22 | val_top10=19.57
Epoch 13 | loss=0.0064 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 14 | loss=0.0058 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 15 | loss=0.0053 | val_top1=13.04 | val_top5=16.30 | val_top10=19.57
Epoch 16 | loss=0.0048 | val_top1=13.04 | val_top5=16.30 | val_top10=19.57
Epoch 17 | loss=0.0045 | val_top1=14.13 | val_top5=17.39 | val_top10=18.48
Epoch 18 | loss=0.0041 | val_top1=13.04 | val_top5=17.39 | val_top10=18.48
Epoch 19 | loss=0.0038 | val_top1=13.04 | val_top5=17.39 | val_top10=18.48
Epoch 20 | loss=0.0035 | val_top1=13.04 | val_top5=17.39 | val_top10=18.48

Best validation top1: 14.130434782608695
Test metrics: {'top1': 19.037199124726477, 'top5': 24.11378555798687, 'top10': 26.739606126914662}

================================================================================
[42/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1973 | val_top1=8.70 | val_top5=10.87 | val_top10=11.96
Epoch 02 | loss=1.6586 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 03 | loss=1.2874 | val_top1=8.70 | val_top5=9.78 | val_top10=11.96
Epoch 04 | loss=0.9470 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 05 | loss=0.5969 | val_top1=8.70 | val_top5=10.87 | val_top10=15.22
Epoch 06 | loss=0.3114 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 07 | loss=0.1149 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 08 | loss=0.0434 | val_top1=11.96 | val_top5=14.13 | val_top10=19.57
Epoch 09 | loss=0.0178 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 10 | loss=0.0120 | val_top1=10.87 | val_top5=16.30 | val_top10=20.65
Epoch 11 | loss=0.0101 | val_top1=10.87 | val_top5=16.30 | val_top10=20.65
Epoch 12 | loss=0.0088 | val_top1=10.87 | val_top5=17.39 | val_top10=20.65
Epoch 13 | loss=0.0078 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 14 | loss=0.0070 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 15 | loss=0.0064 | val_top1=10.87 | val_top5=17.39 | val_top10=20.65
Epoch 16 | loss=0.0059 | val_top1=11.96 | val_top5=17.39 | val_top10=21.74
Epoch 17 | loss=0.0054 | val_top1=13.04 | val_top5=17.39 | val_top10=21.74
Epoch 18 | loss=0.0050 | val_top1=13.04 | val_top5=17.39 | val_top10=21.74
Epoch 19 | loss=0.0046 | val_top1=13.04 | val_top5=18.48 | val_top10=21.74
Epoch 20 | loss=0.0043 | val_top1=13.04 | val_top5=19.57 | val_top10=22.83

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.542669584245075, 'top5': 20.525164113785557, 'top10': 22.713347921225385}

================================================================================
[43/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0509 | val_top1=8.70 | val_top5=14.13 | val_top10=14.13
Epoch 02 | loss=1.5523 | val_top1=9.78 | val_top5=11.96 | val_top10=15.22
Epoch 03 | loss=1.2464 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 04 | loss=1.0110 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 05 | loss=0.8291 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 06 | loss=0.6881 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 07 | loss=0.5765 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 08 | loss=0.4862 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 09 | loss=0.4122 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 10 | loss=0.3510 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 11 | loss=0.3003 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 12 | loss=0.2583 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 13 | loss=0.2235 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 14 | loss=0.1947 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 15 | loss=0.1709 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 16 | loss=0.1512 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 17 | loss=0.1348 | val_top1=10.87 | val_top5=18.48 | val_top10=18.48
Epoch 18 | loss=0.1210 | val_top1=10.87 | val_top5=18.48 | val_top10=18.48
Epoch 19 | loss=0.1093 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 20 | loss=0.0993 | val_top1=11.96 | val_top5=18.48 | val_top10=18.48

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.717724288840262, 'top5': 21.181619256017505, 'top10': 23.719912472647703}

================================================================================
[44/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9778 | val_top1=9.78 | val_top5=13.04 | val_top10=15.22
Epoch 02 | loss=1.4595 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 03 | loss=1.1142 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 04 | loss=0.8566 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 05 | loss=0.6603 | val_top1=11.96 | val_top5=15.22 | val_top10=19.57
Epoch 06 | loss=0.5123 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 07 | loss=0.4005 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 08 | loss=0.3154 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 09 | loss=0.2506 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 10 | loss=0.2016 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 11 | loss=0.1647 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57
Epoch 12 | loss=0.1369 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 13 | loss=0.1160 | val_top1=11.96 | val_top5=17.39 | val_top10=20.65
Epoch 14 | loss=0.1000 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65
Epoch 15 | loss=0.0874 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65
Epoch 16 | loss=0.0773 | val_top1=11.96 | val_top5=18.48 | val_top10=20.65
Epoch 17 | loss=0.0690 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 18 | loss=0.0620 | val_top1=11.96 | val_top5=16.30 | val_top10=21.74
Epoch 19 | loss=0.0561 | val_top1=11.96 | val_top5=16.30 | val_top10=21.74
Epoch 20 | loss=0.0511 | val_top1=11.96 | val_top5=16.30 | val_top10=21.74

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.673960612691467, 'top5': 21.61925601750547, 'top10': 24.463894967177243}

================================================================================
[45/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0004 | val_top1=11.96 | val_top5=11.96 | val_top10=15.22
Epoch 02 | loss=1.2729 | val_top1=10.87 | val_top5=11.96 | val_top10=15.22
Epoch 03 | loss=0.7336 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 04 | loss=0.3828 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 05 | loss=0.1677 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 06 | loss=0.0816 | val_top1=13.04 | val_top5=18.48 | val_top10=18.48
Epoch 07 | loss=0.0362 | val_top1=13.04 | val_top5=18.48 | val_top10=19.57
Epoch 08 | loss=0.0245 | val_top1=13.04 | val_top5=17.39 | val_top10=20.65
Epoch 09 | loss=0.0206 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 10 | loss=0.0177 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 11 | loss=0.0150 | val_top1=14.13 | val_top5=17.39 | val_top10=19.57
Epoch 12 | loss=0.0133 | val_top1=14.13 | val_top5=18.48 | val_top10=19.57
Epoch 13 | loss=0.0114 | val_top1=14.13 | val_top5=18.48 | val_top10=21.74
Epoch 14 | loss=0.0106 | val_top1=14.13 | val_top5=18.48 | val_top10=19.57
Epoch 15 | loss=0.0099 | val_top1=14.13 | val_top5=18.48 | val_top10=21.74
Epoch 16 | loss=0.0089 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 17 | loss=0.0081 | val_top1=14.13 | val_top5=18.48 | val_top10=21.74
Epoch 18 | loss=0.0077 | val_top1=14.13 | val_top5=18.48 | val_top10=20.65
Epoch 19 | loss=0.0071 | val_top1=14.13 | val_top5=18.48 | val_top10=20.65
Epoch 20 | loss=0.0065 | val_top1=14.13 | val_top5=17.39 | val_top10=20.65

Best validation top1: 14.130434782608695
Test metrics: {'top1': 17.505470459518598, 'top5': 22.932166301969364, 'top10': 25.339168490153174}

================================================================================
[46/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1178 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 02 | loss=1.5201 | val_top1=8.70 | val_top5=9.78 | val_top10=11.96
Epoch 03 | loss=1.1049 | val_top1=9.78 | val_top5=10.87 | val_top10=11.96
Epoch 04 | loss=0.6901 | val_top1=9.78 | val_top5=13.04 | val_top10=13.04
Epoch 05 | loss=0.3894 | val_top1=9.78 | val_top5=13.04 | val_top10=16.30
Epoch 06 | loss=0.2202 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 07 | loss=0.1180 | val_top1=7.61 | val_top5=15.22 | val_top10=17.39
Epoch 08 | loss=0.0656 | val_top1=9.78 | val_top5=14.13 | val_top10=15.22
Epoch 09 | loss=0.0306 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 10 | loss=0.0173 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 11 | loss=0.0141 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 12 | loss=0.0125 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 13 | loss=0.0110 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 14 | loss=0.0098 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 15 | loss=0.0091 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 16 | loss=0.0081 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 17 | loss=0.0077 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 18 | loss=0.0068 | val_top1=8.70 | val_top5=15.22 | val_top10=16.30
Epoch 19 | loss=0.0065 | val_top1=9.78 | val_top5=16.30 | val_top10=16.30
Epoch 20 | loss=0.0059 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.01750547045952, 'top5': 20.437636761487965, 'top10': 22.844638949671772}

================================================================================
[47/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2412 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 02 | loss=1.8417 | val_top1=9.78 | val_top5=15.22 | val_top10=18.48
Epoch 03 | loss=1.6240 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 04 | loss=1.4263 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 05 | loss=1.2826 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 06 | loss=1.1258 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 07 | loss=1.0229 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 08 | loss=0.9116 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 09 | loss=0.8094 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 10 | loss=0.7205 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 11 | loss=0.6620 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 12 | loss=0.5783 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 13 | loss=0.5505 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 14 | loss=0.4742 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 15 | loss=0.4464 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 16 | loss=0.3973 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 17 | loss=0.3678 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 18 | loss=0.3370 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 19 | loss=0.3051 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 20 | loss=0.2887 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.14879649890591, 'top5': 20.0, 'top10': 22.144420131291028}

================================================================================
[48/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 4, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1485 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 02 | loss=1.7098 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 03 | loss=1.4519 | val_top1=9.78 | val_top5=13.04 | val_top10=17.39
Epoch 04 | loss=1.2185 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 05 | loss=1.0543 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 06 | loss=0.9049 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 07 | loss=0.7649 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 08 | loss=0.6869 | val_top1=10.87 | val_top5=13.04 | val_top10=17.39
Epoch 09 | loss=0.5771 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 10 | loss=0.5175 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 11 | loss=0.4588 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 12 | loss=0.4136 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 13 | loss=0.3564 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 14 | loss=0.3180 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 15 | loss=0.2961 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 16 | loss=0.2570 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30
Epoch 17 | loss=0.2250 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30
Epoch 18 | loss=0.1990 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 19 | loss=0.1954 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 20 | loss=0.1669 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39

Best validation top1: 10.869565217391305
Test metrics: {'top1': 16.717724288840262, 'top5': 20.08752735229759, 'top10': 22.23194748358862}

================================================================================
[49/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9299 | val_top1=10.87 | val_top5=10.87 | val_top10=10.87
Epoch 02 | loss=1.1108 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 03 | loss=0.5499 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 04 | loss=0.1942 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 05 | loss=0.0620 | val_top1=11.96 | val_top5=18.48 | val_top10=19.57
Epoch 06 | loss=0.0267 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 07 | loss=0.0162 | val_top1=11.96 | val_top5=18.48 | val_top10=19.57
Epoch 08 | loss=0.0134 | val_top1=11.96 | val_top5=19.57 | val_top10=19.57
Epoch 09 | loss=0.0115 | val_top1=11.96 | val_top5=19.57 | val_top10=19.57
Epoch 10 | loss=0.0101 | val_top1=11.96 | val_top5=19.57 | val_top10=19.57
Epoch 11 | loss=0.0089 | val_top1=11.96 | val_top5=19.57 | val_top10=19.57
Epoch 12 | loss=0.0080 | val_top1=11.96 | val_top5=19.57 | val_top10=20.65
Epoch 13 | loss=0.0072 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 14 | loss=0.0065 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 15 | loss=0.0059 | val_top1=15.22 | val_top5=19.57 | val_top10=20.65
Epoch 16 | loss=0.0054 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 17 | loss=0.0050 | val_top1=14.13 | val_top5=18.48 | val_top10=20.65
Epoch 18 | loss=0.0046 | val_top1=14.13 | val_top5=18.48 | val_top10=20.65
Epoch 19 | loss=0.0042 | val_top1=14.13 | val_top5=18.48 | val_top10=20.65
Epoch 20 | loss=0.0039 | val_top1=15.22 | val_top5=18.48 | val_top10=20.65

Best validation top1: 15.217391304347826
Test metrics: {'top1': 18.293216630196937, 'top5': 24.15754923413567, 'top10': 26.2582056892779}

================================================================================
[50/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1431 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 02 | loss=1.5892 | val_top1=9.78 | val_top5=11.96 | val_top10=11.96
Epoch 03 | loss=1.1579 | val_top1=10.87 | val_top5=11.96 | val_top10=13.04
Epoch 04 | loss=0.6616 | val_top1=9.78 | val_top5=11.96 | val_top10=14.13
Epoch 05 | loss=0.3692 | val_top1=9.78 | val_top5=13.04 | val_top10=13.04
Epoch 06 | loss=0.1401 | val_top1=8.70 | val_top5=9.78 | val_top10=11.96
Epoch 07 | loss=0.0498 | val_top1=9.78 | val_top5=13.04 | val_top10=16.30
Epoch 08 | loss=0.0194 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 09 | loss=0.0138 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 10 | loss=0.0115 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30
Epoch 11 | loss=0.0099 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30
Epoch 12 | loss=0.0088 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 13 | loss=0.0078 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 14 | loss=0.0071 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 15 | loss=0.0064 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 16 | loss=0.0058 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 17 | loss=0.0054 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 18 | loss=0.0049 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30
Epoch 19 | loss=0.0046 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30
Epoch 20 | loss=0.0042 | val_top1=10.87 | val_top5=16.30 | val_top10=16.30

Best validation top1: 10.869565217391305
Test metrics: {'top1': 13.654266958424508, 'top5': 17.417943107221006, 'top10': 19.474835886214443}

================================================================================
[51/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0121 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 02 | loss=1.5720 | val_top1=10.87 | val_top5=11.96 | val_top10=16.30
Epoch 03 | loss=1.2962 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 04 | loss=1.0721 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 05 | loss=0.8918 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39
Epoch 06 | loss=0.7489 | val_top1=11.96 | val_top5=11.96 | val_top10=17.39
Epoch 07 | loss=0.6347 | val_top1=11.96 | val_top5=11.96 | val_top10=16.30
Epoch 08 | loss=0.5419 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39
Epoch 09 | loss=0.4653 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 10 | loss=0.4015 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 11 | loss=0.3482 | val_top1=11.96 | val_top5=14.13 | val_top10=16.30
Epoch 12 | loss=0.3033 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 13 | loss=0.2656 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 14 | loss=0.2337 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 15 | loss=0.2067 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 16 | loss=0.1838 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 17 | loss=0.1644 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 18 | loss=0.1478 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 19 | loss=0.1337 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 20 | loss=0.1215 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48

Best validation top1: 11.956521739130435
Test metrics: {'top1': 17.111597374179432, 'top5': 21.88183807439825, 'top10': 24.551422319474835}

================================================================================
[52/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0104 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 02 | loss=1.5005 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 03 | loss=1.1676 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 04 | loss=0.9142 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39
Epoch 05 | loss=0.7221 | val_top1=11.96 | val_top5=11.96 | val_top10=17.39
Epoch 06 | loss=0.5770 | val_top1=11.96 | val_top5=11.96 | val_top10=15.22
Epoch 07 | loss=0.4657 | val_top1=11.96 | val_top5=11.96 | val_top10=15.22
Epoch 08 | loss=0.3787 | val_top1=11.96 | val_top5=11.96 | val_top10=15.22
Epoch 09 | loss=0.3105 | val_top1=11.96 | val_top5=11.96 | val_top10=14.13
Epoch 10 | loss=0.2570 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 11 | loss=0.2153 | val_top1=11.96 | val_top5=11.96 | val_top10=16.30
Epoch 12 | loss=0.1825 | val_top1=11.96 | val_top5=11.96 | val_top10=16.30
Epoch 13 | loss=0.1567 | val_top1=11.96 | val_top5=11.96 | val_top10=17.39
Epoch 14 | loss=0.1361 | val_top1=11.96 | val_top5=13.04 | val_top10=16.30
Epoch 15 | loss=0.1195 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39
Epoch 16 | loss=0.1060 | val_top1=11.96 | val_top5=14.13 | val_top10=18.48
Epoch 17 | loss=0.0948 | val_top1=11.96 | val_top5=14.13 | val_top10=18.48
Epoch 18 | loss=0.0854 | val_top1=11.96 | val_top5=14.13 | val_top10=18.48
Epoch 19 | loss=0.0774 | val_top1=11.96 | val_top5=15.22 | val_top10=19.57
Epoch 20 | loss=0.0706 | val_top1=11.96 | val_top5=16.30 | val_top10=19.57

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.76148796498906, 'top5': 21.181619256017505, 'top10': 24.026258205689278}

================================================================================
[53/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9804 | val_top1=11.96 | val_top5=11.96 | val_top10=14.13
Epoch 02 | loss=1.2038 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 03 | loss=0.6932 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 04 | loss=0.3183 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 05 | loss=0.1310 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 06 | loss=0.0594 | val_top1=11.96 | val_top5=16.30 | val_top10=16.30
Epoch 07 | loss=0.0343 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 08 | loss=0.0248 | val_top1=13.04 | val_top5=16.30 | val_top10=18.48
Epoch 09 | loss=0.0210 | val_top1=11.96 | val_top5=17.39 | val_top10=19.57
Epoch 10 | loss=0.0178 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 11 | loss=0.0158 | val_top1=13.04 | val_top5=17.39 | val_top10=19.57
Epoch 12 | loss=0.0144 | val_top1=13.04 | val_top5=19.57 | val_top10=19.57
Epoch 13 | loss=0.0126 | val_top1=13.04 | val_top5=19.57 | val_top10=19.57
Epoch 14 | loss=0.0112 | val_top1=14.13 | val_top5=19.57 | val_top10=19.57
Epoch 15 | loss=0.0101 | val_top1=13.04 | val_top5=19.57 | val_top10=19.57
Epoch 16 | loss=0.0093 | val_top1=13.04 | val_top5=19.57 | val_top10=19.57
Epoch 17 | loss=0.0084 | val_top1=14.13 | val_top5=19.57 | val_top10=19.57
Epoch 18 | loss=0.0076 | val_top1=15.22 | val_top5=19.57 | val_top10=19.57
Epoch 19 | loss=0.0071 | val_top1=15.22 | val_top5=19.57 | val_top10=19.57
Epoch 20 | loss=0.0068 | val_top1=15.22 | val_top5=19.57 | val_top10=19.57

Best validation top1: 15.217391304347826
Test metrics: {'top1': 18.687089715536104, 'top5': 22.844638949671772, 'top10': 24.770240700218817}

================================================================================
[54/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0674 | val_top1=8.70 | val_top5=10.87 | val_top10=11.96
Epoch 02 | loss=1.4717 | val_top1=8.70 | val_top5=11.96 | val_top10=15.22
Epoch 03 | loss=1.0581 | val_top1=8.70 | val_top5=13.04 | val_top10=13.04
Epoch 04 | loss=0.6820 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 05 | loss=0.3951 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 06 | loss=0.2015 | val_top1=8.70 | val_top5=10.87 | val_top10=16.30
Epoch 07 | loss=0.0874 | val_top1=10.87 | val_top5=14.13 | val_top10=19.57
Epoch 08 | loss=0.0378 | val_top1=10.87 | val_top5=16.30 | val_top10=21.74
Epoch 09 | loss=0.0241 | val_top1=11.96 | val_top5=18.48 | val_top10=21.74
Epoch 10 | loss=0.0184 | val_top1=10.87 | val_top5=19.57 | val_top10=21.74
Epoch 11 | loss=0.0160 | val_top1=10.87 | val_top5=19.57 | val_top10=21.74
Epoch 12 | loss=0.0139 | val_top1=10.87 | val_top5=19.57 | val_top10=21.74
Epoch 13 | loss=0.0120 | val_top1=10.87 | val_top5=19.57 | val_top10=21.74
Epoch 14 | loss=0.0107 | val_top1=11.96 | val_top5=19.57 | val_top10=21.74
Epoch 15 | loss=0.0096 | val_top1=11.96 | val_top5=19.57 | val_top10=21.74
Epoch 16 | loss=0.0090 | val_top1=11.96 | val_top5=19.57 | val_top10=21.74
Epoch 17 | loss=0.0080 | val_top1=11.96 | val_top5=18.48 | val_top10=21.74
Epoch 18 | loss=0.0076 | val_top1=13.04 | val_top5=18.48 | val_top10=21.74
Epoch 19 | loss=0.0070 | val_top1=13.04 | val_top5=17.39 | val_top10=21.74
Epoch 20 | loss=0.0065 | val_top1=13.04 | val_top5=18.48 | val_top10=21.74

Best validation top1: 13.043478260869565
Test metrics: {'top1': 17.024070021881837, 'top5': 21.53172866520788, 'top10': 23.50109409190372}

================================================================================
[55/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2272 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 02 | loss=1.8830 | val_top1=9.78 | val_top5=13.04 | val_top10=16.30
Epoch 03 | loss=1.6768 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 04 | loss=1.5202 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 05 | loss=1.3577 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 06 | loss=1.2416 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 07 | loss=1.1112 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 08 | loss=1.0176 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 09 | loss=0.9352 | val_top1=10.87 | val_top5=14.13 | val_top10=15.22
Epoch 10 | loss=0.8483 | val_top1=10.87 | val_top5=13.04 | val_top10=15.22
Epoch 11 | loss=0.7636 | val_top1=10.87 | val_top5=11.96 | val_top10=15.22
Epoch 12 | loss=0.6959 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 13 | loss=0.6281 | val_top1=10.87 | val_top5=11.96 | val_top10=13.04
Epoch 14 | loss=0.5670 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 15 | loss=0.5369 | val_top1=10.87 | val_top5=11.96 | val_top10=13.04
Epoch 16 | loss=0.4755 | val_top1=10.87 | val_top5=11.96 | val_top10=13.04
Epoch 17 | loss=0.4477 | val_top1=10.87 | val_top5=11.96 | val_top10=13.04
Epoch 18 | loss=0.4043 | val_top1=10.87 | val_top5=11.96 | val_top10=13.04
Epoch 19 | loss=0.3681 | val_top1=10.87 | val_top5=11.96 | val_top10=13.04
Epoch 20 | loss=0.3554 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04

Best validation top1: 10.869565217391305
Test metrics: {'top1': 16.542669584245075, 'top5': 20.35010940919037, 'top10': 22.75711159737418}

================================================================================
[56/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 2, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1414 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 02 | loss=1.7680 | val_top1=9.78 | val_top5=14.13 | val_top10=16.30
Epoch 03 | loss=1.5234 | val_top1=9.78 | val_top5=13.04 | val_top10=17.39
Epoch 04 | loss=1.3534 | val_top1=9.78 | val_top5=13.04 | val_top10=16.30
Epoch 05 | loss=1.1799 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 06 | loss=1.0277 | val_top1=10.87 | val_top5=14.13 | val_top10=19.57
Epoch 07 | loss=0.9392 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 08 | loss=0.8035 | val_top1=11.96 | val_top5=17.39 | val_top10=18.48
Epoch 09 | loss=0.7164 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 10 | loss=0.6648 | val_top1=10.87 | val_top5=15.22 | val_top10=19.57
Epoch 11 | loss=0.5781 | val_top1=11.96 | val_top5=14.13 | val_top10=18.48
Epoch 12 | loss=0.5309 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 13 | loss=0.4767 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 14 | loss=0.4226 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 15 | loss=0.3756 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 16 | loss=0.3432 | val_top1=10.87 | val_top5=17.39 | val_top10=17.39
Epoch 17 | loss=0.3204 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 18 | loss=0.2864 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 19 | loss=0.2582 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 20 | loss=0.2300 | val_top1=11.96 | val_top5=14.13 | val_top10=18.48

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.367614879649892, 'top5': 21.356673960612692, 'top10': 23.98249452954048}

================================================================================
[57/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9434 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 02 | loss=1.1764 | val_top1=11.96 | val_top5=13.04 | val_top10=18.48
Epoch 03 | loss=0.6006 | val_top1=11.96 | val_top5=13.04 | val_top10=15.22
Epoch 04 | loss=0.2606 | val_top1=11.96 | val_top5=13.04 | val_top10=14.13
Epoch 05 | loss=0.0895 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 06 | loss=0.0307 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 07 | loss=0.0146 | val_top1=10.87 | val_top5=17.39 | val_top10=19.57
Epoch 08 | loss=0.0119 | val_top1=11.96 | val_top5=16.30 | val_top10=20.65
Epoch 09 | loss=0.0102 | val_top1=11.96 | val_top5=17.39 | val_top10=21.74
Epoch 10 | loss=0.0089 | val_top1=11.96 | val_top5=17.39 | val_top10=21.74
Epoch 11 | loss=0.0079 | val_top1=13.04 | val_top5=17.39 | val_top10=21.74
Epoch 12 | loss=0.0071 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 13 | loss=0.0064 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 14 | loss=0.0058 | val_top1=13.04 | val_top5=18.48 | val_top10=20.65
Epoch 15 | loss=0.0053 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 16 | loss=0.0049 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 17 | loss=0.0045 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 18 | loss=0.0042 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 19 | loss=0.0039 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74
Epoch 20 | loss=0.0036 | val_top1=14.13 | val_top5=19.57 | val_top10=21.74

Best validation top1: 14.130434782608695
Test metrics: {'top1': 18.643326039387308, 'top5': 24.11378555798687, 'top10': 26.2582056892779}

================================================================================
[58/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1490 | val_top1=8.70 | val_top5=10.87 | val_top10=10.87
Epoch 02 | loss=1.7085 | val_top1=9.78 | val_top5=10.87 | val_top10=10.87
Epoch 03 | loss=1.3088 | val_top1=8.70 | val_top5=14.13 | val_top10=18.48
Epoch 04 | loss=0.9703 | val_top1=9.78 | val_top5=10.87 | val_top10=11.96
Epoch 05 | loss=0.5829 | val_top1=7.61 | val_top5=11.96 | val_top10=11.96
Epoch 06 | loss=0.3188 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 07 | loss=0.1496 | val_top1=10.87 | val_top5=13.04 | val_top10=14.13
Epoch 08 | loss=0.0624 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 09 | loss=0.0248 | val_top1=11.96 | val_top5=13.04 | val_top10=17.39
Epoch 10 | loss=0.0146 | val_top1=11.96 | val_top5=14.13 | val_top10=18.48
Epoch 11 | loss=0.0117 | val_top1=11.96 | val_top5=15.22 | val_top10=18.48
Epoch 12 | loss=0.0100 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 13 | loss=0.0089 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 14 | loss=0.0079 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 15 | loss=0.0071 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 16 | loss=0.0065 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 17 | loss=0.0059 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 18 | loss=0.0055 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 19 | loss=0.0051 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39
Epoch 20 | loss=0.0047 | val_top1=11.96 | val_top5=14.13 | val_top10=17.39

Best validation top1: 11.956521739130435
Test metrics: {'top1': 14.704595185995624, 'top5': 19.34354485776805, 'top10': 21.96936542669584}

================================================================================
[59/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9966 | val_top1=10.87 | val_top5=14.13 | val_top10=16.30
Epoch 02 | loss=1.5307 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 03 | loss=1.2394 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 04 | loss=1.0065 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 05 | loss=0.8212 | val_top1=13.04 | val_top5=16.30 | val_top10=17.39
Epoch 06 | loss=0.6760 | val_top1=11.96 | val_top5=16.30 | val_top10=17.39
Epoch 07 | loss=0.5614 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 08 | loss=0.4697 | val_top1=11.96 | val_top5=16.30 | val_top10=18.48
Epoch 09 | loss=0.3954 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 10 | loss=0.3346 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 11 | loss=0.2849 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 12 | loss=0.2442 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 13 | loss=0.2108 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 14 | loss=0.1835 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 15 | loss=0.1611 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 16 | loss=0.1427 | val_top1=10.87 | val_top5=14.13 | val_top10=18.48
Epoch 17 | loss=0.1273 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 18 | loss=0.1144 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 19 | loss=0.1034 | val_top1=10.87 | val_top5=16.30 | val_top10=17.39
Epoch 20 | loss=0.0940 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.805251641137854, 'top5': 21.575492341356675, 'top10': 24.288840262582056}

================================================================================
[60/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.0, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=1.9422 | val_top1=10.87 | val_top5=11.96 | val_top10=13.04
Epoch 02 | loss=1.3984 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 03 | loss=1.0514 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 04 | loss=0.8025 | val_top1=10.87 | val_top5=13.04 | val_top10=13.04
Epoch 05 | loss=0.6186 | val_top1=10.87 | val_top5=13.04 | val_top10=13.04
Epoch 06 | loss=0.4812 | val_top1=11.96 | val_top5=13.04 | val_top10=13.04
Epoch 07 | loss=0.3776 | val_top1=13.04 | val_top5=13.04 | val_top10=14.13
Epoch 08 | loss=0.2993 | val_top1=13.04 | val_top5=13.04 | val_top10=15.22
Epoch 09 | loss=0.2401 | val_top1=13.04 | val_top5=13.04 | val_top10=15.22
Epoch 10 | loss=0.1955 | val_top1=13.04 | val_top5=13.04 | val_top10=16.30
Epoch 11 | loss=0.1618 | val_top1=13.04 | val_top5=13.04 | val_top10=17.39
Epoch 12 | loss=0.1363 | val_top1=13.04 | val_top5=14.13 | val_top10=17.39
Epoch 13 | loss=0.1166 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 14 | loss=0.1012 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 15 | loss=0.0888 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 16 | loss=0.0788 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 17 | loss=0.0705 | val_top1=13.04 | val_top5=15.22 | val_top10=17.39
Epoch 18 | loss=0.0636 | val_top1=14.13 | val_top5=15.22 | val_top10=17.39
Epoch 19 | loss=0.0577 | val_top1=14.13 | val_top5=16.30 | val_top10=17.39
Epoch 20 | loss=0.0526 | val_top1=14.13 | val_top5=16.30 | val_top10=17.39

Best validation top1: 14.130434782608695
Test metrics: {'top1': 17.37417943107221, 'top5': 23.457330415754925, 'top10': 26.564551422319475}

================================================================================
[61/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0116 | val_top1=10.87 | val_top5=11.96 | val_top10=13.04
Epoch 02 | loss=1.2999 | val_top1=10.87 | val_top5=11.96 | val_top10=14.13
Epoch 03 | loss=0.8018 | val_top1=11.96 | val_top5=11.96 | val_top10=14.13
Epoch 04 | loss=0.4189 | val_top1=11.96 | val_top5=13.04 | val_top10=14.13
Epoch 05 | loss=0.2030 | val_top1=10.87 | val_top5=14.13 | val_top10=14.13
Epoch 06 | loss=0.0889 | val_top1=10.87 | val_top5=16.30 | val_top10=19.57
Epoch 07 | loss=0.0393 | val_top1=11.96 | val_top5=19.57 | val_top10=21.74
Epoch 08 | loss=0.0258 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 09 | loss=0.0200 | val_top1=15.22 | val_top5=19.57 | val_top10=20.65
Epoch 10 | loss=0.0168 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 11 | loss=0.0147 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 12 | loss=0.0125 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 13 | loss=0.0113 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 14 | loss=0.0102 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 15 | loss=0.0092 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 16 | loss=0.0087 | val_top1=13.04 | val_top5=19.57 | val_top10=21.74
Epoch 17 | loss=0.0076 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65
Epoch 18 | loss=0.0071 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 19 | loss=0.0067 | val_top1=13.04 | val_top5=19.57 | val_top10=20.65
Epoch 20 | loss=0.0061 | val_top1=14.13 | val_top5=19.57 | val_top10=20.65

Best validation top1: 15.217391304347826
Test metrics: {'top1': 17.199124726477024, 'top5': 22.450765864332602, 'top10': 24.63894967177243}

================================================================================
[62/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 0.0002, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.1214 | val_top1=7.61 | val_top5=8.70 | val_top10=14.13
Epoch 02 | loss=1.5778 | val_top1=6.52 | val_top5=7.61 | val_top10=9.78
Epoch 03 | loss=1.2416 | val_top1=7.61 | val_top5=9.78 | val_top10=10.87
Epoch 04 | loss=0.8644 | val_top1=7.61 | val_top5=9.78 | val_top10=11.96
Epoch 05 | loss=0.5499 | val_top1=7.61 | val_top5=13.04 | val_top10=14.13
Epoch 06 | loss=0.3179 | val_top1=9.78 | val_top5=13.04 | val_top10=14.13
Epoch 07 | loss=0.1564 | val_top1=9.78 | val_top5=11.96 | val_top10=13.04
Epoch 08 | loss=0.0715 | val_top1=8.70 | val_top5=15.22 | val_top10=15.22
Epoch 09 | loss=0.0307 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30
Epoch 10 | loss=0.0184 | val_top1=9.78 | val_top5=15.22 | val_top10=17.39
Epoch 11 | loss=0.0157 | val_top1=8.70 | val_top5=16.30 | val_top10=18.48
Epoch 12 | loss=0.0130 | val_top1=7.61 | val_top5=16.30 | val_top10=18.48
Epoch 13 | loss=0.0120 | val_top1=8.70 | val_top5=16.30 | val_top10=18.48
Epoch 14 | loss=0.0106 | val_top1=9.78 | val_top5=17.39 | val_top10=18.48
Epoch 15 | loss=0.0093 | val_top1=9.78 | val_top5=17.39 | val_top10=17.39
Epoch 16 | loss=0.0089 | val_top1=10.87 | val_top5=17.39 | val_top10=17.39
Epoch 17 | loss=0.0080 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 18 | loss=0.0073 | val_top1=13.04 | val_top5=17.39 | val_top10=18.48
Epoch 19 | loss=0.0066 | val_top1=13.04 | val_top5=17.39 | val_top10=17.39
Epoch 20 | loss=0.0063 | val_top1=13.04 | val_top5=17.39 | val_top10=17.39

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.01750547045952, 'top5': 20.787746170678336, 'top10': 22.844638949671772}

================================================================================
[63/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 1, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.2150 | val_top1=10.87 | val_top5=11.96 | val_top10=17.39
Epoch 02 | loss=1.8099 | val_top1=10.87 | val_top5=13.04 | val_top10=16.30
Epoch 03 | loss=1.5646 | val_top1=9.78 | val_top5=14.13 | val_top10=18.48
Epoch 04 | loss=1.3725 | val_top1=9.78 | val_top5=14.13 | val_top10=18.48
Epoch 05 | loss=1.2228 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 06 | loss=1.1147 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 07 | loss=0.9940 | val_top1=9.78 | val_top5=14.13 | val_top10=17.39
Epoch 08 | loss=0.8915 | val_top1=9.78 | val_top5=15.22 | val_top10=16.30
Epoch 09 | loss=0.7819 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 10 | loss=0.7082 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 11 | loss=0.6249 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 12 | loss=0.5687 | val_top1=10.87 | val_top5=15.22 | val_top10=15.22
Epoch 13 | loss=0.5143 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 14 | loss=0.4609 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 15 | loss=0.4288 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 16 | loss=0.3826 | val_top1=10.87 | val_top5=15.22 | val_top10=17.39
Epoch 17 | loss=0.3489 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 18 | loss=0.3291 | val_top1=10.87 | val_top5=15.22 | val_top10=16.30
Epoch 19 | loss=0.2911 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39
Epoch 20 | loss=0.2604 | val_top1=11.96 | val_top5=15.22 | val_top10=17.39

Best validation top1: 11.956521739130435
Test metrics: {'top1': 16.89277899343545, 'top5': 21.88183807439825, 'top10': 24.50765864332604}

================================================================================
[64/64] Running TemporalTransformerEncoder with config:
{'input_dim': 1024, 'model_dim': 512, 'output_dim': 256, 'num_heads': 8, 'ff_multiplier': 4, 'dropout': 0.1, 'lr': 1e-05, 'weight_decay': 0.0001, 'batch_size': 32, 'temperature': 0.1, 'num_layers': 2, 'pool': 'mean'}

/opt/anaconda3/envs/LLM/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

Epoch 01 | loss=2.0388 | val_top1=11.96 | val_top5=15.22 | val_top10=15.22
Epoch 02 | loss=1.6558 | val_top1=13.04 | val_top5=14.13 | val_top10=15.22
Epoch 03 | loss=1.3945 | val_top1=13.04 | val_top5=15.22 | val_top10=15.22
Epoch 04 | loss=1.1694 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 05 | loss=1.0093 | val_top1=11.96 | val_top5=15.22 | val_top10=16.30
Epoch 06 | loss=0.8603 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 07 | loss=0.7709 | val_top1=10.87 | val_top5=14.13 | val_top10=17.39
Epoch 08 | loss=0.6773 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 09 | loss=0.5753 | val_top1=10.87 | val_top5=15.22 | val_top10=18.48
Epoch 10 | loss=0.5158 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 11 | loss=0.4560 | val_top1=10.87 | val_top5=16.30 | val_top10=18.48
Epoch 12 | loss=0.3907 | val_top1=10.87 | val_top5=17.39 | val_top10=18.48
Epoch 13 | loss=0.3592 | val_top1=9.78 | val_top5=18.48 | val_top10=18.48
Epoch 14 | loss=0.3073 | val_top1=9.78 | val_top5=17.39 | val_top10=19.57
Epoch 15 | loss=0.2906 | val_top1=9.78 | val_top5=16.30 | val_top10=19.57
Epoch 16 | loss=0.2493 | val_top1=9.78 | val_top5=17.39 | val_top10=20.65
Epoch 17 | loss=0.2281 | val_top1=9.78 | val_top5=17.39 | val_top10=20.65
Epoch 18 | loss=0.2128 | val_top1=9.78 | val_top5=14.13 | val_top10=21.74
Epoch 19 | loss=0.1893 | val_top1=9.78 | val_top5=15.22 | val_top10=20.65
Epoch 20 | loss=0.1696 | val_top1=9.78 | val_top5=17.39 | val_top10=20.65

Best validation top1: 13.043478260869565
Test metrics: {'top1': 16.717724288840262, 'top5': 20.48140043763676, 'top10': 22.669584245076585}

,exp_name,input_dim,model_dim,output_dim,num_heads,ff_multiplier,dropout,lr,weight_decay,batch_size,...,num_layers,pool,best_val_top1,val_top1,val_top5,val_top10,test_top1,test_top5,test_top10,seed
48,temporal_transformer_encoder_dim512_o256_heads...,1024,512,256,8,2,0.0,0.0002,0.0001,32,...,1,mean,16.304348,16.304348,19.565217,20.652174,19.824945,24.638950,26.695842,1990
24,temporal_transformer_encoder_dim256_o256_heads...,1024,256,256,8,4,0.0,0.0002,0.0001,32,...,1,mean,14.130435,14.130435,19.565217,22.826087,19.649891,24.551422,27.308534,1990
64,temporal_transformer_encoder_dim256_o256_heads...,1024,256,256,4,2,0.0,0.0002,0.0001,32,...,1,mean,14.130435,14.130435,19.565217,20.652174,19.606127,24.726477,27.089716,42
144,temporal_transformer_encoder_dim256_o256_heads...,1024,256,256,8,2,0.0,0.0002,0.0001,32,...,1,mean,18.478261,18.478261,20.652174,22.826087,19.518600,24.245077,26.433260,2024
120,temporal_transformer_encoder_dim512_o256_heads...,1024,512,256,8,4,0.0,0.0002,0.0001,32,...,1,mean,14.130435,14.130435,20.652174,22.826087,19.387309,24.245077,26.433260,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,temporal_transformer_encoder_dim512_o256_heads...,1024,512,256,8,2,0.0,0.0002,0.0001,32,...,2,mean,10.869565,10.869565,11.956522,13.043478,13.654267,17.417943,19.474836,2024
57,temporal_transformer_encoder_dim512_o256_heads...,1024,512,256,8,4,0.0,0.0002,0.0001,32,...,2,mean,11.956522,11.956522,13.043478,15.217391,13.566740,16.892779,19.518600,1990
105,temporal_transformer_encoder_dim512_o256_heads...,1024,512,256,4,4,0.0,0.0002,0.0001,32,...,2,mean,9.782609,9.782609,10.869565,10.869565,13.435449,16.105033,17.986871,42
125,temporal_transformer_encoder_dim512_o256_heads...,1024,512,256,8,4,0.1,0.0002,0.0001,32,...,2,mean,13.043478,13.043478,13.043478,14.130435,13.172867,16.805252,18.905908,42
61,temporal_transformer_encoder_dim512_o256_heads...,1024,512,256,8,4,0.1,0.0002,0.0001,32,...,2,mean,9.782609,9.782609,9.782609,11.956522,12.647702,14.748359,16.236324,1990

In [5]:
import pandas as pd

csv_path = ROOT / "results/task3_cislr/temporal_transformer_encoder_gridsearch_results_with_seeds.csv"

df = pd.read_csv(csv_path)

# remove failed runs
df = df[df["error"].isna()].copy()

print("Remaining successful runs:", len(df))
df.head()

ParserError: Error tokenizing data. C error: Expected 15 fields in line 5, saw 21

In [6]:
csv_path = ROOT / "results/task3_cislr/temporal_transformer_encoder_gridsearch_results_with_seeds.csv"

with open(csv_path, "r", encoding="utf-8") as f:
    for i, line in enumerate(f, start=1):
        n_fields = line.count(",") + 1
        if n_fields != 15:
            print(f"Line {i}: fields={n_fields}")
            print(line[:500])
            print("-" * 100)

Line 5: fields=21
temporal_transformer_encoder_dim256_o256_heads4_ff2_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,256,256,4,2,0.0,0.0002,0.0001,32,0.1,1,mean,15.217391304347826,15.217391304347826,20.652173913043477,21.73913043478261,19.12472647702407,24.50765864332604,26.958424507658645,1990

----------------------------------------------------------------------------------------------------
Line 6: fields=21
temporal_transformer_encoder_dim256_o256_heads4_ff2_drop0p0_lr0.0002_wd0.0001_temp0p1_layers2_seed1990,1024,256,256,4,2,0.0,0.0002,0.0001,32,0.1,2,mean,15.217391304347826,15.217391304347826,18.47826086956522,21.73913043478261,18.643326039387308,23.150984682713347,25.601750547045953,1990

----------------------------------------------------------------------------------------------------
Line 7: fields=21
temporal_transformer_encoder_dim256_o256_heads4_ff2_drop0p0_lr1e-05_wd0.0001_temp0p1_layers1_seed1990,1024,256,256,4,2,0.0,1e-05,0.0001,32,0.1,1,mean,10.869565217391305,10.869565217391305,16.304347826086957,17.391304347826086,16.192560175054705,19.956236323851204,22.01312910284464,1990

----------------------------------------------------------------------------------------------------
Line 8: fields=21
temporal_transformer_encoder_dim256_o256_heads4_ff2_drop0p0_lr1e-05_wd0.0001_temp0p1_layers2_seed1990,1024,256,256,4,2,0.0,1e-05,0.0001,32,0.1,2,mean,11.956521739130435,11.956521739130435,13.043478260869565,16.304347826086957,15.886214442013129,20.13129102844639,22.188183807439824,1990

----------------------------------------------------------------------------------------------------
Line 9: fields=21
temporal_transformer_encoder_dim256_o256_heads4_ff2_drop0p1_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,256,256,4,2,0.1,0.0002,0.0001,32,0.1,1,mean,13.043478260869565,13.043478260869565,16.304347826086957,18.47826086956522,17.330415754923415,23.150984682713347,26.2582056892779,1990

----------------------------------------------------------------------------------------------------
Line 10: fields=21
temporal_transformer_encoder_dim256_o256_heads4_ff2_drop0p1_lr0.0002_wd0.0001_temp0p1_layers2_seed1990,1024,256,256,4,2,0.1,0.0002,0.0001,32,0.1,2,mean,16.304347826086957,16.304347826086957,17.391304347826086,19.565217391304348,16.63019693654267,21.61925601750547,24.24507658643326,1990

----------------------------------------------------------------------------------------------------
Line 11: fields=21
temporal_transformer_encoder_dim256_o256_heads4_ff2_drop0p1_lr1e-05_wd0.0001_temp0p1_layers1_seed1990,1024,256,256,4,2,0.1,1e-05,0.0001,32,0.1,1,mean,13.043478260869565,13.043478260869565,14.130434782608695,18.47826086956522,15.886214442013129,19.60612691466083,21.444201312910284,1990

----------------------------------------------------------------------------------------------------
Line 12: fields=21
temporal_transformer_encoder_dim256_o256_heads4_ff2_drop0p1_lr1e-05_wd0.0001_temp0p1_layers2_seed1990,1024,256,256,4,2,0.1,1e-05,0.0001,32,0.1,2,mean,11.956521739130435,11.956521739130435,14.130434782608695,16.304347826086957,15.75492341356674,19.212253829321664,21.13785557986871,1990

----------------------------------------------------------------------------------------------------
Line 13: fields=21
temporal_transformer_encoder_dim256_o256_heads4_ff4_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,256,256,4,4,0.0,0.0002,0.0001,32,0.1,1,mean,14.130434782608695,14.130434782608695,17.391304347826086,19.565217391304348,16.805251641137854,23.10722100656455,26.652078774617067,1990

----------------------------------------------------------------------------------------------------
Line 14: fields=21
temporal_transformer_encoder_dim256_o256_heads4_ff4_drop0p0_lr0.0002_wd0.0001_temp0p1_layers2_seed1990,1024,256,256,4,4,0.0,0.0002,0.0001,32,0.1,2,mean,13.043478260869565,13.043478260869565,18.47826086956522,21.73913043478261,17.505470459518598,22.669584245076585,24.945295404814004,1990

----------------------------------------------------------------------------------------------------
Line 15: fields=21
temporal_transformer_encoder_dim256_o256_heads4_ff4_drop0p0_lr1e-05_wd0.0001_temp0p1_layers1_seed1990,1024,256,256,4,4,0.0,1e-05,0.0001,32,0.1,1,mean,14.130434782608695,14.130434782608695,14.130434782608695,17.391304347826086,17.111597374179432,22.494529540481402,24.9890590809628,1990

----------------------------------------------------------------------------------------------------
Line 16: fields=21
temporal_transformer_encoder_dim256_o256_heads4_ff4_drop0p0_lr1e-05_wd0.0001_temp0p1_layers2_seed1990,1024,256,256,4,4,0.0,1e-05,0.0001,32,0.1,2,mean,10.869565217391305,10.869565217391305,17.391304347826086,18.47826086956522,16.14879649890591,19.781181619256017,21.61925601750547,1990

----------------------------------------------------------------------------------------------------
Line 17: fields=21
temporal_transformer_encoder_dim256_o256_heads4_ff4_drop0p1_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,256,256,4,4,0.1,0.0002,0.0001,32,0.1,1,mean,11.956521739130435,11.956521739130435,14.130434782608695,15.217391304347826,15.886214442013129,19.693654266958426,21.575492341356675,1990

----------------------------------------------------------------------------------------------------
Line 18: fields=21
temporal_transformer_encoder_dim256_o256_heads4_ff4_drop0p1_lr0.0002_wd0.0001_temp0p1_layers2_seed1990,1024,256,256,4,4,0.1,0.0002,0.0001,32,0.1,2,mean,15.217391304347826,15.217391304347826,17.391304347826086,19.565217391304348,17.505470459518598,22.450765864332602,24.9890590809628,1990

----------------------------------------------------------------------------------------------------
Line 19: fields=21
temporal_transformer_encoder_dim256_o256_heads4_ff4_drop0p1_lr1e-05_wd0.0001_temp0p1_layers1_seed1990,1024,256,256,4,4,0.1,1e-05,0.0001,32,0.1,1,mean,10.869565217391305,10.869565217391305,14.130434782608695,15.217391304347826,15.711159737417944,19.299781181619256,21.53172866520788,1990

----------------------------------------------------------------------------------------------------
Line 20: fields=21
temporal_transformer_encoder_dim256_o256_heads4_ff4_drop0p1_lr1e-05_wd0.0001_temp0p1_layers2_seed1990,1024,256,256,4,4,0.1,1e-05,0.0001,32,0.1,2,mean,10.869565217391305,10.869565217391305,15.217391304347826,16.304347826086957,15.536105032822757,19.91247264770241,22.144420131291028,1990

----------------------------------------------------------------------------------------------------
Line 21: fields=21
temporal_transformer_encoder_dim256_o256_heads8_ff2_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,256,256,8,2,0.0,0.0002,0.0001,32,0.1,1,mean,14.130434782608695,14.130434782608695,20.652173913043477,21.73913043478261,18.949671772428886,24.770240700218817,26.87089715536105,1990

----------------------------------------------------------------------------------------------------
Line 22: fields=21
temporal_transformer_encoder_dim256_o256_heads8_ff2_drop0p0_lr0.0002_wd0.0001_temp0p1_layers2_seed1990,1024,256,256,8,2,0.0,0.0002,0.0001,32,0.1,2,mean,14.130434782608695,14.130434782608695,21.73913043478261,25.0,17.549234135667398,23.23851203501094,26.52078774617068,1990

----------------------------------------------------------------------------------------------------
Line 23: fields=21
temporal_transformer_encoder_dim256_o256_heads8_ff2_drop0p0_lr1e-05_wd0.0001_temp0p1_layers1_seed1990,1024,256,256,8,2,0.0,1e-05,0.0001,32,0.1,1,mean,11.956521739130435,11.956521739130435,14.130434782608695,14.130434782608695,17.067833698030636,21.094091903719914,23.544857768052516,1990

----------------------------------------------------------------------------------------------------
Line 24: fields=21
temporal_transformer_encoder_dim256_o256_heads8_ff2_drop0p0_lr1e-05_wd0.0001_temp0p1_layers2_seed1990,1024,256,256,8,2,0.0,1e-05,0.0001,32,0.1,2,mean,11.956521739130435,11.956521739130435,16.304347826086957,16.304347826086957,15.62363238512035,19.693654266958426,22.056892778993436,1990

----------------------------------------------------------------------------------------------------
Line 25: fields=21
temporal_transformer_encoder_dim256_o256_heads8_ff2_drop0p1_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,256,256,8,2,0.1,0.0002,0.0001,32,0.1,1,mean,17.391304347826086,17.391304347826086,18.47826086956522,19.565217391304348,19.080962800875273,24.026258205689278,25.951859956236323,1990

----------------------------------------------------------------------------------------------------
Line 26: fields=21
temporal_transformer_encoder_dim256_o256_heads8_ff2_drop0p1_lr0.0002_wd0.0001_temp0p1_layers2_seed1990,1024,256,256,8,2,0.1,0.0002,0.0001,32,0.1,2,mean,10.869565217391305,10.869565217391305,17.391304347826086,18.47826086956522,16.936542669584245,22.188183807439824,24.332603938730852,1990

----------------------------------------------------------------------------------------------------
Line 27: fields=21
temporal_transformer_encoder_dim256_o256_heads8_ff2_drop0p1_lr1e-05_wd0.0001_temp0p1_layers1_seed1990,1024,256,256,8,2,0.1,1e-05,0.0001,32,0.1,1,mean,11.956521739130435,11.956521739130435,14.130434782608695,16.304347826086957,16.01750547045952,19.693654266958426,21.13785557986871,1990

----------------------------------------------------------------------------------------------------
Line 28: fields=21
temporal_transformer_encoder_dim256_o256_heads8_ff2_drop0p1_lr1e-05_wd0.0001_temp0p1_layers2_seed1990,1024,256,256,8,2,0.1,1e-05,0.0001,32,0.1,2,mean,11.956521739130435,11.956521739130435,15.217391304347826,18.47826086956522,15.711159737417944,20.0,22.188183807439824,1990

----------------------------------------------------------------------------------------------------
Line 29: fields=21
temporal_transformer_encoder_dim256_o256_heads8_ff4_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,256,256,8,4,0.0,0.0002,0.0001,32,0.1,1,mean,14.130434782608695,14.130434782608695,19.565217391304348,22.82608695652174,19.64989059080963,24.551422319474835,27.308533916849015,1990

----------------------------------------------------------------------------------------------------
Line 30: fields=21
temporal_transformer_encoder_dim256_o256_heads8_ff4_drop0p0_lr0.0002_wd0.0001_temp0p1_layers2_seed1990,1024,256,256,8,4,0.0,0.0002,0.0001,32,0.1,2,mean,14.130434782608695,14.130434782608695,18.47826086956522,23.91304347826087,18.424507658643325,23.150984682713347,25.339168490153174,1990

----------------------------------------------------------------------------------------------------
Line 31: fields=21
temporal_transformer_encoder_dim256_o256_heads8_ff4_drop0p0_lr1e-05_wd0.0001_temp0p1_layers1_seed1990,1024,256,256,8,4,0.0,1e-05,0.0001,32,0.1,1,mean,13.043478260869565,13.043478260869565,15.217391304347826,17.391304347826086,17.199124726477024,21.400437636761488,24.37636761487965,1990

----------------------------------------------------------------------------------------------------
Line 32: fields=21
temporal_transformer_encoder_dim256_o256_heads8_ff4_drop0p0_lr1e-05_wd0.0001_temp0p1_layers2_seed1990,1024,256,256,8,4,0.0,1e-05,0.0001,32,0.1,2,mean,11.956521739130435,11.956521739130435,16.304347826086957,16.304347826086957,16.061269146608314,20.568927789934353,22.888402625820568,1990

----------------------------------------------------------------------------------------------------
Line 33: fields=21
temporal_transformer_encoder_dim256_o256_heads8_ff4_drop0p1_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,256,256,8,4,0.1,0.0002,0.0001,32,0.1,1,mean,16.304347826086957,16.304347826086957,20.652173913043477,25.0,18.11816192560175,23.23851203501094,26.433260393873084,1990

----------------------------------------------------------------------------------------------------
Line 34: fields=21
temporal_transformer_encoder_dim256_o256_heads8_ff4_drop0p1_lr0.0002_wd0.0001_temp0p1_layers2_seed1990,1024,256,256,8,4,0.1,0.0002,0.0001,32,0.1,2,mean,13.043478260869565,13.043478260869565,19.565217391304348,20.652173913043477,16.805251641137854,22.01312910284464,24.026258205689278,1990

----------------------------------------------------------------------------------------------------
Line 35: fields=21
temporal_transformer_encoder_dim256_o256_heads8_ff4_drop0p1_lr1e-05_wd0.0001_temp0p1_layers1_seed1990,1024,256,256,8,4,0.1,1e-05,0.0001,32,0.1,1,mean,11.956521739130435,11.956521739130435,16.304347826086957,18.47826086956522,16.323851203501093,21.48796498905908,24.15754923413567,1990

----------------------------------------------------------------------------------------------------
Line 36: fields=21
temporal_transformer_encoder_dim256_o256_heads8_ff4_drop0p1_lr1e-05_wd0.0001_temp0p1_layers2_seed1990,1024,256,256,8,4,0.1,1e-05,0.0001,32,0.1,2,mean,13.043478260869565,13.043478260869565,15.217391304347826,18.47826086956522,16.49890590809628,20.612691466083152,23.36980306345733,1990

----------------------------------------------------------------------------------------------------
Line 37: fields=21
temporal_transformer_encoder_dim512_o256_heads4_ff2_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,512,256,4,2,0.0,0.0002,0.0001,32,0.1,1,mean,14.130434782608695,14.130434782608695,17.391304347826086,23.91304347826087,18.38074398249453,23.588621444201312,26.783369803063458,1990

----------------------------------------------------------------------------------------------------
Line 38: fields=21
temporal_transformer_encoder_dim512_o256_heads4_ff2_drop0p0_lr0.0002_wd0.0001_temp0p1_layers2_seed1990,1024,512,256,4,2,0.0,0.0002,0.0001,32,0.1,2,mean,13.043478260869565,13.043478260869565,16.304347826086957,19.565217391304348,16.14879649890591,20.568927789934353,23.632385120350108,1990

----------------------------------------------------------------------------------------------------
Line 39: fields=21
temporal_transformer_encoder_dim512_o256_heads4_ff2_drop0p0_lr1e-05_wd0.0001_temp0p1_layers1_seed1990,1024,512,256,4,2,0.0,1e-05,0.0001,32,0.1,1,mean,11.956521739130435,11.956521739130435,16.304347826086957,19.565217391304348,16.717724288840262,22.450765864332602,25.38293216630197,1990

----------------------------------------------------------------------------------------------------
Line 40: fields=21
temporal_transformer_encoder_dim512_o256_heads4_ff2_drop0p0_lr1e-05_wd0.0001_temp0p1_layers2_seed1990,1024,512,256,4,2,0.0,1e-05,0.0001,32,0.1,2,mean,11.956521739130435,11.956521739130435,13.043478260869565,15.217391304347826,16.936542669584245,21.794310722100658,23.676148796498907,1990

----------------------------------------------------------------------------------------------------
Line 41: fields=21
temporal_transformer_encoder_dim512_o256_heads4_ff2_drop0p1_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,512,256,4,2,0.1,0.0002,0.0001,32,0.1,1,mean,15.217391304347826,15.217391304347826,18.47826086956522,20.652173913043477,17.899343544857768,23.41356673960613,25.689277899343544,1990

----------------------------------------------------------------------------------------------------
Line 42: fields=21
temporal_transformer_encoder_dim512_o256_heads4_ff2_drop0p1_lr0.0002_wd0.0001_temp0p1_layers2_seed1990,1024,512,256,4,2,0.1,0.0002,0.0001,32,0.1,2,mean,11.956521739130435,11.956521739130435,15.217391304347826,18.47826086956522,16.849015317286653,20.700218818380744,23.150984682713347,1990

----------------------------------------------------------------------------------------------------
Line 43: fields=21
temporal_transformer_encoder_dim512_o256_heads4_ff2_drop0p1_lr1e-05_wd0.0001_temp0p1_layers1_seed1990,1024,512,256,4,2,0.1,1e-05,0.0001,32,0.1,1,mean,11.956521739130435,11.956521739130435,13.043478260869565,17.391304347826086,16.10503282275711,21.53172866520788,24.551422319474835,1990

----------------------------------------------------------------------------------------------------
Line 44: fields=21
temporal_transformer_encoder_dim512_o256_heads4_ff2_drop0p1_lr1e-05_wd0.0001_temp0p1_layers2_seed1990,1024,512,256,4,2,0.1,1e-05,0.0001,32,0.1,2,mean,10.869565217391305,10.869565217391305,14.130434782608695,17.391304347826086,16.367614879649892,20.525164113785557,22.75711159737418,1990

----------------------------------------------------------------------------------------------------
Line 45: fields=21
temporal_transformer_encoder_dim512_o256_heads4_ff4_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,512,256,4,4,0.0,0.0002,0.0001,32,0.1,1,mean,16.304347826086957,16.304347826086957,19.565217391304348,25.0,18.424507658643325,23.676148796498907,26.2582056892779,1990

----------------------------------------------------------------------------------------------------
Line 46: fields=21
temporal_transformer_encoder_dim512_o256_heads4_ff4_drop0p0_lr0.0002_wd0.0001_temp0p1_layers2_seed1990,1024,512,256,4,4,0.0,0.0002,0.0001,32,0.1,2,mean,10.869565217391305,10.869565217391305,16.304347826086957,16.304347826086957,14.266958424507658,19.25601750547046,21.356673960612692,1990

----------------------------------------------------------------------------------------------------
Line 47: fields=21
temporal_transformer_encoder_dim512_o256_heads4_ff4_drop0p0_lr1e-05_wd0.0001_temp0p1_layers1_seed1990,1024,512,256,4,4,0.0,1e-05,0.0001,32,0.1,1,mean,11.956521739130435,11.956521739130435,16.304347826086957,17.391304347826086,16.63019693654267,21.00656455142232,23.326039387308533,1990

----------------------------------------------------------------------------------------------------
Line 48: fields=21
temporal_transformer_encoder_dim512_o256_heads4_ff4_drop0p0_lr1e-05_wd0.0001_temp0p1_layers2_seed1990,1024,512,256,4,4,0.0,1e-05,0.0001,32,0.1,2,mean,11.956521739130435,11.956521739130435,17.391304347826086,19.565217391304348,16.805251641137854,21.2253829321663,23.807439824945295,1990

----------------------------------------------------------------------------------------------------
Line 49: fields=21
temporal_transformer_encoder_dim512_o256_heads4_ff4_drop0p1_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,512,256,4,4,0.1,0.0002,0.0001,32,0.1,1,mean,16.304347826086957,16.304347826086957,20.652173913043477,20.652173913043477,18.46827133479212,22.888402625820568,24.857768052516413,1990

----------------------------------------------------------------------------------------------------
Line 50: fields=21
temporal_transformer_encoder_dim512_o256_heads4_ff4_drop0p1_lr0.0002_wd0.0001_temp0p1_layers2_seed1990,1024,512,256,4,4,0.1,0.0002,0.0001,32,0.1,2,mean,11.956521739130435,11.956521739130435,15.217391304347826,17.391304347826086,15.22975929978118,19.781181619256017,22.23194748358862,1990

----------------------------------------------------------------------------------------------------
Line 51: fields=21
temporal_transformer_encoder_dim512_o256_heads4_ff4_drop0p1_lr1e-05_wd0.0001_temp0p1_layers1_seed1990,1024,512,256,4,4,0.1,1e-05,0.0001,32,0.1,1,mean,13.043478260869565,13.043478260869565,15.217391304347826,16.304347826086957,16.717724288840262,22.01312910284464,24.9890590809628,1990

----------------------------------------------------------------------------------------------------
Line 52: fields=21
temporal_transformer_encoder_dim512_o256_heads4_ff4_drop0p1_lr1e-05_wd0.0001_temp0p1_layers2_seed1990,1024,512,256,4,4,0.1,1e-05,0.0001,32,0.1,2,mean,11.956521739130435,11.956521739130435,14.130434782608695,15.217391304347826,16.49890590809628,21.61925601750547,24.90153172866521,1990

----------------------------------------------------------------------------------------------------
Line 53: fields=21
temporal_transformer_encoder_dim512_o256_heads8_ff2_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990,1024,512,256,8,2,0.0,0.0002,0.0001,32,0.1,1,mean,16.304347826086957,16.304347826086957,19.565217391304348,20.652173913043477,19.824945295404813,24.63894967177243,26.695842450765863,1990

----------------------------------------------------------------------------------------------------
Line 54: fields=21

In [7]:
import pandas as pd

csv_path = ROOT / "results/task3_cislr/temporal_transformer_encoder_gridsearch_results_with_seeds.csv"

cols = [
    "exp_name",
    "input_dim",
    "model_dim",
    "output_dim",
    "num_heads",
    "ff_multiplier",
    "dropout",
    "lr",
    "weight_decay",
    "batch_size",
    "temperature",
    "num_layers",
    "pool",
    "best_val_top1",
    "val_top1",
    "val_top5",
    "val_top10",
    "test_top1",
    "test_top5",
    "test_top10",
    "seed",
]

df = pd.read_csv(csv_path, names=cols, header=0)

print("Loaded rows:", len(df))
print(df.head())
print(df.columns.tolist())

ParserError: Error tokenizing data. C error: Expected 15 fields in line 5, saw 21

In [12]:
import csv
from pathlib import Path
import pandas as pd
import math

raw_csv = ROOT / "results/task3_cislr/temporal_transformer_encoder_gridsearch_results_with_seeds.csv"
clean_csv = ROOT / "results/task3_cislr/temporal_transformer_encoder_gridsearch_results_clean.csv"

expected_cols = [
    "exp_name",
    "input_dim",
    "model_dim",
    "output_dim",
    "num_heads",
    "ff_multiplier",
    "dropout",
    "lr",
    "weight_decay",
    "batch_size",
    "temperature",
    "num_layers",
    "pool",
    "best_val_top1",
    "val_top1",
    "val_top5",
    "val_top10",
    "test_top1",
    "test_top5",
    "test_top10",
    "seed",
    "error",
]

numeric_cols = [
    "input_dim",
    "model_dim",
    "output_dim",
    "num_heads",
    "ff_multiplier",
    "dropout",
    "lr",
    "weight_decay",
    "batch_size",
    "temperature",
    "num_layers",
    "best_val_top1",
    "val_top1",
    "val_top5",
    "val_top10",
    "test_top1",
    "test_top5",
    "test_top10",
    "seed",
]

def to_num(x):
    if x is None:
        return None
    x = str(x).strip()
    if x == "" or x.lower() == "nan":
        return None
    try:
        val = float(x)
        return val
    except Exception:
        return None

def normalize_error(x):
    if x is None:
        return None
    x = str(x).strip()
    if x == "" or x.lower() == "nan":
        return None
    return x

rows = []
bad_rows = []

with open(raw_csv, "r", encoding="utf-8", newline="") as f:
    reader = csv.reader(f)
    header = next(reader, None)

    for line_idx, row in enumerate(reader, start=2):
        # Skip empty lines
        if not row or all(str(x).strip() == "" for x in row):
            continue

        # Case A: already correct width
        if len(row) == len(expected_cols):
            rec = dict(zip(expected_cols, row))
        # Case B: one extra leading unnamed index column
        elif len(row) == len(expected_cols) + 1:
            rec = dict(zip(expected_cols, row[1:]))
        # Case C: malformed rows from earlier error-only logging
        elif len(row) == 15:
            # exp_name ... pool, seed, error
            rec = {
                "exp_name": row[0],
                "input_dim": row[1],
                "model_dim": row[2],
                "output_dim": row[3],
                "num_heads": row[4],
                "ff_multiplier": row[5],
                "dropout": row[6],
                "lr": row[7],
                "weight_decay": row[8],
                "batch_size": row[9],
                "temperature": row[10],
                "num_layers": row[11],
                "pool": row[12],
                "best_val_top1": None,
                "val_top1": None,
                "val_top5": None,
                "val_top10": None,
                "test_top1": None,
                "test_top5": None,
                "test_top10": None,
                "seed": row[13],
                "error": row[14],
            }
        else:
            bad_rows.append({"line_idx": line_idx, "raw": row, "len": len(row)})
            continue

        # Clean types
        for col in numeric_cols:
            rec[col] = to_num(rec.get(col))

        rec["pool"] = None if rec.get("pool") in ("", None) else str(rec["pool"]).strip()
        rec["exp_name"] = None if rec.get("exp_name") in ("", None) else str(rec["exp_name"]).strip()
        rec["error"] = normalize_error(rec.get("error"))

        # Cast integer-like numeric fields
        for col in ["input_dim", "model_dim", "output_dim", "num_heads", "ff_multiplier", "batch_size", "num_layers", "seed"]:
            if rec[col] is not None and not math.isnan(rec[col]):
                rec[col] = int(rec[col])

        rows.append(rec)

df_clean = pd.DataFrame(rows, columns=expected_cols)

# Drop exact duplicates
df_clean = df_clean.drop_duplicates()

# Save cleaned file
df_clean.to_csv(clean_csv, index=False)

print("Clean rows:", len(df_clean))
print("Bad/unparsed rows:", len(bad_rows))
if bad_rows:
    print("Example bad row:", bad_rows[0])

display(df_clean.head())

Clean rows: 2
Bad/unparsed rows: 192
Example bad row: {'line_idx': 5, 'raw': ['temporal_transformer_encoder_dim256_o256_heads4_ff2_drop0p0_lr0.0002_wd0.0001_temp0p1_layers1_seed1990', '1024', '256', '256', '4', '2', '0.0', '0.0002', '0.0001', '32', '0.1', '1', 'mean', '15.217391304347826', '15.217391304347826', '20.652173913043477', '21.73913043478261', '19.12472647702407', '24.50765864332604', '26.958424507658645', '1990'], 'len': 21}

,exp_name,input_dim,model_dim,output_dim,num_heads,ff_multiplier,dropout,lr,weight_decay,batch_size,...,pool,best_val_top1,val_top1,val_top5,val_top10,test_top1,test_top5,test_top10,seed,error
0,temporal_transformer_encoder_dim256_o256_heads...,1024,256,256,4,2,0.0,0.0002,0.0001,32,...,mean,None,None,None,None,None,None,None,1990,'TemporalTransformerEncoder' object has no att...
2,temporal_transformer_encoder_dim256_o256_heads...,1024,256,256,4,2,0.0,0.0002,0.0001,32,...,mean,None,None,None,None,None,None,None,1990,masked_pool() got an unexpected keyword argume...

In [13]:
summary_csv = ROOT / "results/task3_cislr/temporal_transformer_gridsearch_summary.csv"

df = pd.read_csv(clean_csv)

# Successful runs only
df_ok = df[df["error"].isna()].copy()

group_cols = [
    "input_dim",
    "model_dim",
    "output_dim",
    "num_heads",
    "ff_multiplier",
    "dropout",
    "lr",
    "weight_decay",
    "batch_size",
    "temperature",
    "num_layers",
    "pool",
]

summary = (
    df_ok.groupby(group_cols, dropna=False)
    .agg(
        runs=("seed", "count"),
        mean_val_top1=("val_top1", "mean"),
        std_val_top1=("val_top1", "std"),
        mean_test_top1=("test_top1", "mean"),
        std_test_top1=("test_top1", "std"),
        mean_test_top5=("test_top5", "mean"),
        std_test_top5=("test_top5", "std"),
        mean_test_top10=("test_top10", "mean"),
        std_test_top10=("test_top10", "std"),
        best_single_run_top1=("test_top1", "max"),
    )
    .reset_index()
    .sort_values(["mean_test_top1", "mean_test_top5", "mean_test_top10"], ascending=False)
)

summary.to_csv(summary_csv, index=False)

print("Successful runs:", len(df_ok))
print("Unique configs:", len(summary))
display(summary.head(10))

Successful runs: 0
Unique configs: 0

Empty DataFrame
Columns: [input_dim, model_dim, output_dim, num_heads, ff_multiplier, dropout, lr, weight_decay, batch_size, temperature, num_layers, pool, runs, mean_val_top1, std_val_top1, mean_test_top1, std_test_top1, mean_test_top5, std_test_top5, mean_test_top10, std_test_top10, best_single_run_top1]
Index: []

[0 rows x 22 columns]

In [11]:
topk = 10  # change if needed

summary_md = summary.copy()

for col in [
    "mean_test_top1", "std_test_top1",
    "mean_test_top5", "std_test_top5",
    "mean_test_top10", "std_test_top10",
    "best_single_run_top1",
]:
    summary_md[col] = summary_md[col].round(2)

summary_md["Top1 (mean±std)"] = summary_md.apply(
    lambda r: f"{r['mean_test_top1']:.2f} ± {0.0 if pd.isna(r['std_test_top1']) else r['std_test_top1']:.2f}",
    axis=1
)
summary_md["Top5 (mean±std)"] = summary_md.apply(
    lambda r: f"{r['mean_test_top5']:.2f} ± {0.0 if pd.isna(r['std_test_top5']) else r['std_test_top5']:.2f}",
    axis=1
)
summary_md["Top10 (mean±std)"] = summary_md.apply(
    lambda r: f"{r['mean_test_top10']:.2f} ± {0.0 if pd.isna(r['std_test_top10']) else r['std_test_top10']:.2f}",
    axis=1
)

readme_table = summary_md[
    [
        "model_dim",
        "num_heads",
        "num_layers",
        "ff_multiplier",
        "dropout",
        "lr",
        "pool",
        "runs",
        "Top1 (mean±std)",
        "Top5 (mean±std)",
        "Top10 (mean±std)",
        "best_single_run_top1",
    ]
].head(topk)

display(readme_table)

markdown_text = readme_table.to_markdown(index=False)
print(markdown_text)

Empty DataFrame
Columns: [model_dim, num_heads, num_layers, ff_multiplier, dropout, lr, pool, runs, Top1 (mean±std), Top5 (mean±std), Top10 (mean±std), best_single_run_top1]
Index: []

| model_dim   | num_heads   | num_layers   | ff_multiplier   | dropout   | lr   | pool   | runs   | Top1 (mean±std)   | Top5 (mean±std)   | Top10 (mean±std)   | best_single_run_top1   |
|-------------|-------------|--------------|-----------------|-----------|------|--------|--------|-------------------|-------------------|--------------------|------------------------|

In [14]:
import csv
from pathlib import Path
import pandas as pd
import math

raw_csv = ROOT / "results/task3_cislr/temporal_transformer_encoder_gridsearch_results_with_seeds.csv"
clean_csv = ROOT / "results/task3_cislr/temporal_transformer_encoder_gridsearch_results_clean.csv"

expected_cols = [
    "exp_name",
    "input_dim",
    "model_dim",
    "output_dim",
    "num_heads",
    "ff_multiplier",
    "dropout",
    "lr",
    "weight_decay",
    "batch_size",
    "temperature",
    "num_layers",
    "pool",
    "best_val_top1",
    "val_top1",
    "val_top5",
    "val_top10",
    "test_top1",
    "test_top5",
    "test_top10",
    "seed",
    "error",
]

success_cols_21 = [
    "exp_name",
    "input_dim",
    "model_dim",
    "output_dim",
    "num_heads",
    "ff_multiplier",
    "dropout",
    "lr",
    "weight_decay",
    "batch_size",
    "temperature",
    "num_layers",
    "pool",
    "best_val_top1",
    "val_top1",
    "val_top5",
    "val_top10",
    "test_top1",
    "test_top5",
    "test_top10",
    "seed",
]

error_cols_15 = [
    "exp_name",
    "input_dim",
    "model_dim",
    "output_dim",
    "num_heads",
    "ff_multiplier",
    "dropout",
    "lr",
    "weight_decay",
    "batch_size",
    "temperature",
    "num_layers",
    "pool",
    "seed",
    "error",
]

numeric_cols = [
    "input_dim",
    "model_dim",
    "output_dim",
    "num_heads",
    "ff_multiplier",
    "dropout",
    "lr",
    "weight_decay",
    "batch_size",
    "temperature",
    "num_layers",
    "best_val_top1",
    "val_top1",
    "val_top5",
    "val_top10",
    "test_top1",
    "test_top5",
    "test_top10",
    "seed",
]

def to_num(x):
    if x is None:
        return None
    x = str(x).strip()
    if x == "" or x.lower() == "nan":
        return None
    try:
        return float(x)
    except Exception:
        return None

def normalize_error(x):
    if x is None:
        return None
    x = str(x).strip()
    if x == "" or x.lower() == "nan":
        return None
    return x

rows = []
bad_rows = []

with open(raw_csv, "r", encoding="utf-8", newline="") as f:
    reader = csv.reader(f)
    header = next(reader, None)

    for line_idx, row in enumerate(reader, start=2):
        if not row or all(str(x).strip() == "" for x in row):
            continue

        rec = None

        # 21-column successful row
        if len(row) == 21:
            rec = dict(zip(success_cols_21, row))
            rec["error"] = None

        # 22-column row: likely extra leading index
        elif len(row) == 22:
            rec = dict(zip(expected_cols, row[1:]))

        # 15-column early error row
        elif len(row) == 15:
            tmp = dict(zip(error_cols_15, row))
            rec = {col: None for col in expected_cols}
            rec.update(tmp)

        else:
            bad_rows.append({"line_idx": line_idx, "len": len(row), "raw": row})
            continue

        for col in numeric_cols:
            rec[col] = to_num(rec.get(col))

        rec["pool"] = None if rec.get("pool") in ("", None) else str(rec["pool"]).strip()
        rec["exp_name"] = None if rec.get("exp_name") in ("", None) else str(rec["exp_name"]).strip()
        rec["error"] = normalize_error(rec.get("error"))

        for col in ["input_dim", "model_dim", "output_dim", "num_heads", "ff_multiplier", "batch_size", "num_layers", "seed"]:
            if rec[col] is not None and not math.isnan(rec[col]):
                rec[col] = int(rec[col])

        rows.append(rec)

df_clean = pd.DataFrame(rows, columns=expected_cols).drop_duplicates()
df_clean.to_csv(clean_csv, index=False)

print("Clean rows:", len(df_clean))
print("Bad/unparsed rows:", len(bad_rows))
if bad_rows:
    print("Example bad row:", bad_rows[0])

display(df_clean.head())

Clean rows: 194
Bad/unparsed rows: 0

,exp_name,input_dim,model_dim,output_dim,num_heads,ff_multiplier,dropout,lr,weight_decay,batch_size,...,pool,best_val_top1,val_top1,val_top5,val_top10,test_top1,test_top5,test_top10,seed,error
0,temporal_transformer_encoder_dim256_o256_heads...,1024,256,256,4,2,0.0,0.00020,0.0001,32,...,mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1990,'TemporalTransformerEncoder' object has no att...
2,temporal_transformer_encoder_dim256_o256_heads...,1024,256,256,4,2,0.0,0.00020,0.0001,32,...,mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1990,masked_pool() got an unexpected keyword argume...
3,temporal_transformer_encoder_dim256_o256_heads...,1024,256,256,4,2,0.0,0.00020,0.0001,32,...,mean,15.217391,15.217391,20.652174,21.739130,19.124726,24.507659,26.958425,1990,None
4,temporal_transformer_encoder_dim256_o256_heads...,1024,256,256,4,2,0.0,0.00020,0.0001,32,...,mean,15.217391,15.217391,18.478261,21.739130,18.643326,23.150985,25.601751,1990,None
5,temporal_transformer_encoder_dim256_o256_heads...,1024,256,256,4,2,0.0,0.00001,0.0001,32,...,mean,10.869565,10.869565,16.304348,17.391304,16.192560,19.956236,22.013129,1990,None

In [15]:
import pandas as pd

summary_csv = ROOT / "results/task3_cislr/temporal_transformer_gridsearch_summary.csv"

df = pd.read_csv(clean_csv)
df_ok = df[df["error"].isna()].copy()

group_cols = [
    "input_dim",
    "model_dim",
    "output_dim",
    "num_heads",
    "ff_multiplier",
    "dropout",
    "lr",
    "weight_decay",
    "batch_size",
    "temperature",
    "num_layers",
    "pool",
]

summary = (
    df_ok.groupby(group_cols, dropna=False)
    .agg(
        runs=("seed", "count"),
        mean_val_top1=("val_top1", "mean"),
        std_val_top1=("val_top1", "std"),
        mean_test_top1=("test_top1", "mean"),
        std_test_top1=("test_top1", "std"),
        mean_test_top5=("test_top5", "mean"),
        std_test_top5=("test_top5", "std"),
        mean_test_top10=("test_top10", "mean"),
        std_test_top10=("test_top10", "std"),
        best_single_run_top1=("test_top1", "max"),
    )
    .reset_index()
    .sort_values(["mean_test_top1", "mean_test_top5", "mean_test_top10"], ascending=False)
)

summary.to_csv(summary_csv, index=False)

print("Successful runs:", len(df_ok))
print("Unique configs:", len(summary))
display(summary.head(15))

Successful runs: 192
Unique configs: 64

,input_dim,model_dim,output_dim,num_heads,ff_multiplier,dropout,lr,weight_decay,batch_size,temperature,...,runs,mean_val_top1,std_val_top1,mean_test_top1,std_test_top1,mean_test_top5,std_test_top5,mean_test_top10,std_test_top10,best_single_run_top1
18,1024,256,256,8,2,0.0,0.0002,0.0001,32,0.1,...,3,15.942029,2.262680,19.270605,0.291393,24.682713,0.401101,26.900073,0.482063,19.518600
58,1024,512,256,8,4,0.0,0.0002,0.0001,32,0.1,...,3,14.855072,1.255109,19.066375,0.382359,24.011670,0.297893,26.404085,0.133700,19.387309
50,1024,512,256,8,2,0.0,0.0002,0.0001,32,0.1,...,3,15.217391,1.086957,18.949672,0.788961,24.434719,0.248851,26.666667,0.394683,19.824945
34,1024,512,256,4,2,0.0,0.0002,0.0001,32,0.1,...,3,14.492754,1.660354,18.876732,0.463840,24.099198,0.577835,26.725018,0.527590,19.299781
2,1024,256,256,4,2,0.0,0.0002,0.0001,32,0.1,...,3,14.130435,1.086957,18.862144,0.904332,24.449307,0.310486,26.841721,0.322587,19.606127
42,1024,512,256,4,4,0.0,0.0002,0.0001,32,0.1,...,3,15.217391,1.086957,18.570387,0.413638,23.574034,0.597392,26.462436,0.248851,19.037199
54,1024,512,256,8,2,0.1,0.0002,0.0001,32,0.1,...,3,15.217391,1.086957,18.439096,0.291393,22.946754,0.091101,25.222465,0.484046,18.687090
6,1024,256,256,4,2,0.1,0.0002,0.0001,32,0.1,...,3,13.768116,0.627555,18.205689,0.758009,23.282276,0.190761,25.922684,0.297893,18.643326
22,1024,256,256,8,2,0.1,0.0002,0.0001,32,0.1,...,3,15.942029,1.255109,18.074398,0.916951,23.267688,0.692426,25.762217,0.291393,19.080963
26,1024,256,256,8,4,0.0,0.0002,0.0001,32,0.1,...,3,13.405797,2.262680,17.972283,2.095331,22.946754,2.629222,25.543399,2.651347,19.649891
38,1024,512,256,4,2,0.1,0.0002,0.0001,32,0.1,...,3,14.855072,0.627555,17.957695,0.397102,23.428155,0.197341,25.499635,0.571168,18.380744
46,1024,512,256,4,4,0.1,0.0002,0.0001,32,0.1,...,3,15.942029,1.660354,17.870168,0.522116,22.727936,0.316594,25.076586,0.243666,18.468271
19,1024,256,256,8,2,0.0,0.0002,0.0001,32,0.1,...,3,14.492754,0.627555,17.709701,0.277937,23.150985,0.444153,26.039387,0.796210,18.030635
62,1024,512,256,8,4,0.1,0.0002,0.0001,32,0.1,...,3,14.855072,0.627555,17.651349,0.603770,22.582057,0.266204,25.149526,0.503441,18.336980
3,1024,256,256,4,2,0.0,0.0002,0.0001,32,0.1,...,3,15.579710,2.735447,17.592998,1.232396,22.932166,0.537777,25.426696,0.175055,18.643326

In [17]:
import pandas as pd

summary_csv = ROOT / "results/task3_cislr/temporal_transformer_gridsearch_summary.csv"

df = pd.read_csv(clean_csv)
df_ok = df[df["error"].isna()].copy()

group_cols = [
    "input_dim",
    "model_dim",
    "output_dim",
    "num_heads",
    "ff_multiplier",
    "dropout",
    "lr",
    "weight_decay",
    "batch_size",
    "temperature",
    "num_layers",
    "pool",
]

summary = (
    df_ok.groupby(group_cols, dropna=False)
    .agg(
        runs=("seed", "count"),
        mean_val_top1=("val_top1", "mean"),
        std_val_top1=("val_top1", "std"),
        mean_test_top1=("test_top1", "mean"),
        std_test_top1=("test_top1", "std"),
        mean_test_top5=("test_top5", "mean"),
        std_test_top5=("test_top5", "std"),
        mean_test_top10=("test_top10", "mean"),
        std_test_top10=("test_top10", "std"),
        best_single_run_top1=("test_top1", "max"),
    )
    .reset_index()
    .sort_values(["mean_test_top1", "mean_test_top5", "mean_test_top10"], ascending=False)
)

summary.to_csv(summary_csv, index=False)

print("Successful runs:", len(df_ok))
print("Unique configs:", len(summary))
display(summary)

Successful runs: 192
Unique configs: 64

,input_dim,model_dim,output_dim,num_heads,ff_multiplier,dropout,lr,weight_decay,batch_size,temperature,...,runs,mean_val_top1,std_val_top1,mean_test_top1,std_test_top1,mean_test_top5,std_test_top5,mean_test_top10,std_test_top10,best_single_run_top1
18,1024,256,256,8,2,0.0,0.0002,0.0001,32,0.1,...,3,15.942029,2.262680,19.270605,0.291393,24.682713,0.401101,26.900073,0.482063,19.518600
58,1024,512,256,8,4,0.0,0.0002,0.0001,32,0.1,...,3,14.855072,1.255109,19.066375,0.382359,24.011670,0.297893,26.404085,0.133700,19.387309
50,1024,512,256,8,2,0.0,0.0002,0.0001,32,0.1,...,3,15.217391,1.086957,18.949672,0.788961,24.434719,0.248851,26.666667,0.394683,19.824945
34,1024,512,256,4,2,0.0,0.0002,0.0001,32,0.1,...,3,14.492754,1.660354,18.876732,0.463840,24.099198,0.577835,26.725018,0.527590,19.299781
2,1024,256,256,4,2,0.0,0.0002,0.0001,32,0.1,...,3,14.130435,1.086957,18.862144,0.904332,24.449307,0.310486,26.841721,0.322587,19.606127
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35,1024,512,256,4,2,0.0,0.0002,0.0001,32,0.1,...,3,13.405797,1.660354,15.609044,1.209916,20.058352,2.168106,22.669584,2.423654,16.455142
55,1024,512,256,8,2,0.1,0.0002,0.0001,32,0.1,...,3,11.956522,1.882664,15.609044,1.572044,19.562363,2.307056,21.692195,2.655678,17.024070
43,1024,512,256,4,4,0.0,0.0002,0.0001,32,0.1,...,3,11.231884,1.660354,14.748359,1.608576,18.628738,2.275851,20.685631,2.433643,16.542670
59,1024,512,256,8,4,0.0,0.0002,0.0001,32,0.1,...,3,12.681159,1.255109,14.573304,0.947764,18.832969,1.741956,21.604668,1.929742,15.448578
63,1024,512,256,8,4,0.1,0.0002,0.0001,32,0.1,...,3,11.956522,1.882664,13.946025,1.813070,17.447119,3.070431,19.328957,3.324407,16.017505